### PR TITLE
Make web player play DVD video

### PR DESCRIPTION
**Pull request by Nadahar**
This is my so far unsuccessful attempts to make flow player (the web interface player) play DVD videos, separated out from #1287. 

Much of the discussion can be found in #1287, in short: 
* MEncoder/MPlayer can't seem to generate a MP4 format that is consumable by flowplayer, probably because it requires the moov atom to be in front.
* FFmpeg can generate an acceptable output, but can't read DVDs.
* I've not been able to pipe them together

Any suggestions or further experimentation is welcome.

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 I just tried with ```-dumpstream``` - it makes no difference. I'm not sure exactly what the problem is, but I'm not so sure it's with either MPlayer or FFmpeg. I suspect that the *pipe* connecting them doesn't work as it should. This is UMS code, and I could either be using it wrong or it could be bugged.

**Comment by Sami32** [comment]
Actually, i don't know what you've done. I asked you to post your command line.
It seem that you've only tested it in UMS. MKFIFO should work fine, except if FFmpeg have an FIFO input limitation. I could check at that if you want.

**Comment by Nadahar** [comment]
@Sami32 I've spent hours on this and has used many combinations of parameters. I haven't logged each combination, so I can't tell you what I've tried. I've made most of the attempts using UMS, and made simple "functional" tests manually by launching on the command line.

The thing is that if I manually run first Mencoder outputting it to a file and then run FFmpeg to process that to a new file, the final output file is working fine (I haven't tested it with flow player as it would require some JavaScript), but the file seems ok when tested or parsed with MediaInfo. It's when you try to get these processes to run in parallel connected through a pipe that it doesn't work. That's why this has to be tested in that way to have any relevance.

As I see it there's two basic possible causes:
* The pipe doesn't work correctly
* FFmpeg can't read it because a pipe doesn't allow seeking. A normal file can be read in any order, it's possible to "jump" back and forth to look up different information. A pipe, being sequential, doesn't allow that, which could lead to FFmpeg being unable to get the information it needs to start decoding the streams. The exact format output by MEncoder could determine if seeking is necessary or not, as some formats/codecs/streams are made in a way that allows sequential reading while other aren't. It's quite likely that the output from MEncoder isn't possible to read sequentially, and that this is the reason why both flowplayer and FFmpeg can't read it as a "stream".

I'm not sure what you mean by MKFIFO. ```mkfifo``` is a *nix command that doesn't exist on Windows, and isn't what's used by UMS on Windows. [Windows Named Pipes](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365590(v=vs.85).aspx) is used instead, but they can't be created from the command line (AFAIK).

**Comment by Sami32** [comment]
@Nadahar Did you tried on Linux using MKFIFO ? i guess that it should work without any issue.
I'll check at that tomorrow, i mean on Windows.
I suspect FFmpeg input having a limited format support.

Could you post a little sample, generated from the MEncoder command line that i giver you, as i could analyse file.

**Comment by Nadahar** [comment]
@Sami32 I didn't save them to file, they were piped to flow player. That means that I don't have any sample to send. Can't you just generate a sample yourself (from your ISO) and analyze the output?

**Comment by Sami32** [comment]
@Nadahar As i already told you, MEncoder will not encode H264 on my CPU, though MPEG is possible.

As you was saying all around that the generated file was not fragmented as it should , i wrongly thought that you've analysed it.

Never mind, i don't bother for that, it was for help you, but i know that you don't really need so.

**Comment by Nadahar** [comment]
@Sami32 I'm sorry but I don't quite understand. I don't think I've said that the missing fragmentation was the cause. I think I've been talking about possible reasons, that is: My speculation as to what goes wrong.

Also, the fact that I can't find any parameters that will make MEncoder do so, I have no reason to believe that the file is made "streamable".

> Never mind, i don't bother for that, it was for help you, but i know that you don't really need so.

This part I don't understand, please rephrase.

**Comment by Sami32** [comment]
@Nadahar Without any MEncoder output sample provided, using the latest command line that i gived to  you, you're on your own.

**Comment by Nadahar** [comment]
@Sami32 I don't get it, but if it's that important to you just ask if  I can make one for you. Assuming that the "latest command line you gave me" is:
```PowerShell
mencoder -msglevel statusline=2 -sws 9 -cache 8192 -cache-min 4 -ss 0 -dvd-device <source file> dvd://1 -vf scale=640:-10,expand=640:480,harddup -oac lavc -lavcopts aglobal=1:vglobal=1:vcodec=libx264:acodec=libfaac -lavdopts threads=1 -ovc x264 -x264encopts preset=ultrafast:profile=baseline:level_idc=30:global_header:threads=auto -of lavf -lavfopts format=mp4 -ofps 25 -channels 2 -af lavcresample=48000 -srate 48000 -nofontconfig -nosub -noautosub -alang fr,en
```
..the output is an empty file (0 bytes size). 

Console output:
```powershell
PS C:\Repos\Java\UniversalMediaServer> .\win32\mencoder.exe -msglevel statusline=2 -sws 9 -cache 8192 -cache-min 4 -ss 0
 -dvd-device 'E:\data\Sourcecode\Java\Media Sample Video\big-buck-bunny-PAL.iso' dvd://2 -vf scale=640:-10,expand=640:48
0,harddup -oac lavc -lavcopts aglobal=1:vglobal=1:vcodec=libx264:acodec=libfaac -lavdopts threads=1 -ovc x264 -x264encop
ts preset=ultrafast:profile=baseline:level_idc=30:global_header:threads=auto -of lavf -lavfopts format=mp4 -ofps 25 -cha
nnels 2 -af lavcresample=48000 -srate 48000 -nofontconfig -nosub -noautosub -channels 6 -o test.mp4
MEncoder SB65-UMS (C) 2000-2016 MPlayer Team
Custom build by SubJunk, http://www.spirton.com

There are 11 titles on this DVD.
There are 1 angles in this DVD title.

libdvdread: Attempting to retrieve all CSS keys
libdvdread: This can take a _long_ time, please be patient

libdvdread: Found 11 VTS's
libdvdread: Elapsed time 0
audio stream: 0 format: ac3 (5.1) language:  aid: 128.
number of audio channels on disk: 1.
number of subtitles on disk: 0

success: format: 2  data: 0x0 - 0x23d5b800
Cache fill:  0.00% (0 bytes)

MPEG-PS file format detected.
VIDEO:  MPEG2  720x576  (aspect 3)  25.000 fps  7800.0 kbps (975.0 kbyte/s)
[V] filefmt:2  fourcc:0x10000002  size:720x576  fps:25.000  ftime:=0.0400
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
libavcodec version 56.20.100 (internal)
AUDIO: 48000 Hz, 2 ch, floatle, 448.0 kbit/14.58% (ratio: 56000->384000)
Selected audio codec: [ffac3] afm: ffmpeg (FFmpeg AC-3)
==========================================================================
libavformat version 56.19.100 (internal)
** MUXER_LAVF *****************************************************************
REMEMBER: MEncoder's libavformat muxing is presently broken and can generate
INCORRECT files in the presence of B-frames. Moreover, due to bugs MPlayer
will play these INCORRECT files as if nothing were wrong!
*******************************************************************************
OK, exit.
Opening video filter: [expand osd=1]
Expand: -1 x -1, -1 ; -1, osd: 1, aspect: 0.000000, round: 1
Opening video filter: [scale w=640 h=-10]
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
Selected video codec: [ffmpeg2] vfm: ffmpeg (FFmpeg MPEG-2)
==========================================================================
[libfaac @ 02168940]Channel layout not specified
PS C:\Repos\Java\UniversalMediaServer>
```

**Comment by Sami32** [comment]
@Nadahar I'm sure that what i did, but saying that other way should be perceive as an order ?

That's strange, i suspect the` -nofontconfig` is the culprit, as it's with MPlayer. So if you don't mind, could you do an other test ?
I'm frustred that i cannot test it myself, i didn't even receive any message as you do.

**Comment by Nadahar** [comment]
@Sami32 Are you sure this isn't edited?
> Could you post a little sample, generated from the MEncoder command line that i given you, as i could analyse the MP4 file produced.

That's obiously asking, and if that's what it originally said I'm sorry that I missed it. What I perceived that you asked was a sample of my latest attempt using UMS, which I don't have.

The result is the same:
```powershell
PS C:\Repos\Java\UniversalMediaServer> .\win32\mencoder.exe -msglevel statusline=2 -sws 9 -cache 8192 -cache-min 4 -ss 0
 -dvd-device 'E:\data\Sourcecode\Java\Media Sample Video\big-buck-bunny-PAL.iso' dvd://2 -vf scale=640:-10,expand=640:48
0,harddup -oac lavc -lavcopts aglobal=1:vglobal=1:vcodec=libx264:acodec=libfaac -lavdopts threads=1 -ovc x264 -x264encop
ts preset=ultrafast:profile=baseline:level_idc=30:global_header:threads=auto -of lavf -lavfopts format=mp4 -ofps 25 -cha
nnels 2 -af lavcresample=48000 -srate 48000 -nosub -noautosub -o test.mp4
MEncoder SB65-UMS (C) 2000-2016 MPlayer Team
Custom build by SubJunk, http://www.spirton.com

There are 11 titles on this DVD.
There are 1 angles in this DVD title.

libdvdread: Attempting to retrieve all CSS keys
libdvdread: This can take a _long_ time, please be patient

libdvdread: Found 11 VTS's
libdvdread: Elapsed time 0
audio stream: 0 format: ac3 (5.1) language:  aid: 128.
number of audio channels on disk: 1.
number of subtitles on disk: 0

success: format: 2  data: 0x0 - 0x23d5b800
Cache fill:  0.00% (0 bytes)

MPEG-PS file format detected.
VIDEO:  MPEG2  720x576  (aspect 3)  25.000 fps  7800.0 kbps (975.0 kbyte/s)
[V] filefmt:2  fourcc:0x10000002  size:720x576  fps:25.000  ftime:=0.0400
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
libavcodec version 56.20.100 (internal)
AUDIO: 48000 Hz, 2 ch, floatle, 448.0 kbit/14.58% (ratio: 56000->384000)
Selected audio codec: [ffac3] afm: ffmpeg (FFmpeg AC-3)
==========================================================================
libavformat version 56.19.100 (internal)
** MUXER_LAVF *****************************************************************
REMEMBER: MEncoder's libavformat muxing is presently broken and can generate
INCORRECT files in the presence of B-frames. Moreover, due to bugs MPlayer
will play these INCORRECT files as if nothing were wrong!
*******************************************************************************
OK, exit.
Opening video filter: [expand osd=1]
Expand: -1 x -1, -1 ; -1, osd: 1, aspect: 0.000000, round: 1
Opening video filter: [scale w=640 h=-10]
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
Selected video codec: [ffmpeg2] vfm: ffmpeg (FFmpeg MPEG-2)
==========================================================================
[libfaac @ 010b8940]Channel layout not specified
PS C:\Repos\Java\UniversalMediaServer>
```

**Comment by Sami32** [comment]
@Nadahar Yes, and i think i've already asked before in your other PR, but as i edited it while you answered i suspected that you never read it, so i did ask in that one.
OK, it can happen to every one.

Now i'm really perplex, i still need to understand what happen here.

**Pull request closed without merging**
