### PR TITLE
Netty 4 implementation by @mfulgo

### PR DESCRIPTION
**Pull request by SubJunk**
This updates our implementation of Netty from 3.9 to 4.0

### CODE REVIEW

**Comment by SubJunk** [comment]
After merging this with master, we need to refactor our use of setAttachment at requestHandlerV2.java:289

**Comment by SubJunk** [comment]
The exception error in Netty 4.0 has been fixed in https://github.com/netty/netty/commit/28caa873b3350053dfe6dfddbee48489dbe2c94a so that's a good sign for the future of this PR

**Comment by SubJunk** [comment]
@mfulgo are you still around? :)

**Comment by mfulgo** [comment]
@SubJunk Yeah, been distracted by other stuff for a while though.  I'll try to pick this back up next week.

**Comment by SubJunk** [comment]
@mfulgo great!

**Comment by valib** [comment]
@mfulgo can you check if my fix of merging is correct?

**Comment by valib** [comment]
@mfulgo as @SubJunk wrote ```After merging this with master, we need to refactor our use of setAttachment at requestHandlerV2.java:289``` because the setAttachment is not declared in the Netty 4. I simply have taken your original commit https://github.com/UniversalMediaServer/UniversalMediaServer/commit/40d44a7275d22bb96cd6e614d2c6266c6f4146c6 and compared it with the Subjunk's commit https://github.com/UniversalMediaServer/UniversalMediaServer/commit/b2f16981854f086ecc39432546c4f124ec12d251.

**Comment by SubJunk** [comment]
Is anyone testing this? Is it ready to merge?

**Comment by valib** [comment]
@SubJunk I am testing it and for me it also works.

**Comment by SubJunk** [comment]
@valib cool! should we merge it? What do you think @skeptical and @mfulgo ?

**Comment by SubJunk** [comment]
I just got a bug while using this branch but I'm not sure if it's specific to this branch. The folders in the root were displayed twice on my TV. Restarting the server fixed it. Have any of you encountered this bug before? I saved the logs too in case anyone is interested in them

**Comment by valib** [comment]
@SubJunk I don't see such bug.

**Pull request merged**
