### PR TITLE
Decrease the delay before the video starts playing

### PR DESCRIPTION
**Pull request by valib**
@UniversalMediaServer/developers can you test it if it is worth to merge?

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/790)

### CODE REVIEW

**Comment by Nadahar** [comment]
@valib What exactly does it do? How do I test it? I see that it sets faststart, but for what under what circumstances and what is the advantage/disadvantage of doing this?

**Comment by valib** [comment]
@Nadahar there is a standard delay before the video starts to stream to to the renderer. This PR changed this delay to 0 for the web interface and the video should start faster. For me it starts faster but at the beginning the video is a little bit choppy. So I would like others to test it. You can put on your PC running UMS to the web browser (Firefox or Chrome) the address 172.0.0.1:9001 to accsess the UMS web interface and test it.

**Comment by Nadahar** [comment]
@valib In know how to use the web interface, but I think the address you intended was ```127.0.0.1:9001```? It's the same as ```localhost:9001```.

What I meant was enable faststart (which effectively drops the startup buffer) for web players? Is there a special reason why web play doesn't need buffering?

As I see it, the startup buffering logic should be changed in general. How much buffering is needed before playback is started is probably dependent on the "power" of the computer running UMS, not the renderer. It should be possible to adjust this instead of just turning it on or off. Some people might have to live with a long buffering pause due to weak hardware, while others can get away with a much shorter delay. Some buffering however, even if it's just 100ms or something like that, is probably a good idea in any case. But, the file being transcoded probably also matters, the heavier it is to transcode, the more buffering time is needed.

**Comment by valib** [comment]
Seems to me to be unacceptable so I close it.

**Pull request closed without merging**
