### PR TITLE
Parser fixes

### PR DESCRIPTION
**Pull request by ler0y**
Some more parse fixes and format/codec support added :)
And again.. please check my changed code, since i'm not a skilled java programmer.

### CODE REVIEW

**Comment by SubJunk** [comment]
@ler0y ADPCM is a great addition, and some other changes look good too :)
Some of them I'm not sure about, since I only want to add things that are actually supported by at least one renderer - there's not much benefit in making it into a list of all formats/codecs. I'll go through them in detail soon.

**Comment by ler0y** [comment]
@SubJunk I'm working on a renderer config file for the on Android running MX Player app.
This video player can play lots of formats/codecs native.
All the additional formats/codecs were tested on these video player.

**Comment by SubJunk** [comment]
@ler0y oh that's great, disregard my previous comment then :)
One other possible thing I need to check is there has been weirdness in the past with detecting AAC so I'll need to confirm the changes with the different types of AAC

**Comment by ler0y** [comment]
@alfaproject thanks for your comment! still learning :)

**Comment by SubJunk** [comment]
Thanks a lot for this :)

**Pull request merged**
