### PR TITLE
Toggle the state of the install service button

### PR DESCRIPTION
**Pull request by taconaut**
Instead of having two active buttons to install and uninstall UMS as a windows service, have a single one, which shows install or uninstall depending on the installation state of the service.

I have tested it only on win7.
~~I might have put the plugin to copy the wrapper in the wrong spot which might lead to errors on other platforms.~~ Please test :)

Changes:
- Added WindowsUtil class with method isUmsServiceInstalled()
- Moved install and unistall service methods from PMS to WindowsUtil
- Added constant NEWLINE_CHARACTER to StringUtil
- Added empty constructor to CustomJButton
- Removed the unistall button
- Update text, tooltip and executed action for installService button in new method refreshInstallServiceButtonState() depending on the installation state of the service
- Copy the service wrapper into the working directory in order to be able to debug this functionality and add thisdirectory to the git ignore list

### CODE REVIEW

**Comment by SubJunk** [comment]
@taconaut cool, good idea. I only have Windows 7 too so it will be good to get it tested on other versions of Windows :)

**Comment by Optimusprimeums** [comment]
@taconaut @SubJunk I'll check with windows 8.1 today and get back to you. I'll also check Windows 10 tomorrow if you like

**Comment by valib** [comment]
Tested on WIN XP and it works.

**Comment by SubJunk** [comment]
@valib thanks!

@Optimusprimeums cool, if it works on 8.1 let's merge :)

**Comment by Optimusprimeums** [comment]
@SubJunk @taconaut Works great on 8.1 and Windows 10. Merge away!!!

**Comment by SubJunk** [comment]
@taconaut thanks!

**Comment by taconaut** [comment]
Cheers and thanks for testing

**Pull request merged**
