### PR TITLE
Fix NPE in FFmpegVideo for media containing only video stream

### PR DESCRIPTION
**Pull request by valib**

### CODE REVIEW

**Comment by valib** [comment]
@SubJunk do you know how to restart the Travis when the test fails?

**Comment by SubJunk** [comment]
@valib I have this restart button on the right side
image
Has it disappeared for you?

**Comment by valib** [comment]
@SubJunk yes it disappeared. I have this
screen
without t

**Comment by SubJunk** [comment]
@valib it looks like there is an active forum post about it at https://travis-ci.community/t/job-restart-button-are-not-always-appearing-on-build-page/5811/14
A couple of users found it was fixed after logging out and in

**Comment by valib** [comment]
@SubJunk thanks for info. Logging out and in works. But this is a Travis problem which should be solved.

**Pull request merged**
