### PR TITLE
Removed wizard from PMS and created Wizard class.

### PR DESCRIPTION
**Pull request by valib**
Simplify creating options dialogs and make all dialogs buttons text translatable.

### CODE REVIEW

**Comment by valib** [comment]
Rebased to the last master.

**Comment by SubJunk** [comment]
This is a good idea, is there any change to user behavior or is it just a refactor?

**Comment by valib** [comment]
@SubJunk this is only refactored to be able to work on it independently on the main class. The behaviour is still the same.

**Comment by SubJunk** [comment]
I tested and it worked so I'm merging

**Comment by valib** [comment]
@SubJunk a translation in the Crowdin is needed. Can you upload the default message.properies there.

**Comment by SubJunk** [comment]
@valib that's done now, and Merry Christmas to you too :)

**Comment by Nadahar** [comment]
I'm an atheist too, so I wish you all a merry Yule instead :)

**Pull request merged**
