### PR TITLE
Add additional LibMediaInfoParser tests

### PR DESCRIPTION
**Pull request by Jensaarai**
Add basic tests for getAvcProfile, getBitrate, getSpecificID, getSampleFrequency, getFPSValue, getFrameRateModeValue, getLang, and getCover().

### CODE REVIEW

**Comment by SubJunk** [comment]
@Jensaarai yay for tests!

**Comment by SubJunk** [comment]
@Jensaarai do you recommend any tools to automate coverage tracking? I have been using Coveralls.io and I like it but I haven't used it for Java projects. I would be interested in setting up that or a similar service for this project.

**Comment by taconaut** [comment]
@SubJunk you also get code coverage when building the site through maven. http://universalmediaserver-ci.hopto.org:9999/job/ums%20trunk%20(nightly)/site/cobertura/index.html

**Comment by SubJunk** [comment]
@taconaut great, thanks :)

**Comment by Jensaarai** [comment]
I wasn't aware Maven gave coverage, that's cool. I personally used EclEmma because I was using Eclipse and it plays very nicely with JUnit tests.

**Comment by Jensaarai** [comment]
Here's a comparison of others I've heard of (Clover, Cobertura, Jacoco, etc) https://confluence.atlassian.com/plugins/servlet/mobile#content/view/681706101

Another not on that list is Sonar.

**Comment by SubJunk** [comment]
Thanks for the list! Clover looks cool but isn't free, so it looks like Cobertura is a good choice for us still :)

**Pull request merged**
