### PR TITLE
8.0.0

### PR DESCRIPTION
**Pull request by SubJunk**
This major release of UMS will focus on making our handling of web feeds and streams easier to use by making it manageable via GUI, and fixing bugs with it including the implementation of more types of feeds and streams.

In general I will try not to commit directly to this branch, instead I will merge related branches into here, except for quick fixes noticed after those branches are merged.

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib I'm going to sync this with master and the subtitles branch, then do `8.0.0-a2` and `7.7.1` soon unless you disagree, since that MEncoder fix from `master` is important

**Comment by ExSport** [comment]
Hi guys
I was at home for a short time so tested new version 8a1. Unfortunately very bad on parents PanTV. Video with subs no go, also no go with MEncoder from transcode folder. Pictures very bad. Log full of not supported resolutions (4128xDontremember exactly) so TV displayed pictures like 320x240. Same in bubbleUpnp on Android. So reinstalled to latest 7.7 but similar results. Video not playable with MEncoder or FFmpeg but VLC and tsMuxer worked. Pictures were better than 8a1 as full picture wasn't like small thumbnail but had not much time to test it more. Windows 8.1 x64. Btw. v7.7 installer doesn't create HeapMem registry and also it can't be configured during installer (standalone x64).
Unfortunately no logs. Forgot one in debug level only in parents pc. Btw. spotted lot of errors in v7.7? about globalidrepo error -1. Tester clean install with one mkv and lot of backed up pictures from phone (jpg+mp4).
Unfortunately I had to leave so no time to troubleshooting it more or reverting it back to working state 🙄
Anyway thanks for your continuous work guys, all of you! 🤗

**Comment by SubJunk** [comment]
@ExSport thanks for your notes. The problem with MEncoder not playing has been fixed in `master` and will be released soon, unfortunately I broke it on Windows when I fixed it on macOS :D soon we will have automated tests that can catch this kind of thing, we have a branch for it by the wonderful @stasinos 

As for that image problem, I have started work on that too and I hope to merge it soon. There are a lot of branches happening all at once so some can take a while, but I really want to get that image thing fixed since it will only get worse as cameras keep getting better. I will update that story when there is more progress and maybe you can help test :)

**Comment by valib** [comment]
@SubJunk I confirm that bug with pictures. It works only on the web interface but not on my Panasonic or Samsung TVs. The UMS offers only `DLNA.ORG_PN=JPEG_TN`  for resource not larger formats. The master branch is OK.
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2710904/ums_dbg.zip)

**Comment by SubJunk** [comment]
@valib ah ok, thanks for confirming it. We should fix it. It is kinda related to https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1642 and I want to fix it by making the image resizing restriction opt-in, since many renderers support higher resolutions than DLNA spec.
Also now this branch is in sync with master and rebased subs. Can we close rebased subs branch and work on that in here?

**Comment by valib** [comment]
@SubJunk you fix it.

**Comment by SubJunk** [comment]
That seems fair since you just did a lot of work syncing, I will work on it soon

**Comment by SubJunk** [comment]
@valib I just tested on my Panasonic TV with a 6554x1485 image and it displays at the correct resolution (4096×928), it looks high quality too, and sends the correct response over the network:

```
  <item id="91" parentID="75" restricted="1">
    <dc:title>AcrossTheWayTheSunShines</dc:title>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_LRG;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=00900000000000000000000000000000" resolution="4096x928">http://169.254.228.34:5001/get/91/JPEG_LRG_AcrossTheWayTheSunShines.jpg</res>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_MED;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=00900000000000000000000000000000" resolution="1024x232">http://169.254.228.34:5001/get/91/JPEG_MED_AcrossTheWayTheSunShines.jpg</res>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_SM;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=00900000000000000000000000000000" resolution="640x145">http://169.254.228.34:5001/get/91/JPEG_SM_AcrossTheWayTheSunShines.jpg</res>
    <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=00900000000000000000000000000000" resolution="160x36">http://169.254.228.34:5001/get/91/thumbnail0000JPEG_TN_AcrossTheWayTheSunShines.jpg.jpg</res>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_SM">http://169.254.228.34:5001/get/91/thumbnail0000JPEG_SM_AcrossTheWayTheSunShines.jpg.jpg</upnp:albumArtURI>
    <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" dlna:profileID="JPEG_TN">http://169.254.228.34:5001/get/91/thumbnail0000JPEG_TN_AcrossTheWayTheSunShines.jpg.jpg</upnp:albumArtURI>
    <upnp:class>object.item.imageItem.photo</upnp:class>
  </item>
```

is there a step I'm missing?

**Comment by valib** [comment]
@SubJunk thanks for the English language lesson. 😃 I know that sometimes my English is wrong but what would you expect from the 60 years old man?

**Comment by SubJunk** [comment]
Your English is better than my Czech, which does not exist! :D

**Comment by SubJunk** [comment]
@valib can you tell me the Czech greeting? I have been learning to speak Portuguese (Brazilian) lately, it would be nice to learn a small bit of Czech too

**Comment by ExSport** [comment]
Lesson one: Pivo
That's enough 😎

**Comment by valib** [comment]
@SubJunk @ExSport is right `Pivo` means `beer` 😄

**Comment by SubJunk** [comment]
Oh yeah I see `Found no audio track` in the logs for all of my videos. I'm just keeping a record here in case my investigation gets interrupted by my 2 year old waking up :)

**Comment by SubJunk** [comment]
Also seeing `Searching for subtitles without considering audio language` which presumably means it's not reading my config correctly

**Comment by SubJunk** [comment]
Also seems like the `off` language setting isn't always being handled anymore

**Comment by SubJunk** [comment]
Those problems I noticed are fixed now, I think the audio one was fixed by you @valib so I just bumped the database version to make sure the `a1` and `a2` users get the fixed database, and I fixed `off` not working. I feel like the stability is pretty good in this branch now, for the subtitles work.

**Comment by ExSport** [comment]
@SubJunk
Testing latest 8beta1 [#1b8d9bc]:
Small text during installation and missing crowdin text:
image
Some text is rewritten so it is unreadable:
image
Initial scan of 600 MB (500 jpg) done. UMS repeatedly restarted. Unfortunately very slow (2min 30sec) reindexing done again and again with spamming to the log (for each file):
```
17:10:28 DEBUG Cached information about IMG_20181010_155101_HDR.jpg seems to be from a previous version, reparsing information
```
HeapMem set to 2500.
During this reindexing process UMS memory allocation grows up to 1900MB of Working Set and 1003 MB RAM in UMS GUI and doesn't fall down.
UMS DB cleared. UMS restarted. Memory allocation mostly fluctuates between 300 and 650 MB in UMS GUI, sometimes to 850 MB. Initial indexing took 3 mins. Memory usage stopped to fluctuate and ended on 860 MB without any forced garbage collection (no memory change for another 5min after initial indexing ended).
UMS restarted and now UMS GUI shows 98 MB memory utilization and no perpetual reindexing running.
It seems there is a problem in database upgrade process as I did a clean install of v8a2-win and after initial indexing I stopped UMS and replaced ums.jar from the latest https://github.com/UniversalMediaServer/UniversalMediaServer/commit/1b8d9bc3a3d6a3433df960c2280fbbe2cb9b7c2a
When using latest ums.jar with no existing **medias.mv.db** file, there is no spamming in the log about reindexing and no heavy memory utilization 👍 
Hope it helps...had no time to test it further and also right now I don't have any renderer for testing :)

**Comment by ExSport** [comment]
Sorry not to be clear enough. It means that I manually restarted UMS because I saw this spamming to the log about the reparsing if it will repeat again or it was temporary problem...And this behaviour repeated endlessly until I deleted database file.
About the memory. During initial sync it seems there was forced garbage emptying as UMS GUI shows pulsing memory usage up and down during the scan and it never went above 900 MB. But when reparsing was done due to the db upgrading bug, memory raised only, no drops down and finally taken more memory than initial scan what seems to be weird for me so I mentioned it. Also indexing 600 MB of pictures allocates about 1 GB seems a lot but maybe UMS behaviour will be better at time full HeapMem is allocated so garbage emptying is forced so indexing 10 GB of pictures will be without issues? :)

**Comment by SubJunk** [comment]
@ExSport the database version has been bumped since `8.0.0-a2` so it makes sense it would do reparsing. It is because there was a parsing bug in `a2`. Does it reparse the same files twice?

Maybe next time you have spare time for this, you could lower the UMS memory to 1GB to see if a crash happens? I have been testing it on about 5TB of content, mostly videos and audio, with Java set to 1280MB memory, and it has been stable with that, but pictures are different because of all the conversion

**Comment by ExSport** [comment]
@SubJunk
Installed v8a2-Win from GitHub. Used clean install. Started it and configured what initiated initial indexing of configured shared folder.
UMS stopped. ums.jar file replaced with v8b2. UMS started again.
Expected behaviour is that UMS quickly check db file that no file was modified so no reindexing is needed and in few seconds rescanning ends (it is done every UMS start). Another expected behaviour may be forced reindexing due to changes in db schema but it is expected it should run max once.
The tested behaviour was not expected as after UMS.jar update there was forced reinit or reparsing with spamming the log. And this behaviour repeated every restart! Every UMS restart, rescan detected change and reparsed all files. When it ended I restarted UMS and it did it again, reparsing initiated again and again, every UMS restart.
When I repeated it 5 times I stopped UMS, deleted database files and started again. Rescan initiated new file indexing to empty DB. When finished I restarted UMS and voila, there was no reparsing and log spamming. Great, now I achieved expected behaviour but it is not how application should work, it is buggy behaviour.
Hope you understand now. Sorry for my English, seems like language barrier between us :-)

**Comment by ExSport** [comment]
HeapSize set to 600 (533 MB visible in UMS GUI)
Cleared DB, initial indexing started. Mem usage jumps from 100 to 300 and back until initial scan finished.
As I described before, in such case it seems forced mem depletion (GC emptying) is done so memory usage doesn't grow up only but also drops down. Btw. after initial scan finished, memory usage settled on 200 MB.
So now I will try to repeat buggy behavior. Replacing ums.jar v8b1 with v8a2 and deleting 18 MB DB file.
Starting UMS, initial scan and indexing is initiated. Memory behavior is same as above (fluctuates up and down). Initial scan completed, DB size is 20 MB (same/similar as with b1)...ehm, after a while size was reduced to 18MB (some cleanup done a while after indexing finished?).
Starting UMS again (still a2) to check there will be no log spamming about "reparsing never-ending-story". Scan finished in few seconds, no reparsing initiated! Great. Going to reproduce bug and stopping UMS, replacing ums.jar with the a8b1. Starting UMS. Fu*k, no reparsing spamming in the log, weird..there is running scan but no negative influence on memory or DB size, memory fluctuates as before and DB size is same, 18 MB. Closing UMS and giving it last chance before repeating tests with 2500MB HeapMem.
Voila!!!! Another UMS start (ums.jar is still a8b1) and rescan started to spam with reparsing! Great! As HeapMem is small, it seems GC freeing works as memuse fluctuates up and down and ends on 200 MB. DB size has grown to 32 MB. Log full of:
```
DEBUG 2019-01-04 01:18:38.685 [Library Scanner] Cached information about IMG_20181014_105114.jpg seems to be from a previous version, reparsing information
TRACE 2019-01-04 01:18:38.685 [Library Scanner] 
java.io.InvalidClassException: net.pms.image.ImageInfo; local class incompatible: stream classdesc serialVersionUID = 4247040093720562338, local class serialVersionUID = 8947090782856389500
	at java.io.ObjectStreamClass.initNonProxy(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
	at java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at org.h2.util.JdbcUtils.deserialize(JdbcUtils.java:420)
	at org.h2.jdbc.JdbcConnection.convertToDefaultObject(JdbcConnection.java:2023)
	at org.h2.jdbc.JdbcResultSet.getObject(JdbcResultSet.java:534)
	at net.pms.dlna.DLNAMediaDatabase.getData(DLNAMediaDatabase.java:551)
	at net.pms.dlna.RealFile.resolve(RealFile.java:173)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1561)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1358)
	at net.pms.dlna.RealFile.isValid(RealFile.java:66)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:623)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:272)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:328)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:293)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:251)
	at net.pms.dlna.DLNAMediaDatabase.run(DLNAMediaDatabase.java:1510)
	at java.lang.Thread.run(Unknown Source)
```
Another try, UMS restarted...it repeats, reparsing spams log again. Another UMS restart, another reparsing spam initiated,....again and again...size of DB stays at 32 MB.
So now the last test, if it is related to update from a2 to b1 or b1 itself is buggy,
Clearing DB, starting initial scan, new DB created with size ~17.1 MB. UMS restarted (full restart...I never used restart via UMS GUI), there is no spamming and rescan ends in few seconds, DB size is same, 17.1 MB. Another UMS restart and....no spam, rescan ends in few secs. Definitely bug due to initiated DB update between versions. With no DB in a8b1, I can't reproduce this bug here as b1 creates new DB itself without any DB upgrade, my thoughts only, without checking the code.

**Comment by SubJunk** [comment]
@ExSport thanks for the info, I haven't had a chance to read it carefully yet since I only had a short time to release b1, I will look soon :) just wanted to let you know I wasn't ignoring you

**Comment by SubJunk** [comment]
@ExSport I've seen that error with `serialVersionUID` before and it was caused by NetBeans doing some indexing/building in the background and screwing up the versions... were you testing with the official releases or building some for yourself? Maybe I made a mistake when I built the files

**Comment by ExSport** [comment]
@SubJunk 
As I described it in last posts. Installed "v8a2-Win from GitHub", did first tests, initiated DB etc...
Later I updated to #1b8d9bc via ums.jar replace. I used your linux test build from here: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1739#issuecomment-451079171

**Comment by SubJunk** [comment]
@ExSport can you please try to reproduce it on the official b2 release? Maybe I made a mistake when I made that linux test build, like I said if NetBeans is open it seems to mess up the file versioning.
I have tried to reproduce the bug myself but I can't

**Comment by SubJunk** [comment]
@valib can I get your opinion on whether this is ready to merge to master? I have been following up on reported bugs and I don't think any are still there, of the ones related to v8

**Pull request merged**
