### PR TITLE
Added link to release page on automatic downloader

### PR DESCRIPTION
**Pull request by CodeLover254**
This pull request contains features described in issue #2604.

### CODE REVIEW

**Comment by SubJunk** [comment]
@CodeLover254 this looks great! I have just fixed a problem in master that was preventing this branch from running tests, can you please get it up to date with master? The tests will fail on lint. Let me know if you want any help

**Comment by CodeLover254** [comment]
@SubJunk, I have fetched from upstream and merged. Thanks!

**Comment by SubJunk** [comment]
@CodeLover254 thanks, I expected it to fail on lint but I guess there are problems with that, maybe due to a recent checkstyle update. I'll investigate that but it doesn't need to hold this up. I'll test this now

**Comment by SubJunk** [comment]
@CodeLover254 it works great, thanks!

**Review by SubJunk — APPROVED** [review]

**Comment by CodeLover254** [comment]
Thanks. I will continue making contributions to this project. Hoping to learn a lot from it.

**Comment by SubJunk** [comment]
@CodeLover254 that would be awesome, I look forward to seeing your contributions :)

**Pull request merged**
