### PR TITLE
Dms sync3

### PR DESCRIPTION
**Pull request by SubJunk**

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib I have done general testing of this and can't see any obvious bugs. The window position is remembered correctly. If you are happy with it I think we can merge

**Comment by mzji** [comment]
The whitelist function is removed by this PR but document (including Github Wiki or comments in the `UMS.conf` file) related with this function has no change... Could any project maintainer explain that why this function is removed and do we have any plan to restore or reimplement this function? If no such plan exists, which function should be used as alternative to hide folders from some specific renderers?

**Comment by SubJunk** [comment]
@mzji yes we should restore that functionality

**Comment by mzji** [comment]
@SubJunk Thanks for your rapid reply! That's a good message for me.

**Pull request merged**
