### PR TITLE
Fixed Panasonic TV UPnP detection (#918)

### PR DESCRIPTION
**Pull request by SubJunk**
Basically we were only doing this on startup which is why Panasonic TVs would only be properly identified on startup.

Not sure if this may cause other consequences ( @skeptical ?) but I did brief testing and found it causes my TV to be detected correctly at all times.

---
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/920)

### CODE REVIEW

**Comment by Sami32** [comment]
@SubJunk cool :+1:
Now we don't need to trick around anymore, the delay, around 20s on the server side and 30s on the renderer side, stay though...
Since you commit make UMS available for renderers to find a little longer, >1s, do you think change the search delay to 12000 will be fine for you ?

I meet an error, one time thought :

> INFO  2016-06-16 14:42:56.281 [background-task-0-restart(0)] Sending BYEBYE...
> DEBUG 2016-06-16 14:42:56.281 [background-task-0-restart(0)] Reading hostname: null (previous: "192.168.1.28", default: null)
> DEBUG 2016-06-16 14:42:56.296 [background-task-0-restart(0)] **Error sending BYEBYE message**
> java.io.IOException: No usable network interface found for UPnP multicast
> 	at net.pms.network.UPNPHelper.getNewMulticastSocket(UPNPHelper.java:248)
> 	at net.pms.network.UPNPHelper.sendByeBye(UPNPHelper.java:288)
> 	at net.pms.PMS$4.run(PMS.java:951)
> 	at net.pms.util.TaskRunner$2.run(TaskRunner.java:106)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> INFO  2016-06-16 14:42:56.296 [background-task-0-restart(0)] Stopping server on host 192.168.1.28 and port 5001...

[UMS-debug_PR920.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/318652/UMS-debug_PR920.txt)
[UMS-debug_PR920_error.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/318655/UMS-debug_PR920_error.txt)

**Comment by SubJunk** [comment]
I've been noticing the "No usable network interface" errors lately in master too, so I wonder if that error also happens in our main code or if it's new to this branch

**Comment by SubJunk** [comment]
I'm going to test this more tonight and if it goes well I'll merge it unless there are any objections before that

**Comment by Sami32** [comment]
@SubJunk I had never encounter this kind of error before.
I will try with your new commit.

**Comment by SubJunk** [comment]
I'm also getting that connected renderer ghost, but getting it in master too

**Comment by SubJunk** [comment]
@Sami32 is the detection better now?

**Comment by Sami32** [comment]
@SubJunk When UMS start AFTER the renderer, yes, it's like before your PR, immediatly and correctly recognized.
[UMS-debug_PR920_OK.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/326178/UMS-debug_PR920_OK.txt)

But if UMS is started BEFORE the renderer, UMS will indicated "Connected" with the green icon, but the name and icon displayed in UMS are Unknow renderer and default icon; UMS is detected by the renderer though.
[UMS-debug_PR920_NOT_OK.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/326179/UMS-debug_PR920_NOT_OK.txt)

Concerning the "ghost" comportment on the renderer side, it's still here.

**Comment by SubJunk** [comment]
@Sami32 I can see in the logs you posted that the version you were testing was from #916 and not this branch, which probably just means that's the behavior in master. Can you check it's still the same with this branch?

**Comment by SubJunk** [comment]
@valib is it working okay for you?

**Comment by Sami32** [comment]
@SubJunk My bad, i certainly forgotten to disable my _update.jar_ :-/
Sorry for my late answer, **yes it is working OK**, with around 20s delay if we start UMS before renderer, and near immediately when run after renderer.
[UMS-debug_Run.before.TV_bug.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/332175/UMS-debug_Run.before.TV_bug.txt)
[UMS-debug_PR920_Run.before.TV.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/332177/UMS-debug_PR920_Run.before.TV.txt)
If the users they want faster detection when UMS start before renderer they can use `UserAgentAdditionalHeader = X-PANASONIC-Registration`
`UserAgentAdditionalHeaderSearch = ` in their configuration file.

@valib I feel that your fingers tingle to merge it ;-)

**Comment by valib** [comment]
@SubJunk I apologize but I still have my TV connected via WiFi with the restriction that the UPnP doesn't work for me. I promise that I change it to wire to be able to test it. Anyway it works for me.

**Comment by SubJunk** [comment]
Cool, I'll merge this now :) Thanks for the feedback guys

**Pull request merged**
