### PR TITLE
Add Thai support

### PR DESCRIPTION
**Pull request by Sami32**
The more difficult was not to do it but to send it :-D
Thai user found here http://www.ps3mediaserver.org/forum/viewtopic.php?f=6&t=14193
Encodding taken from there https://docs.oracle.com/javase/8/docs/technotes/guides/intl/encoding.doc.html

If something more need to be done, or errors found, don't hesitate to give feedback !

### CODE REVIEW

**Comment by SubJunk** [comment]
What happened with this?

**Comment by Sami32** [comment]
What do you mean ?
I never get any feedback, so i just leave it.

**Comment by Nadahar** [comment]
This isn't enough to implement Thai GUI support. From a quick look it seems like if the change in ```Languages``` is reversed, it might work to support Thai subtitles.

**Comment by Sami32** [comment]
@Nadahar "Quick look" is far better that nothing :wink: 

Sorry i'm not sure to follow you...Do you mean because of Crowdin translation ?

**Comment by Nadahar** [comment]
@Sami32 I just remember that it was difficult to remember all the places that needed changing when adding a language. I planned to write it down in a code comment somewhere, but never got to it. I think one have to look through pretty much everything in "Languages" to make sure everything fits. For most languages not much must be changed, but that's not always the case. It depends on if crowdin and Java agree on the language code, and if the language is "related" to others. I don't remember the details, but I think it's pretty easy to see if you read the class.

To get a hint about where else to make changes, look at 3d393d18881bf0762566d0fe224739a4fd6dc11b.

I can add the language at crowdin, it must be done in the crowdin web interface.

**Comment by Sami32** [comment]
@Nadahar Thanks for pointing me at :)

I didn't do it because i thought that now it need to be done from Crowdin, that i don't know about and don't really want learn it now, so i can edit this as in the old time; it's perfect for me :smile:

**Comment by Nadahar** [comment]
@Sami32 It must be done from crowdin. Anything you write in the ```messages_*``` files will be overwritten by the crowdin integration. 

It's very easy to work with crowdin though, much easier that updating the files manually. Java doesn't recognize UTF-8 in .properties files - so you have to write every unicode character by its code point value. Just look at Arabic or some other non-latin language. When you use crowdin you don't have to think about that at all.

But, if you must do it in a file, I can import UTF-8 files manually at crowdin. That requires all the labels to be 100% correct though.

**Comment by Sami32** [comment]
@Nadahar OK, thanks for letting me know.

So, as it'll time month before slowly translate all, better to do that later, and for now make this PR as ready ?

**Comment by Nadahar** [comment]
@Sami32 I've made it so that a language doesn't show up in the UMS GUI until a given percentage is translated. That means everything can be made ready now, and it will automagically appear in UMS when enough translations are in.

I translated everything to Norwegian (the old Norwegian translation was so bad and outdated that it was easier to start fresh) - it took me about 5 hours. So, there's no reason why that should take months - given that you know Thai ofcourse 😉.

PM me on crowdin and I'll give you some extra permissions for Thai so that you can edit and approve/disapprove translations.

**Comment by Sami32** [comment]
@Nadahar Basic thai, not when it's about computer, so it'll be much more time consuming...and certainly not 100%.

**Comment by Nadahar** [comment]
@Sami32 From the other languages what we've seen is that once the "foundation" is made for a language, others will contribute suggestions. That's what's great about sites like crowdin...

**Comment by Sami32** [comment]
@Nadahar OK.
I like more do my humble work in a file for now, and when i'll feel i make some signifiant progress i'll try to PM you in Crowdin.

**Comment by Nadahar** [comment]
@Sami32 I rebased, added some missing details (wasn't much actually 👍) and synced with latest master. I've pushed this to branch "Thai" on this repository. I can't change the source for this PR since it's from your repository, but maybe you can? Try to click "Edit" on the top of this PR and see if you can change "from" from ```Sami32``` to ```UniversalMediaServer```.

**Comment by Sami32** [comment]
@Nadahar I'm afraid that i can only change the into base and not from.

Do you want i close and delete it, as you already made an other branch.

What did you changed ?

**Comment by Nadahar** [comment]
@Sami32 Create a new PR from the rebased branch - it's still your PR, I just added some slight details.

**Pull request closed without merging**
