### PR TITLE
Extend media receiver registrar compatibility

### PR DESCRIPTION
**Pull request by sc3141**
Certain media renderers require greater adherence to the MS-DRMND protocol than is provided by UMS' current simulation of X_AV_MS_MediaReceiverRegistrar service.  I discovered this when attempting to connect a Denon AVR-4311CI to my UMS server version 9.2.

I investigated the problem, determined the cause, and implemented a solution.  My investigation is documented in [this UMS forum topic](https://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=13984&start=10#p40872).

To fix the connection problem by MSDRM-shackled renderers, this PR does the following:
- Extend the simulation of MS-DRM service, X_AV_MS_MediaReceiverRegistear (MRR), to event subscription.
- Change the parent upnp event and control paths to the MRR service such that they match the other two services. (/upnp/event, /upnp/control).
- Add provision of a service description file on the same path as other service description file
- Change default renderer behavior to include the MRR service in the UMS descriptor (i.e. _description/fetch_).  A renderer configuration option (next item) is provided in order to allow this behavior to be disabled.  
- Add a new renderer configuration option, simulateMRR, which enables/disables exposure of MRR to a renderer (default: true)
- Retain renderer predicate function, isXbox360(), due to specialized service which extends beyond the scope of MRR

This PR _does not add a renderer configuration file for the Denon AVR-4311CI_.  I assume that incorporation of a new renderer is preferred to be done as a separate issue.

### CODE REVIEW

**Comment by SubJunk** [comment]
@sc3141 thanks for this contribution, are you still working on it or do you think it is ready to be merged?

**Comment by sc3141** [comment]
Sorry, I found/fixed a bug which I introduced which regarded the setting of the friendlyName.  Interesting phrasing by github, '_dismissed_' ... all I did was push a commit.

**Comment by sc3141** [comment]
@SubJunk, yes I think it's ready.  FriendlyName now is working as intended, which is that it only gets decorated with '_Windows Media Connect_' for the Xbox 360 i.e. the (legacy behavior). 

If you would like any follow-on work regarding the interaction of friendlyName with MRR authorization, just let me know.

I'm very impressed with UMS. I hope this PR helps a new group of users to enjoy it as much as I have.

**Comment by SubJunk** [comment]
@sc3141 it would be great to have more contributions from you, thanks in advance. Master is failing because of a third party so I'll fix that now and merge this

**Comment by SubJunk** [comment]
@sc3141 this is merged now and will be in the release I'm preparing today. Thanks!
It would be cool to see automated testing added for this to prevent future regressions. I wonder if this test file could be extended to perform that kind of check https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/test/java/net/pms/configuration/RendererConfigurationTest.java#L65

**Comment by sc3141** [comment]
> @sc3141 it would be great to have more contributions from you, thanks in advance. Master is failing because of a third party so I'll fix that now and merge this

Thank you for the kind words, @SubJunk.  I'm sure I'll be wanting to selfishly add another personally desired feature ;-).  Seriously, I'm looking forward to my next contribution.  First, I think I need to spend some more time test driving the server on my network.

> @sc3141 this is merged now and will be in the release I'm preparing today. Thanks!
> It would be cool to see automated testing added for this to prevent future regressions. I wonder if this test file could be extended to perform that kind of check https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/test/java/net/pms/configuration/RendererConfigurationTest.java#L65

I will take a look at it.  I understand the importance of unit tests on a project such as this.

**Pull request merged**
