### PR TITLE
#1664 image fix

### PR DESCRIPTION
**Pull request by drakulis**
This is fix for image load [issue](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1700#issuecomment-445046186) found by @valib after recent refactor regarding #1664

### CODE REVIEW

**Comment by SubJunk** [comment]
@drakulis thanks for this, will merge when @valib confirms :)

**Comment by valib** [comment]
@Nadahar here is used `ByteArrayInputStream` which extends `InputStream` and it uses `byte[]` as a source of the stream. So implemented method `available()` is accurate.

**Comment by Nadahar** [comment]
That said, as long as the source is a `DLNAThumbnailInputStream`, you can use `getImageInfo().getSize()`.

**Comment by drakulis** [comment]
@SubJunk we have green light from @valib

**Pull request merged**
