### PR TITLE
Playlist support

### PR DESCRIPTION
**Pull request by atamariya**
I'm trying to fix the playlist support. Here's what I've found so far:

   - Clicking add add below the media adds it to a dynamic playlist.
   - Clicking play below the media thumbnail adds it to a dynamic playlist and also opens up renderer controls. Currently clicking on play only allows the currently selected media to play. My fix will allow all the media to be played in sequence on the selected renderer.

It's still WIP. Adding media via web or Swing UI should be consistent. Let me know if you have other thoughts around this feature.

---
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/994)

### CODE REVIEW

**Comment by Sami32** [comment]
@atamariya I did the testing job, thankless but necessary ;-) So here my first feedback:

At buildind time i get an heap space error, so i increase it. Memory leaks ?

Whatever i did go for a test.
- UMS is recognized only after 3 to 5mn by my renderer ! but the renderer is immediately recognized by UMS.
[debug.log_atamariya_UPnP_3mn_20items.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/439985/debug.log_atamariya_UPnP_3mn_20items.txt)
Note: IMO DLNA should be used as first choice.
- I leave running alone in standby for perhaps more than 1 hour and when i tried to connect from my renderer no content appear; when i go check my old computer the CPU was used at 100%
[debug.log_atamariya_100%CPU.txt.7z.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/439997/debug.log_atamariya_100.CPU.txt.7z.txt)
- while running a scan of my little library the CPU was used to 100% for very long time.
[debug.log_atamariya_library scan_mediainfo0.7.81.txt.7z.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/440002/debug.log_atamariya_library.scan_mediainfo0.7.81.txt.7z.txt)
- In normal folders, i get a freeze when trying to view more than 20items; sometimes waiting and continue browsing was possible sometime not.
[debug.log_atamariya_UPnP_3mn_20items.txt.7z.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/440007/debug.log_atamariya_UPnP_3mn_20items.txt.7z.txt)
Virtual folders get the 20items bug like before.https://github.com/UniversalMediaServer/UniversalMediaServer/issues/653 https://github.com/UniversalMediaServer/UniversalMediaServer/pull/941
- WMA files was not correctly recognized, not played. MKV was recognized as MP4 and didn't played
[debug.log_atamariya_20items_MKV_4mn_iconAudio.txt.7z.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/440019/debug.log_atamariya_20items_MKV_4mn_iconAudio.txt.7z.txt)
- Audio file without thumbnail get this unecessary one
https://cloud.githubusercontent.com/assets/18471069/16095123/1e77dcc8-333b-11e6-86ea-aa2f62b6cece.jpg

I will more tests later.
Here some logs at the beginning, without waiting for a UMS recognition by my renderer.
[debug.log_atamariya_AfterTV_Start.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/440022/debug.log_atamariya_AfterTV_Start.txt)
[debug.log_atamariya_BeforeTV.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/440026/debug.log_atamariya_BeforeTV.txt)

**Comment by Sami32** [comment]
@atamariya Note about this commit https://github.com/UniversalMediaServer/UniversalMediaServer/pull/987/commits/80dd731c03fb2a0beb5075c4390bc778498ab241
RFC4288  is now obsolete and replaced by **RFC6838** https://www.rfc-editor.org/rfc/rfc6838.tx

QUESTION: What will happen with dsf, dff, aiff, aif, mpo, jps... file are , as they are missing from RFC6838 ? Do you have implemented some fallback ?
I'm asking as many new renderers are able to receive them on DLNA, though it's not yet in the latest standard specifications, maybe it will in the new version in may 2017.

**Comment by valib** [comment]
@atamariya this PR is so complex that it couldn't be merged. This is almost the same like #987. @SubJunk asked you to divide the #987 into small pieces to be able to merge them. You made a lot of interesting changes but you forgot that meantime the master branch was also changed and now is almost impossible to merge them unless you do it. In #987 you only described your changes but it is not what @SubJunk was asking you to do.

**Comment by atamariya** [comment]
@valib and @SubJunk You're right - the change is humongous. Before we talk about merge, I would like to make sure that it works!! @Sami32 is the only other person who tested and reported his problems so far. Once I have positive feedback from atleast couple of folks indicating my changes are stable , I'll merge the master into mine and then break it down to smaller pull requests for easier merge.

@Sami32 SMIL is not supported as in UMS doesn't respond with appropriate SMIL file for that request. That's what my comment indicates. UMS does support lot of subtitle formats with burn-in though.

@valib I've made a fix for following error:
`DEBUG 2016-08-29 00:17:09.991 [DEFAULT] net.sf.ehcache.util.UpdateChecker.checkForUpdate Update check failed:
java.net.UnknownHostException: www.terracotta.org`

`ERROR 2016-08-29 00:17:13.158 [%0050%004d%0053.data] n.s.e.s.d.DiskStorageFactory$DiskWriteTask.call Disk Write of 20 failed:
net.sf.ehcache.CacheException: Failed to serialize element due to ConcurrentModificationException. This is frequently the result of inappropriately sharing thread unsafe object (eg. ArrayList, HashMap, etc) between threads`
The above error is mostly harmless - doesn't break anything. I tried to avoid it. But with the way discoverChildren() method works, it's been a really difficult task. So I've put it on hold for now.

**Comment by atamariya** [comment]
On the topic, I've created a new #995 for easier merge.

@Sami32 up-sampling doesn't increase quality which is not there in the first place. Though it increases CPU usage. Without that flag, ffmpeg just uses the input sample rate.

**Comment by Sami32** [comment]
@atamariya Oups, sorry i missed that it was for upsampling :-/
So that's fine :-)

**Pull request closed without merging**
