### PR TITLE
Mimetype

### PR DESCRIPTION
**Pull request by Sami32**
Some audio Mime-type work that will appreciate your comments for improvements or corrections.

http://www.iana.org/assignments/media-types/media-types.xhtml#audio

OPUS ==> https://tools.ietf.org/html/rfc7845.html

---

This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/998)

### CODE REVIEW

**Comment by Sami32** [comment]
@SubJunk Is it OK for you ithat i create branches in your master ?
You can have the full control, and me a clean and updated file :wink: , as a begginner i found it more easy.
So please, just tell me if it's wrong.

**Comment by SubJunk** [comment]
@Sami32 what do you mean create branches in my master? Didn't you create this branch off the UMS master already?

**Comment by Sami32** [comment]
@SubJunk Yes. So if it's not the correct way just delete it and accept my apology.
As you saw i didn't use Github correctly, so the PR from my fork are "polluted", and i don't want loose some work done for later cleaning it.
I know, i need to learn how to use it correctly from their web interface, ii just didn't found the way yet :-(

**Comment by Nadahar** [comment]
@Sami32 You have done it correctly, but you use wrong terms to describe it. ```master``` is a branch like any branches, you don't create branches *in* other branches. You have created a branch in the UMS github repository, which is fine and "correct" when team members create PRs.

**Comment by Sami32** [comment]
@Nadahar Oh i see, thank you for clarifying that.
As you said my terminology was wrong, and as a matter of fact my english is poor :wink:

**Comment by SubJunk** [comment]
@Sami32 Yeah like @Nadahar said you did it correctly already :)

**Pull request closed without merging**
