### PR TITLE
HTML title set to reflect the page

### LINKED ISSUE #5039: Set HTML title to reflect the page you're on
No matter where you navigate, the HTML title stays as "Universal Media Server". It would be awesome if it could update depending on what area you navigate to, eg "Universal Media Server - TV Shows"

image

It would also speed up navigation and make browser history more meaningful:

image

### PR DESCRIPTION
**Pull request by Sanjeet4567**
# Description of code changes
Added HTML titles to reflect the current page for both 
1. dynamic pages under 'Player' and 
2. static pages

### Closes #5039 
...

# Checklist
- [x] Any relevant issues are [#5039](#5039)
- [ ] Any relevant [Knowledge Base](https://github.com/UniversalMediaServer/knowledge-base) articles are written/modified
- [ ] Any relevant tests have been written/modified

### CODE REVIEW

**Comment by Sanjeet4567** [comment]
Result images

Screenshot 2024-10-28 151318
Screenshot 2024-10-28 151603

**Comment by Sanjeet4567** [comment]
@SubJunk  please merge this with hacktober accepted label

**Review by SubJunk — CHANGES_REQUESTED** [review]
It would be good to be consistent with the spacing. Some of these are using `Universal Media Server-Page name` others are `- Page name`.
The best would be like `Universal Media Server - Page name`

**Comment by Sanjeet4567** [comment]
@SubJunk I have made the requested changes. If anymore chnages are required ,let me know.

**Comment by SubJunk** [comment]
Thanks for your contribution!

**Pull request merged**
