### PR TITLE
Chromacast lib update

### PR DESCRIPTION
**Pull request by Sami32**
- Should fix this issue: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1030
See the work done there: https://github.com/vitalidze/chromecast-java-api-v2/issues/66#issuecomment-277509430

Thanks to @vitalidze

### CODE REVIEW

**Comment by Sami32** [comment]
It seem that some compilation issue appear:

> [ERROR] /home/travis/build/UniversalMediaServer/UniversalMediaServer/src/main/java/net/pms/network/ChromecastMgr.java:[46,33] no suitable constructor found for ChromeCast(javax.jmdns.JmDNS,java.lang.String)
>     constructor su.litvak.chromecast.api.v2.ChromeCast.ChromeCast(java.lang.String,int) is not applicable
>       (actual argument javax.jmdns.JmDNS cannot be converted to java.lang.String by method invocation conversion)
>     constructor su.litvak.chromecast.api.v2.ChromeCast.ChromeCast(java.lang.String) is not applicable
>       (actual and formal argument lists differ in length)

**Comment by Sami32** [comment]
> [ERROR] /home/travis/build/UniversalMediaServer/UniversalMediaServer/src/main/java/net/pms/network/ChromecastMgr.java:[46,33] no suitable constructor found for ChromeCast(javax.jmdns.JmDNS,java.lang.String)  constructor su.litvak.chromecast.api.v2.ChromeCast.ChromeCast(java.lang.String,int) is not applicable (actual argument javax.jmdns.JmDNS cannot be converted to java.lang.String by method invocation conversion) constructor su.litvak.chromecast.api.v2.ChromeCast.ChromeCast(java.lang.String) is not applicable  (actual and formal argument lists differ in length)

**Comment by Sami32** [comment]
Whatever i tried give me a compilation error. Something is wrong but i don't get it.

**Comment by Nadahar** [comment]
@Sami32 h vitalidze/chromecast-java-api-v2@8ceb2aa41c0f18376ed08c4092a995b20fcee656 happened. They have hidden the constructor UMS used. I don't know why, but our implementation was probably using it wrong.

If you would just stop being so stubborn and install Eclipse, you would see it right away. You don't have to build, you don't have to push or run tests to get the error - you get a red underline with a very easy to understand text telling you what's wrong:

hidden-constructor

**Comment by Sami32** [comment]
@Nadahar That's nice, but since he told me and that i read their PR, i don't give more informations that 'm able to use anyway.

**Comment by Nadahar** [comment]
@Sami32 Yes, I saw that - what I mean is that you would have discovered this instantly yourself if you had used a proper tool.

I just pushed a little hack to get around this for now. I have no way to test this, so I don't know if it will work - you will need to get someone with a Chromecast to test it. But, it compiles at least.

**Comment by Sami32** [comment]
@Nadahar Thanks. Luckily we have one ;-)

**Comment by Sami32** [comment]
@Nadahar Do you have a lossless JPEG images to send me (zipped) ?

**Comment by Nadahar** [comment]
Sorry, nope. I haven't looked it up even though they should probably be tested with #1061. It's set up to convert them to lossy JPEGs though, there's no support for lossless in DLNA.

**Comment by Nadahar** [comment]
@Sami32 I found a way to achieve the same without using reflection. Reflection is always a last resort, so I've changed the implementation again. This should do exactly the same as the previous implementation. I have no idea if the code is sound in general, but it fixes the issue with the hidden constructor.

**Comment by Sami32** [comment]
@Nadahar Great :)

Since i totally rely on you for that, please make it ready when you think it's.

**Comment by Nadahar** [comment]
I'm done with it, it still needs testing though.

**Comment by Nadahar** [comment]
@Sami32 I'm not sure it can be tested here, you'd probably have to build it and upload it somewhere to let the Chromecast users test it..

**Comment by Sami32** [comment]
@nadahar It's my target, but in case @subjunk would like run a test...

**Comment by Sami32** [comment]
@Nadahar If we believe that user, that work for him now.
Nice work ;-)

**Comment by Nadahar** [comment]
@Sami32 Yes, but it seems all is not well [#1030](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1030#issuecomment-280968542).

**Comment by Sami32** [comment]
@nadahar Yes, i suspect a network issue in his case. Since he ver trued with an other media server it's difficult to be sure but...
He have a bad renderer configuration, that can be easily fixed and have nothing to do with this PR.

An other possibility is that network issue come from UMS, but it'll be an other issue not related to this PR.

Thanks ;-)

**Pull request merged**
