### PR TITLE
ID and web interface fixes

### PR DESCRIPTION
**Pull request by SubJunk**
This branch has various fixes to bugs I've found while trying to fix the bug where the ID of TV series keeps changing with the old one disappearing, leading to broken browsing on my TV and the web interface

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib if you have any idea why every folder in the Media Library keeps the same IDs except the TV seasons, that would be really helpful

**Comment by SubJunk** [comment]
@valib thanks for fixing that :)

I am starting to make the `isRefreshNeeded` in `MediaLibraryFolder` smarter so it only returns true when the result from the database has changed. That should greatly reduce the number of extra (global) IDs and `DLNAResource`s we create while using the Media Library.

If you can think of a reason not to do that please let me know.

**Comment by SubJunk** [comment]
@valib I've pushed the change now but I haven't tested it yet, just hammered out the code while I had time

**Comment by SubJunk** [comment]
@valib actually I just did some quick testing and it seems to work well so far.

To test I went into a folder in the Media Library via web interface, and refreshed the page, and observed that the IDs of its contents do not change. Then I added a new file to the hard drive that would end up in that folder (I was in `Media Library > Video > Unwatched > Unsorted` and I just copied a random video file I had) then refreshed, and all of the IDs on the page got updated, and the new file displayed on the page.

**Comment by valib** [comment]
@SubJunk I have got an error
`DEBUG 2019-02-24 23:27:25.729 [pool-6-thread-29] Make browse page 25
ERROR 2019-02-24 23:27:25.739 [pool-6-thread-29] null
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "TYPE[*] = 4 ORDER BY FILENAME ASC"; expected "TRUNCATE, {"; SQL statement:
TYPE = 4 ORDER BY FILENAME ASC [42001-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.getSyntaxError(DbException.java:205)
	at org.h2.command.Parser.getSyntaxError(Parser.java:541)
	at org.h2.command.Parser.parsePrepared(Parser.java:526)
	at org.h2.command.Parser.parse(Parser.java:321)
	at org.h2.command.Parser.parse(Parser.java:297)
	at org.h2.command.Parser.prepareCommand(Parser.java:258)
	at org.h2.engine.Session.prepareLocal(Session.java:578)
	at org.h2.engine.Session.prepareCommand(Session.java:519)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at net.pms.dlna.DLNAMediaDatabase.getStrings(DLNAMediaDatabase.java:1326)
	at net.pms.dlna.virtual.MediaLibraryFolder.doRefreshChildren(MediaLibraryFolder.java:127)
	at net.pms.dlna.virtual.MediaLibraryFolder.discoverChildren(MediaLibraryFolder.java:58)
	at net.pms.dlna.DLNAResource.discoverChildren(DLNAResource.java:1449)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1312)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1234)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:43)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:234)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by SubJunk** [comment]
I fixed that in master but didn't sync this branch, will do now

**Comment by SubJunk** [comment]
It's still broken so I'm fixing it now

**Comment by SubJunk** [comment]
@valib could you please retest?

**Comment by SubJunk** [comment]
I have verified that it fixes the problem on my TV where I couldn't scroll down past 20 items within a TV season. I think this is in a good state to be merged

**Comment by SubJunk** [comment]
@valib thanks!

**Pull request merged**
