### PR TITLE
Fix application restart and "Create TRACE Logs" take 2 (#1304, #1183, #1305)

### PR DESCRIPTION
**Pull request by Nadahar**
This is a continuation of #1305 which was reversed because the appbundler wasn't compiled for Java 7. I don't have Java 7 on my OS X VM, and I don't feel like trying to install both os macOS (given how everything is integrated with xcode and it's the world of apples).

I've compiled it with Java 8 but with Java 7 as ```target```, which should work as far as I understand. You'll have to test this before merge @SubJunk and verify that it really works on Java 7.

### CODE REVIEW

**Comment by Nadahar** [comment]
I did, against my better judgement, install both Java 7 and 8 on one of my macOS VMs. I didn't work, it turns out it had to be built with Ant 1.9 as well (I used 1.10, but 1.10 doesn't support Java 7).

Now the appbundler works under both Java 7 and Java 8 according to my testing, but I still think @SubJunk should verify before merge.

**Comment by SubJunk** [comment]
Cool, I hope to test it this weekend

**Comment by Sami32** [comment]
@SubJunk I use it as a quality/issue barometer:
https://sourceforge.net/projects/unimediaserver/files/Official%20Releases/OS%20X/
https://sourceforge.net/projects/unimediaserver/files/Official%20Releases/Linux/

_Fossub_ seem to be good as a quantity barometer, IMO.

**Comment by valib** [comment]
@SubJunk not related to this PR but after the @Sami32 comment about the quality I have to make a comment. It seems that this project when it reached the top in 2016 is now [stagnating](https://sourceforge.net/projects/unimediaserver/files/stats/timeline?dates=2013-02-01+to+2017-07-23). Mayby it is related to the fact that the Forum, PRs and Issues are not properly managed. When I read reactions on the Forum there are active @Sami32, @Nadahar and sometimes me but you are involved rarely in the last time. The same is in PRs and Issues. I can understand that you have other activities whose not allow you to be on line every time but you are the owner of this project and the leader of our small group so your guidence and evaluation is needed if you want to continue in this project. Othervise it will finish like PMS.

**Comment by SubJunk** [comment]
@valib your concerns are good here and thanks for posting them.

I have more time to spend on UMS development but until master is back to a less buggy state than it was at the time of the last 7.0.0 release, we are stuck. I want to release that to our users, and that's the feature-set I was working the most on.

We have users giving up on UMS because our last few releases have introduced so many bugs and I'm also frustrated about that. We can't expect users to stay with us while we experiment with big refactors and break the things they have relied on us for for years.

Sure we always had bugs around the edges of our common use cases, but 99% of our users just do that same thing (browse to videos via DLNA and watch them) and we have had big bugs with that core functionality lately. That can't keep happening if this project is to survive.

I suspect that the way forward is to introduce some stability back to UMS and that will mean getting more strict on peer reviewing again. Happy for input on this from you guys.

**Comment by SubJunk** [comment]
By the way, we moved to FossHub in April 2016 which is exactly when that SourceForge downloads graph dropped away. The downloads didn't go down, they just moved to a different website.

**Comment by Sami32** [comment]
@SubJunk What about that ? It seem that it was an advised suggestion, still more now, isn't it ?
> @SubJunk Great. To be honest I was hoping this would make it into one of your betas before it was released as a "full release", it's hard to know that nothing has snuck in when you change so much.

https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1061#issuecomment-291190366

**Comment by SubJunk** [comment]
@Nadahar I didn't know you had fixed all but the 360 issue. I thought we were waiting on a bug that stops playback being possible on some renderers because of thumbnail formats, I can't remember the exact details. Maybe I should have posted updates on my access to a 360 but I have been trying to get access to one for weeks and have been unable due to things out of my control.

I want to get this project back on track and will be more active with its development. I had a new baby and house last year and significant personal difficulties followed that meant less free time to spend on this, but now my situation is more stable and I am motivated to keep this moving forward.

It seems you guys (at least @Nadahar and maybe @Sami32 ) jumped ship to DigitalMediaServer before this conversation, and that has been pretty upsetting for me to watch, especially since I was in the process of handing over more control of UMS to you @Nadahar with release abilities. I don't see the point in starting another project when you have almost full autonomy with this one. It would've been good to get a heads up on that but I haven't heard anything about it.

@Sami32 I wasn't blaming @Nadahar for the instability since I'm also to blame - I did the FFmpeg update and let it go through without enough testing, and as a result we had users unable to play transcoded videos, which for some users is most videos. My comment was meant to be about our processes in general, that we need more quality control.

I really admire the refactoring and programming ability that you have @Nadahar and I have a love/hate relationship with it. It makes our code nicer and more stable going forward but can cause short term instability. We have talked about it a lot in the past so there's no point going into it again, but the fact is I put my hesitations to the side and trusted in your abilities, and I think that has led to an improved program, so thank you for your significant contributions.

As for the assertion that I didn't test #1061 see the comments that preceded the merge https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1061#issuecomment-291059080
I tested it at other points along the way too and left detailed peer reviews asking questions which you responded to, and I updated dcraw for it; I was involved and collaborated on that PR.

Maybe we should have released it as a beta as well. It seemed messy at the time to have a 6.x beta going as well as a 7.x beta, and I didn't want to mix the testing of that refactor with the 7.x feature testing since it would be harder to know which changes caused any issues that were found. Maybe that was the wrong decision from me though and I will learn from that mistake.

**Comment by Nadahar** [comment]
@SubJunk I haven't "jumped ship" and I certainly don't think @Sami32 has either. I started DigitalMediaServer early 2016 as I said I would "go my own way". My idea has been that when there's PRs that's useful in both projects I might as well submit it to UMS, and when there are things I assume isn't interesting to UMS I will do that in DMS. I haven't worked on in much during this winter though, as I've had my hands full with UMS work (that I also consider DMS work). When there are changes that "fit in both projects" it's preferrable to do them in UMS because it's possible to get user feedback. 

DMS has no users and no releases, and I don't think it will have for a long while yet. It's my "playground" where I can make things what I consider "properly" and doesn't have to worry about backwards compatibility for plugins.

With what has happened lately, I think you will understand why I've decided to work more on DMS instead, as I'm so tired of all the restrictions, the constant battle to try to keep the git history readable and especially being blamed like I have now. Since you aren't much around and I feel there's a history of my approach not being my appreciated, I haven't informed you that much about my thoughts/ideas - and I've tried to work on the parts of UMS that doesn't concern the "video users". That said, if you (or anyone else) would have asked what I was thinking at any point in time, I would have explained. I simply don't feel that there's much interest.

The reason for my "strategy" on working with images and a bit audio is that when is being done there can ultimately be used for video as well (because I strive to make everything as general as possible), but it limits the impact on most users because as you point out the majority use it for video.

While I appreciate the fact that I can get actual user feedback and test the code, it's not worth it when there is too much trouble internally. Then I'd rather just make the code and then deal with potential problems as they appear later.

**Comment by SubJunk** [comment]
> I haven't "jumped ship" and I certainly don't think @Sami32 has either. I started DigitalMediaServer early 2016 as I said I would "go my own way". My idea has been that when there's PRs that's useful in both projects I might as well submit it to UMS, and when there are things I assume isn't interesting to UMS I will do that in DMS. I haven't worked on in much during this winter though, as I've had my hands full with UMS work (that I also consider DMS work). When there are changes that "fit in both projects" it's preferrable to do them in UMS because it's possible to get user feedback.

> DMS has no users and no releases, and I don't think it will have for a long while yet. It's my "playground" where I can make things what I consider "properly" and doesn't have to worry about backwards compatibility for plugins.

Ok, thanks for explaining. I still don't understand why you can't make branches that do that stuff anyway, but maybe it's cleaner to do a fork.

> With what has happened lately, I think you will understand why I've decided to work more on DMS instead, as I'm so tired of all the restrictions, the constant battle to try to keep the git history readable and especially being blamed like I have now. Since you aren't much around and I feel there's a history of my approach not being my appreciated, I haven't informed you that much about my thoughts/ideas - and I've tried to work on the parts of UMS that doesn't concern the "video users". That said, if you (or anyone else) would have asked what I was thinking at any point in time, I would have explained. I simply don't feel that there's much interest.

I don't know what has happened lately that is so bad, I think your perception of it is different to mine. I'm not aware of restrictions - you are able to create a pull request and have it merged as long as it is peer reviewed and tested. Do you want to be able to skip peer review or testing, or do you mean other restrictions I haven't considered?

As for the Git history being readable, I usually squash commits when I merge Pull Requests, so if we all remember to do that on merge unless there is good reason not to (like if someone has gone through and organized the commits already) then I don't see a problem. It can't get more organized than one commit per PR, right?

I read, and I have always read, everything that happens on this project. I get emails when anything is posted and I go through them daily. Sometimes I haven't been able to immediately respond to things, and sometimes tags fall through the cracks, but I do make an effort even when I am busy. This project is important to me. I still use the program every day, and I still have ambitions for it and motivation to spend more time on it.

> The reason for my "strategy" on working with images and a bit audio is that when is being done there can ultimately be used for video as well (because I strive to make everything as general as possible), but it limits the impact on most users because as you point out the majority use it for video.

That's a good reason for that strategy.

> While I appreciate the fact that I can get actual user feedback and test the code, it's not worth it when there is too much trouble internally. Then I'd rather just make the code and then deal with potential problems as they appear later.

It seems to me that the troubles being experienced here are mostly to do with me not being communicative enough and not being around here enough. I take responsibility for it and I will do better at those things.

**Comment by Nadahar** [comment]
@SubJunk With "restrictions" I refer to all the previous discussions about not breaking plugins and keeps tons of deprecated code that makes it much harder to see the actual, relevant warnings and read the code. I'm also referring to the reluctance to clean up all the thread issues and the general idea of applying band-aids to broken code instead of fixing it properly.

In my own fork I can choose not to apply those commits or to fix them before doing so, which I believe results in much less problems in the future.

**Comment by SubJunk** [comment]
About the plugin stuff, I'm still interested in exploring the options in https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1276
We aren't under any obligation to keep plugins working, so if support for a plugin breaks along the way then that's fine and we can remove that plugin from the list. There is a difference between the support breaking along the way vs. just removing deprecated code though.

I'm in favor of removing deprecated code that our plugins do not use, and 7.0.0 represents a good opportunity for that.

**Comment by SubJunk** [comment]
Passed testing on macOS, merging

**Pull request merged**
