### PR TITLE
main fix 4807

### LINKED ISSUE #4807: Web video support broken
It looks like support for all web videos has been broken for a long time, since v11. I thought it was just YouTube but it is also broken for e.g. https://feeds.feedburner.com/tedtalks_video
If I run UMS v10 it works, but all releases since v11 are broken.

I think it never worked since the HLS refactoring https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2880

It seems the video is not parsed before the HLS helper receives it, so this error happens:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because "duration" is null
	at net.pms.encoders.HlsHelper.getHLSm3u8ForRendition(HlsHelper.java:290)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.sendMedia(PlayerApiServlet.java:1144)
	at net.pms.network.webguiserver.servlets.PlayerApiServlet.doGet(PlayerApiServlet.java:117)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at net.pms.network.webguiserver.GuiHttpServlet.service(GuiHttpServlet.java:61)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:858)
	at org.eclipse.jetty.server.Server.handle(Server.java:181)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:648)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:403)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by SurfaceS**
fix #4807

implements FFmpegHlsVideo as engine
implements TranscodingSettings (allow multiple encoding format)
docs TranscodingSettings in default renderer conf
engine is now found for item from TranscodingSettings
fix mp4 moov

@SubJunk about [fix mp4 moov](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4823/commits/be4438aa78e18b4f38b2152022a3b2cd489002c4), you should read my comment.

### CODE REVIEW

**Comment by SubJunk** [comment]
@SurfaceS cool, I will do some testing with my devices

**Comment by SubJunk** [comment]
When I first ran it, the new `FFmpegHlsVideo` engine was disabled. I think it should be enabled by default. There is existing logic for that here https://github.com/UniversalMediaServer/UniversalMediaServer/blob/main/src/main/java/net/pms/PMS.java#L314-L327

**Comment by SubJunk** [comment]
About the mp4 moov, there is a bug in FFmpeg when the input is eac3 that causes a crash when using `frag_keyframe+empty_moov`:

```
DEBUG 2024-07-18 10:22:32.607 [ffmpeg-28-2] [mp4 @ 0x14ce0e300] track 1: codec frame size is not set
DEBUG 2024-07-18 10:22:32.607 [ffmpeg-28-2] [mp4 @ 0x14ce0e300] Cannot write moov atom before EAC3 packets parsed.
DEBUG 2024-07-18 10:22:32.607 [ffmpeg-28-2] [out#0/mp4 @ 0x6000037b0300] Could not write header (incorrect codec parameters ?): Invalid argument
DEBUG 2024-07-18 10:22:32.607 [ffmpeg-28-2] [vf#0:0 @ 0x6000030b19e0] Error sending frames to consumers: Invalid argument
DEBUG 2024-07-18 10:22:32.607 [ffmpeg-28-2] [vf#0:0 @ 0x6000030b19e0] Task finished with error code: -22 (Invalid argument)
DEBUG 2024-07-18 10:22:32.607 [ffmpeg-28-2] [vf#0:0 @ 0x6000030b19e0] Terminating thread with return code -22 (Invalid argument)
```

But using `frag_keyframe+faststart` does not have that problem

**Comment by SurfaceS** [comment]
@SubJunk 
I'll not be available for a week.

**Comment by SubJunk** [comment]
@SurfaceS I will test again

**Comment by SubJunk** [comment]
I have confirmed the EAC3 bug does not happen now

**Comment by SubJunk** [comment]
Nice work. I will do a couple of the related issues to make it easier to add YouTube channels, will write a knowledge base article, then will release it

**Pull request merged**
