### PR TITLE
Respect the renderer setting H264Level41Limited when deciding whether to stream or transcode

### PR DESCRIPTION
**Pull request by SubJunk**

### CODE REVIEW

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers I think this one can be merged pretty quickly, I've tested it and it works well

**Comment by Sami32** [comment]
@SubJunk Cool, that's a good idea.

**Comment by Nadahar** [comment]
@SubJunk I've pushed a minor tweak. The reasons for the changes are:
* The reason to use ```{}``` instead of concatenating strings when making logging calls isn't just aesthetic - the main point is to avoid having do run a StringBuilder when the results are not going to be used (when debug level != trace). Whenever you concatenate strings with ```+``` in Java the compiler makes it into a StringBuilder, which is said to be very expensive in Java. When passed unconcatenated LogBack makes sure to only build the finished string *if* the message is actually used.

**Comment by Nadahar** [comment]
@Sami32 I've already changed the null handling in 9569f7de044264495152f999a84ffcd31275cabf :wink:

**Comment by SubJunk** [comment]
@Nadahar and @Sami32 thanks for the improvements :)

**Pull request merged**
