### PR TITLE
v14.1

### PR DESCRIPTION
**Pull request by SurfaceS**
# Description of code changes

Implements latest Jetty (v12.0.8).
Implements latest JUPnP (v3.0.1).
Removed the JDK HTTP servlet server (personal implementation).
Stop using the deprecated tool 'Create React App' (no longer being maintained)
Implements Vite as replacement.

The webgui / webplayer are now served by Jetty (servlet).

# Goal of the version

Remove multiple engine maintenance.
Remove Netty without stress.  #4058

# To test
We should focus on the webgui / webplayer tests first, as it is now served by Jetty servlets.
It will be easy to test as it is not changing settings / database or so that will break if we revert to v14 build.

Netty is kept as the default engine, letting us time to fix Jetty implementation (by changing the default engine in the GUI settings).
Once Jetty implementation is fully tested, we can remove all Netty related things (engine, deps, and so on).

# Checklist
- [x] Any relevant issues are [referenced](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#referencing-issues-and-pull-requests)
- [x] Any relevant [Knowledge Base](https://github.com/UniversalMediaServer/knowledge-base) articles are written/modified
- [x] Any relevant tests have been written/modified

### CODE REVIEW

**Comment by SubJunk** [comment]
I have been running https://github.com/UniversalMediaServer/UniversalMediaServer/commit/b4b68bb2f35cd7992386cd42b072210809c1d272 for a couple of days and it seems good. Will switch to this one now

**Comment by SubJunk** [comment]
I have a blank page web player browse on https://github.com/UniversalMediaServer/UniversalMediaServer/commit/e6c8bec1a305764dabebcbbdfe21fa6710436cfb

I don't see any obvious problems like failed requests
image

Want logs?

**Comment by SurfaceS** [comment]
> Want logs?

No, it is fixed now

**Comment by SubJunk** [comment]
@dependabot recreate

**Comment by SubJunk** [comment]
This branch is working well for me, but I am mostly a TV user so I don't use the web player much. Is there anything specific I should be testing? Is this branch finished?

**Comment by SurfaceS** [comment]
> This branch is working well for me, but I am mostly a TV user so I don't use the web player much. Is there anything specific I should be testing?

no, but as their is a lot of change on the react gui (new app builder, new http server, new videojs, new mantine), that's why I'd said to focus test on it.

> Is this branch finished?

should be yes.

**Comment by SubJunk** [comment]
@SurfaceS ok cool, are you happy for it to be merged? I haven't found any problems with it

**Comment by SurfaceS** [comment]
> @SurfaceS ok cool, are you happy for it to be merged? I haven't found any problems with it

@SubJunk yes.

next step (v14.2) will be to use the jetty media server implementation as default, then we can remove completely netty.

**Comment by SurfaceS** [comment]
@SubJunk I made a cleanup in the changelog, then it will be easier to merge, after you build the `14.0.1` to fix `14.0.0` regressions.

I think we should build the `14.0.1` before releasing the `14.1.0`, as you may not want to give the `14.0.0`, that users will create issues (regression) already solved on `14.0.1`.

**Comment by SubJunk** [comment]
@SurfaceS ok, I will release 14.0.1 today

**Comment by SubJunk** [comment]
I got this error on this branch, not sure whether it is related to it

```
08:34:07 INFO  Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Window.pack()" because the return value of "javax.swing.SwingUtilities.getWindowAncestor(java.awt.Component)" is null
08:34:07 INFO  	at net.pms.swing.gui.tabs.status.RendererFrame.buildEditBar(RendererFrame.java:131)
08:34:07 INFO  	at net.pms.swing.gui.tabs.status.RendererFrame.buildPanel(RendererFrame.java:99)
08:34:07 INFO  	at net.pms.swing.gui.tabs.status.RendererFrame.update(RendererFrame.java:78)
08:34:07 INFO  	at net.pms.swing.gui.tabs.status.RendererPanel.lambda$updateRenderer$1(RendererPanel.java:200)
08:34:07 INFO  	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
08:34:07 INFO  	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
08:34:07 INFO  	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
08:34:07 INFO  	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by SurfaceS** [comment]
> I got this error on this branch, not sure whether it is related to it
> 
> ```
> 08:34:07 INFO  Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Window.pack()" because the return value of "javax.swing.SwingUtilities.getWindowAncestor(java.awt.Component)" is null
> 08:34:07 INFO  	at net.pms.swing.gui.tabs.status.RendererFrame.buildEditBar(RendererFrame.java:131)
> 08:34:07 INFO  	at net.pms.swing.gui.tabs.status.RendererFrame.buildPanel(RendererFrame.java:99)
> 08:34:07 INFO  	at net.pms.swing.gui.tabs.status.RendererFrame.update(RendererFrame.java:78)
> ```

It is not related to this branch, but it is fixed now

**Comment by SubJunk** [comment]
This is working really well for me. The performance improvement while browsing is very noticeable on my TV

**Pull request merged**
