### PR TITLE
Docker image using "with-dependencies.jar"

### PR DESCRIPTION
**Pull request by atamariya**

### CODE REVIEW

**Comment by SubJunk** [comment]
Looks good to me, is it ready to merge?

**Comment by SubJunk** [comment]
I pushed it to docker as `universalmediaserver/ums`, it doesn't have any of the binaries though like FFmpeg, how do we get that in there?

**Comment by atamariya** [comment]
@SubJunk all the binaries (linux) required can be copied to the docker folder before building.

**Comment by SubJunk** [comment]
That's done now, and pushed

**Pull request merged**
