### PR TITLE
Misc bug fixes to FileUtil

### PR DESCRIPTION
**Pull request by Nadahar**
@UniversalMediaServer/developers This started out as a simple bugfix for [this bug] (http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=6011). But, after fixing that bug I ran FindBugs and Threadsafe, and this lead to much more (and changed this from being a commit to a PR).

I hope we can expedite this once quickly, as there's no (intended) behaviour change here. I have multiple questions and comments though, so this needs to be reviewed. I'll make the comments in Reviewable.

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/813)

### CODE REVIEW

**Comment by Nadahar** [comment]
There were some use of unprotected static class variables here. That is "single threaded" mindset, and something we have to stop doing. While storing things between methods in class variables can be convenient, it's very error prone if multiple threads invoke any of the involved methods even without corruption due to unsynchronized access. I've replaced those that didn't have to be class variables with locals, and protected those that had to be class global.

---

Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 248 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E6QK9Bd5xRPDqOkan:-K9E6QK9Bd5xRPDqOkao:1635805869) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L248)):*
These are a big no-no, and there were no need for them either.

---

*[src/main/java/net/pms/util/FileUtil.java, line 253 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E6fBc7ggaV90HdglC:-K9E6fBc7ggaV90HdglD:-1186322174) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L253)):*
Generally void methods should ring a bell, for them to do anything useful they have to work on some shared object. It static as well, the alarm should really go off it no protection is in place. I've made all these return their results instead of storing them in shared variables.

---

*[src/main/java/net/pms/util/FileUtil.java, line 266 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E8Q2A3vdfhh7ukIM2:-K9E8Q2A3vdfhh7ukIM3:-2013137891) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L266)):*
@valib I removed loopedOnce as I couldn't see that it was used for anything. It was always false when any of these methods were invoked, and primitives doesn't return their state so if the intention was that changes to this should change the same named variable in the calling method, it won't work. If that is needed for this to work, this must be further rewritten.

---

*[src/main/java/net/pms/util/FileUtil.java, line 268 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E7TizDVIHq91Q0kWQ:-K9E7TizDVIHq91Q0kWR:-97065336) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L268)):*
@valib I can't see what's the difference in result between this once and the overloaded version of ```convertFormattedNameToTitleCase()```. I had to rename this one to ```Parts``` because after removing the inactive loopedOnce variable there was nothing separating the two. 

I don't understand why it's necessary to split them on ```-``` and capitalize them separatly - is that really necessary?

---

*[src/main/java/net/pms/util/FileUtil.java, line 275 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E86B4gfKgiJA_0QVX:-K9E86B4gfKgiJA_0QVY:-229269423) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L275)):*
Looping and modifying a String is very inefficient, using a StringBuilder instead.

---

*[src/main/java/net/pms/util/FileUtil.java, line 720 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EA6Oa9Ad1g7vXpNJ0:-K9EA6ObGYao9-ZsLKPP:1643606801) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L720)):*
This code must have been flawed. What's the point of having a cache if it's cleared as soon as one call where ```useCache == false``` is made. The whole method was synchronized, which I removed, since only a small part actually needed to be protected. There's no need to hold a lock longer than necessary. 

The implementation is still very inefficient (thus my comment) as it will lock the whole cache while browsing one folder. It should be locked on a per-folder basis so multiple folders could be populated at once and then inserted into the cache, but that requires more rewriting than I was up to now - and I'm unsure when/how often this is called, although I assume it's whenever a renderer browses a folder, which will make multiple renderers have to wait for eachother.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9EBeubLiJObu5VsJtd:-1051010857) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
This was the original bug I was fixing, it assumes to much about the string (it seems to have been written only thinking about the case at hand, not how it would work in general). It would crash out in a ```StringIndexOutOfBoundsException``` whenever a file or folder name ended with a ```]```, and it could also remove much more than intended depending on where the square braces was placed. I've redone it using regex instead, imposing stricter rules for when it will act. I don't know how long these anime "tags" can be, but I've currently restricted the length between the square braces to 10 characters (that has to be at the start of the String) for this to act.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1358 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EClGGWlbfEW1WGa-s:-K9EClGHQUOusw_M6zr4:1646114412) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/a1728a5fe5d8b6d2daeffcbffbbfa58fd9dfc3a8/src/main/java/net/pms/util/FileUtil.java#L1358)):*
Fixed a missing stream close.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-:-K9E5OGgG3xJEVweIPTI:-183707127)*

**Comment by Nadahar** [comment]
@SubJunk It's a shame you tagged without this one, the bug is on the forum and is "fixed" there, so people will expect it to be fixed in the next version. I've seen this error in many logfiles, but never knew what it was.

**Comment by SubJunk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 268 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E7TizDVIHq91Q0kWQ:-K9Gf-5TtqKMbkBW147l:2023745848) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L268)):*
I probably should've written comments for that part of the code, since I don't know why it does it at a glance. I do remember having a good reason for that and the loopedOnce variable.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9GdrqrMm_Yf5Ruzyh_:741476736) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
10 characters won't be enough for popular release groups. 20 would be safer.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by valib** [comment]
*[src/main/java/net/pms/util/FileUtil.java, line 266 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E8Q2A3vdfhh7ukIM2:-K9GsmRqTI03FL9bQbyW:-985468683) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L266)):*
@Nadahar I only a little bit rewrote the original code so and the loopedOnce was there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by valib** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 266 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E8Q2A3vdfhh7ukIM2:-K9HLlaWCqupykGuQHz7:1852856968) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L266)):*
Yes, but my guess is that in the original code loopedOnce's value was remembered between each run - then it would make some sense. The only way to figure this out properly is to go back in git history and look at earlier code.

---

*[src/main/java/net/pms/util/FileUtil.java, line 268 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E7TizDVIHq91Q0kWQ:-K9HMI3b4E3sQYHoH9U-:1485437710) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L268)):*
Yes, but the question is if that still applies the way the code was now. I suspect that the loopedOnce function has since been lost, for it to have any meaning it must have been retained between runs.

Splitting on ```-``` is very hard for me to see how could have any effect the way the code works now. The method that's called on the separate strings (or the total string in the other variant) splits on space and then loops and replaces the first letter of each word with a capital letter except for certain words. It's very hard to see how the results of this can possible differ when treating a long string versus several shorter ones.

To get to the bottom of this I think the original code must be studied, and the changes done since that must be identified and taken into consideration.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9HOLoPRjDyR7e8v8l4:5174689) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
ok

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by SubJunk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 268 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E7TizDVIHq91Q0kWQ:-K9Kf4-XNRbJLQUybqaG:-817946757) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L268)):*
It looks like it was just a different way of doing exactly what you've rewritten - making sure that the " - " is added to all iterations except the first one. Doing the length check achieves the same thing so this is fine for reformatting.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 268 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E7TizDVIHq91Q0kWQ:-K9KlhAo4efGmDAhnFh2:558531262) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L268)):*
Yes, that part is obvious to me. The part I didn't understand was that the variable was passed as an argument to the method, and was always false. A logical way to do that would have been to use a local variable that was initialized to false. Because of the way it was done, it seems to me that it was somehow supposed to "remember" if it was true from one method call to another, but since this is a primitive (not a reference), that won't work and the value will never be "returned" to the caller.

What I'm afraid of is that this was the functionality at one stage, and that it has been "lost in refactoring". If not, the passing as argument was meaningless and this implementation should work well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9LIoQULHNDdN4UonLn:1479510348) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
I've changed it to 20 characters.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by SubJunk** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 268 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9E7TizDVIHq91Q0kWQ:-K9Lxv0JOghkYSBdJm2O:-552311755) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L268)):*
The loopedOnce variable doesn't need to be passed as a parameter to the method.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9LyENJH78osqHkJK-m:232232202) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
Cool. I'll test it this week if I get a chance.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by SubJunk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by valib** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9fciU8Gc-DQQ3c4zOG:610963288) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
Did you have a change to test this?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by SubJunk** [comment]
@Nadahar I just tested it and it seems to have changed the file ordering

**Comment by SubJunk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9jnNzIjYdhhyi_rWlk:-1758849584) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
I just tested it and it seems to have broken file ordering for files that use underscores for spaces. This is the order of some files after this change:

[DeadFish]_Natsume_Yuujinchou_-_01 [BD][720p][MP4][AAC].mp4
The.100.S02E02.1080p.BluRay.x264-SHORTBREHD.mkv
Banshee.S03E08.1080p.HDTV.x264-BATV.mkv

Whereas it should be the other way around - the correct order being "1, B, N" instead of "N, 1, B"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9mFXYx_tgXLrD7EM4u:-1078990417) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
@SubJunk I just tested in current master, and it lists them in the exact same order. What settings do you use (Prettifying and sorting)? Have you compared to master and found a regression in this PR?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9mGudOjijGdDAsX91I:-1575311002) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
When I turn on prettifying and set sorting to alphabetic, I get the exact same sort order in this PR and in master, "1, B, N". Are you sure there's actually a bug here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1243 \[r3\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9mNQTQpPCeUlTCDsE8:-K9mNQTQpPCeUlTCDsE9:1772976257) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/76aa35751a27e98c7a74052713fffeef29f18e46/src/main/java/net/pms/util/FileUtil.java#L1243)):*
I added underscores here, not that I can understand how this PR have affected that. I thought prettifying already had treated the filename before it came here, so I thought both dots and underscores were already gone at this stage..?

---

*[src/main/java/net/pms/util/FileUtil.java, line 1251 \[r3\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9mNgGv0BkuFGERlwdY:-K9mNgGv0BkuFGERlwdZ:602946448) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/76aa35751a27e98c7a74052713fffeef29f18e46/src/main/java/net/pms/util/FileUtil.java#L1251)):*
I fixed ignoring "the" while I were at it. The option says ignore "the", not ignore "the" in the beginning of words only. Also, it would only ignore "the" followed by space or dot as it were, not all "non word" character on either side will match. This also have unicode support, even though that's not relevant as this is relevant for English titles only.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by SubJunk** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9nJ_llZxB1LRwCNgNB:-83140487) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
Yes the issue isn't in master using the default sorting, which is alphanumeric. It's possible there is a bug in master with alphabetic sorting. It's working the same as master after 76aa357 with alphanumeric sorting.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9nNTl1O5Uycx54QW4j:1384170043) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
I'm not sure I follow you. Are you talking about with prettifying on or off? Where is the difference, with alphabetic or alphanumeric sort?

I need to find where the difference is so I can find the cause.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by SubJunk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9nssMroqcTCVSLbjXn:-1975280700) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
The issue seems to be resolved after 76aa357

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by valib** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by Nadahar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/net/pms/util/FileUtil.java, line 1193 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813#-K9EBeubLiJObu5VsJtc:-K9o13XTr8K8sabl94tG:-1295626228) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/280eb4be029a7e7687fb6adf2f5b48b1c47ea771/src/main/java/net/pms/util/FileUtil.java#L1193)):*
Ok, I see it now. It was only valid for anime folders with prettify on.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/813)*

**Comment by SubJunk** [comment]
So this seems ready to merge now in my opinion - I don't notice any behavior change between this and master

**Comment by Nadahar** [comment]
Great.

@UniversalMediaServer/developers Anyone else has any objections?

**Comment by valib** [comment]
No objection.

**Pull request merged**
