### PR TITLE
Synced other language files with messages.properties

### PR DESCRIPTION
**Pull request by Nadahar**
This is based on 468b0f372d6507137115cfab742e8b2ea5ea0bda (#601). 2b28c3c89b7077f9ccff9f2483dfbf21cf370dc3 (#614) and 23d45fc3367068f282887b4cbbe5179cdf02724f (#611) are also merged and manually synced (that is, the same lines are deleted).

@SubJunk I think it's important to merge this before some more translations are done, as it's getting hard to keep track of.

Unfortunately the diffs are pretty much useless because my eclipse language file editor has rearranged the labels in alphabetical order. Because of that, most of the files shows as changed, but I've only deleted the same lines that was removed in 468b0f372d6507137115cfab742e8b2ea5ea0bda. Once I discovered this, I opened and resaved all language files so that as of this PR they are all sorted the same. That was far from the case, and I figured that it only makes things easier in the future.

@K4r0lSz You should use this version when you insert the polish characters - because this file has about 50 lines less.

### CODE REVIEW

**Comment by K4r0lSz** [comment]
It was not easy, but got it ;)

**Comment by Nadahar** [comment]
@K4r0lSz Oh, sorry I should have given you [the link] (https://raw.githubusercontent.com/Nadahar/UniversalMediaServer/cleanup_languages/src/main/resources/i18n/messages_pl.properties)

**Comment by Nadahar** [comment]
@SubJunk I merged #618 into this, so if this is merged #618 doesn't have to be.

**Comment by SubJunk** [comment]
@Nadahar thanks for all your work on this. I haven't checked it all manually so I hope it's good :)

**Comment by Nadahar** [comment]
@SubJunk I hope so too ;) It doesn't feel good when the diffs get useless and I can't really verify it, but I did them all manually deleting one line at a time, and I kept checking that the line number and label numbers matched between the english file and the translated file througout, also at the last line, so it shouldn't be much room for mistakes. I still would have liked to be able to verify it by diffs though :)

**Pull request merged**
