### PR TITLE
New6.7.0version

### PR DESCRIPTION
**Pull request by valib**
@SubJunk I recommend to reset master to this branch and rewrite the official release 6.7.0.

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib the way we have addressed critical bugs like this in the past is to do a release like 6.7.0.1. That's less confusing for people who have already downloaded it (which is a lot already)

**Comment by valib** [comment]
@SubJunk OK. I am deleting this branch.

**Comment by Sami32** [comment]
@SubJunk If you do that, don't forget to update MediaInfo to 0.7.96 as well.
Because TS, MTS, M2TS issues (freezing) will arise with the 0.7.94...

**Comment by Nadahar** [comment]
I agree that once something is released, it's "frozen forever". That's the general "rule" used by most software, so that's what people expect.

**Pull request closed without merging**
