### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by valib**
Updates of some renderers for better recognition. To be correctly recognized the Samsung-CD.conf and Samsung-NotCD.conf should be disabled because they use very general recognition `(Samsung|AllShare)` which is nonsens.
Selected renderers are now sorted before they are saved to the UMS.conf.

### CODE REVIEW

**Comment by valib** [comment]
@SubJunk should not be Travis integration deleted here in the GitHub?

**Comment by SubJunk** [comment]
@valib there is good reason for general detection - it means that when the new TVs come out in 2021 that we don't have a config for yet, we will still have approximate support for them until a specific config can be made. Then the more specific ones use `LoadingPriority` to make sure they get priority over the generic ones.

**Comment by SubJunk** [comment]
Please submit a new branch with LoadingPriority added back in for these, otherwise it may conflict with the generic configs

**Comment by valib** [comment]
@SubJunk set the `LoadingPriority=1` is not working properly. If I set it for my renderesrs then the result is 
Bez názvu.
When the `LoadingPriority` is not set the result is correct 

correct

It seems that the renderer with the  `LoadingPriority=1` which is recognized first overrides the second renderer. Maybe it is only  the thumbnail problem but who knows.

**Comment by SubJunk** [comment]
I have made a bug for that at https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2187
Maybe since you have a good way to reproduce it, you could work on it?

**Comment by valib** [comment]
@ @SubJunk I will try.

**Comment by valib** [comment]
@SubJunk all it was only about wrong setting of the `UpnpDetailsSearch`

**Comment by SubJunk** [comment]
@valib do you mean we can close #2187 ?

**Pull request merged**
