### PR TITLE
Update wizard

### PR DESCRIPTION
**Pull request by valib**
Add file chooser to the wizard to partialy solve the issue #1411. Set the wizard as mandatory for the clean install.

### CODE REVIEW

**Comment by SubJunk** [comment]
I'm excited about this, will test soon!

**Comment by SubJunk** [comment]
When it starts up we should remove the alert that says "Starts the UMS configuration wizard". It isn't an option so it should just start. I might make that change now

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers what do you think about this now? I'm happy to merge if you are

**Comment by valib** [comment]
@SubJunk agreee with your update and I rebased all commits. If others agree and somebody review it we can merge it.

**Comment by Nadahar** [comment]
Don't wait for me to approve it, I think it's a rather hackish way to do it. If you guys think it's good, go ahead.

If you wonder why I think it's hackish, I think that should be obvious, but in case it isn't: I don't think it really solves anything. It's probably just confusing to users to suddenly get an open file dialog presented and only being able to select one folder. Who shared just one folder anyway? What happens if the cancel or close the dialog? If they have to navigate to the navigation tab to add the rest of their folders, what's the point with the whole thing?

In my opinion it would be better to either isolate the part of the GUI that handles the shared folders to a separate JPanel subclass and then simply display this panel as a part of the wizard. Alternatively, as simpler solution would be to make UMS focus on the correct tab and section after starting if the wizard was running.

The bugs that prevents the configured folders form actually being used without a restart would have to be fixed either way, or it still won't make any sense to users.

**Comment by valib** [comment]
@Nadahar mayby this partially satisfied your expectation.

**Comment by SubJunk** [comment]
I agree with you @Nadahar that having the real folder chooser in the wizard would be better. I tried to do that a while ago and failed. I believe in iterative improvements so the question for me is "is this better than what we currently have?" rather than "is this perfect?". For me the answer is "yes, it is better than what we have, and it can and should be improved later".

**Comment by SubJunk** [comment]
@valib thanks for the extra work on it. I noticed that the others have done some related work in DMS too https://github.com/DigitalMediaServer/DigitalMediaServer/pull/26

I'm not happy with the new language so will edit that before merging

**Comment by Nadahar** [comment]
@SubJunk I don't know since when I became "others". I would have mentioned https://github.com/DigitalMediaServer/DigitalMediaServer/pull/26 if I thought it was relevant. It isn't as I see it, since it breaks plugins and reverses #140. The beauty of working with DMS is that I don't have to care about that.

Making this work without the reversal and breaking the plugins would've made it a much bigger task, which I don't think is worth it.

**Comment by Nadahar** [comment]
@SubJunk @valib My original comment wasn't meant as a complaint, I was simply trying to say "Don't wait for my approval, do as you see fit". I generally try to stay away from things I don't agree with or see the point with if I consider them relatively harmless. As always, I explain myself a bit too much which makes it sound like critisism, which wasn't really my intention. I was just trying to explain why I'm not *for* this.

**Pull request merged**
