### PR TITLE
Try saving log zip to desktop first

### PR DESCRIPTION
**Pull request by dotslash21**
fixes: #2247

Hi @SubJunk, As per our discussion https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2247#issuecomment-711106316, I've implemented the changes. Please review my PR and confirm the same.

I request you to label this PR as `hacktoberfest-accepted` if you deem this PR as a valid contribution, that would help me very much.

Thanks.

### CODE REVIEW

**Comment by valib** [comment]
@dotslash21 it works but I would recommend to store "debug.log" and "debug.log.prev" back to the UMS defined folder and store in the new folder only zip file. Also create only e.g. "UMS-log" folder instead of create folder "UMS" and subfolder "log".

**Comment by SubJunk** [comment]
@dotslash21 thanks, we will be happy to add the `hacktoberfest-accepted` label when @valib 's suggestions are implemented

**Comment by dotslash21** [comment]
@SubJunk, @valib thanks for reviewing my code. If the requirement is trying to save only the zip file on the desktop first, then I'm thinking of creating a method (say `getDefaultZippedLogFilePath()`) that will first verify the path to the desktop, then return it if ok, otherwise it will fall back to the default path from `PmsConfiguration.getDefaultLogFilePath()`.

At this point, I have a question. where will it be best to create this method?

I have considered 2 possible answers,

1. At `DbgPacker.java`, because all the zip logic seems to be there so creating this method here adheres to the single responsibility principle. But creating the method here would need me to re-implement all the path verification logic already present in `PmsConfiguration`.

2. At `PmsConfiguration.java`, because it is concerned with all the config of UMS. Also, in the future, if zipping log file functionality is introduced in say, a web interface then getting the zip configs from a central config source will reduce code duplication.

**Comment by dotslash21** [comment]
@SubJunk, @valib I assume that you have missed my [last comment](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2267#issuecomment-712923650) given the load due to `Hacktoberfest`. I've taken the liberty to go ahead with the option [2](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2267#issuecomment-712923650). Could you please review the code and check if it is in line with the requirements?

Thanks :smiley:

**Review by valib — DISMISSED** [review]

**Review by valib — APPROVED** [review]

**Comment by valib** [comment]
I feel that is the time to formate this whole class.

**Comment by valib** [comment]
Merged thanks @dotslash21

**Comment by dotslash21** [comment]
Hi @valib, could you please label this PR as `hacktoberfest-accepted`? That would be very helpful as this will be my 4th PR for hacktoberfest.

**Comment by Mik-S-UMS** [comment]
Had trouble finding the logs, couldn't see them on my desktop after saving them.

After a bit of searching I found them in C:\Users\Mik\Desktop\UMS-log as I guess should be expected

However I use a small boot SSD and most of my user directories like Downloads and Desktop are pointed to D:\Users\Mik\

I would assume %USERPROFILE%\Desktop would point to D: in my case but it appears it does not. Is there a way of using the actual Desktop directory being used or is my case a strange one to detect?

**Pull request merged**
