### PR TITLE
Fix the subs recognition bugs

### PR DESCRIPTION
**Pull request by valib**

### CODE REVIEW

**Comment by Sami32** [comment]
@valib Sorry, it didn't worked for me.
[debug.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/596448/debug.log.txt)
See the _data0001.ts_ file in the log.

**Comment by valib** [comment]
@Sami32 I checked the log and didn't see anything wrong. What is not working for you? Can you comment it?

**Comment by Sami32** [comment]
@valib Concerning the _data0001.ts_ sample specific case posted [here](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1053#issuecomment-260208813):
- The "{External subtitle}" is again displayed when it shouldn't.
   I mean that the subtitles are correctly parsed and identified, but not displayed.
- The internal subtitle are correctly parsed but not displayed as {sub:...}
- The external subtitle begining with the same name are parsed when they shouldn't.

**Comment by Sami32** [comment]
@valib I just didn't want open new issues for that so i posted there, but i don't know if it's the correct way to do that though ?

- About "{External subtitle}" i'm not sure which one should be the correct way, i mean since external subtitles are displayed by alphabetical order and not by user subtitle preferences. (Ex. SRT will be choosen before SUB or TXT subtitles files)
Of course it need to be uniform for all the videos, and it isn't, so that is a bug.


- About the issue (`subtitlesTrackTitle`) affecting the parsing of subtitles beginning with the same name,
That could be annoying in the case of movies having title like _the_sea_tooth_2_ or _title_the_return_...
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/dlna/DLNAResource.java#L1652-L1667
```
	String subtitlesTrackTitle = "";
			if (
				media_subtitle.getSubtitlesTrackTitleFromMetadata() != null &&
				!"".equals(media_subtitle.getSubtitlesTrackTitleFromMetadata()) &&
				mediaRenderer != null &&
				mediaRenderer.isShowSubMetadata()
			) {
				subtitlesTrackTitle = " (" + media_subtitle.getSubtitlesTrackTitleFromMetadata() + ")";
}
```
img_0602

**Note**: As a side note, to repeat myself, "null" is not too logic/"speaking".
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1053#issuecomment-260208813
> TRACE 2016-11-13 18:43:11.320 [Library Scanner] Parsing results for file "data0001.ts": container: mpegts, bitrate: 4693857, size: 18825216, video tracks: 1, audio tracks: 3, subtitle tracks: 6, video codec: h264, duration: 00:00:31.00, width: 1920, height: 1080, frame rate: 25.000, mime type: video/mp4, matrix coefficients: BT.709
> Audio track id: 530, lang: fr, audio codec: eac3, sample frequency:48000, number of channels: 2, bits per sample: 16
> Audio track id: 531, **lang: qaa**, audio codec: eac3, sample frequency:48000, number of channels: 2, bits per sample: 16
> Audio track id: 532, **lang: qad**, audio codec: eac3, sample frequency:48000, number of channels: 2, bits per sample: 16

That was not used...
```
if (getMediaAudio() != null) {
			String audioLanguage = "/" + getMediaAudio().getLangFullName();
			if ("/Undetermined".equals(audioLanguage)) {
				audioLanguage = ""; //could be "und" instead
}
```
As we can see, in that case no icons are displayed, not even a white full disk with a red `?`

**Comment by Sami32** [comment]
ISO 639-2 (in reserved area):
https://github.com/videolan/vlc/blob/fbaa27ae2d7fcf5ccee7f0ca424ec0cc5bf01f4c/src/text/iso-639_def.h#L154
**qaa**: used for "original" "Original audio" or "original version"
**qad**: used for "audio description" or "Audio for the visually impaired"


> Four codes are set aside in ISO 639-2 and ISO 639-3 for cases where none of the specific codes are appropriate. These are intended primarily for applications like databases where an ISO code is required regardless of whether one exists.
> mis 	uncoded languages
> mul 	multiple languages
> **und 	undetermined languages**
> zxx 	no linguistic content / not applicable
> 
>     mis (originally an abbreviation for 'miscellaneous') is intended for languages which have not (yet) been included in the ISO standard.
>     mul is intended for cases where the data includes more than one language, and (for example) the database requires a single ISO code.
>     **und** is intended for cases where the language in the data has not been identified, such as when it is mislabeled or never had been labeled. It is not intended for cases such as Trojan where an unattested language has been given a name.

**Comment by Nadahar** [comment]
@Sami32 You continue to confuse me, I think we need to find a more structured way to report the bugs you find. As I see it now, the test I did wasn't valid as I only had one external subtitle file when I tested (the one you gave me) while you had multiple. I didn't understand that until now. It's generally not very helpful for me when you post logs or parts of logs when I don't know what to look for, it's like looking for a needle in a haystack for me to look at the log and "find" the same thing that you found. A clear, concise description is much better - and if it's backed up by a log that is good, but just the log isn't.

Here are some general views I have (I'm not saying that's how it has to be, but I'd prefer it):
* Discuss one problem at a time. I don't mean that we have to create one issue for every single thing, but when there's a PR or an issue dealing with one specific thing, other things shouldn't be mixed in. I for one assume that whatever is said for in a given PR/issue is regarding that topic. Instead, an issue called "Subtitle problems/bugs/whatever" could be created, where each problem is described separately
* Describe what happens and in what way that differs from what you expect should happen. 
* Describe under which circumstances/situation the unexpected happens.
* If you have any interesting observations regarding the unexpected behaviour please include them, but make sure to separate those observations from the description of the problem itself.

Regarding the ```{External Subtitles}``` tag if the subtitle type is unknown or can't be parsed I don't know if that is really a problem. What should it say if it can't parse? When it comes to what to display when there are multiple available subtitles, I agree that just picking the first isn't very useful. At the same time, it isn't possible to display the information for all the different files in a simple tag, so maybe something like ```{Multiple external subtitles}``` would be the best solution?

**Comment by Sami32** [comment]
@Nadahar I already given you logs, easy text display and photos, i don't know how to make it better/simpler...
I confess that i'm throwing ideas, reports as/when they come to my mind, so not necessarely at the good place, but that's my way of working...not meaning that it's good, just that i'm no well structured as you are; it's more like spontaneous thoughts.


**External subtitles** being already displayed in plural form, i think it's fine as it is. That's said, if i get it and you don't, there is a bug somewhere...You can compare your configuration and log to mine, as you have all mines already.
Don't worry, i don't mind if your file is a mess, just checking all the parameters. So answering you is difficult, as i'll search at audios and subtitles parameters first, but also check all the others, as they can make me think or verify somethink that i didn't thought before.

As a side note, that made me remember an other subtitles issue that involved more than 2/3 internal subtitles and external subtitles. That's said, i suspect that it's related to the fact that it didn't display internal subtitles for this file, already correctly parsed; but it's look like can get it displayed, without external subtitles.

**Comment by valib** [comment]
@Sami32 can you test this if it solve the problem you reported?

**Comment by Sami32** [comment]
@valib I reported too many bugs already ;-)
I'm compiling your PR right now.

**Comment by Nadahar** [comment]
@Sami32 I know you have given me logs, photos etc - the problem is that you don't explain what you think is wrong and why - at least in a way that I understand. That's what I'm trying to say, it's much better if you explain what the problem is than that we're supposed to guess what you mean from pictures, logs etc.

**Comment by Sami32** [comment]
@Nadahar Sorry about that, but as you know very well my english is top level, so i thought that log and photos should be better.

**Comment by valib** [comment]
@Sami32 I agree with @Nadahar that without explaining what do you think that is wront we are blind. The debug.log or images are useless in this case.

**Comment by Sami32** [comment]
@valib I explained many time or tried to :-(
You fixed incorrect parsing/displaying of the subtitles having the same beginning name :+1:

**Comment by Sami32** [comment]
Nornally, into the TRANSCODE folder, when an audio track language is detected in a video, a country flag is displayed (if available) on the renderer. The flag is usually superseded by the one of the subtitle's language if it's there.
**BUT** when the audio language is Hindi, for example, and the movie have subtitle with an identified language (english, french...), it's not taken in consideration and no flag are displayed at all.
**The flag analyse process is stopped before the normal end that should make the subtitle flag displayed.**

For me that is a flaw in the code.
[debug.log.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/601638/debug.log.txt)
(Check "The dictator....mkv")

**P.S.** About the `{External subtitles}` issue, if none of you is able to reproduce it with my video file sample, just don't bother you with that.

**Comment by valib** [comment]
@Sami32 thanks for the report. This PR is changing the subs recognition I made long time ago and this PR I made for the testing. When it will be completed I will reorganize it to meet @Nadahar 's recommendation. The main question is if flags could be used only for audio language or changed by subtitles language. I think that flags should be used only for audio because the subs language is shown in the file description. Also flags should be shown only in the TRANSCODE folder. Do you have any other idea?

**Comment by Sami32** [comment]
@valib Yes.
**While external subtitles are present, choose a renderer supported one if any**, instead of taking the first one and tell that it's not supported in that the movie will be transcoded.

I agree that the flag display should be only audio related.

**Comment by Sami32** [comment]
Again this "@#! Sourceforge cookie that make the commit build fail !

@valib :+1:

**Comment by valib** [comment]
@UniversalMediaServer/developers what about to use something like 
audio and subspng to show audio and subtitles languages in the TRANSCODE folder?

**Comment by Sami32** [comment]
@valib As you told me, it's already right in TRANSCODE folder.
On other hand it has a fast language overview. But for me it's look a little "crowdy".
When it come to estetic, i like refer to @SubJunk .


**How do you distinguish internal and external subtitles in TRANSCODE folder ?**
Supposing that i have a movie with 1 internal subtitle and the 1 different external subtitle, the 2 with same language: (Example: the internal one was by default but incorrectly encoded, so the external one was added)
Internal: sub1.srt
External: sub1.srt
Do the external subtitles will be always the first displayed and internal subtitles the last ones ? 
As no specific indications is displayed to differenciate them.

**Comment by valib** [comment]
@Sami32 the external subtitles always override the internal one. The logic is that users prefere the extenal subs because the internal are wrong. What should be the other logic to use the external subs when internal exists?

**Comment by Nadahar** [comment]
@valib Some times files have some subtitles embedded and then further languages added externally. That doesn't mean that it's the external (often more "exotic"/rare) subtitle you want to use.

When it comes to the "double flag" I think it looks ok, but I'm not sure if it's very intuitive to the user to understand what those flags mean.

**Comment by Sami32** [comment]
@valib I guess one time again, i was not clear:
I cannot differenciate them in the renderer display, do you ?
If i send you a photo with the 2 SRT subtitle displayed in the TRANSCODE folder, internal and external,  can you tell me which one is the external one ?

**Comment by valib** [comment]
@Nadahar all external subtitles are listed in the TRANSCODE folder. The UMS is looking for all internal or external subs and if they are matching the users preferencies they are used. Preffered are the external one. Is there something wrong or it is not working?
@Sami32 in the TRANSCODE folder there are all subs internal and external when they need to be transcoded. When internal subs are supported by the renderer there are not listed because this is up to rederer to choose the propper one to play.

**Comment by Sami32** [comment]
@valib  Like i say, a phot is better than a thousand words:
img_0605

Can you tell me which one is the external subtitle ?

**Comment by Nadahar** [comment]
@valib Forget it, I misunderstood you. I thought you meant that internal subtitles was hidden if external existed - but now I undertand that it was just what the automatic transcoding selected. It has to be one of them if both have the same language, so I agree that external is the best choice then.

**Comment by Sami32** [comment]
@valib Great work :+1: 
Give the expected result ;-)

**Comment by Sami32** [comment]
@valib When testing an other issue, i saw that SSA subtitles was not displayed in TRANSCODE folder in [No transcoding] case.

img_0612

**Comment by Sami32** [comment]
On other subtitle handling issue is that there are not all displayed on the renderer in the case of **AviSynth/FFmpeg** engine (it's working fine for all others engines and AviSynth/MEncoder):

img_0613

**Comment by Nadahar** [comment]
@Sami32 This PR is marked as "Not ready" - we shouldn't approve things until they are ready imo.

**Comment by Sami32** [comment]
@Nadahar I give derogation for subtitles PRs :-P

It will already work as it's, and give improvements.

**Comment by Nadahar** [comment]
@Sami32 Then say that - approving something when the author is planning to add more is giving a "carte blanche" for any further changes.

**Comment by Sami32** [comment]
@Nadahar That's correct...i assume that for the subtitles, as we are talking about the "subtitle" guy :wink:

**Comment by Nadahar** [comment]
@Sami32 I understand the part with encouraging, but I don't think approvals should be used for that. You could just write that you've tested it and it works great or something like that. 

Giving an approval is supposed to be based on a review of the code, which is why I've said before that you can't approve code you don't understand. That is impossible to do until it is finished. The approval isn't there just to allow merge, it's meant to be a safety for the author that someone has gone through it and see no problems as well.

**Comment by Sami32** [comment]
@Nadahar I did tested and review the code long ago but didn't approved or commented before.

I know you don't like that, but that will not stop me to appreciate the job done here and to encourage to merge if HE want.
And i know that like a pitbull you'll argue :wink: but i'm a hard head...

**Comment by Nadahar** [comment]
@Sami32 There's not much point in arguing more then I've done as it's ultimately not up to me - but I see it as invalid use of the approval system.

**Comment by SubJunk** [comment]
What's left to do in this PR?

**Comment by Sami32** [comment]
@SubJunk Some other subtitles issues exist, but i didn't posted here are they have already an issue report, so except the _AviSynth/FFmpeg_ case not displaying some subtitles i think it's all, AFAIK.
And still, as it's not the very used, i guess, it could be postdated to an other PR, IMO.

**Comment by Nadahar** [comment]
No rebase first 😢

**Comment by Nadahar** [comment]
@valib What happened to this? It seems to me that there are at least parts of this that should be merged.

**Pull request merged**
