### PR TITLE
Solved Issue #2246 

### PR DESCRIPTION
**Pull request by midhun1998**

### CODE REVIEW

**Comment by valib** [comment]
@SubJunk do you know what is wrong with this checks? I cannot go inside and restat the check.

**Review by valib — APPROVED** [review]

**Comment by valib** [comment]
@SubJunk I have no idea what is wrong with the Github or my Eclipse. I tried to merge UMS master to this PR but the result is wrong. I will try to fix it.

**Comment by valib** [comment]
Solved in PR #2262

**Comment by SubJunk** [comment]
Ok cool, thanks @midhun1998 and @valib

**Pull request closed without merging**
