### PR TITLE
Network configuration overhaul

### PR DESCRIPTION
**Pull request by Nadahar**
I've come to the conclusion that I've got to stop "hijacking" PRs like I've done with #1102, #1061 and others. I'm sorry about that.

I'm therefore creating this PR which better describes what this has evolved into. It started with #1095 and the goal is that this will achieve what #1095 intended to, and a whole lot more. As per now, this is just a transfer of the current state of #1102. I will continue this once #1061 is complete and hopefully merged.

### CODE REVIEW

**Comment by SubJunk** [comment]
Will you come back to this?

**Comment by Nadahar** [comment]
@SubJunk It depends on many things, I was planning to but as I said my motivation has gotten a serious dent lately. If it's important to you to close as much as possible, go ahead. As a general note, I don't think closing PR's that has some value is such a good idea. It quickly results in the branch being deleted at some later stage, and before you know if valuable work has been lost. In this case this isn't a problem though, as I'll keep the branch anyway.

**Comment by SubJunk** [comment]
I'm not in a rush to close any PRs, only ones that will never have more work done :) I also won't delete branches without asking first. I'm just trying to get a bit more organized with the PRs and issues

**Comment by Nadahar** [comment]
@SubJunk Even if you don't delete the branch, past experience has shown that when sombody else "cleans up" the branches those tend to get deleted.

**Comment by SubJunk** [comment]
If anyone is cleaning up other people's branches that is a problem and they shouldn't be doing it. Anyway all I'm doing here is asking people if they want to close their stale PRs, not taking any action at all. Sami closed a bunch of his but I wasn't going to do anything with them except maybe rebase to keep them current.

**Comment by Nadahar** [comment]
@SubJunk Ok. Remember that pushing anything to a closed PR's branch will invalidate the PR so it can't be reopened. If rebasing/updating a PR branch, the PR must first be opened.

**Comment by Nadahar** [comment]
I won't be completing this for obvious reasons.

**Pull request closed without merging**
