### PR TITLE
Make web server interface binding configurable

### PR DESCRIPTION
**Pull request by zero0cool0**
Changes to RemoteWeb to make the web server interface (port 9001) binding configurable, similar to the server (port 5001)

### CODE REVIEW

**Comment by valib** [comment]
@zero0cool0 I a little bit formated your commit and push it to GitHub as branch [web_server_interface_configurable](https://github.com/UniversalMediaServer/UniversalMediaServer/tree/web_server_interface_configurable). Next time it will be better you create a new branch in the UniversalMediaServer not in your personal fork to allow us to add some changes before the PR will be merged. 
Anyway this PR I tested and it work.

**Comment by Nadahar** [comment]
@valib Only those that have write permission to UniversalMediaServer can create branches in this repository.

**Comment by valib** [comment]
@Nadahar ahh I see. So I can make a new PR for the branch I created and close this one.

**Comment by Nadahar** [comment]
@valib Yes. Add a comment with a pointer to the "replacement PR" like "Continued in #nnnn".

**Comment by valib** [comment]
I created new PR #1102 and this PR will be closed and will be continue there.

**Comment by zero0cool0** [comment]
BTW, the background to this PR is that it would be nice to control which interfaces that UMS would bind to as a whole (i.e. ports 5001, 9001 and UPNP ports). To that extent, I've added 

```
-Dorg.fourthline.cling.network.useInterfaces=<my interface> 
-Dorg.fourthline.cling.network.useAddresses=<my ip address>
```

to UMS.sh as start parameters. However, I'm not sure how to commit these changes and if UMS.sh is the correct place to do it. Please advise.

**Comment by Nadahar** [comment]
@zero0cool0 It can be done through code as well, but as that part of the code is quite "messy" I'm guessing nobody really dares to touch it.

**Pull request closed without merging**
