### PR TITLE
Htmlify JLabels + fix gui overlaps

### PR DESCRIPTION
**Pull request by skeptical**
A partial and mostly untested fix for #656 which
- implements automatic wrapping of long gui labels by ensuring text is wrapped in `<html>` tags.
- fixes `FormLayout`s and cell coordinates in transcoding tab and removes problematic `CellConstraints` intended to overlap labels leftwards.

Please test extensively. It still needs much prettifying which I'm hoping someone else jumps in to do because I've had enough of swing/jgoodies headaches for one day (correction: lifetime tbh :-).

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/657)

### CODE REVIEW

**Comment by Nadahar** [comment]
Nice work, but I'm just wondering if it's a good idea to HTMLify the texts because of potential encoding issues. You should atleast then HTML encode the string in htmlify().

The other approach [mentioned here] (http://stackoverflow.com/questions/26420428/how-to-word-wrap-text-in-jlabel) is to customize a JTextArea to look and behave like a label. I don't know what the disadvantages of this approach might be.

**Comment by skeptical** [comment]
@Nadahar this is a public branch, feel free to jump in and push any improvements you like.  I've mostly just pinpointed the issues here.

PS "Nice work" is a little premature as yet, geometry has gone a little haywire :P. Text fields are too tiny, side effects (scrollbars, weird 'check for updates', etc). I hate swing.

**Comment by Nadahar** [comment]
@skeptical Ok, I didn't test it yet, I simply looked at what you did and assumed the layout in general was untouced :wink: 

I'm still trying freneticly to test my latest incarnation of #616 before pushing it, so I haven't really looked into it.

**Comment by skeptical** [comment]
@Nadahar vis. encoding: imo we should verify there's an actual problem before getting too concerned.  The labels are all from ```messages.properties```, so they should in theory be 'safe' (thx to you and @ler0y's recent efforts).

**Comment by valib** [comment]
@skeptical you forgot to commit net.pms.newgui.components.CustomPanelBuilder class

**Comment by Nadahar** [comment]
@skeptical I was thinking of "problematic" HTML characters like ```& < > ' "```. There might be more, I'm not really that updated on HTML - but it seems to me that most "normal" UTF-8 characters is accepted by HTML these days.

**Comment by skeptical** [comment]
@valib I just realized that too, d'oh :P.  Will repush.

**Comment by skeptical** [comment]
@valib force-pushed, hopefully not causing pull problems for you :).

@Nadahar remember we're dealing with a different animal here, i.e. html as understood by ```JLabel```.

**Comment by skeptical** [comment]
@taconaut Seems ```getPreferredSizeComponent``` and htmlified ```JCheckBox``` label-wrapping didn't like each other so I took the liberty of discontinuing the latter in favor of filtering mouse events, which is probably the hackiest solution for this but seems to work .

I found that a lot of the checkbox hit zones worked right by avoiding the ```cc.xyw()``` construct in favor of ```cc.xy()```, i.e. it's the ```w``` that expands the hit zone into the empty area.  Doing this fixed everything except the rightmost cells, which are presumably being auto-expanded by ```PanelBuilder``` in some different way. So in theory the whole hit zone issue may be able to be fixed via jgoodies manipulation alone and we wouldn't need any workarounds (assuming one has the patience to dig into it :-). Maybe you've dug deeper into this already?

**Comment by taconaut** [comment]
@skeptical with jgoodies we have to think in grids. I had noticed that most components which are being put in a cell (or spanning multiple cells when using the w parameter) fill the entire available width. This is why I had wrapped the components into an additional panel to fit its size. I can imagine it's causing issues when adding a html layer but haven't got any experience with it.
Swing can give lots of headaches ;) I guess I've spent about 70% of the time implementing mlx with it.
Without using the w parameter, the component will only fill the cell and not the entire row. This might also end up in a bad layout as the text will be wrapped where there would be additional space available.
Feel free to remove the wrapping code I had added if you find a better way to layout components.

Btw to test, I usually set a background colour to see the space a component is really using.

**Comment by Nadahar** [comment]
I just pulled and ran this, and I'm getting multiple of these:
```
23:47:13.822 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: net.pms.newgui.PluginTab$PasswordCellRenderer cannot be cast to net.pms.newgui.components.CustomJLabel
23:47:20.153 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at net.pms.newgui.PluginTab$PasswordCellRenderer.getTableCellRendererComponent(PluginTab.java:684)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JTable.prepareRenderer(JTable.java:5736)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintComponent(JComponent.java:779)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1055)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintChildren(JComponent.java:888)
23:47:20.154 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1064)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JViewport.paint(JViewport.java:731)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintChildren(JComponent.java:888)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1064)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintChildren(JComponent.java:888)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1064)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintChildren(JComponent.java:888)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1064)
23:47:20.155 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JViewport.paint(JViewport.java:731)
23:47:20.156 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintChildren(JComponent.java:888)
23:47:20.156 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1064)
23:47:20.156 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintChildren(JComponent.java:888)
23:47:20.156 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1064)
23:47:20.156 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintChildren(JComponent.java:888)
23:47:20.157 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paint(JComponent.java:1064)
23:47:20.157 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5232)
23:47:20.157 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1529)
23:47:20.157 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1452)
23:47:20.157 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
23:47:20.157 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent._paintImmediately(JComponent.java:5180)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.JComponent.paintImmediately(JComponent.java:4991)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager$3.run(RepaintManager.java:808)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.security.AccessController.doPrivileged(Native Method)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
23:47:20.158 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventQueue.access$300(EventQueue.java:103)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventQueue$3.run(EventQueue.java:706)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventQueue$3.run(EventQueue.java:704)
23:47:20.159 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.security.AccessController.doPrivileged(Native Method)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
23:47:20.160 [AWT-EventQueue-0] INFO  net.pms.util.SystemErrWrapper - 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by skeptical** [comment]
@Nadahar you beat me to it :)!

**Comment by Nadahar** [comment]
I think I fixed that one. The problem was at ```PluginTab```. We have a specialized field ```PasswordCellRenderer``` that prints ```*``` instead of the actual characters, but the problem is that it extends ```DefaultTableCellRenderer``` which again extends ```JLabel```. Casting it to ```CustomJLabel``` is therefore invalid. Since the ```*```'s printed is a fixed length, I don't think wrapping will ever be an issue for that table cell, so it should be safe to fall back to ```JLabel``` for that case.

**Comment by skeptical** [comment]
@Nadahar yeah, I know. I was recasting when your fixed popped up... Looks like this branch needs a whitespace cleanup too.

**Comment by Nadahar** [comment]
@skeptical I've configured Eclipse to strip any trailing whitespace at save (because it has an annoying habit of creating trailing whitespace without my knowledge in some situations), so any file I edit is automaticly whitespace trimmed. It messes up the diffs a bit, but I figure rather that than that I create a lot of trailing whitespaces.

**Comment by skeptical** [comment]
@taconaut it's insane :).

My point was that in our case ```cc.cyw()``` calls are unnecessary when it comes to ```JCheckBoxes```, we get the same visual result with ```cc.xy()```, and every where except the rightmost elements it requires no additional hit zone fixing (whether via ```getPreferredSizeComponent()``` or otherwise), so most of the problem vanishes instantly.  This makes me think that fixing the rightmost part is just a matter of tinkering with jgoodies too.

@Nadahar I have a homemade ```wsfix``` script git-commit hook for jumpy too, but I don't run it in ums since it always adds unrelated changes and obscures the relevant diff issues.

**Comment by Nadahar** [comment]
@skeptical I have to run it, the alternative is worse. I think it's the auto indenting that creates all those white spaces I push in front of the cursor, but manually cleaning up that mess in diff view before every commit drove me crazy. Maybe I should just open, save and commit all classes one day I have waay to much spare time - to get it over with once and for all.

**Comment by taconaut** [comment]
@skeptical I'll illustrate what I mean with print screens. I've set a background color for the checkboxes to see where they end.

Current layout of this branch:
Current layout

Layout without spanning multiple cells (without `w`):
Layout without spanning
The left column gets larger because of the text 'Run the configuration wizard (needs application restart)

With this branch I've noticed a weirs behavior with tool tips. Sometimes they are being displayed when hovering over a check box where there is no text, sometimes not. What was consistently reproducible is that the tool tip doesn't disappear when entering the 'Only run a single instance' checkbox and exiting it from the right (where there is no text).

**Comment by skeptical** [comment]
@taconaut You're right about the left column being subject to checkbox width unless we use ``w``, as usual I overstated my case :).  Here's what I get in linux without ```w``` for checkboxes:
checkbox_xyonlyAlso Note the weird 'check for updates' checkbox.

Your 'without ```w```' middle column seems strange too, are you disabling ```w``` for checkboxes only or for everything?

I think the tooltip thing is fixed now, right-side leave events were getting blocked.

**Comment by taconaut** [comment]
@skeptical 

> Also Note the weird 'check for updates' checkbox.

D'oh, this is a bug I've introduced (which has nothing to do with the issue we are discussing here). If the platform is other than windows no text is being set for the button 'Install as windows service'. 
`installService.setText(Messages.getString("NetworkTab.4"));` should be added in the first if of `GeneralTab.refreshInstallServiceButtonState()`. Could you add this? (Creating a pull request for a single line seems a bit over the top ;)

> Your 'without w' middle column seems strange too, are you disabling w for checkboxes only or for everything?

I had only changed a few `xyw` to `xy` and made a revert. Sorry, can't tell you what I had exactly changed.

I think keeping the possibility to set the `w` should be kept, as it allows for a cleaner layout though.

> I think the tooltip thing is fixed now, right-side leave events were getting blocked.

:+1: I can't test it right now.

**Comment by skeptical** [comment]
@taconaut not saying ```w``` is bad, just use it wisely :). This discussion is academic anyway since the rightmost checkbox hit zones aren't fixed except by intervention, so I would leave things as-is until I figure that one out.

**Comment by skeptical** [comment]
@Nadahar after a little testing ```<>``` seem to be the only problem chars here, but I threw in ```&``` per your excellent suggestion (and for the sake of convention of course :-).

**Comment by skeptical** [comment]
After many more excellent adventures down a myriad of swing/gui rabbit holes the scope of this pr has grown to include fixing many non-English gui weirdnesses.  As of now it seems to be fairly stable and not hide/crop anything in other languages, plus RTL is delivered in a more or less sensible manner.

There are a few  remaining gui quirks I've noticed in master yet to be fixed:
* For jgoodies WindowsLookAndFeel LAF RTL Table headers only, e.g. Shared Folders table in Navigation/Share, display incorrectly and respond bizarrely to mouse hovering, with headings popping up/moving/vanishing. I've browsed WindowsLookAndFeel source, but haven't spotted anything yet. This can be seen with e.g. Arabic or Hebrew, and is fixed by using any other LAF, e.g.
```diff
+++ b/src/main/java/net/pms/newgui/LooksFrame.java
@@ -134,7 +134,8 @@ public class LooksFrame extends JFrame implements IFrame, Observer {
 		LookAndFeel selectedLaf = null;
 		if (Platform.isWindows()) {
 			try {
-				selectedLaf = (LookAndFeel) Class.forName("com.jgoodies.looks.windows.WindowsLookAndFeel").newInstance();
+				selectedLaf = (LookAndFeel) Class.forName("com.sun.java.swing.plaf.windows.WindowsLookAndFeel").newInstance();
 			} catch (ClassNotFoundException | InstantiationException | IllegalAccessException e) {
 				selectedLaf = new PlasticLookAndFeel();
 			}
```


* We still get 'hanging' hyperlink tooltips if we exit from the tooltip to a non-tooltip-containing region, i.e. the exit event doesn't seem to propogate to the tooltip until we open some other tooltip.

**Comment by valib** [comment]
@skeptical somewhere you changed the UI standard labels to the ToolTipText which are now shown in the UI instead of standard labels.This affects only non-English implementation.

**Comment by skeptical** [comment]
@valib not knowingly, will look :).

**Comment by Nadahar** [comment]
@skeptical The hanging tooltips is really annoying, I did some testing on that a long time ago but doesn't really remember what I found out. Is the problem the same with the standard tooltip as with our custom one? 

There's also some extra problems with combo boxes and the missing tooltip shadow, but that might be one of the things you've fixed already?

**Comment by valib** [comment]
@skeptical sorry for my mistake. Labels are OK but they are for no reason wrapped.  So the window is  doing to go be bigger by height not by width. What is the reason you are doing that?

**Comment by skeptical** [comment]
@Nadahar it seems to be possible to hang any of our tooltips if you can manage to slip in and then flee into neutral territory, but I haven't made a study of it :).  I haven't done anything with the combo boxes, being mostly concerned with text visibility/wrapping and locale orientation stuff.

@valib they say beauty is in the eyes of the beholder ;). Beyond allowing text to be automatically wrapped by the layout I haven't actually forced anything myself (more or less, anyway).  If there are specific things you don't like please point them out and maybe the layout can be tweaked (e.g. ```cc.xy() --> cc.xyw()``` or using different columnspecs).

**Comment by SubJunk** [comment]
I'll test this soon

**Comment by valib** [comment]
@skeptical  there is one problem. Some tooltips are shown OK like 
picture2 but the rest of them have height bigger than needed like 
picture1

**Comment by skeptical** [comment]
@valib I don't think it's from this branch. I'm in Windows looking at official 5.3.1 release right now and tooltips are similarly inconsistent.

**Comment by valib** [comment]
@skeptical ahh you are right I overlooked that. And what is strange the height is changing. Sometimes it is OK but it can be also like this 
picture3

**Comment by Nadahar** [comment]
@valib @skeptical I can confirm that this has nothing to do with this PR, as I've been annoyed by that before. In fact, I started a branch a long time ago trying to look at that, but never got very far.

**Comment by Nadahar** [comment]
@valib Completely unrelated, I think you should take a look [here] (http://www.universalmediaserver.com/forum/viewtopic.php?p=21757#p21757).

**Comment by valib** [comment]
@Nadahar I tested commits and found that the problem with tooltips started here 8c61e06b0eed72439da9ff4d1d38d651499c823f Before that it worked OK.

**Comment by Nadahar** [comment]
@valib That can't be correct, my branch looking at the same problem has a commit date 21. July 2015 (950eb66eadab403e379194b084be659a121500db) long before 8c61e06b0eed72439da9ff4d1d38d651499c823f. It's more likely that the font scaling make you see it more often because the scaled font happens to trigger the bug more often on your setup with scaled fonts.

**Comment by Nadahar** [comment]
@skeptical I hate to bring this up for reconsideration again, but while trying to solve the proper sizing of multi line, word wrapped texts I [stumbled upon this] (https://community.oracle.com/thread/2376090?tstart=0). According to that thread ```JLabel``` (and other components) used to wrap before Java 7, and it has something to do with a new (broken) calculation of the minimum width of a component if I understand correctly.

While I still don't properly understand how all these objects are tied together, code is given there to override that behaviour. From what I understand, this is the "core" of the fix:
```java
    class WrapLabelView extends LabelView {
        public WrapLabelView(Element elem) {
            super(elem);
        }

        public float getMinimumSpan(int axis) {
            switch (axis) {
                case View.X_AXIS:
                    return 0;
                case View.Y_AXIS:
                    return super.getMinimumSpan(axis);
                default:
                    throw new IllegalArgumentException("Invalid axis: " + axis);
            }
        }

    }
```

Maybe it can give you an idea of how to fix ```JLabel``` without applying HTML.

**Comment by skeptical** [comment]
@Nadahar you're the one who doesn't like html, not me (swing is what I hate :-). And btw to make matters even worse we're now using ```<div align=right>``` for rtl here too.

**Comment by Nadahar** [comment]
@skeptical Ok, I though it was preferrable to keep "native" behaviour if possible but with line wrap.

**Comment by skeptical** [comment]
@Nadahar either way "native"="buggy" here, I'm just happy when something more or less works and don't expect much more from swing.

**Comment by Nadahar** [comment]
@skeptical I agree that swing is... better not characterized in public. But, I also know that the more you build "around" something, the more unforeseen challenges you get responsibility for in the future. It's easy to end up with something very complicated and messy, or an impossible situation. That's what I dislike, not HTML in itself.

But, there's no point in starting that discussion again. I just came across that, and it seems like a really small thing could fix line wrapping in ```JLabel``` and other related components. I've realized that basicly the problem I'm struggelig with (line wrapping and correct preferred size in ```JTextArea```) and line wrapping in ```JLabel``` is closely related. If ```JLabel``` actually worked properly, that would have been the "correct" component to use, I'm using ```JTextArea``` solely for the line wrapping.

**Comment by skeptical** [comment]
@Nadahar the irony is that you're now effectively working around the workaround. Lately I've been fooling around with gtk3 in unrelated python stuff, you get a lot more bang for your gui coding buck there it seems.  On the whole I'm in java fatigue now, very labor-intensive and rewards are slim.

**Comment by Nadahar** [comment]
@skeptical I'm not sure what you mean about working around the workaround. I just realized that the cases have much in common, that's not been my idea from the start.

When it comes to gtk3 that can't really be compared, as then you're coding for one particular graphical environment. Coding in native Windows also is a whole lot easier. The problem with Java is that they try to abstract from the native functionality and in the process ends up with no functionality at all. Honestly I think they could've made other approaches that would make much more sense, e.g making classes that correspond to the native components and then making superclasses that were abstracted. Then we could work with the abstracted components when that was sufficient, and with the native corresponding non-cross platform components where that was needed, or a combination only overriding certain behaviour on a per-platform basis. But, in the end it doesn't matter what I think.

**Comment by skeptical** [comment]
@Nadahar I meant workaround1=JLabel->JTextArea for wrapping, if I follow you right.  Out of curiosity have you also tried the unthinkable, i.e. JLabel+html.  I know it's an added layer of abstraction, but it could also be that the folks who wrote the html support might have done a better job than the "natives".

**Comment by SubJunk** [comment]
Feel free to resurrect this

**Pull request closed without merging**
