### PR TITLE
Shared Configurations

### PR DESCRIPTION
**Pull request by SurfaceS**
don't reload when writing file.
`readAllConfigurations` better handle when it need to save.

### CODE REVIEW

**Comment by SubJunk** [comment]
Not sure if this was ready for testing but I tried it and I have the same bugs as before, and I can reproduce this too where closing and starting UMS undoes new folder additions https://github.com/UniversalMediaServer/UniversalMediaServer/issues/3698

**Comment by SurfaceS** [comment]
I can't reproduce this error from this PR.
if I add or remove with both gui, I see the java one instantly update.

The only bug is a visual bug an react side, due to :
`const userConfig = _.merge({}, configuration, sse.userConfiguration);`

In fact, when configuration.shared_content contain thing on it, merge will keep it.

**Comment by ExSport** [comment]
Hi guys
It seems I spotted similar bug when cleaning up some default shares which stayed in the list, only reordered until I force refreshed the browser. Hopefully the fix will resolve this behavior as well :-) Thank you for great work, btw!
More info here: https://github.com/UniversalMediaServer/UniversalMediaServer/discussions/3687#discussioncomment-4422359

**Comment by SubJunk** [comment]
Using this latest version I reproduced the following bug:
I removed two shared items via web interface (one folder and one image feed) and then hit save. The items are correctly updated in the Java GUI, but the web interface added the folder back, and duplicated the last entry:
image
Refreshing the page fixes that, and the content is still saved correctly after restarting the program. So the bug where the content comes back after closing UMS is not consistent. I guess there are a few different bugs in this area to fix. I'm going to prioritize this and hopefully do a release very soon. Today if I can fit in the timing

**Comment by SurfaceS** [comment]
@SubJunk did you try the latest ?? 

> The only bug is a visual bug an react side, due to :
> const userConfig = _.merge({}, configuration, sse.userConfiguration);
> 
> In fact, when configuration.shared_content contain thing on it, merge will keep it.

https://github.com/UniversalMediaServer/UniversalMediaServer/pull/3699/commits/bc2f73a763d7dc2c4ec090001436bdf18710ad0a

**Comment by SurfaceS** [comment]
> So the bug where the content comes back after closing UMS is not consistent. I guess there are a few different bugs in this area to fix.

I think the first commit https://github.com/UniversalMediaServer/UniversalMediaServer/pull/3699/commits/d40a6bf606dec3e9254cea3060cd0e9f0fa20a40 fix that.

**Comment by SubJunk** [comment]
You're right, https://github.com/UniversalMediaServer/UniversalMediaServer/commit/bc2f73a763d7dc2c4ec090001436bdf18710ad0a seems to fix the removal bug. The quickrun maven command didn't update the react app when I tested the first time.
I will do some more playing around to see if there are any other bugs but this looks good

**Comment by SubJunk** [comment]
It seems a similar bug is still there when I remove an entry via Java GUI. Here I removed two entries so I get two duplicates at the end:
image

**Comment by SubJunk** [comment]
@SurfaceS I think that is fixed here https://github.com/UniversalMediaServer/UniversalMediaServer/pull/3703
so between our fixes I think we have a good state now

**Review by SubJunk — APPROVED** [review]

**Comment by SurfaceS** [comment]
fix #3697
fix #3698

**Pull request merged**
