### PR TITLE
Repaired Splash branch

### PR DESCRIPTION
**Pull request by Nadahar**
@UniversalMediaServer/developers @SubJunk 
It seems something went terribly wrong with #700 before it was merged. I've reversed the bad changes and done one merge with master as it was before #700 was merged. That means this PR should be ready when #700 is unmerged.

It's probably down to permissions, but I'm not able to "undo" the merge of #700 although I was able to undelete the branch. I hope we can undo it and doesn't have to make a reverse commit, because that will leave a terrible mess in the git history. If it's not possible for any of you to undo the merge either, I can take on the task of rebasing it away, but I won't do anything until you guys say you can't.

To not make things worse then it already is, **nobody** should make any commits or merges to master until this is straightened out.

Tasks:
- [ ] Agree if the splash image is final

### CODE REVIEW

**Comment by Nadahar** [comment]
By the way, the reason Travis is failing now is not because of this PR, but because master is failing from the bad merge of #700.

**Comment by SubJunk** [comment]
What a mess... I don't see a way to undo it easily so feel free to rebase.

**Comment by SubJunk** [comment]
Yeah let's make it default to off I guess, if anything

**Comment by Nadahar** [comment]
How come it was mergable with failed checks? Isn't there something you can turn on in the GitHub settings that make PR's with failed checks unmergable?

**Comment by SubJunk** [comment]
@Nadahar I can't see a setting for that, but would enable it if there were one

**Comment by Nadahar** [comment]
@SubJunk It should be something according to [this blog post] (https://github.com/blog/2051-protected-branches-and-required-status-checks). It was new this September.

**Comment by Nadahar** [comment]
@SubJunk Default is changed to splash screen off.

**Comment by SubJunk** [comment]
I've uploaded an updated splash image. Feel free to merge if you like it

**Comment by Nadahar** [comment]
I'll leave it for @valib, it's his baby.

**Comment by valib** [comment]
Sorry guys for that mess. I have no idea why the subs are merged together with the PR. When I made a commit in Eclipse it correctly shows only changed files but when I push it to Git then suddenly also that subs are pushed.

**Comment by valib** [comment]
@SubJunk @Nadahar thanks for your effort to fix it. I would do that myself but I commited that changes late at night and now I am at work. I you don't mind I will merge it again.

**Comment by Nadahar** [comment]
@valib I urge you to try [TortoiseGit] (https://tortoisegit.org/) - it gives a very good overview over what is happening, exactly which files are committed (and diffs for those).

**Comment by SubJunk** [comment]
Yeah I use TortoiseGit too, very handy. I'm happy for you to merge it valib

**Comment by valib** [comment]
Guys thanks for the suggestion. I will check what it is the TortoiseGit about. Anyway Eclipse is doing well except that stupid merging but it may be caused by my wrong setting. Thanks @SubJunk I will merge this PR now.

**Comment by Nadahar** [comment]
@valib The great thing is, that whether you use TortoiseGit, Eclipse or git command line, it's all git and it all works on the same repository. That means that you can use those funcitons you find convenient from Eclipse and do the "more advanced stuff" from either TortoiseGit or the command line. It doesn't have to be one or the other.

TortoiseGit is simply a GUI for Windows for git command line. It's great for viewing logs, repositories, browse other branches or commits, merging, viewing diffs and it has GUI screens for push, pull, fetch etc. that show you relevant options from where you are. It also works on Windows icons, so you can see by just looking at each file what stat it is in (commited, changed or conflict). 

The most advanced git'ing is better to do from the command line, and personally I don't like the rebase in TortoiseGit (I use ```git rebase -i``` instead). But for mostly everything else it's great in that give you a very good overview over what you are actually doing.

**Comment by taconaut** [comment]
I like the splash screen and enabled it by default in ums-mlx. Thanks :+1:

**Pull request merged**
