### PR TITLE
refactor(requestv2): extract dlna stream handler

### PR DESCRIPTION
**Pull request by drakulis**
regarding #1664. 

This one was a real nightmare. The code was really messed up and fragile. The process flow were implemented very twisted way and related parts of functionality were spread out across whole `answer` method. I had to gather them together and put into one method. I hope I didn't break anything during this refactor. Please do the code review and test this branch on your devices. I will test this changes for few days to be sure it still works as it should.

Additionally I've made some other small code polishing - removed unused methods and moved variable declarations to the scope where they belongs.

The size of `answer` method has been already reduced from ~1000 to >100 lines of code, and the code has been organized into single responsibility methods. It is still far from perfect but it is enough to extract separate classes for eg `ContentDirectoryHandler`, `ConnectionManagerHandler` etc so we could reduce all those `if` / `else` statements and size of `RequestV2` class itself

## Testers are very welcome!

**Refactor progress**
- [x] extract common `createResponse` method to avoid adding `XML_HEADER`, `SOAP_ENCODING_HEADER` and `SOAP_ENCODING_FOOTER` over and over again
- [x] extract `searchHandler` method
- [x] extract other easy to extract handlers like `imageHandler`, `mediaReceiverRegistrarHandler`, `getSystemUpdateIdHandler` and others
- [x] `inputStream` as a local variable instead of class property.
- [x] create separate methods for `streamResponse`, `xmlResponse`, `headerResponse` 
- [x] extract fileHandler (movie, music etc). This one will be tricky.
- [ ] rename `argument` to `uri` (as in fact it is) and make some improvements in handlers related with it
- [ ] extract service handlers (`ContentDirectoryHandler`, `ConnectionManagerHandler` etc)
- [ ] drop support for first version of request (`Request` class)

### CODE REVIEW

**Comment by SubJunk** [comment]
@drakulis thanks, please let me know when you are happy with your testing and I can merge

**Comment by drakulis** [comment]
@SubJunk found and fixed bug in image serve - missing content-length header. 

I've checked movies, music and photos and all seems to be played well. Form my site it is ready to merge.

**Comment by valib** [comment]
@drakulis I found problem. When I tested this branch it was and still is working on my old Panasonic TV and also on web interface. But I didn't realized that there is a problem on Samsung Q9 TV.  It stopped support for images. There are not thumbnails and images are not showing at all. 
The difference I can see in the log is in the response. For working is
 `  HTTP/1.1 200 OK (non-chunked)
  Content-Type: image/jpeg
  Expires: Mon, 01 Apr 2019 14:56:15 GMT
  Accept-Ranges: bytes
  Connection: keep-alive
  Server: Windows_10-amd64-10.0, UPnP/1.0 DLNADOC/1.50, UMS/7.6.3-SNAPSHOT
  Content-Length: 27499`

and not working is
 `HTTP/1.1 200 OK (non-chunked)
  Server: Windows_10-amd64-10.0, UPnP/1.0 DLNADOC/1.50, UMS/7.6.3-SNAPSHOT
  Content-Length: 1394277
  Content-Type: image/jpeg
  Accept-Ranges: bytes
  Expires: Mon, 01 Apr 2019 14:46:43 GMT
  Connection: keep-alive` 

I am not the DLNA expert but I think that the response could comply with the DLNA Guidelines.

**Comment by drakulis** [comment]
@valib hmm... that's weird... are you trying to say that headers order in the response does matter? It will be really strange.

I also noticed images load issues but i fixed it in this commit: https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1700/commits/0280e9d3bb49ccbdf85b7785a245a55bc6733c79

Could you verify if you see those changes in your code?

**Comment by valib** [comment]
@drakulis I am not sure but when it works on my Panasonic TV it can mean that this renderer can accept the different order of the items but the Samsung TV doesn't. And yes the commit 0280e9d is there.

**Comment by drakulis** [comment]
@valib Damn. I can't reproduce it. Could provide full logs from version where it is working for you and from current version of UMS for the same request? I have no idea what I missed.

**Comment by drakulis** [comment]
@Nadahar do you have any knowledge what could be wrong in this case? Could you check it on your TV?

**Comment by valib** [comment]
@drakulis her you are. 
[debug working.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2655272/debug.working.log)
[debug not working.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2655273/debug.not.working.log)

**Comment by Nadahar** [comment]
@drakulis I haven't really paid attention to what has been happening here lately as I'm deep down in my own problems. I don't have a smart-TV though, only a PS3 :wink: 

The DLNA spec defines a lot of things, but I don't remember ever seeing anything about the order in the header. Didn't you mentioned earlier that you fixed content length or something for images? Could that be the cause?

Generally, regarding the DLNA guidelines, I don't think you'll get that much useful information from Google. Anyone can download the guidelines, but we're not allowed to share them - so everybody is required to download them themselves: https://spirespark.com/dlna/guidelines/

As usual when you don't pay, you don't get access to the latest version or previous versions, but the 2016 guidelines has most of the relevant information. Most of what's relevant for us is found in `Part 1-1 Architectures and Protocols` and `Part 2 Media Format Profiles`. 

What is important to remember is that the DLNA guidelines build upon UPnP AV, version 1.0. The UPnP specs can be downloaded here: https://openconnectivity.org/wp-content/uploads/2017/05/upnpresources.zip

So, whenever reading the DLNA specs one also have to take into consideration whatever UPnP AV says about the same topic :confused:

**Comment by amb-jarek** [comment]
@Nadahar Thanks for your response.

@valib I just notices that you have changed renderer settings for Samsung Q. Could you restore 
`ChunkedTransfer = true` property and check if it works. I don't know what impact on app has this flag. It's just a lucky shot. I will check it when I get back home.

**Comment by drakulis** [comment]
@Nadahar Thanks for your response.

@valib I just notices that you have changed renderer settings for Samsung Q. Could you restore 
`ChunkedTransfer = true` property and check if it works. I don't know what impact on app has this flag. It's just a lucky shot. I will check it when I get back home.

**Comment by drakulis** [comment]
@valib 
One more question, you've provided two responses working / not working. Are they for the same file? I noticed that `Content-Length` header significantly differs

**Comment by drakulis** [comment]
@valib 
I have found potential issue in `Content-Length` header calculation. Could you please checkout this branch and verify if it works for you now?
https://github.com/drakulis/UniversalMediaServer/tree/%231664-image-fix

This branch has been created from master so it contains all your changes regarding Samsung Q9 renderer

**Comment by valib** [comment]
@drakulis yes in the log they are the same files from the same folder. In the comment there was only an example to show the different order of the items.

**Comment by valib** [comment]
@drakulis you fix it. Perfect.

**Comment by drakulis** [comment]
Glad to hear it! I'll prepare PR for SubJunk.

**Comment by SubJunk** [comment]
@drakulis FYI this PR broke support for external subtitles on some Samsung TVs, we have a thread for it at https://www.universalmediaserver.com/forum/viewtopic.php?f=4&t=13118&sid=81ff620d241252da2877f4d5feae4a1b&start=20

**Pull request merged**
