### PR TITLE
FFmpeg remux

### PR DESCRIPTION
**Pull request by SubJunk**
Mux to MPEG-TS via FFmpeg instead of tsMuxeR.
This code shouldn't be permanent since it's hackish, it is just for testing. It can easily be written in a better way if we conclude that it can be done.

So far it is working for some but not all files.

### CODE REVIEW

**Comment by WolfganP** [comment]
Thx @SubJunk . I tested the version you posted on issue #503 and noticed no major errors on common media files. Which files did you notice it didn't work?
Would it make sense to promote the code as a config option for broader testing? (ie [ ] force remux with ffmpeg, besides the [ ] defer remux with txmuxer)

**Comment by SubJunk** [comment]
@WolfganP one file that doesn't work with one of my devices using this method is Banshee.S03E08.720p.HDTV.DD5.1.x264-DON. I'm looking into it

**Comment by ExSport** [comment]
@SubJunk any news about stability? I will try this code with some of my files as I get home hopefully this weekend so post tips what should I test specially for you :+1: 
Anyway we have here options like remux with tsmuxer, mux when possible for MEncoder and FFmpeg engines, so one additional "beta option" doesn't kill anyone :+1: 
I vote for implementing it to the master, configurable via ums.conf or in GUI so anybody can test all engines which best work for them, easily changeable on-the-fly. What do you think?

**Comment by SubJunk** [comment]
@ExSport tsMuxeR has some cool abiliities that FFmpeg doesn't have, so I'm starting to think that our best option will be to continue to use tsMuxeR but via FFmpeg instead of via MEncoder. In my testing, that option is more stable than this one, because tsMuxeR is so good at it.

**Comment by ExSport** [comment]
@SubJunk What cool abilities exactly do you mean?
I thought FFmpeg is more robust and bug free when comparing to tsMuxeR but maybe it is only my opinion without any real evidence. I only remember communication with Roman about incompatible tsMuxeR output when used file created by FFmpeg so great you found FFmpeg is now more compatible than before :+1:
Thx

**Comment by SubJunk** [comment]
@ExSport tsMuxeR gives a lot of control over aspects of the output that FFmpeg doesn't give, with settings like "no-pcr-on-video-pid", "new-audio-pes", "no-asyncio", and other stream-specific ones that control/rewrite the timestamp information to make the stream more compatible.
I think FFmpeg has the timestamp options but not the PCR and PES ones.

The file I listed above (Banshee.S03E08.720p.HDTV.DD5.1.x264-DON) is a good example of it - it works with FFmpeg via tsMuxeR, but not with just FFmpeg.

Also I should note that all options are as stable as each other on my Panasonic TV, and probably other renderers. PS3 just seems very picky about how it likes MPEG-TS.

**Comment by SubJunk** [comment]
I'm closing this for now because it is more stable to use FFmpeg>tsMuxeR than FFmpeg by itself. It can be reopened if FFmpeg does some work on it.

**Pull request closed without merging**
