### PR TITLE
Chromecast Ultra

### PR DESCRIPTION
**Pull request by Sami32**
As reported by a user here:  http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=9130&p=29381#p29381

I slightly modified it from some others documentions.

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 Windows use <CR><LF> for new line, while "the rest of the world" use only <LF>. We use only <LF> in the UMS repository, as is normal to do. You should configure your git to remove any <CR>s automatically (although I though it did this by default). I'd also think that GitHub's editor would make <LF> only.

I've seen several of your commits containing <CR>. I don't know how this happens, the only thing I can think of is if you edit a file on notepad or something similar and then paste it on GitHub. That's not a good way to do it.

**Comment by Sami32** [comment]
@Nadahar Until now, i always used the Github web interface.
And from today, Notepad++.

**Comment by Nadahar** [comment]
@Sami32 I just saw that my first post made no sense, as I had written e.g ```<LF``` without marking it as code, meaning they were interpreted as (invalid) HTML tags and hidden 😊 It's edited and should make more sense now...

**Comment by Sami32** [comment]
Thanks for your review and approval.

As i said i mainly take the work of a UMS user having used/tested it, and added little changes taken from Google developpers and other media server forums.

We cannot test most of the renderers created, we rely on users for that. I know it's not perfect and sure, but he tell that he well tested. And if not, the following users will be able to use it and report back if any issues arise.

**Comment by Sami32** [comment]
Yes, i didn't really understood your first post but i searched on Git documentation about line ending, and finally configurated it since then.

Could you confirm me that everything is fine to be merged now, i mean "line ending" or images that could have been affected by my automatic space/tabulation deletion ? Thanks.

**Comment by Nadahar** [comment]
@Sami32 The line endings are wrong, the are ```<CR><LF>```. This is very easy to check, just open a file in Notepad++ and click on the "All characters" button [below the ```d``` in ```Window``` in this image](https://i.stack.imgur.com/cocPP.png). Notepad will then show all the ```<CR>``` and ``` <LF>```s in the document. Each line should only end with ```<LF>```, no ```<CR>``` should be anywhere.

**Comment by Sami32** [comment]
Thanks to point this. Now that should be fine :P

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers This is a problem, now this "stage.diff" git file has been merged into master. It wasn't there when I approved this, and it just shows the problem with modifying PR's after approval.

Nothing more must be merged until this is fixed. Only you can do that @SubJunk, because master is "protected". 

What you have to do is really simple: 
* Fetch and check out master
* issue ```git reset --hard b47da0314b6c265fc897473a48737a3fbf5916bb"
* Force-push to master.

That will remove the commit made by this PR from master.

**Comment by SubJunk** [comment]
GitHub isn't letting me force-push to master so maybe I need to use different credentials for that action. I ran out of time to do this tonight so I will tomorrow

**Comment by Nadahar** [comment]
@SubJunk The easy way is for you to remove the "protected" status for master just for the few seconds it takes to push.

**Comment by Nadahar** [comment]
@SubJunk I've also left you a couple of questions in #942 that I need you to answer for me to continue merging master into 7.0.0.

**Comment by SubJunk** [comment]
I did the force push. Thanks for the comments in 7.0.0, will get to them next

**Comment by Nadahar** [comment]
@SubJunk Great, thank you.

**Pull request merged**
