### PR TITLE
Fix supported video bit depths

### PR DESCRIPTION
**Pull request by SubJunk**
There are a few other bugfixes in here too that should improve our file compatibility consistency

### CODE REVIEW

**Comment by valib** [comment]
@SubJunk I have a problem with the latest FFmpeg version. There is an error for all transcoded files. See the log.
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6159975/debug.log)

``` DEBUG 2021-03-17 22:42:52.586 [ffmpeg64.exe-14-2] [auto_resampler_0 @ 00000276ed03f9c0] [SWR @ 00000276ed140fc0] Requested resampling engine is unavailable
DEBUG 2021-03-17 22:42:52.586 [ffmpeg64.exe-14-2] [auto_resampler_0 @ 00000276ed03f9c0] Failed to configure output pad on auto_resampler_0
DEBUG 2021-03-17 22:42:52.589 [ffmpeg64.exe-14-2] Error reinitializing filters!
DEBUG 2021-03-17 22:42:52.589 [ffmpeg64.exe-14-2] Failed to inject frame into filter network: Invalid argument
DEBUG 2021-03-17 22:42:52.589 [ffmpeg64.exe-14-2] Error while processing the decoded data for stream #0:1
DEBUG 2021-03-17 22:42:52.630 [ffmpeg64.exe-14-2] Conversion failed!

**Comment by valib** [comment]
@SubJunk it is not related to this PR which is fine and works with previous FFmpeg version.

**Review by valib — APPROVED** [review]

**Comment by SubJunk** [comment]
Ok I will roll back FFmpeg, thanks

**Comment by SubJunk** [comment]
@valib it would be good to know the command that causes that FFmpeg problem, since I can't reproduce it

**Comment by SubJunk** [comment]
Ok so the command being used is:

```
ffmpeg -y -loglevel info -i file.avi -filter_complex "subtitles=file.ass" -bufsize 18000k -maxrate 17000k -crf 22 -ab 448k -ar 48000 -resampler soxr -precision 33 -cheby 1 -c:a ac3 -c:v libx264 -tune zerolatency -preset ultrafast -level 31 -pix_fmt yuv420p -f mpegts file.ts
```

Does it still happen if you disable the SoX setting? Since I can't reproduce the problem

**Comment by SubJunk** [comment]
I've been trying to reproduce the problem but I still can't. This one works for me:

```
"C:\Program Files (x86)\Universal Media Server\win32\ffmpeg64.exe" -y -loglevel info -i "file.avi" -filter_complex "subtitles=input.ass" -bufsize 18000k -maxrate 17000k -crf 22 -ab 448k -ar 48000 -resampler soxr -precision 33 -cheby 1 -c:a ac3 -c:v libx264 -tune zerolatency -preset ultrafast -level 31 -pix_fmt yuv420p -f mpegts file.ts
```

So I don't know why we would get different results for the same command

**Pull request merged**
