### PR TITLE
Dutch language unicode fix

### PR DESCRIPTION
**Pull request by ler0y**
The \ufffd unicode gives a question mark (unknown unicode) in the GUI.
The now used  \u00EF gives right character ï

### CODE REVIEW

**Comment by ler0y** [comment]
@Nadahar https://github.com/UniversalMediaServer/UniversalMediaServer/commit/4ccdf1c49484bc375cf8ec458e33d6e51aff1485 introduced the \ufffd unicode character to the Dutch language.
Was this intended? If so, than please check changes in this PR.

**Comment by ler0y** [comment]
I used this online Unicode code converter: https://r12a.github.io/apps/conversion/

**Comment by Nadahar** [comment]
@ler0y No it was not intended, and I'm sorry for this. I used a tool for comparing all the different languages in one view that ultimately was to buggy to use. I ended up doing the files all manually one by one, but have noticed that this tool has done bad things both here and there - so I should probably go back to the #615 files and do the job again without ever thouching the files with this buggy tool. I did correct the errors I found, so the dutch question mark was unknown to me.

That said, this was the reason I made #624. I haven't gotten any feedback on it yet and I don't know if it will be adopted, but this little program both converts to unicode and sorts and formats the files. My though was that if all files were treated with this, formatting would be consistent across the different files and each time nomather what tool the individual translater used to edit the translation.

**Comment by ler0y** [comment]
Closed this PR because https://github.com/UniversalMediaServer/UniversalMediaServer/pull/631 solved mentioned unicode issue.

**Comment by Nadahar** [comment]
@ler0y We have moved the translations to [crowdin] (https://crowdin.com/project/universalmediaserver). You can log in there with your github account (or create one if you like) and submit translations. This way you don't have to use git or worry about file formats.

There are some new strings that need translation. We'd appreciate if you'd be willing to translate the missing strings to Dutch.

**Comment by ler0y** [comment]
@Nadahar cool, I will do that soon.
Thanks for your work to integrate the crowdin.
I hope now more people get involved to translate the project.

**Pull request closed without merging**
