### PR TITLE
Fix WMP for Windows 10

### PR DESCRIPTION
**Pull request by Sami32**
Following this user report: http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=9142
And this WMP user-agent strings posted here:
https://forums.plex.tv/discussion/211935/dlna-server-not-accessible
http://www.universalmediaserver.com/forum/viewtopic.php?t=8108
https://emby.media/community/index.php?/topic/42118-dlna-profiles-perhaps/
...

### CODE REVIEW

**Comment by Sami32** [comment]
I don't understand why these string are set ? Anyone have an idea ?
```
 Video = false
 Audio = false
 Image = false
```

**Comment by Nadahar** [comment]
@Sami32 They are probably set to "disable" WMP to prevent UMS going on a scan frenzy if there's a Windows with DLNA enabled on the network. There are several problems between UMS and WMP. According to @atamariya one of the problems is that UMS doesn't support search (on the UPnP/DLNA level), and WMP requires this. In addition I think that WMP queries the whole directory tree up front (just like VLC pre 3.x) which really doesn't work well with UMS. That means that every folder will be queried, including #TRANSCODE# folders, settings folders etc and the media library. UMS will as a result go crazy trying to scan all this (often parsing each item multiple times) and the whole thing simply times out. 

I once wanted to fix this myself, but when I realized how massive changes would be needed to be able to handle this I abandoned the idea.

**Comment by Sami32** [comment]
@Nadahar Thank you for the explaination :smile:

**Comment by Sami32** [comment]
Infos take from [this user log](http://www.universalmediaserver.com/forum/download/file.php?id=3624):
> INFO  2017-01-22 15:14:19.232 [New I/O worker #8] net.pms.network.RequestHandlerV2 Media renderer was not recognized. Possible identifying HTTP headers:User-Agent: User-Agent: Microsoft-DLNA DLNADOC/1.50

> TRACE 2017-01-22 15:14:19.779 [New I/O worker #6] net.pms.network.RequestHandlerV2 Received on socket: User-Agent: Microsoft-Windows/10.0 UPnP/1.0

> TRACE 2017-01-22 15:14:19.232 [New I/O worker #8] net.pms.network.RequestHandlerV2 Received on socket: User-Agent: User-Agent: Microsoft-DLNA DLNADOC/1.50

> INFO  2017-01-22 15:14:19.195 [New I/O worker #5] net.pms.network.RequestHandlerV2 Media renderer was not recognized. Possible identifying HTTP headers:User-Agent: Microsoft-Windows/10.0 UPnP/1.0, Cache-Control: no-cache, Pragma: no-cache

> User-Agent: DAFUPnP

Should i add this last one ? is it really WMP specific or Windows in general ?

I think that i should add `Microsoft-DLNA` as well. Any objection to that ?

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/pull/697

**Pull request closed without merging**
