### PR TITLE
Use H.264 in Chrome web interface

### PR DESCRIPTION
**Pull request by SubJunk**
I have tested this on Chrome and Firefox on macOS and it correctly automatically differentiates the browsers - it uses libvorbis on Firefox still, but uses the Chrome-specific args for Chrome.

I think this can be merged as it is and we can continue to make similar changes for other browsers to make sure they all work.

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib I've also made it use x264 on Firefox by default, and stopped it from downscaling resolution unless it's using libvorbis. Should be good to merge and makes the web interface videos much faster and nicer on Chrome and Firefox

**Comment by valib** [comment]
@SubJunk it works but I see one difference on Chrome. It stops time seeking.

**Comment by SubJunk** [comment]
@valib thanks for testing, I will try some different options to see if that can work on Chrome

**Comment by SubJunk** [comment]
@valib I am trying to reproduce the ability to time seek on `master` but I can't do it when it is transcoding. How are you doing it?

**Comment by valib** [comment]
@SubJunk in fact the time seek worked mostly only back in time and partially forward depends on how fast was transcoding but now video player shows only "Live" without any chance to seek. The question is if it is possible to set the web player to show the video duration not the time available to the end of the actually send partially transcoded video. This is working on my Pansonic TV and also on my new Samsung TV so the time seeking is available.

**Comment by SubJunk** [comment]
@valib AFAIK the "live" message in the browser is happening on `master` too, so does this have anything to do with these code changes? Or are we just discussing another problem that is in the same area?

This is a screenshot from master showing "LIVE":

image

**Comment by valib** [comment]
@SubJunk as I wrote before this is not real seeking support. For .OGG format was possible to return back to the beginning or somwere between from the current playing time. Also was possible to jump forward but only between current time and the end of the last transcoded chunk not the duration time.

**Comment by SubJunk** [comment]
@valib I see, well it looks like there are a lot of video.js plugins that we can possibly use to implement a kind of chapter support, but maybe that could be part of a different branch. Do you think this is enough to stop this branch from being merged?

**Pull request merged**
