### PR TITLE
Cling for java 8+

### PR DESCRIPTION
**Pull request by SurfaceS**
Cling using apache `HttpClient` as `StreamClient` instead of the _hacked_ `HttpConnection` (that doesn't work on java >8).
It does not use `org.slf4j.Logger` to reflex what old `HttpConnection` impl does (not logging on UMS).

### CODE REVIEW

**Comment by SurfaceS** [comment]
- Created `NetworkAddressFactory` to let cling be aware what net interface / ip port is used for http handler (even if it's not yet used as UMS use his own http server).
- Set cling `AliveIntervalMillis` from UMS config (even if it's not used as UMS do not add local device).
- Avoid Default cling StreamServer creation as it is not used at all.
For now, cling start his own java httpserver with port 0 (random) and listen for nothing on it.
As UMS don't add local device and have it's own ssdp server that point to his own http server, it's safe to not let cling start this never pointed server.

**Comment by SurfaceS** [comment]
I think it's a good start to review / merge.
The only changes are :
- cling use now apache `HttpClient` as a `StreamClient` (allowing java 8+).
- cling won't start his own `StreamServer`.

The rest is refactoring, organizing, cleaning, commenting that should not change how UMS works.

**Comment by SubJunk** [comment]
@SurfaceS I'm testing this now

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
It works for me

**Comment by valib** [comment]
For me it stops working for UPnP Player. See log.
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7941316/debug.log)

**Comment by SurfaceS** [comment]
@valib 
UMS shutdown requested at 12:15:17.946
Errors about socket closed after 12:15:18.212 (UPNP-AliveMessageSender, UPNPHelper) are fixed in #2805

I'll look if the 12:15:14.175 error is not linked to the 12:15:13.623 one.

**Comment by SubJunk** [comment]
Ok cool, I'll hold off on the next release until we have this resolved

**Comment by valib** [comment]
I think the problem started here:
```DEBUG 2022-01-26 12:14:38.689 [cling-8] Created upnp player for [AV] Samsung Soundbar MS750
DEBUG 2022-01-26 12:14:39.249 [cling-8] Subscription failed: StreamSplicing on [AV] Samsung Soundbar MS750:  HTTP response was: 200 OK
DEBUG 2022-01-26 12:14:39.273 [cling-15] Subscription failed: ConnectionManager on [AV] Samsung Soundbar MS750:  HTTP response was: 200 OK
DEBUG 2022-01-26 12:14:39.290 [cling-12] Subscription failed: RenderingControl on [AV] Samsung Soundbar MS750:  HTTP response was: 200 OK
DEBUG 2022-01-26 12:14:39.302 [cling-8] Subscription failed: AVTransport on [AV] Samsung Soundbar MS750:  HTTP response was: 200 OK

All subscriptions failed

**Comment by SurfaceS** [comment]
could you try this one ?
#2806
Should fix your issue

**Comment by SurfaceS** [comment]
If it help I can email you the compiled jar. Just ask.

**Comment by SurfaceS** [comment]
#2807 one is a fix for your founded bug.

**Pull request merged**
