### PR TITLE
Fix for malformed ContentFeatures.DLNA.ORG header sent to renderer

### PR DESCRIPTION
**Pull request by master-nevi**
Fix for issue mentioned here: https://github.com/UniversalMediaServer/UniversalMediaServer/issues/493

### CODE REVIEW

**Comment by skeptical** [comment]
Thanks!

**Comment by SubJunk** [comment]
Thanks :)

**Comment by valib** [comment]
@SubJunk It seems to me that this pull request makes problems reported in http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=3192. I can reproduce that bug and confirm that the .PNG files are reported as JPEG

**Comment by SubJunk** [comment]
@valib I think this issue is fixed in 69e04b6

**Comment by SubJunk** [comment]
@valib or is this a separate issue?

**Pull request merged**
