### PR TITLE
Audio Selection: More Options and all Album sorts by Track

### PR DESCRIPTION
**Pull request by Executioner0**
There is also a change in here commenting out -nosync for ISO container as it caused Audio sync problems when I finally got DVD ISO playing working on my PS3 (PS3 won't play converted ISO with vrc_buf_size=7000, fails with unsupported data).

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/617)

### CODE REVIEW

**Comment by Nadahar** [comment]
@Executioner0 In my opinion it's better to leave strings out of the language files then use google translate. If a string isn't found for a particular language, UMS will just use "standard" instead, which is ```messages.properties``` aka english. It's much easier for someone translating to discover a line that's missing than to catch that it's just wrong. And it is, in most cases google translate is wrong to the point that it gives no meaning.

**Comment by K4r0lSz** [comment]
Google Translate for Polish... it's nightmare ;) I agree, better keep EN, then easier to catch it.

**Comment by Executioner0** [comment]
Point taken, it is a nightmare, especially as the English word "Letter" has multiple meanings. I have left out the translations for "By Year" (PMS.30).

**Comment by SubJunk** [comment]
@Executioner0 this looks good. Please fix the merge conflicts :)

**Comment by Executioner0** [comment]
I would fix the merge conflicts if I had any idea how to do that. There doesn't appear to be anything here online or in Netbeans to help me do that.

**Comment by Executioner0** [comment]
To be honest, Git/gitHub seems like 10 times as much work as should be required to do anything. I have no idea what I'm doing, I tried doing a Pull to my local code from UniversalMediaServer/UniversalMediaServer and Netbeans gave me heaps of conflicts. Tried to resolve them but the diff engine in Netbeans is about as much use as tits on a bull, and just gave me the entire file in pink on both sides, so I thought I'd revert my code back (for which there are three options referring to Index, HEAD and working copy, god knows which fork/repo). Picked HEAD and it's now stuffed my local copy completely filling the properties files with <<<<HEAD and =======. I tried, but Git is obviously not designed to be used by humans and I don't have time to spend days figuring out how to use it. About the only thing I think I can do is make a copy of my code, delete the fork I have, create a new one and try again.

**Comment by Nadahar** [comment]
@Executioner0 If you're on Windows, try [TortoiseGit] (https://code.google.com/p/tortoisegit/). Even though you still have to understand git to some extent, it gets much more logical to me atleast. With TortoiseGit installed you can see which files conflict, use it's diff editor and resolve the conflicts one by one. Once all the conflicts' are resolved, you commit your merge and all is fine.

I don't merge by pulling UniversalMediaServer into my repo, although that might work as well. Instead, there's a remote reference called "UniversalMediaServer" that I use to merge like this:
* Make sure all is commited/repo is not "dirty", if you have some changes you don't want to commit, do a ```Stash save```
* git fetch UniversalMediaServer
* git merge UniversalMediaServer/master
* it will tell you which files are conflicting, rightclick -> "edit conflicts" - once the conflicts is taken care of, click "mark as resolved". 
* Rightclick repo root -> commit. 
* Rightclick repo root -> push (to your github ```Executioner0:master``` in this case)
* The pull request is mergable again

Is seems to me that you did a "soft" reset that basicly just moved the head back without deleting the commits after. Doing a "hard" reset actually deletes the changes and doesn't fill your repo with <<<<<<HEAD files, and that's still not to late. Just do a hard reset, but be sure to do it to the correct place (the commit before the pull/merge). It's much easier to see what you do in TortoiseGit, and once the reset is set right, you should be ready to fetch and merge as described above.

**Comment by Nadahar** [comment]
@SubJunk @Executioner0 Looking into all the merge conflicts (language files), I did a rebase skipping the google translations in #622 instead.

**Comment by Executioner0** [comment]
Now I just need to go through them all and add the PMS.29 (By Letter) where they already have PMS.28 (By Letter/Artist/Album) without using Google Translate.

**Comment by Nadahar** [comment]
@Executioner0 It's strictly not neccesary as I see it, some of the other PR's that are waiting have several new labels so once all this is merged, new translations is needed anyway.

**Comment by Executioner0** [comment]
One thing I don't understand here is why the .properties files are showing that the whole file has been changed when I only changed one or two lines. Something to do with line endings?

**Comment by Nadahar** [comment]
It's the line endings yes, I pulled down your fork and reviewed it in TortoiseGitMerge - it shows the correct diffs (only one or two lines changed), but show different line endings.

**Comment by Executioner0** [comment]
what line endings does the server use then? I should be able to change my git-config on my local machine to match.

**Comment by Nadahar** [comment]
Your files have <CR><LF> line endings - Windows standard. The files in the repo have just <LF> - which is the standard for anything but Windows as far as I know, often called Unix, Linux or *nix ending. I'd think you could adjust that in your editor, I have mine sat to follow whatever lineendings are in the file I open already.

**Comment by Executioner0** [comment]
I'm hating Git more and more every time I use it. I installed Git for Windows and it changed ownership and file permissions on my entire Program Files and Program Files (x86) structure, now a lot of programs have stopped working.

**Comment by Nadahar** [comment]
@Executioner0 That sounds very strange, but I haven't tried "Git for Windows". I use [TortoiseGit] (https://code.google.com/p/tortoisegit/) as a frontend for [git] (https://git-scm.com/) and that works quite well.

**Pull request closed without merging**
