### PR TITLE
Replace external dependencies plugin

### PR DESCRIPTION
**Pull request by Nadahar**
I've replaced the ```com.savage7.maven.plugins:maven-external-dependency-plugin``` with [my fork] (https://github.com/Nadahar/external-dependency-maven-plugin).

It was nowhere as quick and easy as I'd hoped to modify the plugin, since it were made for Maven 2 and a lot of stuff didn't exist anymore or were deprecated. I've managed to replace most of the Maven 2 logic, but because of Maven's infamous no-documentation strategy I haven't been able to find new ways of doing everything. The Maven 2 stuff I've kept is available in [org.apache.maven:maven-compat:3.3.3] (https://maven.apache.org/ref/3.3.3/maven-compat/) so until they ditch ```maven-compat``` or somebody really want to vacuum every last corner of internet or read the Maven source code to find the "modern alternatives" I feel like letting them stay.

The good thing is that it now seems to be working. The Maven repository is yet to be solved, but except from that it seems good from my testing so far. Creating this PR will be the next test.

### CODE REVIEW

**Comment by Nadahar** [comment]
That didn't work entirely according to plan. I configured the plugin to run at phase ```generate-sources``` (which is the same phase that Maven solves dependencies). In the Travis log I can see no trace of the external dependency plugin actually starting (or anything else other than dependency resolution). I therefore moved the plugin's phase to ```initialize``` so that it should run before Maven resolved dependencies (and hopefully find them in the local repository), but to no avail. I still don't see any trace of it starting.

It's puzzeling, when I copy the command from the Travis build and run it locally, everything behaves as expected and the plugin downloads as it should.

**Comment by Nadahar** [comment]
I got it to download the external dependencies by removing them from "dependencies" section. It seems dependency resolution isn't during "generate-sources" but before the lifecycle begins. The problem with this however is that the compile fails because they are not dependencies (even though they are actually in the local repository now).

So they have to be in the dependencies for it to compile, but they can't be in the dependencies for Maven to start the lifecycle. Catch-22...

**Comment by Nadahar** [comment]
Ok, I got it to run by cheating a little with the ```.travis.yum``` file. Now however it fails on 22 tests (which has nothing to do with this PR).

I've got to look at that later, my eyes are square noe.

**Comment by Nadahar** [comment]
@SubJunk I've done some trickery here, but Travis has passed now. I just need to find some better solutions to some of the tricks.

**Comment by SubJunk** [comment]
*claps* great job getting it to pass! I love the green ticks

**Comment by Nadahar** [comment]
I've now got mediainfo (https://github.com/travis-ci/apt-package-whitelist/pull/1514) and libzen (https://github.com/travis-ci/apt-package-whitelist/pull/1515) on the travis white list so they can be installed before building. This will hopefully make all tests runnable.

**Comment by Nadahar** [comment]
That worked :+1: With mediainfo and libzen approved and ```travis.yml``` changed to:
```yml
language: java
addons:
  apt:
    packages:
    - mediainfo 
install: 
  - mvn external-dependency:resolve
  - mvn external-dependency:install
script: mvn install -Dmaven.javadoc.skip=true -B -V
```
..Travis will succeed in all tests. Without those packages, 9 tests are skipped.

**Comment by Nadahar** [comment]
This is really strange, the push build failed and the pr build succeeded. I don't even get why Travis run two builds for every push I make, but it's probably because the PR originated from this repo. But, I have no idea how one can fail and one can succeed when it's the exact same head being tested.

**Comment by SubJunk** [comment]
@Nadahar do you think this is ready to merge? is it using your Maven repository since we haven't been able to get the one on universalmediaserver.com going yet? I'm happy to look into the passive FTP option this weekend if it would still be useful

**Comment by Nadahar** [comment]
@SubJunk No, it's not ready. I'm still working on it, but I'm getting closer. As you can see my last commit is still "testing".

I'm still using my repo yes. But, I've actually applied and gotten approved for deploying to [OSSRH] (http://central.sonatype.org/pages/ossrh-guide.html) now. I got ```com.universalmediaserver``` as our prefix. There's still a lot of requirements I have to figure out though, like Javadocs publishing and signing. You can see the requirements [here] (http://central.sonatype.org/pages/requirements.html). If you register at [JIRA] (https://issues.sonatype.org/secure/Signup!default.jspa) I'll try to get your account added.

**Comment by Nadahar** [comment]
@SubJunk This isn't a problem for me, but I get a warning while testing the plugin on one of the files. There might be something you should fix at the web server:
```
WARNING: Invalid cookie header: "Set-Cookie: sf_mirror_attempt="mediachest:heanet:MediaUtil/Version%201.0/mediautil-1.zip"; expires=120; Path=/". Unable to parse expires attribute: 120
```

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers @SubJunk I have been trying to get fetching external dependencies completely integrated in the Maven build, but I'm now giving up. This was my main goal with replacing the external dependency plugin, but I've now realized that I just can't find anyway to do it in Maven 3.

The reason is that Maven 3 does the dependency resolution before starting processing the lifecycle phases alltogether. That means that there's no way to do anything in any phase to get the dependencies copied in any lifecycle phase as that's already to late; Maven won't even try that because it will throw an error since these dependencies are missing from the local Maven repository. If I remove them as dependencies I can make Maven copy them during one of the early phases, but then the compile phase fails because the dependencies aren't in the compiler's classpath. I've been trying to find a way around this by somehow adding them to the classpath without them having to be dependencies, and I thought I had made it happen by using the ```<includes>``` section of the compiler plugin. At first it seemed to work, but when I looked at it closer that made it skip compiling alltogether without throwing an error. The tests were also skipped, and the build process was successful - but in reality compiling and testing was simply skipped. This must be a bug in Maven - it's hard for me to understand how that can be deemed a successful build, or why adding something to the classpath could make it just skip compiling.

In any case I'm stuck at this, and have decided to let it rest for now. It makes this exercise a whole lot of work for very little benefit, but I have in the very least made some improvements that makes the process a bit easier. I've combined the ```resolve-external``` and ```install-external``` goals into just one goal named ```install```. The old ```resolve-external``` is functionality is still there now called just ```resolve``` and the old ```install-external``` is now called ```localinstall```. I don't know exactly in which scenario you'd want to do this in two steps, but there was no reason to remove the possibility. ```install``` will do it all in one go though.

That means that what I've accomplished is to reduce:
```
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:install-external
```
to
```
mvn external:install
```
There's still one possibility to not having to run this command though, I could bind ```external:install``` to the ```clean``` lifecycle. That would mean that the first time one were to build UMS one'd have to run
```mvn clean package```. It's a hack, installing external dependencies in the ```post-clean``` phase isn't really correct as I see it, but it would work. The alternative is that the first build will be:
```
mvn external:install
mvn package
```
In either case, subsequent builds can be done simply with ```mvn package``` since then the external dependencies are already there to be found.

I don't know which version you see as preferrable, please throw in your views. In addition to making it a bit simpler to run, this plugin has the advantage of being Maven 3 while the old plugin is pure Maven 2. That probably means that it will stand a better chance of working in the future, as the old plugin relies mostly on deprecated and badly outdated libraries and methods.

@SubJunk I read that github have made it possible to give a "add repository" permission to organization members. If you could give me this temporarily I could move the external-dependency repository from my user to ```UniversalMediaServer``` instead of you having to create a repository and me having to populate it and then delete my repository.

**Comment by Nadahar** [comment]
@SubJunk I'm getting close to try to publish the plugin at Maven central. They do require a lot of stuff, SCM information included, and I'm afraid it can create trouble if I want to change that later. I don't want to try to publish until the correct SCM is in place, and that means moving the repository from my user to UniversalMediaServer. I therefore need you to either give me "create repo permissions" or to create a repository named "external-maven-plugin" and give me write permissions to that.

**Comment by SubJunk** [comment]
@Nadahar cool, I gave you (and all devs) write permissions to that repository

**Comment by Nadahar** [comment]
@SubJunk Great.

I'm currently having a hard time with javadoc. One of Central's requirements is that javadoc has to be included with the artifact. However, since this artifact is a mojo (a Maven plugin) there are special tags that have to be used in class and field descriptions. Javadoc doesn't understand these and throws a lot of errors. I haven't been able to figure out how to get javadoc to accept "foreign" tags like ```@goal```, ```@parameter``` or ```@component```. If anyone has any experience with similar issues and javadoc, please share... I'm a bit frustrated at the moment being caught in this sticky red tape of requirements and prohibitions.

**Comment by Nadahar** [comment]
Ok, javadocs and all other requirements are finally met. At times it felt like I would never get here, but he's proof:
external-maven-plugin-release
:grin: 

It won't be synced to Maven central until they start work at get to work at Sonatype because they have to manually approve the first release, but as you can see all the automatic tests passed so I'm guessing it's just a matter of time now.

Once this is in place, I can finish this PR.

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers @SubJunk 
Then I've gotten confirmation that ```com.universalmediaserver:external-maven-plugin``` is hosted a Maven central repository.

I've finished testing the POM configurations, and this PR should be ready to merge. 

When this PR is merged, installing external dependencies is changed from:
```
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:install-external
```
to:
```
mvn external:install
```
I opted not to bind external:install to the clean phase since it still wouldn't work if you called ```clean``` on the same line as ```package``` (```mvn clean package```). It had to be split into two lines for Maven not to try to resolve all dependencies before starting with ```mvn clean``` and then ```mvn package```. I figured that it made more sense to run ```mvn external:install``` than ```mvn clean``` then, since it's more logical what's actually happening. Binding installation to the ```clean``` lifecycle was always a hack anyway.

The final changelog is:

* Replaced external dependencies plugin with our own:
  * Updated ```.travis.yml``` to install ```mediainfo``` and run ```mvn external:install``` before build
  * Updated ```pom.xml``` to use our external dependencies plugin instead of that from savage7:
    * Updated comment in beginning of POM to reflect the new command needed to install external dependencies.
    * Removed unneeded repositories. This is stricly not tied to this PR, but it help speed up the Travis build because Maven contacts all repositories for every artifact. It should also speed up normal builds somewhat, but only when dependencies need to be downloaded.
    * Updated ```org.eclipse.m2e:lifecycle-mapping``` configuration to use the new external dependencies plugin
    * Updated the plugin and plugin configuration for external dependencies to use the new plugin
    * Removed obsolete Maven 2 execution from plugin executions as it doesn't work as intended with Maven 3 anyway and wastes time during build.
    * Removed non-existing repository nexus.codehaus.org to save time by trying to contact the repository
* Minor modifications of tests for smoother testing and no failures during Travis build
* Changed ```mediainfo``` library load failure log message from ```info``` to ```error```

**Comment by Optimusprimeums** [comment]
Nice work @Nadahar your putting in alot of work around here!!!

**Comment by Nadahar** [comment]
@Optimusprimeums Thanks, I'm a bit OCD and get a bit addicted to things when I've first started.

**Comment by Nadahar** [comment]
I'm about to merge the lastest master into #679 so I can continue on that, and I'd really like for this to make it into that merge. This basicly just touches the POM (besides some very minor adjustments) and is very easy to reverse, so I think I'll take the chance to merge it now, since there's been no sound about any reservations/potential issues.

**Comment by SubJunk** [comment]
I was about to mention that I wanted to coordinate this merge with an update to UMSBuilder but it has already been merged.

**Comment by Nadahar** [comment]
@SubJunk Sorry, I didn't hear anything and as I said I wanted to merge this into the crowdin branch. I don't know what UMSBuilder is - is that an instruction for how to build UMS? The changes are very small as shown above.

**Comment by Nadahar** [comment]
@SubJunk: I've updated the information here: https://github.com/UniversalMediaServer/UniversalMediaServer/wiki/BUILD#6-resolve-and-install-external-libraries

Is that UMSBuilder, or is it some kind of software?

**Comment by SubJunk** [comment]
@Nadahar it's no problem, I'm excited to have this merged for passing tests. UMSBuilder is a small program/script that gives users the ability to compile UMS from master with one click. @skeptical also does a version called UMSBuilderV2 but I still release UMSBuilder myself, although I'd be open to making V2 the official one

**Comment by Nadahar** [comment]
@SubJunk Ok, the sources aren't anywhere for me to edit then? All you need to change is:
```
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:resolve-external
mvn com.savage7.maven.plugins:maven-external-dependency-plugin:install-external
```
to:
```
mvn external:install
```

**Comment by SubJunk** [comment]
@Nadahar the sources aren't anywhere but I could add a repository for it on here. For now I've done that update manually. Now I'm trying to track down a link to JDK 1.7.80 for Linux, got a link?

**Comment by Nadahar** [comment]
@SubJunk Ok, I could only find [JDK 1.7.79] (http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html), but I figure you solved it.

**Comment by SubJunk** [comment]
@Nadahar thanks for looking. I'm about to release UMSBuilder with the update. Nice work on this branch!

**Comment by SubJunk** [comment]
@Nadahar any idea why Travis runs the tests for master and the PR with each commit to a PR, instead of just one for the PR? I wonder if there's a config setting for that

**Comment by Nadahar** [comment]
@SubJunk If you click "settings" on the Travis page, you can choose which to run. It's currently set at run at both every PR and every Push or somewhing like that. It's only PR's from the "UniversalMediaServer" repository that runs twice, normal PR's are only run once.

**Comment by taconaut** [comment]
@Nadahar FYI Changing the build configuration on Jenkins to run `mvn external:install` fixed the build (which had failed after your last commit). [UMS trunk build](http://universalmediaserver-ci.hopto.org:9999/job/ums%20trunk/)

**Comment by taconaut** [comment]
@Nadahar Btw is this comming from your change?

`Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-eclipse-plugin/2.10/maven-eclipse-plugin-2.10.jar
4/219 KB   
8/219 KB   
12/219 KB   
16/219 KB   
20/219 KB   
24/219 KB   
28/219 KB   
32/219 KB   
36/219 KB   
40/219 KB   
41/219 KB   
42/219 KB   
46/219 KB   
50/219 KB   
54/219 KB   
58/219 KB   
62/219 KB   
66/219 KB   
70/219 KB   
74/219 KB   
78/219 KB   
82/219 KB   
86/219 KB   
90/219 KB   
93/219 KB   
94/219 KB   
98/219 KB   
102/219 KB   
104/219 KB   
107/219 KB   
111/219 KB   
115/219 KB   
118/219 KB   
119/219 KB   
123/219 KB   
127/219 KB   
131/219 KB   
135/219 KB   
139/219 KB   
143/219 KB   
147/219 KB   
151/219 KB   
155/219 KB   
156/219 KB   
158/219 KB   
159/219 KB   
162/219 KB   
163/219 KB   
167/219 KB   
168/219 KB   
172/219 KB   
176/219 KB   
180/219 KB   
184/219 KB   
188/219 KB   
192/219 KB   
196/219 KB   
200/219 KB   
204/219 KB   
208/219 KB   
212/219 KB   
216/219 KB   
219/219 KB`

It probably lloks good in the console but takes a lot of space in the command line output.

[Full log] (http://universalmediaserver-ci.hopto.org:9999/job/ums%20trunk/467/console)

**Comment by Nadahar** [comment]
@taconaut I can't understand how anything I did you lead to that. But, the "new" external dependencies plugin has a lot of updated dependencies which again probably has a lot of updated dependencies etc, so the first build after the change will probably download a lot of new artifacts. Can that be the reason you noticed it?

I've never seen such a "progress" function in Maven myself, and this seems to come from Maven itself...?

**Comment by taconaut** [comment]
@Nadahar I've just triggered a new build to see how the log looks and it's a lot cleaner. I'm surpirsed I've never noticed these progress messages before.

**Comment by Nadahar** [comment]
@taconaut Nice to know I hadn't affected something completely unknown to me ;)

**Comment by taconaut** [comment]
@Nadahar :smile: :+1:

**Pull request merged**
