### PR TITLE
m3u uri handling + radiobrowser + store webstream info in db

### PR DESCRIPTION
**Pull request by ik666**
PR #4572 follow up 

Implements RadioBrowser Metadata lookup.
Added MediaTableContainerFiles to track files included in a container.
Store WebStream media info into the database.
Use of FFmpegParser to parse media info.
Implements WebStreamParser to parse headers of an http streams.
Added possibility to add playlist in playlist.

### CODE REVIEW

**Comment by ik666** [comment]
@SurfaceS One step taken, but still an issue exists. I see a difference in handling mime-type. In the original PR the content and content-type was just copies and not transcoded. Now, the renderer get's a transcoded URL. But the presented URL is not playing anything. Maybe it's even a good idea to transcode the stream ... 

```
URL: http://10.0.8.14:5001/ums/media/83338f0f-7194-3c41-84d6-160e72848cee/178/Discover+Trance+Radio+192kbps+%28GB+-+Mid+8006%29_transcoded_to.pcm Headers: {Accept-Ranges=[bytes], [HTTP/1.1 200 OK], Server=[Mac_OS_X-x86_64-14.5, UPnP/1.0 DLNADOC/1.50, UMS/14.1.0], Connection=[keep-alive], Content-Type=[audio/wav]}
```

**Comment by SurfaceS** [comment]
> In the original PR the content and content-type was just copies and not transcoded.

yes, that is why it was breaking the webstream handle.

`_transcoded_to.pcm`
Mean UMS determine that the renderer cannot play the content and will transcode it.
engine != null
renderer.isTranscodeToMP3 = false
renderer.isTranscodeToWAV = false
-> transcode to PCM

Most time, transcode to PCM is for renderer that do not has a `TranscodeAudio` setting.

**Comment by SurfaceS** [comment]
In fact I think we should not create a new table in db for that.
I'll back with something.

**Comment by ik666** [comment]
@SurfaceS Then the transcoding seem not to work, i.e. VLC is not playing anything.

There is also one NPE:

````
RROR 16:52:34.051 [jupnp-sync-protocol 239-1] Exception in result creation "Cannot invoke "java.io.File.lastModified()" because the return value of "net.pms.store.container.PlaylistFolder.getPlaylistfile()" is null"
java.lang.NullPointerException: Cannot invoke "java.io.File.lastModified()" because the return value of "net.pms.store.container.PlaylistFolder.getPlaylistfile()" is null
	at net.pms.store.container.PlaylistFolder.resolve(PlaylistFolder.java:160)
	at net.pms.store.StoreResource.syncResolve(StoreResource.java:355)
	at net.pms.store.container.PlaylistFolder.resolveOnce(PlaylistFolder.java:293)
	at net.pms.store.container.PlaylistFolder.resolve(PlaylistFolder.java:161)
	at net.pms.store.container.PlaylistFolder.discoverChildren(PlaylistFolder.java:93)
	at net.pms.store.StoreContainer.discover(StoreContainer.java:728)
	at net.pms.store.MediaStore.getResources(MediaStore.java:669)
```

One wierd thing ... WAV is actually just the container which can contain PCM, MP3, MQA, etc. If the WAV container contains a PCM stream, then the container is call/named "wav". If it contains a MP3 stream, it is called/named "mp3". So transcode to WAV means what? Transcoding the container, keeping the stream as is?

**Comment by SurfaceS** [comment]
> `at net.pms.store.container.PlaylistFolder.resolve(PlaylistFolder.java:160)`

you are not running the current implementation as `net.pms.store.container.PlaylistFolder.resolve` is at line 163 and `PlaylistFolder.getPlaylistfile()` is checked on this one.

From what I see on the FFmpegAudio command :
WAV = wav = PCM signed 16-bit little-endian in wav file format
LPCM= s16be = PCM signed 16-bit big-endian in raw format

**Comment by SurfaceS** [comment]
> One question: is `-> transcode to PCM` = transcode to LPCM ? I think this using LPCM as a default stream encoding for audio files is not such a good idea, because in real world audio devices PCM is more common and should therefore be the most compatible format.
> 
> Maybe we should rename `isTranscodeToPCM` to `isTranscodeToLPCM` and `isTranscodeToWAV` to `isTranscodeToPCM`
> 
> Unsure if it's done: If UMS delivers "audio/wav" as mime type to the renderer, FFMPEG must encode a WAV header at the beginnen of the stream, so the renderer can extract the stream type.

I was not yet their when this was implemented.
I just tell you what it do in `FFmpegAudio`.

```
		if (renderer.isTranscodeToMP3()) {
			cmdList.add("-f");
			cmdList.add("mp3");
			cmdList.add("-ab");
			cmdList.add("320000");
		} else if (renderer.isTranscodeToWAV()) {
			cmdList.add("-f");
			cmdList.add("wav");
		} else { // default: LPCM
			cmdList.add("-f");
			cmdList.add("s16be");
		}
```

According to http://trac.ffmpeg.org/wiki/audio%20types

The default for muxing into WAV files is pcm_s16le
```
s16le           PCM signed 16-bit little-endian
s16be           PCM signed 16-bit big-endian
```

so, I presume : 
TranscodeToWAV is PCM signed 16-bit little-endian onto a wav container.
default (not mp3 or wav) is PCM signed 16-bit big-endian in raw format.

**Comment by SurfaceS** [comment]
> Unsure if it's done: If UMS delivers "audio/wav" as mime type to the renderer, FFMPEG must encode a WAV header at the beginnen of the stream, so the renderer can extract the stream type.

In my point of view, `audio/wav` should have wav container.
raw format `PCM signed 16-bit big-endian` should be `audio/L16`.

**Comment by SurfaceS** [comment]
@ik666 
I added a PR on your git : 
https://github.com/ik666/UniversalMediaServer/pull/91

Now streams are parsed then we should be able to know if transcode is needed or not.
+ a lot work on storing metadata the right way

**Comment by ik666** [comment]
@SurfaceS I think this is working so far, but needs a tweak. From what I see, the transcoding section is "optimized" for video transcoding only. I think we have 2 use cases :

1) container having audio and video streams
If you have a video container with audio streams inside, the audio streams get transcoded to LPCM since most AV receiver are able to handle raw data audio (i.e. LPCM encoded 7.1 streams) for home theater systems. This is currently the config-default and just fine I believe.

2) container having only audio streams
In this case we usually have a 2 channel audio stream only. The renderer usually accept only PCM, not LPCM. So you have to disable the `transcode to LPCM` checkbox in the audio transcoding section for audio streams/files to work correctly.

You can check this even in the web ui. If you navigate to this entry in the web-ui
```
#EXTM3U

#RADIOBROWSERUUID:960e4940-0601-11e8-ae97-52543be04c81
#EXTINF:1,Ibiza Global Radio
http://ibizaglobalradio.streaming-pro.com:8024/
```

having the `transcode to LPCM` option checked => no sound in the web-ui
having the `transcode to LPCM` option disabled => radio station is playing

But I believe if LPCM is disabled the video files (having DTS, ATMOS, etc.) won't play any audio any more since the AV receiver usually requires LPCM audio streams. The user would need to switch between the two option, in regard of the file type ... 

Maybe we should have a "video files transcoding" configuration section and a "audio files" configuration section to separate the config between those two container types. 

Quick fix would be default transcoding to PCM if we have no video streams in the container (maybe ignoring if LPCM is checked) or moving this option to a renderer configuration section.

**Comment by SurfaceS** [comment]
container having audio and video streams -> FFMpegVideo engine
container having only audio streams -> FFMpegAudio engine

> having the transcode to LPCM option disabled

you should set this on the renderer configuration.
`TranscodeAudio = WAV` or `TranscodeAudio = MP3`

> Maybe we should have a "video files transcoding" configuration section and a "audio files" configuration section to separate the config between those two container types.
> 
> Quick fix would be default transcoding to PCM if we have no video streams in the container (maybe ignoring if LPCM is checked) or moving this option to a renderer configuration section.

I think this PR is huge and have a lot of changes.
Maybe it should be merged first, then we can open another PR for next thinking.

**Comment by ik666** [comment]
> you should set this on the renderer configuration.
> `TranscodeAudio = WAV` or `TranscodeAudio = MP3`

Maybe you can help: Which renderer configuration uses the web-gui (player)?

**Comment by ik666** [comment]
@SurfaceS Probably another issue, not directly related to this PR. For the above example "Ibiza Global Radio" delivers a MP3 stream. The renderer has a supports line for that

```
Supported = f:mp3                       m:audio/mpeg
```
However, a transcoding engine is set. Looks like the class `StoreItem` line 484 sets a compatible engine, without matching against the supported line of the renderer? Probably at the start of the `public Engine resolveEngine()` method this check ought to be done.
```
		// Try to match an engine based on mediaInfo information and format.
		resolvedEngine = EngineFactory.getEngine(this);
```

**Comment by ik666** [comment]
> container having audio and video streams -> FFMpegVideo engine container having only audio streams -> FFMpegAudio engine
> 
> >

I believe the problem is, that both engines (audio & video) use the global `transcode to LPCM ` configuration option. It's not configurable for "only audio" or "only video".

**Comment by ik666** [comment]
> I think this PR is huge and have a lot of changes.
> Maybe it should be merged first, then we can open another PR for next thinking.

Yeah. I tried a few thing, but let's first merge this and see, how to proceed ...

**Comment by SubJunk** [comment]
I added the file suggested at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4572#issue-2233442576 and I get an error:

```
DEBUG 2024-06-14 18:50:34.544 [MediaScanner File Parser] Analyzing file my_internet_radio_station2.m3u
TRACE 2024-06-14 18:50:34.544 [MediaScanner File Parser] Matched format PLAYLIST to ".m3u"
DEBUG 2024-06-14 18:50:34.545 [MediaScanner File Parser] Reading m3u playlist: my_internet_radio_station2.m3u
DEBUG 2024-06-14 18:50:34.545 [MediaScanner File Parser] Adding playlist entry: [https://dancewave.online/dance.mp3,Dance Wave!]
TRACE 2024-06-14 18:50:34.545 [MediaScanner File Parser] Matched format WEB to "https://dancewave.online/dance.mp3"
TRACE 2024-06-14 18:50:34.545 [MediaScanner File Parser] Adding new child "Dance Wave!" with class "WebAudioStream"
TRACE 2024-06-14 18:50:34.545 [MediaScanner File Parser] Adding "Dance Wave!" to transcode folder for engine: "null"
ERROR 2024-06-14 18:50:34.545 [MediaScanner File Parser] Adding container entry 24127 for 24130 
TRACE 2024-06-14 18:50:34.545 [MediaScanner File Parser] Store do not yet contains MediaInfo for https://dancewave.online/dance.mp3
TRACE 2024-06-14 18:50:34.546 [MediaScanner File Parser] Adding audio from the database: Audio Id: 0, Codec: -, Bitrate: 128, Channels: 2, Sample Frequency: 48000 Hz
TRACE 2024-06-14 18:50:34.546 [MediaScanner File Parser] Searching AUDIO_METADATA with "HikariProxyPreparedStatement@2041336265 wrapping prep200495: SELECT * FROM AUDIO_METADATA WHERE FILEID = ? LIMIT 1 {1: CAST(24127 AS BIGINT)}"
TRACE 2024-06-14 18:50:34.546 [MediaScanner File Parser] Searching VIDEO_METADATA with "HikariProxyPreparedStatement@2106837540 wrapping prep200496: SELECT * FROM VIDEO_METADATA WHERE VIDEO_METADATA.FILEID = ? AND (VIDEO_METADATA.IMDBID IS NOT NULL OR VIDEO_METADATA.TMDBID IS NOT NULL) LIMIT 1 {1: CAST(24127 AS BIGINT)}"
TRACE 2024-06-14 18:50:35.350 [NetworkConfiguration Watcher] Checking network configuration changes
ERROR 2024-06-14 18:50:37.799 [MediaScanner File Parser] Database error while trying to add parsed information for "https://dancewave.online/dance.mp3" to the cache: Cannot invoke "net.pms.media.audio.MediaAudio.setBitRate(int)" because the return value of "net.pms.media.MediaInfo.getDefaultAudioTrack()" is null
TRACE 2024-06-14 18:50:37.799 [MediaScanner File Parser] Queuing background WebStream lookup for https://dancewave.online/dance.mp3
INFO  2024-06-14 18:50:37.799 [MediaScanner File Parser] New file my_internet_radio_station2.m3u was detected and added to the media store
INFO  2024-06-14 18:50:37.799 [Lookup RadioBrowser Metadata background worker 2] paging=Paging(offset=0, limit=1)
DEBUG 2024-06-14 18:50:37.799 [Lookup RadioBrowser Metadata background worker 2] Connecting to https://nl1.api.radio-browser.info/json/stations/byuuid/962cc6df-0601-11e8-ae97-52543be04c81
DEBUG 2024-06-14 18:50:37.799 [Lookup RadioBrowser Metadata background worker 2] POST WWW-Form-UrlEncoded body: offset=0&limit=1
```

**Comment by SurfaceS** [comment]
@SubJunk 
I fixed that on the @ik666 PR https://github.com/ik666/UniversalMediaServer/pull/92
Just have to wait he merge it :)

**Comment by ik666** [comment]
@SubJunk Now it's merged

**Comment by SubJunk** [comment]
Thanks, I will test it. Can you resolve the conflicts?

**Comment by ik666** [comment]
@SubJunk  Conflict is resolved ... but now we have a compile error ... @SurfaceS maybe you can have a look, since it look like a small change you made.

**Comment by SurfaceS** [comment]
@SubJunk fixed

**Comment by SubJunk** [comment]
Now I get a very long stacktrace when I add that same file:

```
WARN  2024-07-02 20:37:52.440 [Lookup RadioBrowser Metadata background worker 1] Endpoint https://all.api.radio-browser.info/ had an exception
java.util.concurrent.ExecutionException: de.sfuhrm.radiobrowser4j.RadioBrowserException: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching all.api.radio-browser.info found.
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at de.sfuhrm.radiobrowser4j.EndpointDiscovery.discoverApiUrls(EndpointDiscovery.java:179)
	at de.sfuhrm.radiobrowser4j.EndpointDiscovery.discover(EndpointDiscovery.java:202)
	at net.pms.external.radiobrowser.RadioBrowser4j.isRadioBrowserExists(RadioBrowser4j.java:90)
	at net.pms.external.radiobrowser.RadioBrowser4j.getWebStreamMetadata(RadioBrowser4j.java:111)
	at net.pms.external.radiobrowser.RadioBrowser4j.lambda$backgroundLookupAndAddMetadata$0(RadioBrowser4j.java:192)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: de.sfuhrm.radiobrowser4j.RadioBrowserException: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching all.api.radio-browser.info found.
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.lambda$get$0(RestDelegateImpl.java:195)
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.retryLoop(RestDelegateImpl.java:206)
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.get(RestDelegateImpl.java:185)
	at de.sfuhrm.radiobrowser4j.RadioBrowser.getServerStats(RadioBrowser.java:431)
	at de.sfuhrm.radiobrowser4j.EndpointDiscovery.lambda$discoverApiUrls$2(EndpointDiscovery.java:166)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching all.api.radio-browser.info found.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.logResponseStatus(RestDelegateImpl.java:383)
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.checkResponseStatus(RestDelegateImpl.java:369)
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.readerFor(RestDelegateImpl.java:171)
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.lambda$get$0(RestDelegateImpl.java:189)
	... 8 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching all.api.radio-browser.info found.
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
	at java.base/java.net.URLConnection.getContentEncoding(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(Unknown Source)
	at de.sfuhrm.radiobrowser4j.RestDelegateImpl.readerFor(RestDelegateImpl.java:167)
	... 9 common frames omitted
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching all.api.radio-browser.info found.
	at java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)
	at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 29 common frames omitted
```

**Comment by ik666** [comment]
Funny, I don't get this error ...
I could bypass "SSL Certificate Verification" but ... don't know if this is a good idea ...

**Comment by ik666** [comment]
And it is playing fine ... 
dance_radio_playing

**Comment by ik666** [comment]
@SubJunk I took a deeper look. The `radiobrowser4j` library does the following in the class `de.sfuhrm.radiobrowser4j.EndpointDiscovery`

1) DNS lookup for the domain `all.api.radio-browser.info`  (line 115 )

In my case I get the following IP addresses: 91.132.145.114, 89.58.16.19, 65.109.136.86

2) reverse DNS lookup of delivered IP addresses (line 118)

In my case I get : de1.api.radio-browser.info, at1.api.radio-browser.info, nl1.api.radio-browser.info

3) Pick the fastest endpoint and open an API connection.

Here you get the error for the address in step 1 `all.api.radio-browser.info`. Looks like the complete DNS lookup doesn't work on your side. Instead your system tries to connect to the DNS QUERY record. However the HTTP address `http://all.api.radio-browser.info` doesn't have a valid certificate (and actually no api endpoint, so wouldn't work anyway). 

Maybe you can do a `dig` from command line. It should show you the IP addresses reachable from your side. In my case they are the same :

```
# dig all.api.radio-browser.info

; <<>> DiG 9.10.6 <<>> all.api.radio-browser.info
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20312
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;all.api.radio-browser.info.	IN	A

;; ANSWER SECTION:
all.api.radio-browser.info. 18	IN	A	89.58.16.19
all.api.radio-browser.info. 18	IN	A	65.109.136.86
all.api.radio-browser.info. 18	IN	A	91.132.145.114

```

**Comment by SurfaceS** [comment]
seems that radio-browser is mainly served for http (not https).
http://all.api.radio-browser.info/
All the API syntax are http://.....

and they serve mostly http links.

https://all.api.radio-browser.info/ advertise nl1.api.radio-browser.info certificate, without any cert for the all.api.radio-browser.info domain. -> fail.

Sadly, de.sfuhrm.radiobrowser4j.RadioBrowser hard coded https to format the url `String.format("https://%s/", s)` and check on it (that is falling).
Would be better if they had added an option to use http or https.

http run fine btw.

**Comment by ik666** [comment]
> seems that radio-browser is mainly served for http (not https).

I don't think so ... from the docs reading at `https://api.radio-browser.info/` 

```

[...]
Now you have a list of multiple names of servers which you can use to directly connect to with HTTP and preferably HTTPS.
Example: https://de1.api.radio-browser.info, https://de2.api.radio-browser.info, ..
[...]
```

The issue is, that `all.api.radio-browser.info` is not a valid endpoint. It's only a DNS record for looking up IP addresses.

**Comment by SubJunk** [comment]
It plays ok if I go to the mp3 file directly in the web browser
I will run dig soon, probably tomorrow

**Comment by ik666** [comment]
> It plays ok if I go to the mp3 file directly in the web browser I will run dig soon, probably tomorrow

You can try to force a default renderer like `BubbleUPnP`.

**Comment by SubJunk** [comment]
By "directly" I mean I just open https://dancewave.online/dance.mp3 in Chrome, outside of UMS

**Comment by SubJunk** [comment]
# dig all.api.radio-browser.info

; <<>> DiG 9.10.6 <<>> all.api.radio-browser.info
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17099
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;all.api.radio-browser.info.	IN	A

;; ANSWER SECTION:
all.api.radio-browser.info. 300	IN	A	91.132.145.114
all.api.radio-browser.info. 300	IN	A	65.109.136.86
all.api.radio-browser.info. 300	IN	A	89.58.16.19

;; Query time: 930 msec
;; SERVER: 2405:da40:4371:3200:8601:12ff:fe22:a9d7#53(2405:da40:4371:3200:8601:12ff:fe22:a9d7)
;; WHEN: Fri Jul 05 10:47:58 NZST 2024
;; MSG SIZE  rcvd: 103

**Comment by SubJunk** [comment]
Is there another radio station I can test with?

**Comment by ik666** [comment]
> By "directly" I mean I just open https://dancewave.online/dance.mp3 in Chrome, outside of UMS

Yeah, I thought so, but still please try to force a default renderer like "BubbleUpnp" or "Nextcp2". I believe, both configurations will play the stream in the UI, even if you can't collect the metadata from radiobrowser.

**Comment by ik666** [comment]
> Is there another radio station I can test with?

Sure, this is also playing in the UI ...

```
#EXTINF:1,Discover Trance 2
http://chicago.discovertrance.com:9214/relay?type=http&nocache=2136
```

**Comment by ik666** [comment]
> ;; ANSWER SECTION:
> all.api.radio-browser.info. 300	IN	A	91.132.145.114
> all.api.radio-browser.info. 300	IN	A	65.109.136.86
> all.api.radio-browser.info. 300	IN	A	89.58.16.19

Hmmm ... looks good, the answer section is just right. So the first `InetAddress` array (line 115) should be filled with those 3 IP addresses ... 

Could you please check the reverse DNS lookup with `dig -x`  of the 3 ip addresses ... like 
```
# dig -x 91.132.145.114

; <<>> DiG 9.10.6 <<>> -x 91.132.145.114
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8459
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;114.145.132.91.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
114.145.132.91.in-addr.arpa. 1753 IN	PTR	de1.api.radio-browser.info.

;; Query time: 8 msec
;; SERVER: 10.0.0.9#53(10.0.0.9)
;; WHEN: Fri Jul 05 08:19:54 CEST 2024
;; MSG SIZE  rcvd: 96
```

Checking the "ANSWER SECTION" is just enough ... You should get these 3 answers : `de1.api.radio-browser.info, at1.api.radio-browser.info, nl1.api.radio-browser.info`

**Comment by SubJunk** [comment]
That one does not give me that error, but I got another one. Possibly related to the way I created the file. I made a new `.txt` file, then populated it, then renamed it to `radio-sample.m3u`. And I get:

```
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Matched format WEB to "https://dancewave.online/dance.mp3"
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Adding new child "Dance Wave!" with class "WebAudioStream"
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Getting engine for resource "Dance Wave!"
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Engine "FFmpeg Video" is incompatible
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Engine "AviSynth/FFmpeg" is incompatible
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Engine "MEncoder Video" is incompatible
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Engine "AviSynth/MEncoder" is incompatible
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Engine "tsMuxeR Video" is incompatible
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Engine "VLC Video" is incompatible
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Returning compatible engine "FFmpeg Audio"
DEBUG 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] File "Dance Wave!" will not be streamed because it is not supported by the renderer Chrome
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Matched format MP3 to ".mp3"
DEBUG 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Final verdict: "Dance Wave!" will be transcoded with engine "FFmpeg Audio" with mime type "audio/mpeg"
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Adding "Dance Wave!" to transcode folder for engine: "FFmpeg Audio"
ERROR 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Container entry 24209 for 24210 already exists
TRACE 2024-07-07 20:30:42.167 [LibraryResource resolver thread 221259-1] Queuing background WebStream lookup for https://dancewave.online/dance.mp3
```

I see the file as a folder when I browse to it, but nothing is inside it. How do I use it?

image

**Comment by ik666** [comment]
@SubJunk Maybe you can try to naming it with a `.m3u8` extension. However FYI,  your logs are still pointing to `https://dancewave.online/dance.mp3` and not `http://chicago.discovertrance.com:9214/relay?type=http&nocache=2136` ...

Both radio stations in one file would look like this :

```
#EXTM3U

#EXTINF:1,Discover Trance 2
http://chicago.discovertrance.com:9214/relay?type=http&nocache=2136

#RADIOBROWSERUUID:962cc6df-0601-11e8-ae97-52543be04c81
#EXTINF:1,Dance Wave!
https://dancewave.online/dance.mp3
```

**Comment by SubJunk** [comment]
It would probably be good to use a different icon for the playlists because they look like just folders @ik666 

Also the ordering changes every time I visit the page in the web player, it goes from A-Z to Z-A, maybe one for @SurfaceS 
This is the same browse page, fetched twice in a row:

image

image

**Comment by SubJunk** [comment]
The good news is that Discover Trance 2 plays for me:

image

So it seems like despite the problems it works. It would be good to get those problems fixed before it merges though

**Comment by SurfaceS** [comment]
> Also the ordering changes every time I visit the page in the web player, it goes from A-Z to Z-A, maybe one for @SurfaceS
This is the same browse page, fetched twice in a row:

@SubJunk this is not related to this PR, as it does it without it.
I'll have a look.

**Comment by SubJunk** [comment]
@dependabot recreate

**Comment by ik666** [comment]
> It would probably be good to use a different icon for the playlists because they look like just folders @ik666

This is actually the default behaviour. All playlists look like folders. I usually put my own "folder artwork" by placing an image file with same basename next to the playlist file.

**Comment by SubJunk** [comment]
Ok, we can make another issue for the icons
It would be good to fix that `At least one output file must be specified` FFmpeg error though

**Comment by sf666** [comment]
> Ok, we can make another issue for the icons It would be good to fix that `At least one output file must be specified` FFmpeg error though

@SurfaceS I think you have added the ffmpeg link? I'm actually not familiar with this tool. Maybe you can have a look?

**Comment by SurfaceS** [comment]
should fix FFmpeg error

**Comment by SubJunk** [comment]
@dependabot recreate

**Pull request merged**
