### PR TITLE
11.0.0 HLS implementation

### PR DESCRIPTION
**Pull request by SurfaceS**

### CODE REVIEW

**Comment by SurfaceS** [comment]
@SubJunk did you try this one ?

**Comment by SubJunk** [comment]
@SurfaceS not yet, but I'm excited to when I have time. Hopefully later tonight

**Comment by SubJunk** [comment]
@SurfaceS testing this now. Can you sync v11 branch with master please?

**Comment by SubJunk** [comment]
@SurfaceS great job, this is working very well already! I'm impressed. If we released it today it would be an improvement on what we have.
I noticed a couple of things:

1) There's no "started playing" event and the GUI doesn't seem to know which video is playing, despite showing the correct time:
image

2) The video seems starved for bitrate in some cases so those settings can maybe be tweaked. The browser by default on 1080p used Standard Definition and it was very blocky in places, despite that being the right pixels at the time, so maybe `1200000` can be increased. It's a fine bitrate but the ultrafast preset requires high bitrates since it is skipping so many compression optimizations.

**Comment by SurfaceS** [comment]
> The video seems starved for bitrate in some cases so those settings can maybe be tweaked. The browser by default on 1080p used Standard Definition and it was very blocky in places, despite that being the right pixels at the time, so maybe 1200000 can be increased. It's a fine bitrate but the ultrafast preset requires high bitrates since it is skipping so many compression optimizations.

Video js choose the quality from bitrates and size. If you full screen the video, it will change the quality (after playing the buffered parts) automatically. On our case, it's not the bitrate settings, it's the div that show the screen that choose the LD quality.
You can see that before playing the video, your browser have chosen LD to buffer. Even with lower bitrate it choose LD to fit the div.

**Comment by SubJunk** [comment]
@SurfaceS I pushed a fix to make the bitrates automatic, so it will be lower with low motion and higher with high motion/more difference between frames. Will that break anything in your code? Does your approach need a constant bitrate?

**Comment by SurfaceS** [comment]
> I pushed a fix to make the bitrates automatic
That what I've done before seeing HLS requirements (bitrates must not exceed 70% or something like that, or the client should close the stream) so I'd added this. But I believe most HLS client implementation would not really obey that rule.

I added chapters to UMS.

**Comment by SubJunk** [comment]
@SurfaceS can you please point me to the documentation about the bitrate limits? I can make FFmpeg limit the maximum bitrates but still use crf

**Comment by SubJunk** [comment]
That's done now with the previous values. Seems to work well in brief testing

**Comment by SurfaceS** [comment]
@SubJunk [HLS Spec](https://developer.apple.com/documentation/http_live_streaming/http_live_streaming_hls_authoring_specification_for_apple_devices)

> 	1.29. For live (linear) content, the measured peak bit rate MUST be less than 125% of the BANDWIDTH attribute.
1.30. For VOD content, the peak bit rate SHOULD be no more than 200% of the average bit rate.

**Comment by SurfaceS** [comment]
@SubJunk I add a quality selector

**Comment by SubJunk** [comment]
@SurfaceS That's a good idea especially for those accessing via external network

I noticed an error when I started this version:

```
WARN  2022-04-10 15:04:10.081 [jupnp-sync-protocol-5] Error generating requested device/service descriptor: org.jupnp.binding.xml.DescriptorBindingException: Could not build DOM: Could not generate device descriptor: String index out of range: 22
DEBUG 2022-04-10 15:04:10.081 [jupnp-sync-protocol-6] Matched media renderer "Panasonic TV" based on headers {Host=192.168.1.128:5001, User-agent=Panasonic MIL DLNA CP UPnP/1.0 DLNADOC/1.50, X-panasonic-dmp-profile=MPEG_PS_PAL JPEG_SM PV_DIVX_DIV3 PV_DIVX_DIV4 PV_DIVX_DIVX PV_DIVX_DX50 PV_DRM_DIVX_DIV3 PV_DRM_DIVX_DIV4 PV_DRM_DIVX_DIVX PV_DRM_DIVX_DX50, X-panasonic-registration=VklFUkEgVlQ2MCBTZXJpZXMAAAAAAAAAAAA=}
DEBUG 2022-04-10 15:04:10.082 [jupnp-sync-protocol-6] Reading automatic_maximum_bitrate: false (default: true)
DEBUG 2022-04-10 15:04:10.082 [jupnp-sync-protocol-6] Reading RendererName: "Panasonic TV" (default: "Unknown renderer")
DEBUG 2022-04-10 15:04:10.082 [jupnp-sync-protocol-6] Adding status button for Panasonic TV
DEBUG 2022-04-10 15:04:10.082 [jupnp-netty-worker-3] Received MessageEvent event: GET /dev/520553da-d500-4f05-aa1a-05f1f2e2493e/desc
DEBUG 2022-04-10 15:04:10.082 [jupnp-netty-worker-3] Received synchronous stream: (NettyUpnpStream)
WARN  2022-04-10 15:04:10.082 [jupnp-sync-protocol-5] Exception root cause: 
java.lang.StringIndexOutOfBoundsException: String index out of range: 22
	at java.base/java.lang.StringLatin1.charAt(Unknown Source)
	at java.base/java.lang.String.charAt(Unknown Source)
	at java.base/java.util.regex.Pattern$SliceI.match(Unknown Source)
	at java.base/java.util.regex.Pattern$Start.match(Unknown Source)
	at java.base/java.util.regex.Matcher.search(Unknown Source)
	at java.base/java.util.regex.Matcher.find(Unknown Source)
	at net.pms.configuration.RendererConfiguration.match(RendererConfiguration.java:2694)
	at net.pms.configuration.RendererConfiguration.getRendererConfigurationByHeaders(RendererConfiguration.java:625)
	at net.pms.configuration.RendererConfiguration.getRendererConfigurationByHeaders(RendererConfiguration.java:602)
	at net.pms.configuration.RendererConfiguration.getRendererConfigurationByHeaders(RendererConfiguration.java:597)
	at net.pms.network.mediaserver.jupnp.model.meta.UmsRemoteClientInfo.toRendererConfiguration(UmsRemoteClientInfo.java:84)
	at net.pms.network.mediaserver.jupnp.model.meta.UmsRemoteClientInfo.<init>(UmsRemoteClientInfo.java:57)
	at net.pms.network.mediaserver.jupnp.model.meta.UmsDeviceDetailsProvider.provide(UmsDeviceDetailsProvider.java:49)
	at net.pms.network.mediaserver.jupnp.model.meta.UmsLocalDevice.getDetails(UmsLocalDevice.java:64)
	at org.jupnp.binding.xml.UDA10DeviceDescriptorBinderImpl.generateDevice(UDA10DeviceDescriptorBinderImpl.java:443)
	at org.jupnp.binding.xml.UDA10DeviceDescriptorBinderImpl.generateRoot(UDA10DeviceDescriptorBinderImpl.java:428)
	at org.jupnp.binding.xml.UDA10DeviceDescriptorBinderImpl.buildDOM(UDA10DeviceDescriptorBinderImpl.java:406)
	at org.jupnp.binding.xml.UDA10DeviceDescriptorBinderImpl.generate(UDA10DeviceDescriptorBinderImpl.java:390)
	at org.jupnp.protocol.sync.ReceivingRetrieval.createResponse(ReceivingRetrieval.java:98)
	at org.jupnp.protocol.sync.ReceivingRetrieval.executeSync(ReceivingRetrieval.java:82)
	at org.jupnp.protocol.ReceivingSync.execute(ReceivingSync.java:62)
	at org.jupnp.protocol.ReceivingAsync.run(ReceivingAsync.java:69)
	at org.jupnp.transport.spi.UpnpStream.process(UpnpStream.java:81)
	at net.pms.network.mediaserver.jupnp.transport.impl.NettyUpnpStream.run(NettyUpnpStream.java:151)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
@SurfaceS it looks like the spec doesn't have any rules about bitrates, it says:

> There are many possible choices of bit rates for variants. The following tables provide one possible set of bit rate variants.

So for now I have made it rely on x264's CRF. It defaults to a good compromise between bitrate and quality (CRF 23 from memory) so it should provide a nice starting point. I think the client can make its own choices about which video it wants to play.

**Comment by SubJunk** [comment]
@SurfaceS I get an error when creating the chapters table:

```
org.h2.jdbc.JdbcSQLNonTransientException: General error: "Chunk 35 not found [2.1.210/9]"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."CHAPTERS"(
    "ID" INTEGER SELECTIVITY 4 NOT NULL,
    "FILEID" BIGINT SELECTIVITY 12 NOT NULL,
    "LANG" CHARACTER VARYING(3) SELECTIVITY 1 NOT NULL,
    "TITLE" CHARACTER VARYING(255) SELECTIVITY 36,
    "START_TIME" DOUBLE PRECISION SELECTIVITY 76,
    "END_TIME" DOUBLE PRECISION SELECTIVITY 87,
    "THUMBNAIL" JAVA_OBJECT SELECTIVITY 1
) [50000-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166)
	at org.h2.mvstore.db.Store.createTable(Store.java:200)
	at org.h2.schema.Schema.createTable(Schema.java:781)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:109)
	at org.h2.engine.MetaRecord.prepareAndExecute(MetaRecord.java:77)
	at org.h2.engine.Database.executeMeta(Database.java:660)
	at org.h2.engine.Database.executeMeta(Database.java:634)
	at org.h2.engine.Database.<init>(Database.java:357)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:322)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:352)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:233)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:198)
	at net.pms.database.Database.getConnection(Database.java:140)
	at net.pms.database.Database.open(Database.java:202)
	at net.pms.database.Database.init(Database.java:160)
	at net.pms.database.MediaDatabase.init(MediaDatabase.java:191)
	at net.pms.PMS.init(PMS.java:429)
	at net.pms.PMS.createInstance(PMS.java:922)
	at net.pms.PMS.main(PMS.java:1087)
Caused by: org.h2.mvstore.MVStoreException: Chunk 35 not found [2.1.210/9]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:1383)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2565)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:631)
	at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:656)
	at org.h2.mvstore.MVMap.setRootPos(MVMap.java:641)
	at org.h2.mvstore.MVStore.openMap(MVStore.java:694)
	at org.h2.mvstore.MVStore.openMap(MVStore.java:640)
	at org.h2.mvstore.tx.TransactionStore.openMap(TransactionStore.java:564)
	at org.h2.mvstore.tx.TransactionStore.openVersionedMap(TransactionStore.java:550)
	at org.h2.mvstore.tx.Transaction.openMap(Transaction.java:456)
	at org.h2.mvstore.db.MVPrimaryIndex.<init>(MVPrimaryIndex.java:53)
	at org.h2.mvstore.db.MVTable.<init>(MVTable.java:156)
	at org.h2.mvstore.db.Store.createTable(Store.java:196)
	... 22 common frames omitted
```

**Comment by SurfaceS** [comment]
You can choose and advice the bitrate you want, but :
1.27. For VOD content, the measured peak bit rate MUST be within 10% of the BANDWIDTH attribute.
https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/creating_a_multivariant_playlist
BANDWIDTH -> (Required) An integer that is the upper bound of the overall bit rate for each media file, in bits per second.

**Concerning frame rates :**
1.19. Frame rates above 60 fps SHALL NOT be used. 
1.20. * For HDR content, frame rates less than or equal to 30 fps SHOULD be provided.

**Comment by SubJunk** [comment]
@SurfaceS I see, yes the bandwidth is quite restrictive there, I guess we can go back to having more control over it but then it will need to use more bandwidth overall.
Maybe we should try leaving it like this for testing, and if people have problems we can lock it down more, what do you think?

**Comment by SubJunk** [comment]
@SurfaceS if you can remove https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2880/commits/e0f3d162c520300315e76dfbc261f9f2c0749641 from this branch I think we can merge this to v11 branch, it is working well for me

**Pull request merged**
