### PR TITLE
Playlist support - PR2

### PR DESCRIPTION
**Pull request by atamariya**
Smaller subset for easier merge.

### CODE REVIEW

**Comment by Sami32** [comment]
That's a much more handling size :wink:

**Comment by Sami32** [comment]
@atamariya I just tried it, without error, except a NPE, but i suspect it's need to come from elsewhere since you didn't touch _FFmpegVideo.java_ file.
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/java/net/pms/encoders/FFMpegVideo.java#L248

[debug.log_atamariya.txt.7z.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/467554/debug.log_atamariya.txt.7z.txt)

**Comment by Sami32** [comment]
@atamariya I get some compilation issues (missing symbol):
capture_09122016_172423

**Comment by Sami32** [comment]
Did anyone tested it ?

As i'm not able to compile it without issues, perhaps someone did ?

**Comment by SubJunk** [comment]
Feel free to resurrect if the compilation problem that @Sami32 mentioned is fixed

**Pull request closed without merging**
