### PR TITLE
H2 upgrade

### LINKED ISSUE #2742: Unstable testIsFullyPlayed
This test is making master unstable and needs to be fixed. Unfortunately I can't reproduce the failure locally, so am debugging it by pushing commits to here. Any ideas would be helpful. https://github.com/UniversalMediaServer/UniversalMediaServer/runs/4611809555?check_suite_focus=true

```
Error:  Failures: 
Error:    TableFilesStatusTest.testIsFullyPlayed:103 
Expecting actual not to be null
```

### PR DESCRIPTION
**Pull request by SurfaceS**
#2715 #2733 #2745
db upgrade to 2.0.204 

Renamed table and column names that conflict with SQL reserved words (YEAR, KEY, VALUES, TABLES, TYPE, and so on).

Move the net.pms.dlna.DLNAMediaDatabase to pms.database.MediasDatabase
Split the database, helper, and medias database into classes.
Move the tables creation, usage, etc from DLNAMediaDatabase to their own table class to reflect others tables handling.
Renamed all tables class to reflect their database (in case a day you want to add another database and avoid mess up).

Refactored database to mediasDatabase from pms.java.

Fixes #2742
For the bug, I can't reproduce the failure locally as well.
I put a drop on tables/constraints to make the test on a fresh tables, and seems that's do the trick.

### CODE REVIEW

**Comment by SubJunk** [comment]
@SurfaceS thank you, this looks great at first glance. I will review and test it.
Can you make a small change, to use `media` instead of `medias`? e.g. `mediaDatabase` instead of `mediasDatabase`

**Comment by SurfaceS** [comment]
@SubJunk  
>Can you make a small change, to use media instead of medias? e.g. mediaDatabase instead of mediasDatabase

I named it `medias...` because the database is `medias`, but yes, I can do it.

**Comment by SubJunk** [comment]
@SurfaceS I see, that will be a really old typo in the codebase :) thanks

**Review by SubJunk — APPROVED** [review]
The code looks good to me, but I still need to test before merging. Nice work!

**Comment by SubJunk** [comment]
@SurfaceS during testing the table upgrades appear to succeed, but later on during the library scan I see this error:

```
ERROR 2021-12-27 11:03:09.057 [Library Scanner] Database error while trying to add parsed information for "video.mkv" to the cache: Data conversion error converting "'' (AUDIOTRACKS: ""MBID_RECORD"" UUID SELECTIVITY 1)"; SQL statement:
UPDATE "PUBLIC"."AUDIOTRACKS" SET "FILEID"=? ,"ID"=? ,"MBID_RECORD"=? ,"MBID_TRACK"=? ,"LANG"=? ,"TITLE"=? ,"NRAUDIOCHANNELS"=? ,"SAMPLEFREQ"=? ,"CODECA"=? ,"BITSPERSAMPLE"=? ,"ALBUM"=? ,"ARTIST"=? ,"ALBUMARTIST"=? ,"SONGNAME"=? ,"GENRE"=? ,"MEDIA_YEAR"=? ,"TRACK"=? ,"DISC"=? ,"DELAY"=? ,"MUXINGMODE"=? ,"BITRATE"=?  WHERE "FILEID"=? AND "ID"=? [22018-204]
TRACE 2021-12-27 11:03:09.057 [Library Scanner] SQL error code: 22018
TRACE 2021-12-27 11:03:09.059 [Library Scanner] 
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (AUDIOTRACKS: ""MBID_RECORD"" UUID SELECTIVITY 1)"; SQL statement:
UPDATE "PUBLIC"."AUDIOTRACKS" SET "FILEID"=? ,"ID"=? ,"MBID_RECORD"=? ,"MBID_TRACK"=? ,"LANG"=? ,"TITLE"=? ,"NRAUDIOCHANNELS"=? ,"SAMPLEFREQ"=? ,"CODECA"=? ,"BITSPERSAMPLE"=? ,"ALBUM"=? ,"ARTIST"=? ,"ALBUMARTIST"=? ,"SONGNAME"=? ,"GENRE"=? ,"MEDIA_YEAR"=? ,"TRACK"=? ,"DISC"=? ,"DELAY"=? ,"MUXINGMODE"=? ,"BITRATE"=?  WHERE "FILEID"=? AND "ID"=? [22018-204]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:525)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.table.Column.getDataConversionError(Column.java:413)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:372)
	at org.h2.table.Table.convertUpdateRow(Table.java:959)
	at org.h2.command.dml.SetClauseList.prepareUpdate(SetClauseList.java:140)
	at org.h2.command.dml.Update.update(Update.java:88)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:61)
	at org.h2.command.CommandContainer.update(CommandContainer.java:173)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at org.h2.result.UpdatableRow.updateRow(UpdatableRow.java:296)
	at org.h2.jdbc.JdbcResultSet.updateRow(JdbcResultSet.java:3363)
	at net.pms.database.MediaTableAudiotracks.insertOrUpdateAudioTracks(MediaTableAudiotracks.java:252)
	at net.pms.database.MediaTableFiles.insertOrUpdateData(MediaTableFiles.java:886)
	at net.pms.dlna.RealFile.resolve(RealFile.java:270)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1492)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1291)
	at net.pms.dlna.RealFile.isValid(RealFile.java:95)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:537)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:289)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:364)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:284)
	at net.pms.dlna.RootFolder.scan(RootFolder.java:250)
	at net.pms.database.MediaDatabase.run(MediaDatabase.java:96)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.message.DbException: Data conversion error converting  [22018-204]
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.value.ValueUuid.get(ValueUuid.java:125)
	at org.h2.value.Value.convertToUuid(Value.java:2446)
	at org.h2.value.Value.convertTo(Value.java:1180)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	... 23 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting  [22018-204]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:525)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 30 common frames omitted
```

**Comment by SubJunk** [comment]
There are also some remaining instances of the renamed columns to change, like renaming `TYPE` to `FORMAT_TYPE` in `MediaLibrary.java`

**Comment by SubJunk** [comment]
I'm not seeing the problems after the last commit, I'll continue testing just in case but it's looking good so far

**Comment by SubJunk** [comment]
There's still the bug with 22018 error code:

```
ERROR 2021-12-27 17:52:07.036 [StopPlaying Event] Database error while trying to add parsed information for "video.mkv" to the cache: Data conversion error converting "'' (AUDIOTRACKS: ""MBID_RECORD"" UUID SELECTIVITY 1)"; SQL statement:
UPDATE "PUBLIC"."AUDIOTRACKS" SET "FILEID"=? ,"ID"=? ,"MBID_RECORD"=? ,"MBID_TRACK"=? ,"LANG"=? ,"TITLE"=? ,"NRAUDIOCHANNELS"=? ,"SAMPLEFREQ"=? ,"CODECA"=? ,"BITSPERSAMPLE"=? ,"ALBUM"=? ,"ARTIST"=? ,"ALBUMARTIST"=? ,"SONGNAME"=? ,"GENRE"=? ,"MEDIA_YEAR"=? ,"TRACK"=? ,"DISC"=? ,"DELAY"=? ,"MUXINGMODE"=? ,"BITRATE"=?  WHERE "FILEID"=? AND "ID"=? [22018-204]
TRACE 2021-12-27 17:52:07.036 [StopPlaying Event] SQL error code: 22018
TRACE 2021-12-27 17:52:07.036 [StopPlaying Event] 
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (AUDIOTRACKS: ""MBID_RECORD"" UUID SELECTIVITY 1)"; SQL statement:
UPDATE "PUBLIC"."AUDIOTRACKS" SET "FILEID"=? ,"ID"=? ,"MBID_RECORD"=? ,"MBID_TRACK"=? ,"LANG"=? ,"TITLE"=? ,"NRAUDIOCHANNELS"=? ,"SAMPLEFREQ"=? ,"CODECA"=? ,"BITSPERSAMPLE"=? ,"ALBUM"=? ,"ARTIST"=? ,"ALBUMARTIST"=? ,"SONGNAME"=? ,"GENRE"=? ,"MEDIA_YEAR"=? ,"TRACK"=? ,"DISC"=? ,"DELAY"=? ,"MUXINGMODE"=? ,"BITRATE"=?  WHERE "FILEID"=? AND "ID"=? [22018-204]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:525)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.table.Column.getDataConversionError(Column.java:413)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:372)
	at org.h2.table.Table.convertUpdateRow(Table.java:959)
	at org.h2.command.dml.SetClauseList.prepareUpdate(SetClauseList.java:140)
	at org.h2.command.dml.Update.update(Update.java:88)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:61)
	at org.h2.command.CommandContainer.update(CommandContainer.java:173)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at org.h2.result.UpdatableRow.updateRow(UpdatableRow.java:296)
	at org.h2.jdbc.JdbcResultSet.updateRow(JdbcResultSet.java:3363)
	at net.pms.database.MediaTableAudiotracks.insertOrUpdateAudioTracks(MediaTableAudiotracks.java:252)
	at net.pms.database.MediaTableFiles.insertOrUpdateData(MediaTableFiles.java:884)
	at net.pms.dlna.RealFile.resolve(RealFile.java:270)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1492)
	at net.pms.dlna.RootFolder.parseFileForDatabase(RootFolder.java:1600)
	at net.pms.dlna.MediaMonitor.stopped(MediaMonitor.java:272)
	at net.pms.dlna.RootFolder.stopPlaying(RootFolder.java:1510)
	at net.pms.dlna.DLNAResource.internalStop(DLNAResource.java:4475)
	at net.pms.dlna.DLNAResource.lambda$null$1(DLNAResource.java:3019)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.message.DbException: Data conversion error converting  [22018-204]
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.value.ValueUuid.get(ValueUuid.java:125)
	at org.h2.value.Value.convertToUuid(Value.java:2446)
	at org.h2.value.Value.convertTo(Value.java:1180)
	at org.h2.value.Value.convertForAssignTo(Value.java:1092)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:369)
	... 20 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting  [22018-204]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:525)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 27 common frames omitted
```

**Comment by SurfaceS** [comment]
UUID's are not strings. I think before they store it like a string and now as 128 bit as it should.
If we try to store an empty string, the new db engine will fail on converting it to uuid.
I'll make change to handle this.

**Comment by SubJunk** [comment]
That seems to have fixed this problem, but now I noticed another problem with hanging shutdown which I'm investigating. It's the same bug we had before that caused us to rollback h2 to 197, but I thought it had been fixed

**Comment by SubJunk** [comment]
I don't think it's related to this since I also reproduced it on `master`, unreliably. Very strange. Anyway this seems to work well, and is a great improvement. Thank you!

**Review by SubJunk — APPROVED** [review]

**Pull request merged**
