### PR TITLE
Added ThumbnailPadding renderer option, defaulting to false

### PR DESCRIPTION
**Pull request by SubJunk**
@UniversalMediaServer/developers I think this is ready to merge unless there are objections

It removes the black padding from our thumbnails by default.

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/821)

### CODE REVIEW

**Comment by Nadahar** [comment]
I'm working on a more complete solutions for thumbnails, but it will take some time because there's so much job to get some kind of an overview of this as it's mixed together with everything else.

Any such temporary solutions will just be more to undo, so I'm not sure it's worth it unless it's extremely annoying for the users.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/net/pms/dlna/DLNAMediaDatabase.java, line 64 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/821#-K9clEu25apPOduG46Yi:-K9clEu3lcYWf7fFRTou:-1536636971) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/9ab3c3f72070d390910bf234b392cb4a8faaaf25/src/main/java/net/pms/dlna/DLNAMediaDatabase.java#L64)):*
I have to object to this, are you increasing the version just to clear the cached thumbnails? This recreate the whole database, including non-related tables. In my opinion it's much better to just ask any users having problems with this to press "clear cache".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/821#-:-K9ckzpu9P6RyFjJa1pA:1558190345)*

**Comment by SubJunk** [comment]
I've reverted the database version bump. This change seems pretty simple so I don't think we should hold back on it because of added complexity to refactoring, especially after it seems like it was important enough to block my web interface enhancements branch.

**Comment by Nadahar** [comment]
Ok, I agree.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/821#-:-K9fd2IDYoHmLgUX4XAu:1880218798)*

**Comment by Nadahar** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/821)*

**Comment by skeptical** [comment]
:+1:

**Pull request merged**
