### PR TITLE
Update Vizio-SmartTV.conf

### PR DESCRIPTION
**Pull request by nsomniac281**
Fixed streaming of media types to vizio tv, so far, from my testing, as long as FFMPEG is the default rendering device, it will transcode anything, also, menus load MUCH faster, though run times are not working, i have streamed video up to 4k with this. have a great day.

### CODE REVIEW

**Comment by Nadahar** [comment]
@nsomniac281 As far as I know, there is no profile ```MP4-H264-AC3```.

**Comment by Sami32** [comment]
@Nadahar I suspect him to have used my testing build from a forum's issues;)

**Comment by Sami32** [comment]
@nsomniac281 It was also done for Vizio, but as Vizio user are few, i didn't get a chance to get it tested.
So, i'll realy appreciate if you could post your full trace log to improve the Vizio's renderer configuration file, as i never get a SinkProtocolInfo for such renderer.

Thank you for you understanding ;)

**Comment by nsomniac281** [comment]
I will gladly provide you with whatever I can to make it work better for everyone,  I also do understand that there isn't specifically a profile like the one I made the change for, but, it does work amazingly, if you can provide a link or links to tuts or programs so that I can provide you with files I will happily. I didn't use any test files from anywhere, this was done on a whim.. tv said it only worked with mp4, so I changed it to mp4.. rofl..

**Comment by Sami32** [comment]
@nsomniac281 https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/CONTRIBUTING.md

Thanks.

**Comment by nsomniac281** [comment]
[ums_dbg.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/1476531/ums_dbg.zip)
there you go. also if you could get ac3 streaming to work that would be freaking sweet. i would love real surround. :) thanks a lot

**Comment by valib** [comment]
@nsomniac281 as I read your log the setting `TranscodeVideo = MP4-H264-AC3` doesn't work and video is transcoded to mpeg2 as a default setting which is correct when the setting ` MP4-H264-AC3` is not supported. So the only difference is when you set the supported video mime type to `m:video/mp4` which means that even the video is transcoded to mpeg2 format you offer the TV that it is the `mp4` format. It is confusing to me. Is the mp4 video format supported by the TV? In this case there should be added a line like `Supported = f:mp4   v:h264|mp4|mpeg2           a:aac-lc|he-aac|ac3|eac3|mp3|mpa                     m:video/mp4`

**Comment by valib** [comment]
@nsomniac281 as I read your log the setting `TranscodeVideo = MP4-H264-AC3` doesn't work and video is transcoded to mpeg2 as a default setting which is correct when the setting ` MP4-H264-AC3` is not supported. So the only difference is when you set the supported video mime type to `m:video/mp4` which means that even the video is transcoded to mpeg2 format you offer the TV that it is the `mp4` format. It is confusing to me. Is the mp4 video format supported by the TV? In this case there should be added a line like `Supported = f:mp4   v:h264|mp4|mpeg2           a:aac-lc|he-aac|ac3|eac3|mp3|mpa                     m:video/mp4`

**Comment by Sami32** [comment]
@nsomniac281 <https://github.com/nsomniac281>What do you mean by AC3 issue ?

2017-11-15 23:37 GMT+01:00 Libor Vala <notifications@github.com>:

**Comment by Sami32** [comment]
@nsomniac281 I was hoping get the UPnP string and SinkProtocolInfo from
your renderer but nope...Perhaps your Vizio model is only DMP ?

2017-11-15 23:14 GMT+01:00 nsomniac281 <notifications@github.com>:

**Comment by nsomniac281** [comment]
@Nadahar I removed that from there, changed the supported line with the one you have put up and it seems to work just fine, tried avi divx and xvid, some h.264 and h.265, will test more later, though for the first time i also got a hard crash @ a black screen while attempting to play a movie, had to unplug the tv..

**Comment by Sami32** [comment]
@nsomniac281 
>is there something else i can do to get the info from my tv?

I don't think so...
About your AC3 issue, did you tried when adding the `WrapEncodedAudioIntoPCM = true` option into your renderer's configuration file ?

**Comment by nsomniac281** [comment]
Should i comment out wrapdtsintopcm?

**Comment by Sami32** [comment]
@nsomniac281 If it already exist into your renderer's configuration file, uncomment the existing line, other way ad that line.

**Comment by nsomniac281** [comment]
Tried, even set transcoding to ac3 and still not even a blip, my pc says
its an invalid data format, like i said, it could easily be my crappy 1st
gen "smart" tv, because if i check the signal, lpcm outputs at 48,000 and
when i set the tv to ac3 my pc says its 47,999.. but the most important
part works, I can watch my collection, your work is very much appreciated.

**Pull request closed without merging**
