### PR TITLE
Copy web resources into the working dir while debugging

### PR DESCRIPTION
**Pull request by taconaut**
This pull request modifies the maven config to copy the web resources from external resources into the working dir during the process resource phase for all environments (win, osx, linux).
With this, the website will be available while debubugging from the IDE without having to manually copy files.

### CODE REVIEW

**Comment by valib** [comment]
@taconaut nice one. It helps a lot.

**Comment by skeptical** [comment]
@taconaut +1:.

PS not a big deal, but some of us are dinosaurs without IDEs and don't actually need this, so might be good to make it optional, e.g. ```<target if="copyresources">```, enabled by ```-Dcopyresources```.

**Comment by SubJunk** [comment]
Yeah would be cool to see it made optional :)

**Comment by taconaut** [comment]
To be coherent, the MediaInfo DLLs as well as the win32 folder (I've added with #575) should also be copied conditionally into the working dir, right?

**Pull request closed without merging**
