### PR TITLE
Audio Selection: More Options and all Album sorts by Track *rebased*

### PR DESCRIPTION
**Pull request by Nadahar**
I did a rebase of #617 where I removed the google translations as they caused all kind og merge problems because of the recent language cleanup (#601 & #615). In addition I don't believe google translatation is a good idea, as it often is completely off.

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/622)

### CODE REVIEW

**Comment by Executioner0** [comment]
Thanks @Nadahar, does that mean this is now merged? Is there some way I can (or do I have to) delete my previous Pull Request?

**Comment by Nadahar** [comment]
@Executioner0 No, it's not merged until this (#622) is marked as merged. You can close your request anytime you want on the bottom to the left of the "Comment" button, but I'd let it stay open until a merge is done.

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers @SubJunk 
This PR haven't gotten much attention, the things in here might be worth a look. The change in ```MEncoderVideo``` is particularly interesting as I've read about synchronization issues in the forum that could be caused by this. Any idea why it's there in the first place?

Also, the sorting of the categories in the media library isn't something that usually gets much attention, and it looks to me to be for the better. The fact that it's still mergable after this time, speaks to how seldom this code is touched.

I'm going to fast forward the branch so it can be tested with the current incarnation of UMS.

**Comment by SubJunk** [comment]
@Nadahar I think I get notified when you tag the developers group so no need to tag me separately :)

I don't get sync issues with MEncoder anymore, but then we should hardly be using it anymore. We used to have to use special sauce parameters to get it to work perfectly but over time it became more stable. DVD playback is and has always been occasionally troublesome but mostly works.

The PR looks okay, nice and simple. If it's tested it can be merged

**Comment by Nadahar** [comment]
@SubJunk I haven't tested it, but I can look at it. It's not long since I read on the support forum about missinc sync and DVD ISO.

About the tagging, I'm not so sure. I started doing that because you didn't seem to notice when I only tagged the dev group, and when I look at its members you're not in it. Can't you just add yourself to the group, and I can really stop?

**Comment by SubJunk** [comment]
I get notified about every post on this org regardless of who gets tagged

**Pull request closed without merging**
