### PR TITLE
Update Sony-Bravia5500.conf

### PR DESCRIPTION
**Pull request by Sami32**
Correct an incorrect parameter since UMS 4.0.0 version.

### CODE REVIEW

**Comment by Sami32** [comment]
@Nadahar Should i revert it ?

**Comment by Nadahar** [comment]
@Sami32 I have no idea, I'm completely confused as to what has been done here and why. What do these settings do first of all? The most important thing imo is to don't merge/revert etc before you think it's the "final" solution. There's no rush, take the time to figure it out and maybe test it if needed, so that whatever you end up doing is the best solution..

**Comment by Sami32** [comment]
@as you saw it wasn't used since 4.0.0 and when restablished it given the issue the was referred by the phantom commit.
It's why i ask you that, but it's OK for me, i leave Git things to you.

**Comment by Nadahar** [comment]
@Sami32 I still don't understand the phantom commit, so I'm as lost as you. I don't know if I appreciate you using @as as my nickname though.... or did you mean @ass?

**Comment by Sami32** [comment]
@nadahar Sorry :flushed: i didn't saw it !
Sometimes my browser become so slow that it doesn't display the name or smiley automatically...
Be assured that i will never write it here, again less that i'm thinking it !

**Pull request merged**
