### PR TITLE
Update SubtitleType.java

### PR DESCRIPTION
**Pull request by Sami32**
Better description proposal. Feel free to adapt or complement.
http://www.perlfu.co.uk/projects/asa/ass-specs.doc
https://en.wikipedia.org/wiki/MPEG-4_Part_17 ("TX3G" for "3GPP Timed Text")

"Teletext" or "DVB_subtitle" could be added ;-)
https://github.com/tvheadend/tvheadend/blob/42c9423d8aaf6834ea122c57039d39286eecaae8/src/parsers/parsers.c#L1691
https://tvheadend.org/projects/tvheadend/wiki/Tvheadend_post_recording_scripts

**EDIT**: PGS/SUP
https://trac.mpc-hc.org/ticket/1411
https://github.com/mpc-hc/mpc-hc/commit/2443b3b49227b328152ab6dcf6a4328cf4443a6c
https://ffmpeg.org/pipermail/ffmpeg-devel/2014-September/162504.html

Some other SUP conversion code:
https://github.com/mjuhasz/BDSup2Sub

Softwares d'extraction:
TSdoctor
VideoRedo

Pieces of code:
https://github.com/mpc-hc/mpc-hc/blob/develop/src/Subtitles/DVBSub.cpp
https://github.com/mpc-hc/mpc-hc/blob/develop/src/Subtitles/DVBSub.h
https://github.com/mpc-hc/mpc-hc/blob/master/src/Subtitles/RLECodedSubtitle.cpp
https://fossies.org/dox/mpc-hc-1.7.10/DVBSub_8cpp.html

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 Does FFMpeg have proper DVB subtitle support? Teletext isn't the same thing though, that is yet another standard that I'm betting isn't very well supported. DVB subtitles is image based while Teletext is text based. I know because I started to write a DVB subtitle converter once (was going to covert it into som other image based format), but the task ended up being pretty huge and I never finished it. I did manage to write code that extracts them from MPEGTS streams though, demuxing MPEGTS is a task in itself given the complexity of the format. I ended up thinking that continuing where ProjectX stopped would be easier since they already have some support for it.

I haven't looked at this for years though, but I have a lot of GB's of TV recordings with DVB subtitles that I would like to convert into something less space consuming and better supported format (VLC on a computer plays them, and my Dreambox does, but that's about it).

If FFmpeg can convert these into something reasonable, I can free up half a TB or something like that.

**Comment by Sami32** [comment]
@Nadahar Your are right, i just saw that in Travis log.
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1049

**Comment by Sami32** [comment]
@Nadahar In fact it's look the FFmpeg could do it but you'll need to compile a version `--enable-libtesseract`.

You can easily extract them with standard FFmpeg build though:
`ffmpeg -i file.ts -map 0:$number -scodec copy dvbsub.ts`  (other variations, like `ffmpeg -i file.ts -map 0:s:$number -c copy dvbsub.ts`, are also possible)

ProjectX being limited to SD, you can use a faster and a live open source tool [SubtitleEdit](https://github.com/SubtitleEdit/subtitleedit), using [Tesseract](https://github.com/tesseract-ocr/tesseract) as well: (usable on Windows or Linux, in command line or GUI mode)
(Google translate will be your friend, but i can try to help if something stay unclear)
http://linuxfr.org/users/mac_is_mac/journaux/extraire-les-sous-titres-des-enregistrements-de-la-tnt-hd
It's work great.

As a side note, the DVBSUB take 4 to 5 less space than audio.
Hoping that could help you.

**Comment by Nadahar** [comment]
@Sami32 I'm aware of ProjectX's limitation to SD, my original plan was to try to fix that as from what I can see the DVB subtitles are exactly the same for HD and SD. That said, this has been my plan for a loong time and nothing has happened yet, so I don't know if I'm up to doing that just to get those subtitles converted. Building a custom FFmpeg is probably a better option if it can convert them into something sensible, but I'm *not* interested in using OCR - that I already have found solutions for. I wan't to convert them into another image/bitmap format that has better support, not convert them into text. I'm not too fond of the rendering of text based subtitles, the original font, transparancy, colors and position is usually much better than any text rendering I've used. In addition they are stable across devices, while text rendering varies a lot.

Regarding saving space, I wasn't referring to saving space on the subtitles themselves - that space is negligible imo. I was thinking of reencoding the video into something more optimized and dropping audio tracks where there are several as I only care for the best quality original audio. But, I don't want to do that before I have something sinsible to do with the subtitles, because otherwise I can't delete the original anyway.

**Comment by Sami32** [comment]
@Nadahar Reading you trying to extract the subtitles made me think that you tried to convert them....
So if you don't bother just use FFmpeg:
FFmpeg -i file.ts -map 0:0 -map 0:1 -map 0:3 -c:v yourcodec -c:a yourcodec -c:s copy -f matroska output.mkv

**Comment by Nadahar** [comment]
@Sami32 The whole point is that I need to convert the subtitles to something else than DVB since that isn't very well supported, but I don't want to convert them into text - I want to convert them into a different image based format with better support.

**Comment by Sami32** [comment]
@Nadahar You was not clear on what you want.
Do you want convert your DVBSUB subtitles to VOBSUB ?

**Comment by Nadahar** [comment]
@Sami32 I have tried to explain it several times, but yes: I want to convert the subtitles into a generally supported image based subtitle format. I don't know which ones there are to choose from, VobSub is image based as far as I understand and so is SUP I think..? It's also important that the format supports alpha channel as partial transparancy is vital for good subtitles. What I seem to remember from when I looked into this, whatever format is used for bluray can handle alpha channel while the DVD format can't. I might remember this wrong though, there's been 3-4 years since I looked at it last.

**Comment by Sami32** [comment]
@before all better to know what you really want.
Image subtitles formats are the more widely supported but as you told you wanted an image format supporting transparency, VOBSUB is the more adequat to your wish.
https://wiki.multimedia.cx/index.php?title=VOBsub
https://github.com/mjuhasz/BDSup2Sub/wiki/Color-Palettes

FFmpeg is secondary, your purpose it to convert them, not the tool used for.
That's said when the target is clearly defined, FFmpeg can do "miracles" ;-)

**Comment by Nadahar** [comment]
@Sami32 It doesn't have to be FFmpeg of course, I was just mentioning that it doesn't seem like FFmpeg is of much help when it comes to encoding image based subtitle formats.

**Comment by Sami32** [comment]
@Nadahar If the transparency of VOBSUB not satisfy you, you can encode your videos with FFmpeg for divx subtitles in AVI files.
If you want a other specific subtitle codec or a specific container, just be clear on that.

**Comment by Nadahar** [comment]
@Sami32 I don't understand what you're saying, I haven't said that the VobSub transparancy isn't good enough - it probably is - but I've found no way to convert DVB subtitles into VobSub. What isn't good enough is the DVD 16 bits format.

**Comment by Sami32** [comment]
@Nadahar Try that:
`FFmpeg -i input.ts` ... `-scodec dvdsub -f matroska outpout.mkv`

**Comment by Nadahar** [comment]
@Sami32 Won't that just produce a ```MKV``` with a DVB subtitle stream inside..? FFmpeg can't, as far as I can see, encode VobSub.

**Comment by Sami32** [comment]
@Nadahar It'll produce a MKV file with VOBSUB subtitle from you TS file having DVB subtitle.
Yes, FFmpeg can do it.

**Comment by Nadahar** [comment]
@Sami32 It did something, according to MediaInfo the subtrack is now VobSub - but whatever was done to the subtitles it wasn't correct. The subtitles seem to have the timing correct, but that's about it. When played with VLC, the subtitles are very small and is placed a little below centered vertically and way to the left horizontally. Played with MPC the subtitles are too far down to read, you can just see the top of the first line in the bottom of the screen. In both cases they are heavily "pixelated" in the edges where the original is smooth, so something went wrong with the alpha as well it seems.

I don't understand what happened here, how can FFmpeg generate VobSub without a class for writing encoding them? It seems to me like the content is just transferred and that the track, when being embedded in a MKV, is interpreted as VobSub even though the format is really DVB subtitles.

**Comment by Sami32** [comment]
@Nadahar In fact the image subtitles are very near, so easy to convert.
[VOBSUB](https://github.com/FFmpeg/FFmpeg/blob/415f907ce8dcca87c9e7cfdc954b92df399d3d80/libavcodec/dvdsubenc.c) are a transparency limited to 4bit when the others have 16 bit, as your alredy read in the doc i linked to.

Many parameters need to be adjusted, as you will saw in FFmpeg documentation:
`-palette`...
`-even_rows_fix`
https://github.com/FFmpeg/FFmpeg/blob/872b35890395878ca927e226965117482429fceb/doc/encoders.texi#L2547-L2561
And many others that i cannot remember now for the size...too late i go sleep :-)

**Comment by Nadahar** [comment]
@Sami32 I didn't see that the parameter was ```dvdsub``` not ```dvbsub```. That explains why the palette was screwed up, as ```dvdsub``` simply can't display proper subtitles.

I don't know if ```VobSub``` has the same limitations as DVD subtitles, but if they do I guess ```PGS``` is my only hope.

**Comment by Sami32** [comment]
@Nadahar If if you don't want read or try FFmpeg options for [VOBSUB subtitle](http://ffmpeg-users.933282.n4.nabble.com/How-to-associate-a-palette-to-DVD-subtitle-td4661342.html), like `FFmpeg -analyzeduration 1000M -probesize 1000M -palette "101010,7d7d7d,eaeaea,eaeaea,101010,eaeaea,101010,101010,c4c4c4,0d4270,b0a06d,d8650c,333333,4c4c4c,655a35,944c0c" -i input.ts ... -scodec dvdsub -s:s:0 720x576 -metadata:s:s:0 language=nor output.mkv` for example, try this: (and adjust at your needs with FFmpeg options)
`FFmpeg -i input.ts` ... `-scodec pgssub -f matroska output.mkv`

**Comment by Nadahar** [comment]
@Sami32 I don't understand - I can't create the palette up front, I need it to use the palette from the DVB subtitles - and it's a 256 color palette, not a 16 like in the example above. I think the palette can change from image to image as well.

I've already tried ```-scodec pgssub``` and as I've said before, FFmpeg has no PGS encoder. It simply replies:
```
Unknown encoder 'pgssub'
```

**Comment by Sami32** [comment]
@Nadahar So, if you don't like the VOBSUB color limitation, 16 instead of 256, you are stuck to `xsub` subtitle codec or keep it as it is.

I didn't tried "pgssub" so i'm not surprise at all as i never saw it in the code but only on a forum.

**Comment by Nadahar** [comment]
@Sami32 I've said from the start that the 16 color/4 color transparancy palette isn't usable. It makes the subtitles very hard on the eyes and would mean that converting to SubRip would be a better option (would render nicer). The lack of a solution for this is probably why "everybody" seems to OCR them to SubRip. Converting them to PGS would be a much better solution though as the rendering of the "original" subtitles is soo much easier to read and less disturbing than a SubRip rendering.

If you've never had properly rendered subtitles, I understand why you prefer dubbing/think they are disturbing 😉

**Comment by Sami32** [comment]
@Nadahar Mainly because without transcoding, the original SRT subtitles appear to little for me.
I guess that if i have a huge screen, 65 to 80", or if i had a Samsung TV (i read that they can change the size of the subtitles) it'll be fine, but for now i find that dubbing is much more usable :wink:

**Comment by Nadahar** [comment]
@Sami32 That's the whole point with preserving the original image subtitles. The outcome obviously depends on what the original subtitle author did, but those used on TV here is generally well made. They have a size that's appropriate for the media format and make good use of the available space (while SRT renderings generally only use a part of the width), they tend to have fonts that's easily readable while not being invasive, and the use of colors, transparancy and position is done in such a way that the subtitles interfere as little as possible with the media content.

It might sound like I'm being "picky", but to me it's the difference between preferring subtitles or finding them annoying. When done well, I love subtitles and prefer to have them even if I understand the audio language perfectly well. It's nice to be able to adjust the audio volume to a pleasant level instead of having to turn it up so that you can hear the voices over all kind of background noice. This is especially important on surround sound content as the producers often seems to be so proud of their "surround effects" and "dynamic effects" that I often find the volume for which voices can be heard without missing bits and pieces is very unpleasant when some "action sequence" comes along. Shame on them by the way.

**Comment by Sami32** [comment]
@Nadahar Since, like me, you don't use the web interface, i don't really get your choice as near all TV are able to render DVB subtitles now, so keeping them is not a big deal...
MPC-HC, VLC, MPC-BE and maybe many other players are able to handle them.
[SSA](http://moodub.free.fr/video/ass-specs.doc) can be a good choice with transparency and [font choice](http://docs.aegisub.org/manual/ASS_Tags) for some users as well.
Whatever, too many choices, so each user can find which one feed its own needs, but it look like binaries/images subtitles conversion for TV need many [tweaks](http://forum.videohelp.com/threads/373331-Make-a-transparent-background) to render them "properly".

That's said, i didn't use it too much and doesn't like when it's hardly readable because of color contrast issue, so i check it on PC in the black border under the movie.
Just the fact that some Samsung TV models are able to choose the color or size of the subtitles make me appreciate them ;-)

**Comment by Nadahar** [comment]
@Sami32 I'm not sure what you mean with "near all TVs are able to render DVB subtitles now". Is DVB subtitles even supported by DLNA? In any case, my experience is that support for DVB subtitles isn't that good, and that's why I want them converted into something more generally supported. It seems like PGS is the only viable option, so if I even decide to figure this out I guess I will have to write a conversion from DVB to PGS myself.

**Comment by Sami32** [comment]
https://ffmpeg.org/pipermail/ffmpeg-devel/2014-September/162504.html

**Comment by Sami32** [comment]
@Nadahar It's look that this open source software is the only one able to convert your movies without loosing your subtitles look : [TVheadend](https://tvheadend.org/)

**Comment by Sami32** [comment]
> News Highlights:
> 
>     DLNA has achieved its mission, changing how consumers live, work and play using products that work together seamlessly in the connected home.
>     Organization will dissolve, and ongoing DLNA Certification activities will be managed by a newly formed professional services firm.
> 
> PORTLAND, Ore., Jan. 5, 2017 – The Digital Living Network Alliance (DLNA®) today announced that the organization has fulfilled its mission and will dissolve as a non-profit trade association. Product certification services for the multimillion-unit DLNA ecosystem will continue to be provided through a newly formed professional services firm with all required DLNA test tools, infrastructure equipment and end-to-end certification expertise.

> **DLNA’s world class certification program will now be provided by SpireSpark International**, which has been founded by former DLNA executives and will be located in Portland, Oregon. Staffed by the team experienced in all aspects of DLNA Certification, the firm will provide a seamless transition for companies that are currently certifying products or wish to do so in the future. DLNA Certification is now open to all companies, with no DLNA membership required. Access to the comprehensive DLNA test suite including the Conformance Test Tool (CTT), Media Capabilities Verification Tool (MCVT), Awox Golden Reference Devices and many other tools for testing media sharing, including DRM and HTML5, will be available under a new fee structure.

**Comment by Nadahar** [comment]
@Sami32 Tragic about DLNA - hopefully someone more sain will pick up where they left it. They just want to make loads of cash from this by "certification". Buhu.

@Sami32 TVHeadend: It'a s "streaming server" - can it also be used for conversion? I don't need more that one program to do it ;)

**Comment by Sami32** [comment]
@Nadahar Yes, i don't think anything good will come from it...let's see the next specifications and their price at the end of this year...

TVheadend can record, in MKV by default but it can do in others formats as well with script, including DVB subtitles. At my knowledge it's the only tool able to do it for now, as Matroska themself discuss it since 2011 but never make it happen. I added a link to the code at the beginning of this post.
I never tried it myself though, as i discovered this today.
But having access to their source code is already nice, isn't it ?

**Comment by Sami32** [comment]
@Nadahar Actually, i have the specifications but..., do you think i should send to Matroska or FFmpeg ?
Since it's sensible copyleft i'm not sure about what can or should be done...

**Comment by Nadahar** [comment]
@Sami32 What specification? For DVB subtitles? I have that as well, it's freely available ([ETSI EN 300 743] (http://www.etsi.org/deliver/etsi_en/300700_300799/300743/01.03.01_60/en_300743v010301p.pdf)). The problem is that nobody seem to have implemented it in a way to can generate output. VLC decodes these nicely.

**Comment by Sami32** [comment]
@Nadahar Well, something like that, from 2013. They call it "_DVB BlueBook_".

**Comment by Sami32** [comment]
@sami32 As of today FFmpeg support `S_HDMV/TEXTST`
https://github.com/Matroska-Org/matroska-specification/blob/dfaf1eb14cd2cdb628967a09c8bbdd630f5b6118/subtitles.md
https://github.com/Matroska-Org/matroska-specification/blob/a2de2b67338fc6f5f64d58e0a65df88850eaca76/codec_specs.md

**Comment by Nadahar** [comment]
@Sami32 Did you mean to address yourself? Also, I guess you meant Matroska - not FFmpeg?

Anyway, it's great that it's supported by Matroska now, but player rendering support is still not the best. I guess you might have had something to do with this?

**Comment by Sami32** [comment]
@Nadahar Yes, an idea for later work...

I really mean [FFmpeg support](https://git.ffmpeg.org/gitweb/ffmpeg.git/blobdiff/e87a4a85c11e348be8682acf39573fd2c5e22193..dface53497c3531da101b2872df301acca313142:/libavformat/matroska.c):
Matroska support it since some time already, and i surpriseling discovered Matroska docs about the S_DVBSUB as well.

**Comment by Nadahar** [comment]
@Sami32 Ok, that's great. It will probably be in the next release then?

**Comment by Sami32** [comment]
@Nadahar  You are kidding me, right ?

I'm a inexperimented turtle, so nothing sure about timing :wink:

**Comment by Nadahar** [comment]
@Sami32 I was referring to the next version of FFmpeg.. not UMS.

**Comment by Sami32** [comment]
@nadahar I've good new for you, _**mkvmerge**_ is now able to produce MKV with DVBSUB after the release 9.7.1 :wink: 

Things are moving ;)

**Comment by Nadahar** [comment]
@Sami32 Nice work 👍 🥇

**Comment by Sami32** [comment]
FFmpeg DVBSUB issue:
https://trac.ffmpeg.org/ticket/6165

**Comment by Sami32** [comment]
That's the beggining of a great subtitles support enhancement in the coming year :-)
https://git.ffmpeg.org/gitweb/ffmpeg.git/blobdiff/ea49308402d9df27a9c4b7555912100096b140d3..ce7098b8f2b59c62b5abdb3d74819db75cf67698:/libavcodec/dvdsubdec.c

**Comment by SubJunk** [comment]
Will this ever be worked on more?

**Comment by Nadahar** [comment]
@Sami32 I've updated the branch. I don't know if this actually is finished, did you intent to add more stuff or was is simply forgotten?

**Comment by Sami32** [comment]
@Nadahar Never mind, i've an up to date version in my fork.
I waited after FFmpeg fixes, that has been done for most of them.
But as we still use an old version, that doesn't really matter and nothing urge anyway, IMO

**Comment by SubJunk** [comment]
It's a real shame how FFmpeg has been in that broken state for so long with fontconfig. I doubt it will be fixed

**Comment by Sami32** [comment]
@SubJunk Well, i'm really not sure that FFmpeg have anything to do with this issue. As i didn't reproduced this issue. It seem affect only some users, and the logs are missing, except perhaps one, AFAIK.
Their fontconfig cache seem the root of their subtitles issue.
I didn't investigate on it, since much more skilled people stay around.

**Comment by Nadahar** [comment]
@SubJunk Are you referring to a specific known issue with FFmpeg?

**Comment by SubJunk** [comment]
Yeah I suspect it is more related to FontConfig or possibly the FFmpeg implementation of it, or either of them. It seems that sometime last year the Zeranoe build started causing people issues with subtitles. I haven't reproduced it but I can look into it more, since I've dealt with this kind of thing before.

The problem can be that an old fontconfig cache is present on the computer and the new version of fontconfig can't read it, in which case our "clean install" should fix it, but sometimes it's the opposite issue, that a clean install removed the working cache and the newer version can't create it properly.
There are lots of support threads about it on the Zeranoe forums, a quick search turned up https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=7&t=4821 and the last post on this one https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=7&t=2554

Either way we have tried 3 times now to update to newer versions of FFmpeg and we keep having to roll back to fix issues. Frustrating.

**Comment by mirh** [comment]
Is it so hard to bisect using zeranoe archive?
Or [media-autobuild_suite](https://github.com/jb-alvarado/media-autobuild_suite) if very surgical precision was needed.

**Review by SubJunk — APPROVED** [review]

**Pull request merged**
