### PR TITLE
Add FFmpeg GPU decoding

### PR DESCRIPTION
**Pull request by onon765trb**
Issues #1530 and the discussion of #1175
UMS can support for FFmpeg GPU decoding by This PR.
This significantly decreases the burden of PC.

### CODE REVIEW

**Comment by SubJunk** [comment]
@onon765trb Also I tested it and it didn't work for me by default (I didn't set anything), I expected it to add `-hwaccel auto` to the params but it didn't. I hope I didn't break it! Can you have a look?

**Comment by mirh** [comment]
What is decoding needed in ums?

**Comment by onon765trb** [comment]
@SubJunk Your change is interesting. Do you check GPU acceleration? Your code work in my test.

I have a few on my mind by looking your code. How do you think the change from all variables name GPU Acccelation to GPU Decoding Accelation for the future.

This is because GPU acceleration has decoding and encoding. If using your code taking lists and `ffmpeg  -hide_banner -encoders | grep h264`, can set GPU acceleration encoding easily. Of course, the tuning of encoding set is need and it may take a long time.

At least, I can make the change from GPU Acccelation to GPU Decoding Accelation on my code, easily.

**Comment by Nadahar** [comment]
> What is decoding needed in UMS?

When you *transcode*; that is, convert from one format to another, the existing format must be *decoded* and the new format must be *encoded*.

In most cases, encoding is significantly more resource intensive than decoding. This is by design, as the goal when codecs are designed is usually to make the decoding cost as low as possible, at the expense of the encoding cost. Thus, hardware accelerated encoding is where you're likely to see the biggest "gains", but hardware accelerated decoding also helps by freeing the CPU capacity that would otherwise have been used on decoding.

**Comment by SubJunk** [comment]
@onon765trb that sounds like a good change

**Comment by onon765trb** [comment]
I changed the names. But I did not touch variables reflects on other than ffmpeg.

**Pull request merged**
