### PR TITLE
main fix tmdb api version

### PR DESCRIPTION
**Pull request by SurfaceS**
@SubJunk [tmdb-api repo](https://github.com/UniversalMediaServer/tmdb-api/tree/main) need to be published for this PR to pass.

- update TMDb schemas to 24/09/2024.
- fix uri bug.
- updated deps.

### CODE REVIEW

**Comment by SubJunk** [comment]
Ok, I will do it soon

**Comment by SubJunk** [comment]
I released it but it's not showing up yet at https://repo.maven.apache.org/maven2/com/universalmediaserver/tmdbapi/, I think it takes a while because of caching

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
@SurfaceS is this ready to merge?

**Comment by SurfaceS** [comment]
Sure

**Pull request merged**
