### PR TITLE
Dms minor fixes 2

### PR DESCRIPTION
**Pull request by SubJunk**

### CODE REVIEW

**Comment by SubJunk** [comment]
There are a bunch of instances of PMS and UMS changing to DMS in here but I don't really care about code branding, do you agree @valib ?

**Comment by valib** [comment]
@SubJunk I have no problem with using code from the DMS without changing descriptions.

**Comment by SubJunk** [comment]
@valib cool thanks, that will make it easier for me. Do you think this needs more testing or can it be merged? Seems minor enough to me

**Comment by SubJunk** [comment]
Also any opinion on removing the plugins code?

**Comment by valib** [comment]
@SubJunk this can be merged. About plugins I don't know. I used only Jumpy but with new Kodi it stopped working. Are there any plugins still working?

**Comment by SubJunk** [comment]
From memory, it was only the MovieInfo plugin that was working, and we have had a few reports on the forum of it not working anymore, so I think it is probably time to retire that part of the code since it will just cause users to waste time and have a bad experience

**Pull request merged**
