### PR TITLE
Update mime types for Panasonic-VieraAS650.conf

### PR DESCRIPTION
**Pull request by Nadahar**
@UniversalMediaServer/developers 
I have no way to verify if this is correct, but according to [this post] (http://www.universalmediaserver.com/forum/viewtopic.php?p=22809#p22809) it is. Do we apply this or not?

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/815)

### CODE REVIEW

**Comment by Nadahar** [comment]
This user isn't great at clarity, but from what I understand now this only apply to jumpy content. That sounds to me like jumpy need to specify different/better format information instead of us doing some hack to the renderer configuration.

@skeptical Do you have any information to add to this, or should we just close this PR?

**Comment by skeptical** [comment]
@Nadahar no idea, this part of it is more of a question for @SubJunk /@valib, who both own Panasonics afaik.

**Comment by Nadahar** [comment]
@skeptical I was referring to that the user claims that the change was needed to get jumpy streams to work - not media files. If that is accurate, I'd say it's likely that jumpy sends wrong media information.

**Comment by skeptical** [comment]
@Nadahar as you also say "This user isn't great at clarity" :-).

**Comment by Nadahar** [comment]
Ok, I'm closing this. If someone think there's anything of interest here feel free to reopen.

**Pull request closed without merging**
