### PR TITLE
Bugfix: LanguageSelection trying to open in headless mode.

### PR DESCRIPTION
**Pull request by Nadahar**
I forgot to do the headless check before spawning the language selection window :blush: 

If a graphical environment is available it will show even if UMS is run headless. If that's not available, UMS will crash during initialization. This PR fixes this.

Source: http://www.universalmediaserver.com/forum/viewtopic.php?p=28558#p28558

---
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/1057)

### CODE REVIEW

**Comment by Nadahar** [comment]
@SubJunk Why is this Reviewable? I thought you turned it off?

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers This is a simple bug fix and should be easy to approve.

**Comment by valib** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/1057)*

**Comment by Nadahar** [comment]
@valib I know it's a bit confusing, and it's the reason I asked @SubJunk to remove Reviewable, but that's not the approval that's needed.

To approve a PR go to the diff (the "Files changed" tab). In the upper right corner you can find a green button "Review changes" - click that, write a text and select "Approve".

**Comment by Nadahar** [comment]
@valib Thanks :+1:

**Comment by SubJunk** [comment]
I have tried to remove Reviewable but apparently that didn't work

**Comment by Nadahar** [comment]
@SubJunk I think you have to remove it two places: One for the test integration (which seems to be gone) and one for the "integration" itself.

**Comment by SubJunk** [comment]
@Nadahar there aren't any integrations or webhooks listed for this repository or this organization, and the slider is disabled within Reviewable. Maybe I should remove my Reviewable account altogether

**Comment by SubJunk** [comment]
Ah I think I found it, there's another page with application settings

**Comment by Nadahar** [comment]
@SubJunk Seems like that did the trick, can't say for sure until a new PR is created, but it looks promising. Those that have already been reviewed in reviewable will stay linked I guess - that would be the best solution to not loose anything.

**Pull request merged**
