### PR TITLE
GlobalIdRepo: use weak references

### PR DESCRIPTION
**Pull request by skeptical**
Not an actual PR, for reference in #1680.

### CODE REVIEW

**Comment by valib** [comment]
@skeptical there is a bug see the log
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/2622003/debug.log)

**Comment by skeptical** [comment]
How are you @valib?  As mentioned in the other thread this is untested and for information purposes only and comes without any guarantees :). I googled the error and have added an untested fix for your sake, but it isn't my intention to support this extensively.  The bug has to do with concurrency which is outside the main point being illustrated here, I just attempted to transcribe my old pre-concurrency commits to the current code.  @Nadahar is the experienced locksmith here and would probably have more useful suggestions as to getting that aspect of it right.

**Comment by SubJunk** [comment]
By the way for testing this it will be useful to temporarily revert https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1486 since running a scan is the fastest way to reproduce the bug.

Also another note is that generally audio files will produce it faster if they have cover art, in my experience.

**Comment by Nadahar** [comment]
> Also another note is that generally audio files will produce it faster if they have cover art, in my experience.

I don't think audio files makes the problem any bigger, they will simply use more memory and thus deplete the available memory faster. The reason for this is that I chose to store audio thumbnails in higher resolution than other thumbnails, since they are also used as "cover art" and are often shown as a background or a larger image while a music track is playing. Thus I think they are limited to 640 x 480 instead of 320 x 240 for other thumbnails. The thumbnails aren't really a part of the problem though, they only make the symptoms easier to see.

**Comment by skeptical** [comment]
@SubJunk :+1: glad one of us is actually thinking here :P.

**Comment by SubJunk** [comment]
@skeptical I don't get accused of that too often, it's a nice change! :)

**Comment by SubJunk** [comment]
Tonight I had what might be a side-effect of this PR - I had some folders stop working. The experience on the TV was that I was browsing folders and some of them didn't have our custom folder icon anymore, and nothing happened when I went into them, but the folders with the icon still worked so I guess the parent hadn't been removed but those specific children had. I am guessing that's a predictable side-effect of this approach.

I wonder if it would be better to not include the thumbnails in what we cache in the global ID repo, since then it could store many times more IDs without needing to discard potentially needed ones?

**Comment by skeptical** [comment]
@SubJunk maybe I'm too far out of it at this point :), but you'll need to translate because it's not computing for me:

> some of them didn't have our custom folder icon anymore

Is this something to do with renderers that support custom folder icons?

> I wonder if it would be better to not include the thumbnails in what we cache in the global ID repo, since then it could store many times more IDs without needing to discard potentially needed ones?

What do you mean by "caching thumbnails" and "discarding needed IDs" in the global id repo? Are you running this in conjunction with #1673?

**Comment by SubJunk** [comment]
My PC is back up and working, luckily the damage was limited to my power supply so replacing that fixed it. I will continue to test this branch. Unfortunately I am back to the first day again so will need to keep it running for a few more days to try to reproduce the bug I was seeing last time, and then I will look into it more if it happens again.

We also have word from the user who is helping with testing, he has been running it for 5 days when it would usually crash in 3 days, so it seems promising.

**Comment by SubJunk** [comment]
Well I have been running this for 7 days with no problems and no noticeable increase in memory usage, and the user who is helping me test has also had no problems for 6 days and then another chunk of 5 days, after being interrupted by a power outage.
Is anyone else testing this currently? Should I put together a public beta release for it?

**Comment by SubJunk** [comment]
@valib do you think we should just merge this instead of doing a beta release?

I have been running it continuously all this time and still haven't noticed any problems, not sure why I got issues the first time I ran it but I haven't reproduced it so that might have been something else.

**Comment by SubJunk** [comment]
OK well we have a few big branches in progress (this one, subtitles, and 8.0.0) so I'm gonna make a frankenstein branch of those 3 and release it as `8.0.0 alpha 1` in the next 24 hours. If anyone has objections let me know :)

**Comment by SubJunk** [comment]
8.0.0-a1 is released with this in it, let's see what people say

**Comment by SubJunk** [comment]
Closing this since it is in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1615

**Pull request closed without merging**
