### PR TITLE
Thumbnail image is DLNA compliant.

### PR DESCRIPTION
**Pull request by atamariya**
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/989)

### CODE REVIEW

**Comment by Sami32** [comment]
@SubJunk https://github.com/UniversalMediaServer/UniversalMediaServer/issues/981#issuecomment-246376857

**Comment by SubJunk** [comment]
Cool, I'm happy to merge this if the conflicts are resolved

**Comment by Sami32** [comment]
@atamariya :-)

**Comment by valib** [comment]
I also like this PR but it uses currently deprecated methods `getThumbSize()` and `getThumbBG()` so we should decide if we should revert those methods and deprecate (delete) the parameters `ThumbnailWidth` and `ThumbnailHeight` used in the renderers conf.

**Comment by atamariya** [comment]
@SubJunk conflict is resolved.

**Comment by SubJunk** [comment]
@valib good point, we should make a decision about that... The main relevance of ThumbnailWidth and ThumbnailHeight in the renderer was when we added black bars to the thumbnails. Now we just output them at their actual aspect ratio so that doesn't matter. Do you agree?

@atamariya thanks

**Comment by Nadahar** [comment]
I am completely confused by this PR. Why is there 32 commits in this where only 3 (and one merge) is done by @atamariya? There must be some git error that should be figured out and corrected here. The easiest might be to create a new branch and cherry-pick the relevant commits to the new one.

**Comment by SubJunk** [comment]
Yeah I'm not sure how some branches end up with those extra commits either. It shouldn't happen.

**Comment by Nadahar** [comment]
IMO it should be cleaned up before merge. I don't have write access to this branch so I can't do it without copying it to a new branch. Either @atamariya do it in his branch or I can do a copy and clean operation - just let me know. If I do this I'll have to create a new PR though.

**Comment by SubJunk** [comment]
Maybe if @atamariya pulls from master into this branch it will fix that weird diff. I agree it should be cleaned up since there are a lot of unrelated changes showing up here

**Comment by atamariya** [comment]
Created PR #1024

**Pull request closed without merging**
