### PR TITLE
Solving issue #1674

### PR DESCRIPTION
**Pull request by maciekberry**
Solving issue #1674 (correct language passed to MediaInfoLib and avoiding incorrect genre labels) as per discussion in the ticket

### CODE REVIEW

**Comment by maciekberry** [comment]
OK @SubJunk , I give up, I do not know how I can make this pull request that will only contain my change (src/main/java/net/pms/dlna/LibMediaInfoParser.java).

Every time I try to create a pull request, github automatically takes all the commits made to the branch (so mainly my synchronisation commits). I have read everything I could find on Github help but I do not know whether it is normal or not.

Perhaps (I am speculating here), those "synchronisation merges" will be ignored and only the change I want will be merged upstream?

Or - more probably - I am a github noob and somebody needs to help me (unless you do not want to see any more commits from me :) )

Can you help?

**Comment by Nadahar** [comment]
@maciekberry I don't think this is a GitHub issue, but a Git issue. The problem is that you weren't "in sync" with UMS master when you made your commit.

On the GitHub side, it's not too late to "revive" this PR. By fixing the branch `maciekberry:master` this PR will be updated accordingly. But, this will fail if the PR is closed, so make sure to open the PR before you make any changes to the branch.

A PR will contain all commits that is different between UMS' master branch and then PR branch. Thus, the commits you see is those that differ from UMS' master branch. When making a PR, you're supposed to make sure that only the changes you intend the be merged are in the PR branch.

First off, you should never use your "master" branch for PRs, even though that's what most of us does when we make our first PR :wink: Instead, you should make one branch per PR you create, so that you can make changes to them individually. Since you haven't done this, the remains of #1657 is causing some trouble.

What happened is that @SubJunk "squashed" some commits when he merged #1657. "Squashing" means to combine several commits into one. That means that the 4 commits [in #1657](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1657/commits) (451abc9caa737494a4e75286477f8530b59d4063, b7b7177b5567b065e23c6af0c691cde4c6c68822, 3420de1666c8f3a434b728a06fdcd589a942c512 and 0b909aad4cf18a7197e4d36eb8cb88cc735aabe3) were combined to a "new" commit ee550c6ef81336b5f538949939d76f0a88e3fafc. Although the code is identical, the "Git tree" is not. Since then a lot of other commits have been added to UMS master, and you have added some more "sync commits" before you made 5db7739a8aa21eef651f25bc0cec1dd7c5fe3756, which is what I suppose this PR was supposed to be.

There are multiple ways to solve this, the first thing I would do is to create a new branch in your repo called for example `backup`. It will be a copy of your `master` as it is now, which means that you can always "start again" if something you attempts fails.

There are basically two ways you can then "clean up" your `master branch` that I can think off. You could either `reset` your `master` to be equal to UMS's `master` and then `cherry-pick` the last commit from your `backup` branch. The other way is to `rebase` your `master` branch on UMS' `master` branch.

They would both produce the same result, but I think the rebasing is easiest to do, so I'll suggest that you use that. I don't know how you use Git, but I'll give you the command line commands which should be available to you regardless.

First, make sure you're checked out to your local `master` branch:
```powershell
git checkout master
```

Then fetch UMS' repo (to make sure you're using the latest version of it) and then do the rebase:
```powershell
git fetch upstream
git rebase upstream/master
```

That should be all to fix your local branch, but to push it to GitHub you need to use "force push" since you have to overwrite the commits that are already there:
```powershell
git push --force-with-lease origin master
```

Assuming that you reopened this PR before making the push, everything should be in perfect order when this is done. If some of the code changed by this PR has changed in UMS' `master` in the meantime, you might get a `conflict` (it means that Git can't figure out how to merge the code). If that's the case, it gets a bit more complicated as you have to manually merge the part of the code that Git can't figure out. I don't think that will happen in this case though.

**Comment by maciekberry** [comment]
Thanks @Nadahar ! Your answer not only makes perfect sense but is also very helpful :)

I went for the rebase. For some obscure reasons, I did got 2 conflicts (the same changes that Subjunk suggested to my original PR), but a bit of git mergetool seems to have fixed that. 

Let me know if all is ok now (I have three commits in this PR, but in fact it is the same one with a revert in the middle)

**Comment by valib** [comment]
@maciekberry @Nadahar it can be simply squashed and merged here in GitHub.

**Comment by maciekberry** [comment]
Yes please. For now, I have broken my repo by messing up the commits while rebasing as per Nadahar advice :(
So I would appreciate if you could squash it while merging on "your" side, please.

**Comment by Nadahar** [comment]
@valib I'm aware of that, but I was thinking that it was best to learn how to deal with such issues.

@maciekberry How have you broken your repo? I have done a lot of strange things with Git, but I haven't managed to "break" a repo yet. In which way is it "broken"?

**Comment by valib** [comment]
@Nadahar I understand your effort but even if  @maciekberry  commited a lot of partial commits we can still squash them into one commit here by one click.

**Comment by maciekberry** [comment]
OK, it is not broken of course. 
git rebase --abort fixed it all.

However, the valib solution seem to be a bit more pragmatic than forcing you to spend more time teaching me all the git arcanes.

I promise, next time I will learn this.

**Comment by Nadahar** [comment]
@valib I know that, this was about how to "clean up" when things have gone wrong. As always I take the "educational route" :wink:

**Comment by valib** [comment]
@Nadahar that is why I like you 👍

**Comment by SubJunk** [comment]
@maciekberry Git can be tricky to learn at first, great to see all the help being given in here :)

**Pull request merged**
