### PR TITLE
Remote control navigation support in webgui

### PR DESCRIPTION
**Pull request by acanive**
Remote control navigation support in webgui.
Fixed error in remotecontroller.js that prevented playing videos.
Fixed references to jQuery, restored to $ symbol.
Added some styling modifications.

### CODE REVIEW

**Comment by acanive** [comment]
this is ready for test, wait for a couple more days, I'm finishing some fixes to make it work better. I have changes I haven't commited yet.

**Comment by SubJunk** [comment]
Cool thanks!

**Comment by acanive** [comment]
Please give this a try.

**Comment by valib** [comment]
@acanive looks good

**Comment by SubJunk** [comment]
@acanive thanks for all your hard work!

**Comment by valib** [comment]
@acanive there is a bug when the UMS name is longer. See
ums
Also this is not good for playing audio
ums audio

**Pull request merged**
