### PR TITLE
More web content improvements

### PR DESCRIPTION
**Pull request by SubJunk**

### CODE REVIEW

**Comment by valib** [comment]
@SubJunk It doesn't show the TYPES_READABLE (translated) in the types column and when the row is edited and used the readable type than it destroys the WEB.conf.

**Comment by SubJunk** [comment]
I have a bunch of unpushed code for this branch btw, I just created this PR to track progress

**Comment by SubJunk** [comment]
Did you get a chance to look at the extract subtitles branch?

**Comment by valib** [comment]
@SubJunk the imagefeed doesn't work for my Samsung Q9 TV. See what it offers for the original image
` <res xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=01" size="0">http://10.0.0.10:5001/get/111/20210719_140311</res>`
the resolutions is  `DLNA.ORG_PN=JPEG_TN` and the size is `0`. Also the image name has missing the JPG extension. Than the renderer chooses one thumbnail to show instead of the original image. On the web interface it works correctly.

**Comment by Nadahar** [comment]
@valib That sounds like something I would expect if the image hasn't been parsed. That's the fundamental problem with using "web content", you often know little or nothing about the media file.

The reason it "works" on the web interface is probably because it does very few checks and just passes the image on to the browser.

**Comment by valib** [comment]
@SubJunk that is maybe the general problem because also videofeeds doesn't work on my Samsung TV.

**Comment by SubJunk** [comment]
Yes there are a lot of bugs to do with this stuff. I have also noticed that video.js doesn't seem to support our streaming mp3s for web radio on Chrome, but the default Chrome player does, so I am working on a fix to just use the browser player for that.

It would be good to keep track of the bugs in separate issues as we find them, and merge this branch soon, because this is already a good improvement to release for users

**Comment by SubJunk** [comment]
That is fixed now. I think this is a good chance to review and merge this, and continue to improve web content support in other branches

**Review by valib — DISMISSED** [review]

**Comment by SubJunk** [comment]
@valib which errors?

**Comment by valib** [comment]
`INFO  2021-07-20 10:59:49.932 [net.pms.PMS.main()] Error at line 45 of WEB.conf: 3
DEBUG 2021-07-20 10:59:49.935 [net.pms.PMS.main()] null
java.lang.ArrayIndexOutOfBoundsException: 3
	at net.pms.newgui.SharedContentTab.parseWebConf(SharedContentTab.java:990)
	at net.pms.newgui.SharedContentTab.build(SharedContentTab.java:216)
	at net.pms.newgui.LooksFrame.buildMain(LooksFrame.java:589)
	at net.pms.newgui.LooksFrame.buildContent(LooksFrame.java:559)
	at net.pms.newgui.LooksFrame.<init>(LooksFrame.java:398)
	at net.pms.PMS.init(PMS.java:537)
	at net.pms.PMS.createInstance(PMS.java:942)
	at net.pms.PMS.main(PMS.java:1108)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by valib** [comment]
@SubJunk I think the main problem is different syntax for feeds and streems in the WEB.conf

**Comment by SubJunk** [comment]
@valib thanks, I'll fix that

**Comment by SubJunk** [comment]
I think that's fixed now:

image

**Comment by valib** [comment]
@SubJunk why the played media image is so big?
Bez názvu

**Comment by SubJunk** [comment]
To maintain compatibility for existing users, since they have been different since the start. Not sure why your logo is big like that, after I set max-width in the last commit

**Comment by valib** [comment]
@SubJunk it was my bad than I didn't copy the web folder to the default Eclipse folder before testing. Testing in the Eclipse needs to have the web folder in the root.

**Review by valib — APPROVED** [review]

**Pull request merged**
