### PR TITLE
main MusicBrainz work

### PR DESCRIPTION
**Pull request by SurfaceS**
## What's Changed
Splitted MusicBrainz API and Cover Art Archive (not the same at all).
Cover Art Archive API is cleaned and now use the new dependency.

## Removed dependencies : ##
fm.last:coverartarchive-api dependency

## Added dependencies : ##
com.universalmediaserver:coverartarchive-api

## Todo : ##
@SubJunk
For this PR to run :

You will need to create 1 new repository from [coverartarchive-api](https://github.com/SurfaceS/coverartarchive-api)
You need then to publish it on maven (v1.0.0).

Also, as TMDb api [tmdb-api](https://github.com/UniversalMediaServer/tmdb-api) had rate limiter fixed and some few fixes, you can publish it as well (v1.0.0).

@ik666
When reviewing the MusicBrainz API part of the old `CoverArtArchiveUtil` class (now `MusicBrainzUtil` in this PR), I see that a lot of search value are ignored, or worst (fail the request).

**For release :**
https://musicbrainz.org/doc/MusicBrainz_API/Search#Release
`tid` for trackId -> ignored
`recording` for title -> ignored
only `date` is take into account by MusicBrainz.

`arid` is not their but can be : (the MBID of any of the release artists)
`artistname` is not their but can be : (part of the name of any of the release artists)

**MusicBrainzUtil :**
The `MusicBrainzUtil` class should use `com.universalmediaserver:musicbrainz-api`
example :
```
MusicBrainzAPIClient client = new MusicBrainzAPIClient("UMS/Version ( https://www.universalmediaserver.com )");
ReleaseSearchEndpoint search = client.release().search();
//can be added inline
search.with(title).withArtistName(artist);
//or not
search.withReleaseDate(date);
...
//set a limit or not
search.setLimit(10);

//get results
ReleaseSearchResultsSchema results = search.getResults();
if (results == null) {
//something wrong
} else if (results.getCount() == 0) {
//no result
} else {
//do something with results.getReleases()
}
```
Be aware that MusicBrainz expect no more than 1 request by second by IP.
https://musicbrainz.org/doc/MusicBrainz_API/Rate_Limiting

> For example: if your requests are coming in at 4 requests per second, we don't honour 25% of them and decline the other 75% - we decline 100% of them, until the rate drops to 1 per second or lower. 

`com.universalmediaserver:musicbrainz-api` has a rate limiter implemented that follow this, then you will never fall in a declined request for that.

### CODE REVIEW

**Comment by ik666** [comment]
@SurfaceS I can have a look at the MusicBrainzAPI, however, I didn't write it. That's why I'm unsure about the original UMS use case. I think there is no real "album" bracket in the database yet, and none in the UI. All metadata is read from the track file itself and stored in the `AUDIO_METADATA` table.

From a workflow perspective: If a user adds a `MusicBrainzID` to his music track(s) with let's say with "Piccard" or songkong, usually the other fields (like author, date, etc.) are also set correctly. So there is no real need to collect them over the MusicBrainz API again ...  @Nadahar : Have you started this implementation and can tell your intention?

I added the `my albums` = liked albums and `MUSIC_BRAINZ_RELEASE_LIKE` table, because navigating the CDS by `media library-> album` is somehow cumbersome. If you have to many albums, you lose the overview.

Maybe the `MusicBrainzReleases` table can be deleted. Looks like all columns already exists in `AUDIO_METADATA` (except the rating which can be miggtrated to MUSIC_BRAINZ_RELEASE_LIKE).

**Comment by SurfaceS** [comment]
@ik666 I opened an issue last week about this #4742.

@SubJunk this PR is ready to go.

**Comment by SubJunk** [comment]
@SurfaceS it has failing tests

**Comment by SurfaceS** [comment]
@SubJunk
For this PR to run :

You will need to create 1 new repository from [coverartarchive-api](https://github.com/SurfaceS/coverartarchive-api)
You need then to publish it on maven (v1.0.0).

Also, as TMDb api [tmdb-api](https://github.com/UniversalMediaServer/tmdb-api) had rate limiter fixed and some few fixes, you can publish it as well (v1.0.0) as this PR use this version.

**Comment by SubJunk** [comment]
@dependabot recreate

**Comment by Nadahar** [comment]
> Have you started this implementation and can tell your intention?
It's so long ago now that I don't remember clearly, but I think a lot of other things have changed in the meanwhile too. As far as I remember, finding the `MusicBrainzID` was just a means to find the correct cover art. Since there was no way to query Cover Art Archive, an attempt to use whatever metadata was available to identify the correct track/song/music piece using the MusicBrainz database. If that succeeded, the `MusicBrainzID` was used to retrieve the correct cover art.

**Comment by SubJunk** [comment]
Oh I forgot that this was waiting on me. @SurfaceS are you still interested in it if I publish the coverartarchive-api? I should just give you the ability to publish to maven

**Comment by SubJunk** [comment]
@dependabot recreate

**Comment by SurfaceS** [comment]
> Oh I forgot that this was waiting on me. @SurfaceS are you still interested in it if I publish the coverartarchive-api? I should just give you the ability to publish to maven

Sorry for delay, I had a lot to do on my work this days...

Yes, it should be published before it can be merge.

**Comment by SubJunk** [comment]
@SurfaceS no problem, I get busy with work too. Do you want me to send you the credentials to publish things on Maven? Then you don't need to wait for me to do that in the future

**Comment by SubJunk** [comment]
@SurfaceS the coverartarchive-api is published now

**Comment by SurfaceS** [comment]
This one is good to go

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
@SurfaceS is there anything to add to the changelog?

**Comment by SurfaceS** [comment]
@SubJunk 
No, everything in on the first post.

**Pull request merged**
