### PR TITLE
fix Italian translation

### PR DESCRIPTION
**Pull request by bartsimp**

### CODE REVIEW

**Comment by SubJunk** [comment]
@bartsimp thanks for the contribution. What effect does the tick marks part have?

**Comment by bartsimp** [comment]
for machines with lot of memory (I've 3625 MB (3,6Gb)), a tick every 100mb result in too many tick. My propose is to scale the tick based on real memory

**Comment by SubJunk** [comment]
Thanks for this :)

**Comment by skeptical** [comment]
@bartsimp thanks, it's a valid issue re tickmarks, but solution is way overkill computationally speaking, plus I don't think this is desireable, for example 1028 mb memory:
1028mb

**Comment by SubJunk** [comment]
@skeptical feel free to revert that part of it, or change it

**Comment by skeptical** [comment]
Already changed in f87f744 when I posted the comment above, should've mentioned it.

**Comment by SubJunk** [comment]
Nice one

**Comment by bartsimp** [comment]
happy to contribute :)
@skeptical good idea

**Pull request merged**
