### PR TITLE
JUPnP device and more

### PR DESCRIPTION
**Pull request by SurfaceS**
This PR replace #2805 and add JUPnP implementation.

* `JUPnP` replace Cling to remove Cling dependency, seamless-xml dependency, 4thline-repo repository.
Then Set up Maven is not needed on the workflow. 
fix https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2462.

* `JUPnP` added 'upnped' JDK `HttpURLConnection`.
* `JUPnP` added 'upnped' Apache `HTTPClient` implementation.
As hacked `HttpURLConnection` will bother us when upgrading JDK version, this should become the default StreamClient.

* `JUPnP` added device and services.
`UmsLocalDevice`, `UMSContentDirectoryService`, `ConnectionManagerService `and `UMSMediaReceiverRegistrarService`.
For now, `UMSContentDirectoryService` is just registered (not implemented) to be advised on the UDP part of UPnP.
That let JUPnP `UpnpService` the ability to handle the full UDP (HTTPMU/HTTPU) traffic.
Then `SocketSSDPServer` is not needed to run.

* `JUPnP` added handlers for Netty and JDK HttpServer.
As `UMSContentDirectoryService` is not yet implemented, the JUPnP HttpServer will use RequestV2 class to serve it.
That let JUPnP `UpnpService` the ability to handle the full UDP/TCP (HTTPMU/HTTPU/HTTP) traffic.
Then `HttpMediaServer` is not needed to run.

* `mDNS` handled now by `MediaServer`.
It was started by `PMS` and not restarted on reset (interface change for ex) or stopped.
Few log/clean on it.

* `UpnpService` handled now by `MediaServer`.
It was started by `UPNPHelper`, hold by `UPNPControl`.

* `HttpMediaServer` now advise `MediaServer` the port it use.
If you start the `MediaServer` with the magic port number 0 (from conf), the bind call will take an automatically allocated free port on the network interface.
Before it was buggy as the `MediaServer` will give an url with port = 0.
So the UPnP advise server port 0, etc. => doesn't work.
Now it should work.

* `MediaServer` provide now the `InetSocketAddress` for all Media Services.

* `MediaServer` now really reset ALL its network services.

* `MediaServer` and its services log a bit more on start / stop / shutdown.

* `SpeedStats` is now static instead of instanciated.
Instance was created as static, without any constructor. Non-sens.

* `DbIdResourceLocator` moved under `dlna` as it's not network related.

* `ControlHandler` (bump) is now started by `WebInterfaceServer`.
It was started by `UPNPHelper` with the only condition that `WebInterfaceServer` is up.
So let `WebInterfaceServer` start it itself.

### CODE REVIEW

**Comment by SurfaceS** [comment]
**Few words about `JUPnP` logging:**
As `JUPnP` logging changed from `java.util.logging` to `org.slf4j`, it now log by default into UMS.
Cling use `java.util.logging`, so it was not.
To reflect the cling implementation, I put a config flag to enable JUPnP verbose log (CONFIGURATION.isUpnpDebug()).
JUPnP logging is disabled by default, as it was with Cling (under `UmsUpnpService` creation).
I also based the new transport classes logging to the class they extend to log from `org.jupnp` package.

**Comment by SubJunk** [comment]
@SurfaceS thanks for all the explanations. Maybe it would be good to enable the logging - it was concerning for me at first but now that I know the explanation it sounds like it's good logging that would be useful for us

**Comment by SurfaceS** [comment]
There is a reason that UMS doesn't follow the UPnP standard on server field ?
I mean, UDA 1.0 (and 1.1) section 1.2.2 say SERVER field for datagram messages should be like :
OSNAME/OSVERSION UPnP/1.x PRODUCTNAME/PRODUCTVERSION
space should be the splitter.

**When UMS send this :**
`Server: Windows_10-amd64-10.0, UPnP/1.0 DLNADOC/1.50, UMS/10.16.1-SNAPSHOT`

**UPnP client discovery service understand :**
OSNAME = `Windows_10-amd64-10.0,`
OSVERSION = empty string
UPnP version : `1.0`
PRODUCTNAME = `DLNADOC`
PRODUCTVERSION = `1.50, UMS/10.16.1-SNAPSHOT`

At least UMS provide the UPnP version, that why it doesn't break even if the UPnP device follow exactly the UPnP standard.

**Comment by SubJunk** [comment]
I can’t remember if there’s a reason. Feel free to fix it

**Comment by SubJunk** [comment]
I've been testing this branch and it's working well for me so far, though my TV doesn't have the best UPnP support

Keen for your input @valib

**Comment by SubJunk** [comment]
I just had an interesting situation on this branch where I noticed my fans were really loud, I identified UMS as the cause (using 100% of one core) so I attached JProfiler to see what was happening, but as soon as it attached, the process activity stopped.

It might be unrelated to the branch, just wanted to mention it in case it happens again.

**Comment by SurfaceS** [comment]
Be careful with JUPnP log (in trace mode) as it's a lot verbose... 200 MB for 1 hour UMS run.

**Comment by valib** [comment]
Guys I am not sure we are speaking about the same. I am testig this
screen
and the last working commit is a6b8e192009d0e0738b28b8606da0e14805fc19b and the next commit cabcc7a013cc34a8c2d11707fff82939658e928a broken it. See the log of working UMS 
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7977993/debug.log) There is a part from time `12:14:50.903` to `12:14:51.914` which is missing in the current code. Seems like it needs the StreamServer working.

**Comment by SurfaceS** [comment]
#2812 you're right.
As subscription is made by cling, subscribed services use the cling http server to send events back.

**Comment by valib** [comment]
@SurfaceS now it works. There are some errors. See the log
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7980168/debug.log)

**Comment by SurfaceS** [comment]
Errors are now show for streamclient, as I wrote the class with our logger method.
cling was not logging as it use java logger (not logging on our logger), that's why we never seen that kind of errors.

**Comment by SubJunk** [comment]
@SurfaceS [60a8d7c](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2806/commits/60a8d7cd4b3c14a2cf3026e420a761975941f24a) is great to see!
I think we might be able to remove the `Set up Maven` steps on CI now, e.g. https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/.github/workflows/ci.yaml#L20
Can you try it?

**Comment by SubJunk** [comment]
@SurfaceS You have been contributing a lot lately, would you like to join the project? Assuming that is ok with the other @UniversalMediaServer/developers

**Comment by SurfaceS** [comment]
@SubJunk
_I think we might be able to remove the Set up Maven steps on CI now_
I'll have a try

_would you like to join the project?_
It's up to you. I contribute as I can.

**Comment by SurfaceS** [comment]
@SubJunk
Latest test was successful without set up maven steps on CI

**Comment by SubJunk** [comment]
@SurfaceS i have invited you to join UMS. There are no time expectations involved, it’s just nice to have a group of people to help each other when we have time

I’ll test and review this PR over the next few days I hope. I want to be careful with it

**Comment by SubJunk** [comment]
@SurfaceS I had the 100% CPU thing happen again, exactly the same as before but I used a different profiler (YourKit Java Profiler) and it still stopped happening as soon as that attached.

It seems it is specific to this branch.

**Comment by SurfaceS** [comment]
@SubJunk  `I had the 100% CPU thing happen again`
Do you have a log file ?

**Comment by SubJunk** [comment]
@SurfaceS I can reproduce it reliably by clicking the "Restart server" button at the top of the Java GUI, so hopefully that will reproduce for you too. If you want my logs I can email them or send them on our forum

**Comment by SubJunk** [comment]
@SurfaceS aside from the bug with the "restart server" button, it is working well for me. @valib is there anything here that you want to test before it progresses?

**Comment by SurfaceS** [comment]
@SubJunk I can't reproduce the bug on restart. I removed the partial JUPnP service restart then now it's fully restart. Maybe stopping the network services made JUPnP entering in a state it doesn't like, I don't know as I can't reproduce this bug.

Again, be careful with log as everything is logged in trace mode. It's nice to debug, but the log file grow quickly.

For you to understand better the server engine choice :
**Sockets, Netty and Java :** (nothing changed except Cling is replaced by JUPnP)
UPnP UDP datagrams by UMS `SocketSSDPServer`
UPnP registry by JUPnP
UPnP client (subscriber) by JUPnP (need a HttpServer/HttpClient, so run another HttpServer)
UPnP HttpServer (UMS device/services) by the chosen engine (Sockets, Netty and Java).

**Sockets :** really old based http server based on JDK socket only (seems not maintained / up to date)
**Netty :** http server based on Netty 3 (current default)
**Java :** http server based on JDK HttpServer (partially working for now, need more investigation)

**JUPnP (Netty) and JUPnP (Java) :**
Everything is under JUPnP, with Netty 3 or JDK HttpServer for HttpServer.
JUPnP construct and serve UMS device, ConnectionManagerService and MediaReceiverRegistrarService.
To handle the not yet implemented service (`ContentDirectoryService`), requestV2 is called directly from the JUPnP server.
That let us the ability to use both JUPnP and requestV2 as needed on the same running server.
Again, Java HttpServer is not fully working.

**Comment by SubJunk** [comment]
@SurfaceS Here's a clean debug file with the latest commit, which still has the restart bug for me. I clicked "restart server" at 12:00:02 and these errors appeared:

```
TRACE 2022-02-10 12:00:02.281 [SSDP Service] 
java.net.SocketException: socket closed
	at java.net.TwoStacksPlainDatagramSocketImpl.receive0(Native Method)
	at java.net.TwoStacksPlainDatagramSocketImpl.receive(TwoStacksPlainDatagramSocketImpl.java:114)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$1(SocketSSDPServer.java:482)
	at java.lang.Thread.run(Thread.java:750)
TRACE 2022-02-10 12:00:02.305 [SSDP Alive Service] Error when sending the ALIVE message: {}
java.net.SocketException: Socket is closed
	at java.net.DatagramSocket.send(DatagramSocket.java:658)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:314)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:281)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendAlive(SocketSSDPServer.java:245)
	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$0(SocketSSDPServer.java:462)
	at java.lang.Thread.run(Thread.java:750)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] Exception in thread "SSDP Alive Service" java.lang.IllegalArgumentException: unsupported address type
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at java.net.DatagramPacket.setSocketAddress(DatagramPacket.java:313)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at java.net.DatagramPacket.<init>(DatagramPacket.java:144)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at java.net.DatagramPacket.<init>(DatagramPacket.java:178)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:300)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendMessage(SocketSSDPServer.java:281)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.sendAlive(SocketSSDPServer.java:245)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at net.pms.network.mediaserver.socketssdpserver.SocketSSDPServer.lambda$listen$0(SocketSSDPServer.java:462)
INFO  2022-02-10 12:00:02.305 [SSDP Alive Service] 	at java.lang.Thread.run(Thread.java:750)
```

[ums_dbg_2022-02-10-12-00-100percentbug.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/8036751/ums_dbg_2022-02-10-12-00-100percentbug.zip)

**Comment by SurfaceS** [comment]
@SubJunk The error is not the 100% CPU thing. It have no impact. But I fixed that on to avoid this kind of error.
Looking at your run, everything is fine. The only thing is the delay on stopping JUPnP http server that I remove.
12:00:01.982 restart started

12:00:04.428 STOPPING MEDIASERVER
12:00:01.982 - 12:00:02.279 =  297ms Stopping the SSDP Service
12:00:02.279 - 12:00:03.299 = 1020ms Stopping JUPnP services. (here it was a delay).
12:00:03.299 - 12:00:03.306	=    7ms Stopping Netty HTTP server

12:00:03.307 - 12:00:03.420 =  113ms Loading renderer configurations
12:00:03.420 - 12:00:04.428 = 1008ms Waiting 1 second...

12:00:04.428 STARTING MEDIASERVER
12:00:04.597 - 12:00:04.601 =    4ms refresh NetworkInterfaces
12:00:04.602 - 12:00:04.612 =    2ms Starting Netty HTTP server
12:00:04.612 - 12:00:05.310 =  698ms Starting UPnP (JUPnP) services.
12:00:05.310 - 12:00:08.052 = 2742ms Starting the SSDP Service

12:00:08.052 restart finished
Total time = 6070ms

The thing is that on this PR, restart really restart all network services.
Before, it was just restarting the netty server and the SSDP Service.
So if you change inet or iface config, the upnp "client" (Cling) was leave in the old config => mistake.

Now, JUPnP restart, so it need to advise all devices that it is leaving, deregister, shutdown network services, restart network services, advise, register.

On my computer, restart time is (including the "Waiting 1 second..." delay from reset thread) :
Default (Netty) and Java : 4 689ms.
JUPnP(Netty) and JUPnP(Java) : 2 279ms.

**Comment by SubJunk** [comment]
I switched to the latest commit and ran JProfiler, which shows a blocked `background-task-0-restart` thread after restart:

image

I think the fact that when profiling tools attach to the instance, the CPU leak stops, is a big clue, since I think they request a garbage collection at first. So I would assume this is a process that is relying on GC to clean it up later.

**Comment by SubJunk** [comment]
@SurfaceS I switched to the latest commit and ran JProfiler, which shows a blocked `background-task-0-restart` thread after restart:

image

I think the fact that when profiling tools attach to the instance, the CPU leak stops, is a big clue, since I think they request a garbage collection at first. So I would assume this is a process that is relying on GC to clean it up later.

**Comment by Nadahar** [comment]
@SubJunk I'm not sure I understand what you mean, but if you suggest that GC "cleans up" running threads that's not the case. GC will only collect a thread once it's dead.

**Comment by SurfaceS** [comment]
I tried JProfiler on UMS 14.1 and on this PR... same result.
background-task-0-restart is yellow and green as your start one, but it's yellow after that for about 1 min (not red) then closed.
Your one is **red** after run, but on your log is goes to the end (`[background-task-0-restart(0)] task ended`).
Strange, and I can't find nothing as it's not happening on my side.

**Comment by SurfaceS** [comment]
@SubJunk  I don't understand your bug.
The reset thread do not block on the reset function itself otherwise you will not have the 'task ended' logged.
The reset function launch multiple threads that may block, but in that case, the red bar will be on this new thread, not on the background-task-0-restart one.
And the code under `TaskRunner` was not modified since Dec 2020, so I doubt it come from it.

**Comment by SubJunk** [comment]
Using YourKit Java Profiler I can see that it's the SSDP Service using that CPU

image

**Comment by SurfaceS** [comment]
Yes... that one show a mistake.
I'll investigate.
I'll not be available during the week end btw

**Comment by SurfaceS** [comment]
In fact the bug exist for a while.

Before, the second loop throw and it is a 1 sec sleep on the Exception catch, so you notice nothing (just logging an error each sec) instead of looping like the buggy.

But as I added a check on the multicastSocket state before entering the second loop, it not more throw, but stay in the first loop indefinitely without any sleep => 100%.

Fixed.

**Comment by SubJunk** [comment]
@SurfaceS thanks, I’ll test it today

**Comment by SubJunk** [comment]
@SurfaceS that was it, the CPU leak is fixed

**Comment by SubJunk** [comment]
@SurfaceS I know you are busy this weekend but when you get time, can you please either revert the renaming of `DbidTypeAndIdent` or use a different name for the file, instead of just changing case? It can be a problem for Git on Windows to change filename case

**Comment by SubJunk** [comment]
@SurfaceS my plan for this branch is to pull it into a v11 feature branch and release it as a beta, along with the HLS web interface and some other Media Library metadata changes I have been planning.
The way we usually do major releases is to release alphas and betas (and sometimes RC) to ease into it.

I have been testing this locally and it works well for me, but my TV doesn't have the best UPnP support so hopefully users will help us test it more broadly. What do you think?

**Comment by SurfaceS** [comment]
@SubJunk 
I can't help you on this decision :)
If you feel more confident with a beta, just do it.

**Comment by SubJunk** [comment]
@SurfaceS I have a recurring warning that has an interesting line `GET http://192.168.1.128:5001/description/fetch was not complete: Unexpected end of file from server`. Any idea why that would happen? I can go to that URL in my browser and it loads fine

```
DEBUG 2022-02-19 18:39:46.264 [jupnp-async-protocol-98] Preparing HTTP request message with method 'GET': (StreamRequestMessage) GET http://192.168.1.128:5001/description/fetch
TRACE 2022-02-19 18:39:46.264 [jupnp-async-protocol-98] Parsing all HTTP headers for known UPnP headers: 1
TRACE 2022-02-19 18:39:46.264 [jupnp-async-protocol-98] Trying to parse 'USER_AGENT' with class: UserAgentHeader
TRACE 2022-02-19 18:39:46.264 [jupnp-async-protocol-98] Adding parsed header: (UserAgentHeader) 'UMS/10.17.1-SNAPSHOT UPnP/1.0 DLNADOC/1.50 (Windows_10)'
DEBUG 2022-02-19 18:39:46.264 [jupnp-async-protocol-98] Writing headers on HttpURLConnection: 1
DEBUG 2022-02-19 18:39:46.264 [jupnp-async-protocol-98] Setting header 'User-agent': UMS/10.17.1-SNAPSHOT UPnP/1.0 DLNADOC/1.50 (Windows_10)
DEBUG 2022-02-19 18:39:46.264 [jupnp-async-protocol-98] Sending HTTP request: (StreamRequestMessage) GET http://192.168.1.128:5001/description/fetch
DEBUG 2022-02-19 18:39:46.266 [jupnp-async-protocol-98] SocketException while HTTP request (StreamRequestMessage) GET http://192.168.1.128:5001/description/fetch was not complete: Unexpected end of file from server
TRACE 2022-02-19 18:39:46.266 [jupnp-async-protocol-98] Releasing router lock: ReadLock
WARN  2022-02-19 18:39:46.266 [jupnp-async-protocol-98] Device descriptor retrieval failed, no response: http://192.168.1.128:5001/description/fetch
```

**Comment by SurfaceS** [comment]
@SubJunk 
It like with Cling (muted) but you have log with JUPnP.

192.168.1.128:5001 is your UPnP HTTP service.
In default profile, JUPnP is not handling the LocalDevice, so SSDP is advertise by SocketSSDPServer.
Then JUPnP think it is a new RemoteDevice, and try to connect to the advertised url to discover it.
If it have the data, it will show it on the gui, etc.
So someone prevent this by closing the HTTP connection on top of RequestHandler if it come from Cling (or JUPnP) :



 		// Is the request from our own Cling service, i.e. self-originating?
		boolean isSelf = ia.getHostAddress().equals(MediaServer.getHost()) &&
			headers.get(HttpHeaders.Names.USER_AGENT) != null &&
			headers.get(HttpHeaders.Names.USER_AGENT).contains("UMS/");


		// Filter if required
		if (isSelf || filterIp(ia)) {
			event.getChannel().close();
			/*if (isSelf && LOGGER.isTraceEnabled()) {
				LOGGER.trace("Ignoring self-originating request from {}:{}", ia, remoteAddress.getPort());
			}*/
			return;
		}

**Comment by SurfaceS** [comment]
Using JUPnP (netty) will not have this workaround as JUPnP advise itself the UMS device.

**Comment by SurfaceS** [comment]
I have tried this PR on JDK17 LTS (branch on my git [jdk17](https://github.com/SurfaceS/UniversalMediaServer/tree/jdk17)).
Seems to work well.

**Comment by SubJunk** [comment]
> I have tried this PR on JDK17 LTS (branch on my git [jdk17](https://github.com/SurfaceS/UniversalMediaServer/tree/jdk17)).

That's great. V11 can be our chance to bump to JRE17 too. I will review this soon

> Using JUPnP (netty) will not have this workaround as JUPnP advise itself the UMS device.

We could also use the v11 beta stages to change the default engine

**Comment by SurfaceS** [comment]
@SubJunk 
> V11 can be our chance to bump to JRE17 too

Maybe a good thing will be to add :
**Liberica Java 17.0.2**
copy :
https://download.bell-sw.com/java/17.0.2+9/bellsoft-jre17.0.2+9-windows-i586.zip
https://download.bell-sw.com/java/17.0.2+9/bellsoft-jre17.0.2+9-windows-amd64.zip
https://download.bell-sw.com/java/17.0.2+9/bellsoft-jre17.0.2+9-linux-i586.tar.gz
https://download.bell-sw.com/java/17.0.2+9/bellsoft-jre17.0.2+9-linux-amd64.tar.gz

to :
https://www.universalmediaserver.com/svn/binaries/win32/jre17-x86.zip
https://www.universalmediaserver.com/svn/binaries/win32/jre17-x64.zip
https://www.universalmediaserver.com/svn/binaries/linux/x86/jre17.tar.gz
https://www.universalmediaserver.com/svn/binaries/linux/x86_64/jre17.tar.gz

And to copy MediaInfo from base to /win32 (where it should be from start).

https://www.universalmediaserver.com/svn/binaries/
MediaInfo64.dll
MediaInfo.dll
MediaInfo-License.html

copy to :
https://www.universalmediaserver.com/svn/binaries/win32/

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
Good idea, I will do that

**Pull request merged**
