### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by SubJunk**
A playground to see how to fix our Bionic build

### CODE REVIEW

**Comment by SubJunk** [comment]
Well this is passing now so it was probably a bug on GitHub that has been fixed

**Comment by SubJunk** [comment]
It passed and I closed the PR, then it failed when I opened it

**Comment by SubJunk** [comment]
Same error on Linux 20.04

**Comment by valib** [comment]
@SubJunk as you can see only the `linux-focal` and the `linux-bionic` have a problem to make a new RealFile even if I used the real file not the fake one.

**Comment by SubJunk** [comment]
Ok so we have a "fix" now, the configuration was coming through `null`, but I will spend more time on it to figure out why that is the case, as I suspect it may be causing other bugs in the program, like maybe (hopefully) this https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2258

**Comment by SubJunk** [comment]
@valib I think this is an acceptable fix - the PMS instance wasn't initiated properly by the test

**Review by valib — APPROVED** [review]

**Pull request merged**
