### PR TITLE
Migrates from Netty 3.x to 4.0.25.Final

### LINKED ISSUE #454: Upgrade to Netty 4.x
To improve streaming from the server, an upgrade to Netty 4.x is needed. See [issue 253](https://github.com/UniversalMediaServer/UniversalMediaServer/issues/253#issuecomment-70592990) for more info.

### PR DESCRIPTION
**Pull request by mfulgo**
In Netty 3.x, if the kernel's send buffer fills up, it will suspend
writing data to the client until the stream is finished being generated.
In the case of transcoding large videos, that may be (and often is)
longer than the TV is willing to wait before closing its request and
opening a new one. The issue is not present in Netty 4.x.

**Note, this is a naive migration to Netty 4.x. It should probably go
through some more testing and incubation before being released.**

Closes #454

### CODE REVIEW

**Comment by SubJunk** [comment]
Very cool, I'll test it tonight and report my findings

**Comment by SubJunk** [comment]
It seems to work great for me, I tested a bunch of videos and the behavior was the same as before.

**Comment by SubJunk** [comment]
So now we have to decide whether to merge it for the 5.0.0 final release, or merge it then release another beta or RC version before the final one.

**Comment by SharkHunter** [comment]
go ahead and merge everything :)

**Comment by SubJunk** [comment]
@SharkHunter cool, thanks :) What do you think @mfulgo ? Ready for merge?

**Comment by mfulgo** [comment]
Sure! I'd be most comfortable releasing it under another beta or RC though, especially since there isn't really a comprehensive suite of tests.

That said... Users get what they pay for. ;) It really just comes down to how fast and loose you want to play it as an organization.

**Comment by SubJunk** [comment]
@mfulgo I'm going to release 5.0.0 final today without this, so if you can resubmit this to master after I've done that, we should have time to get more of an idea of its stability before releasing it in 5.0.1 or 5.1.0. In general I don't like having betas running all the time but maybe that's just me being lazy ;)

**Comment by mfulgo** [comment]
Sounds good to me. I'll do some refactoring while I'm at it and resubmit it to master after you merge the 5.0.0 branch into master and release.

Betas and nightly builds aren't a big deal if you're using an automated build/release system... Then it's up to your users how much risk they're willing to accept.

**Comment by mfulgo** [comment]
Closing this request and opening a new one to submit to master.

**Pull request closed without merging**
