### PR TITLE
JRE 14

### PR DESCRIPTION
**Pull request by SubJunk**
Implements https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1984

### CODE REVIEW

**Comment by valib** [comment]
@SubJunk when I build the `UMS-setup.exe` and installed on the WIN 10 the and tried to run it an error returns.
UMS error

**Comment by SubJunk** [comment]
That's a good point @valib I will add that to the installer, we already do that for some files.
I'll also look into that startup failure

**Comment by SubJunk** [comment]
I have tested it on a fresh install and on top of 9.5.0, and it seems to work now. Can you please confirm @valib ?

**Comment by valib** [comment]
@SubJunk I think that the same should be done in the workspace otherwise the wrong build could be possibly made.

**Comment by valib** [comment]
@SubJunk I can confirm that your last update works. But before testing I deleted JRE folders in the `target/bin/win32` to obtain the clean version of the Java.

**Comment by SubJunk** [comment]
@valib are you suggesting we add a deletion step to the Maven process as well? I can see how the current way can cause problems but I also don't want to have to maintain a huge list of files that used to exist in pom.xml.

One way to get around maintaining a list of old JRE files is to change the folder in this release. I can call it like `jre14-x64`. Would that be a good way to fix it for developers who are building before and after this change?

**Comment by valib** [comment]
@SubJunk you make it as I mentioned. Simply delete the old folders.

**Pull request merged**
