### PR TITLE
Rudimentary synchronization of InfoDb

### PR DESCRIPTION
**Pull request by Nadahar**
I just quickly did some redimentary synchronization of ```InfoDb``` based on the log in #1111. I don't know if the CPU issue is related to this, but it's extremely thread-unsafe the way that class is today. 

This implementation won't be very efficient (but I don't know if the difference is noticable). A more refined implementation should be made, but some heavy refactoring would be needed. As it is now this code almost qualifies as obfuscated to me, so it would take some effort to sort it out.

### CODE REVIEW

**Comment by Nadahar** [comment]
I'd like to add that I haven't tested it, as I'm not sure how ```FileDB``` is used. Although this should require massive testing, it should be verified as it (still) works as intended.

**Comment by SubJunk** [comment]
@Nadahar some if not all of this is unused or due to be unused in 7.0.0 anyway, in favor of SQL

**Comment by Sami32** [comment]
@Nadahar Do you think it can be merged now for see if it solved #1111, until 7.0.0 become a stable release ? or closed while waiting for 7.0.0 ?

**Comment by Nadahar** [comment]
@Sami32 I'd ideally want for this to be tested, but I guess that's not really going to happen. The changes aren't what I'd consider likely to cause bugs, neither FindBugs nor Threadsafe have any complaints so I guess I might as well merge it.

**Comment by Sami32** [comment]
@Nadahar I understood that, but i didn't know how to test it correctly/efficiently, as database use is not my strong use...
:-/

**Comment by Nadahar** [comment]
@Sami32 It's database only in the name. It is really only a text file where you can add and remove entries, much like a "file-backed" ```List<String>```. That part is enough, I'm just not sure how it's actually being used and what implications a bug here would have. I could find out by studying the code, but isn't *that* interested, especially when 7.0.0 will replace its use with a real database.

**Pull request merged**
