### PR TITLE
Fix bug for the FFmpeg setting of the CPU cores

### PR DESCRIPTION
**Pull request by valib**
@SubJunk this is really annoying to make a PR for the evident bugs fix.

### CODE REVIEW

**Comment by valib** [comment]
Sorry guys I made a mistake

**Comment by Nadahar** [comment]
@valib Maybe the PR wasn't such a bad idea then, we just saved ourselves a reversal in master.

**Comment by valib** [comment]
There must be something wrong with my WIN 10 because during testing the UMS offered only 1 CPU core instead of 4 available. When I retested this PR againn the 4 CPU cores are available and everything is OK.

**Comment by SubJunk** [comment]
That was good timing for the PR to prove its usefulness ;)

**Pull request closed without merging**
