### PR TITLE
Add thai support

### PR DESCRIPTION
**Pull request by Sami32**
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/922)

### CODE REVIEW

**Comment by SubJunk** [comment]
@Sami32 it looks like there are some extra + characters in here that will need to be removed

**Comment by Sami32** [comment]
@SubJunk I was thinking it was because i didn't yet make add to the constant file...my bad.
Thank for your comment, advice.
By the way, i did leave you an Thai flag to insert as i don't know how to do that myself :-(
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/924

**Comment by SubJunk** [comment]
@Sami32 it's cool, I learn the same way :) I can add that flag soon

**Comment by SubJunk** [comment]
Our automated test is failing for this branch, so it needs to pass before we merge it. This is the failure:

```
/home/travis/build/UniversalMediaServer/UniversalMediaServer/src/main/java/net/pms/util/SubtitleUtils.java:[81,29] cannot find symbol
[ERROR] symbol: variable CHARSET_WINDOWS_874
[ERROR] /home/travis/build/UniversalMediaServer/UniversalMediaServer/src/main/java/net/pms/util/SubtitleUtils.java:[82,29] cannot find symbol
[ERROR] symbol: variable CHARSET_ISO_8859_11
[ERROR] /home/travis/build/UniversalMediaServer/UniversalMediaServer/src/main/java/net/pms/util/SubtitleUtils.java:[83,29] cannot find symbol
[ERROR] symbol: variable CHARSET_TIS_620
```

**Comment by Sami32** [comment]
Thank for helping :+1: 
I did saw the message on _Travis CI_ but didn't understood it, yet trying to figure out this meaning...

**Comment by Sami32** [comment]
@SubJunk Ok, i compiled them and it's working :-), it was the constants that need to be compiled at same time.
P.S. I closed the PR related to thai translation, because it give error since it's look like it depend on Crowdin and i will not do that for now...

**Pull request closed without merging**
