### PR TITLE
Update Viera TX32V10E setting

### PR DESCRIPTION
**Pull request by valib**
@SubJunk this is really annoying to make a new branch to make a small not so interesting change when big changes I made are still waiting to be merged like #911

EDIT: If you want to not allow us to mergre our  changes directly please evaluate our PR's and decide whose of it are ready to be merged or not and  give us your decision.

### CODE REVIEW

**Comment by Sami32** [comment]
@UniversalMediaServer/developers  To be honest it is a shared responsibility.
Someone asked for reviewing and more documentation...good ideas that need to be acted, imo, without any wills to offense anyone.
It was mean for the best, not the worst...My limited skill don't give me to much freedom on that matter.

**Comment by SubJunk** [comment]
@valib I understand it's frustrating but there was a lot of activity in master and a lot of reversions so something had to change.

For months I tried telling everyone that they need to make branches for things that are not simple, and if everyone had stuck to that then we would be ok with how it was before.

Do you have a suggestion of how we could do it better?

**Comment by Nadahar** [comment]
@SubJunk I've written down some thoughts about how to handle this [here](https://github.com/UniversalMediaServer/UniversalMediaServer/pull/911#issuecomment-254974117). I think the whole process would go much smoother if everyone knew how to review/give feedback.

**Comment by SubJunk** [comment]
@Nadahar maybe we can have the rest of the discussion in this PR

I think we have enough active developers now that a PR can wait until there is a review done.

@UniversalMediaServer/developers if you approve a PR via review, that means you have understood and approve of the code in that PR. I put real thought into making reviews mandatory and it is actually me giving up some control over the project, and therefore giving you guys more freedom with it. In the past I have needed to approve every PR and that resulted in stale PRs which isn't great for anyone, so this is a chance for our small team to self-moderate.

It can either go badly, in which case we will go back to me having more control, or it might go well and result in faster turnarounds for PRs. I hope the latter happens.

I suggest that we do not review a PR until the developer has indicated they think it is ready to be merged. I have created a new label for us to use called `awaiting review` to give us more visibility over that too.

It is also the job of code contributors to keep their PRs from being too large. I know we have already discussed it and I think we all agree on it. One PR is for one feature. If there are two features in your PR then split it into two PRs unless those features are inseparable.

I am not in favor of a time limit for a PR to be merged. It must be more purposeful than that. I have some PRs open that I don't want to be merged, sometimes I open them just to get more feedback or to play around with no intention to merge.

**Comment by Nadahar** [comment]
@SubJunk What I think is the "difficult" point in this is how to determine if the change is something we want. Reviewing the PR on a technical level is one thing, but how do we decide if it's a good idea?

**Comment by SubJunk** [comment]
@Nadahar yeah that is a good point and it is difficult. I still want to retain control over which ideas/features make it into the program. I don't think I've ever rejected a new feature, but I have had opinions on whether it lives in the GUI or not, since I think most users already feel overwhelmed by our GUI so I want to be careful about what we add there.

So I guess a guideline is:

* If something **adds** new functionality, it's probably okay to merge unless it involves GUI clutter
* If something **changes** any current functionality, I need to approve it before merge (and probably to save you time, before development starts on it)
* If something **fixes** any current functionality, I don't need to be involved

I will try to be involved everywhere anyway but hopefully this will stop it grinding to a halt when I get busy :)

**Pull request merged**
