### PR TITLE
Don't log the GetPositionInfo failure

### PR DESCRIPTION
**Pull request by valib**
and not set the renderer as false in this case. This fix the implementation of the GetPositionInfo which could be wrong in the renderer like the Movian.

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib I agree it is spammy at INFO level, but maybe it would be better to change the level to DEBUG or TRACE, since it might be useful for debugging renderer capabilities

**Comment by valib** [comment]
@SubJunk this could be the final version

**Comment by valib** [comment]
@SubJunk in the `UPNPControl `is implemented the `Device` and the `Renderer` whose in fact should be the same. Maybe we could rewrite it to use only one of those.

**Comment by SubJunk** [comment]
How can I test this?

**Review by SubJunk — COMMENTED** [review]
Why is ps3slim.png in here?

**Comment by valib** [comment]
> Why is ps3slim.png in here?

Because during testing I that the PS3Slim icon is much bigger than others. So I take the opportunity to fix it in one PR.

**Comment by valib** [comment]
@SubJunk you can test by installing Movian on PC or Android phone. The UMS shoud show the error only once.

**Comment by valib** [comment]
Maybe we can try to send the GetPositionInfo two or three times before we set that the renderer is not capable to respond. What do you think?

**Comment by valib** [comment]
@SubJunk what do you think about the several checking if the GetPositionInfo is implemented? I think that it could be done only once and if renderer doesn't respond than it could be marked as not implemented this feature.

**Comment by SubJunk** [comment]
@valib yes that seems like a good idea. Has @Mik-S-UMS tested this fix to see if it fixes https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2338 ?

**Comment by Mik-S-UMS** [comment]
If you can do me a build I'll give it a test but my network setup has changed to a more normal setup, with the router connected to the internet instead of using a second wireless connection for the internet. I have no way of replicating my original setup for that issue.

I should be able to check that Movian doesn't spam the log with errors though, and maybe my Samsung TV too as it creates that error when it's turned off.

**Comment by SubJunk** [comment]
I have 3 variations of that error that I get a lot on my Panasonic TV.

### 1) The error happens after my TV has been turned off, and UMS knows it is off

```
DEBUG 2021-04-06 08:48:24.320 [cling-359] VIERA VT60 Series is now offline.
DEBUG 2021-04-06 08:48:24.320 [cling-361] Subscription cancelled: ConnectionManager on uuid:4D454930-0100-1000-8001-000B977EA155: DEVICE_WAS_REMOVED
DEBUG 2021-04-06 08:48:38.732 [UPNP-AliveMessageSender] Sending ALIVE...
ERROR 2021-04-06 08:48:45.440 [UPNP-VIERA VT60 Series] Failed to send action "GetPositionInfo" to VIERA VT60 Series: Error: Current state of service prevents invoking that action. Connection error or no response received.
```
That is our fault, because a TV can't be playing, recording or transitioning when it is powered off, so we should add logic to not send GetPositionInfo when a device is offline.

### 2) TV is telling UMS that it does not support that feature with "Not implemented":

```
Failed to send action "GetPositionInfo" to VIERA VT60 Series: Error: Current state of service prevents invoking that action. Non-recoverable remote execution failure: 501 Not Implemented. (HTTP response was: 501 Not Implemented)
```
So again that is our fault for not gracefully handling that situation, when the renderer has specifically told us that it does not support what we are asking from it.

### 3) TV is on, but reports that the state of service prevents invoking the action.

Have we considered that the error is correct? For example in the UPnP spec it says:

> a control point can invoke GetPositionInfo every second *when the TransportState is
PLAYING, RECORDING or TRANSITIONING*. This is more efficient and flexible than requiring event
notifications to be sent to all subscribing control points, in all cases.
from http://upnp.org/specs/av/UPnP-av-AVTransport-v1-Service.pdf

So maybe our TransportState isn't correct in this case. Do we have logic to verify that the state is ok before we send GetPositionInfo?

**Comment by valib** [comment]
> So maybe our TransportState isn't correct in this case. Do we have logic to verify that the state is ok before we send GetPositionInfo?

It is here:
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/589692cb390c19e70c3d1fa913185fc45aab5830/src/main/java/net/pms/network/UPNPControl.java#L204

**Comment by valib** [comment]
> 1) The error happens after my TV has been turned off, and UMS knows it is off

I see a way how to fix it. Do not mark the renderer as not active but remove them from the renderers pool and let the UMS recognize them again when it responds to the UMS ALIVE message. This may

**Comment by SubJunk** [comment]
Maybe that logic should be changed to match what the spec says instead of just saying not stopped?

**Comment by SubJunk** [comment]
@valib I pushed a commit to show what I mean, do you think that's a good idea? Feel free to revert if not

**Comment by SubJunk** [comment]
@valib I think cases 1 and 2 from https://github.com/UniversalMediaServer/UniversalMediaServer/pull/2366#issuecomment-816338332 are still problems, do you think we should try to fix them here or in another branch?

**Comment by valib** [comment]
@SubJunk the case 2 is fixed in
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e809aa533c7e6350aacc33f079672097c3916b43/src/main/java/net/pms/network/UPNPControl.java#L781-L783

The only question if this should be shown like error here
https://github.com/UniversalMediaServer/UniversalMediaServer/blob/e809aa533c7e6350aacc33f079672097c3916b43/src/main/java/net/pms/network/UPNPControl.java#L770-L773

**Comment by SubJunk** [comment]
Maybe we should not treat it as an error if the renderer has responded correctly like that, what do you think?

**Comment by valib** [comment]
@SubJunk why only MacOS (push) is not working? The (pull_request) is OK. There should be somethink wrong in the checks setup.

**Comment by SubJunk** [comment]
@valib there is a PR that might fix it, I ran it 4 times without failure. I think it is just a caching problem

**Comment by valib** [comment]
@SubJunk the commit e19b8d6 should also fix the case 1.

**Comment by valib** [comment]
@SubJunk the MacOS problem is here again. Maybe the Github has a problem with cache when it is trying to download artifacts from the URL `http://0.0.0.0/com/...`  which is nonsense. What about to not use the cache for MacOS?

**Comment by SubJunk** [comment]
Hmm yeah it's weird. I don't think our use of the cache will affect it, it's more like an internal cache at GitHub. I'll try that though.

**Comment by SubJunk** [comment]
Oh I think I see the problem. They have updated to Maven 3.8.1 and that has disabled access to HTTP URLs. Will try to fix.

Maybe the inconsistency is that sometimes we get an instance with Maven 3.6 as they roll out the update

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
I have been testing this with my TV and it seems to work

**Pull request merged**
