### PR TITLE
Add Eclipse codeStyle.xml

### PR DESCRIPTION
**Pull request by Nadahar**
This is not ready to merge, it's more of a suggestion. I haven't really figured out the "UMS code style" yet other than that you prefer less blank lines than me and that you put else, catch etc on the same line as }.

I've simply exported my current Eclipse profile as a starting point. It would really make it easier if you agreed on what the desired settings are and then included the file in the project. In that way, anyone using Eclipse could get it right from the beginning.

### CODE REVIEW

**Comment by SubJunk** [comment]
We aren't very strict about code style but it would be nice to define an ideal standard.
A few things that I usually change in formatting commits are:

Use tab-indentation, but use space-indentation for inline-indentation. This is because it allows developers to change their tab display to match the level of indentation they prefer (i.e. developers who like using 2-space indentation can just change their IDE settings to use 2-space tab width), and using spaces for inline-indentation means the indentation is always in sync with itself no matter which tab-width is set by the developer.

if {
} else {
}

Use switches instead of ifs for 3 or more conditions.

Use blank lines for grouping. So if you initialize a variable just before the statement it's use in, there's no blank line between them. But if you're initializing a variable to be used later in the code, a blank space is used. Similarly if if statements are related they don't have a blank space but if they are separate they do.

Those are some ranty thoughts on code style and I'm happy for people to disagree and it would be cool if we can define a document that explains what we agree on

**Comment by Nadahar** [comment]
I've made certain changes to my ```codeStyle.xml``` since then to better fit UMS' style (UMS' style isn't homogeneous, so it's hard to be precise). It's good enough to use for automatic formatting of simple files, but I wouldn't dare to use it on more complex classes.

I also have a ```checkstyle.xml``` that I'm using some, but I think it still needs some more work to fit properly. We could always make updates to them as we see fit later though, so it might be an idea to start with those I have.

**Comment by Sami32** [comment]
:+1:
Better, yes ;)

**Comment by Nadahar** [comment]
I've added more "formatting" setting files I use, and updated the one that was already here. They are far from perfect, but they're much better than nothing and should ideally evolve with the project.

**Comment by Nadahar** [comment]
@SubJunk @valib Do you have any reservations against merging this? None of this is applied automatically, it's just template files that provides a default that matches UMS a bit better than the default settings.

**Comment by SubJunk** [comment]
I haven't reviewed the changes but since I don't use Eclipse I don't mind :) Happy for it to be merged

**Comment by valib** [comment]
@Nadahar no objection but I reccomend to add somewhere how to set Eclipse to use those settings.

**Comment by Nadahar** [comment]
@valib Is that better?

**Comment by valib** [comment]
@Nadahar mybe I am doing something wrong but the setting is not automatically enabled. This works only when I manually change the Eclipse setting.

**Comment by Nadahar** [comment]
@valib Yes, I described how to use them in the Eclipse.README file. Nothing of this is automatically applied. If we want them to be automatically applied we have to check in the ```.settings``` folder as well. My thought wasn't to enforce any of this, but to make these settings easily available for those who wanted them.

**Pull request merged**
