### PR TITLE
Access-Control-Allow-Origin set to "*"

### PR DESCRIPTION
**Pull request by ik666**
Hey guys. I'd like to add this policy for manipulating thumbnail images delivered by UMS in JavaScript. I need to crop images that are delivered as rectangle to squares. Without this policy the browser will not allow to do that.

### CODE REVIEW

**Comment by SurfaceS** [comment]
Setting Access-Control-Allow-Origin to * is never a good choice.

**Comment by SurfaceS** [comment]
Why don't u use your API to do that for you ?

**Comment by ik666** [comment]
Access control can be set more restrictive, i.e. to GET requests. Actually, making it configurable (opt in) could also be a solution.

I'm uncertain, what you mean with using the/my API  ... thumbnail URL's in the DIDL response are generated by the DLNAResource class.

**Comment by SubJunk** [comment]
@ik666 depending on the use case this can be done easily with CSS like this:

```
img.thumbnail {
  width: 175px;
  height: 175px;
  object-fit: cover;
}
```

**Comment by ik666** [comment]
@SubJunk I think your renderer option is a good choise. CSS approach: I used to square images like you proposed with CSS in the past, but then I switched to a responsive design with flexbox div's resizing and wrapping images to cover most of the users screen leading to flexible image width and height values.

**Comment by SubJunk** [comment]
@ik666 similar strategy should work with flexbox too, for example there is the `aspect-ratio` CSS property that will work with dynamic widths and heights. IMO CSS is a better choice for this than JavaScript, usually the CPU use is much lower for CSS, and less code

**Comment by ik666** [comment]
@SubJunk You're absolutely right. I've searched for CSS solutions myself, but didn't find any until now. Thanks a lot, the `aspect-ratio` property did the trick. Must be a new one, haven't heard of it, yet :)

Regarding this PR ... maybe in the future someone can still find it useful to set the 'Access-Control-Allow-Origin' response header. Since it's now configurable one can narrow the domain now.

**Pull request closed without merging**
