### PR TITLE
Cling remove apache dependency

### PR DESCRIPTION
**Pull request by SurfaceS**
Removed apache HTTPClient implementation as it's a bit buggy.
Replaced by an `HttpURLConnection` client implementation with a custom 'upnped' `HttpHandler` (`UpnpHttpHandler`) that will work for java 8+ (tested on Java 17 LTS).

Should fix @valib founded bug introduced in #2801.

That fix was included in the #2806, but as it is a big PR, it may need some time to be reviewed.

### CODE REVIEW

**Comment by SurfaceS** [comment]
Ready for review to allow @SubJunk to release the next version.

**Comment by valib** [comment]
Still not working
[debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7950427/debug.log)

**Comment by SurfaceS** [comment]
@valib This time subscriptions are established.
DEBUG 2022-01-27 13:34:30.634 [cling-9] Subscription established: StreamSplicing on [AV] Samsung Soundbar MS750
DEBUG 2022-01-27 13:34:30.636 [cling-19] Subscription established: ConnectionManager on [AV] Samsung Soundbar MS750
DEBUG 2022-01-27 13:34:30.725 [cling-19] Subscription established: RenderingControl on [AV] Samsung Soundbar MS750
DEBUG 2022-01-27 13:34:30.785 [cling-19] Subscription established: AVTransport on [AV] Samsung Soundbar MS750

I'll review the log.

**Comment by valib** [comment]
@SurfaceS yes subscriptions are established but it seems that values are not transfered. The volume, pause, fast forward buttons on the UPnP Player are disabled and when I try to play it starts but is not possible to stop it.

**Comment by SurfaceS** [comment]
Can you try with the netty server (HTTPv2) as engine (not java HTTPv3) ?
It may be a connection closed on HTTPv3.

**Comment by valib** [comment]
@SurfaceS this log is for Netty
[Netty debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7950880/debug.log)
 and for Java
[Java debug.log](https://github.com/UniversalMediaServer/UniversalMediaServer/files/7950933/debug.log)

For Netty it works partially. For Java is not working at all.

**Comment by SurfaceS** [comment]
@valib
It can be normal that it doesn't work on `JavaHttpServer` impl, as it is not yet fully supported (HTTPv2 is messy to follow).
But `NettyServer` was not changed on this PR, so I don't understand why you have this.
I putted a more detailled log on both `NettyServer` and `JavaHttpServer` to understand why your Play action failed, as `NettyServer` and your device seams to well communicate each other.

**Comment by SurfaceS** [comment]
@SubJunk you can merge this one, as it fix cling `StreamClient`.

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
I'll merge it but I think we are still blocked on a release is that right @valib @SurfaceS ? Based on the comment that netty is "partially" working

**Pull request merged**
