### PR TITLE
More documentation

### PR DESCRIPTION
**Pull request by Sami32**
MediaParserV2_ThumbnailGeneration

---
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/1017)

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 You should read a bit about git and it's possibilites. There's no need to create a new PR for each change, this could easily have been another commit on #1015 (and just renamed #1015 to "Add documentation").

Although not all here agree with me on this, you need to understand how what you are doing affects the git history. Having a "understandable" git history is valuable when trying to figure out how something ended up as it did when researching how to best refactor or add functionality to existing code. Merging generally makes the history a mess both because you get a lot of "merge commits" that's not really commits and because you get multiple parents making it harder to track changes.

Refactoring is very powerful and can and should be used an a branch when working on it. You can combine commits (squash on gitish), remove commits and even go back and edit commits and/or commit messages. That way several small "partial" commits can be combines to one logical commit including everything that should have been in that commit in the first place (but wasn't because you forgot to do things or found out you did a mistake). When done this way, the history makes much more sense to anyone trying to read it, and it's much cleaner/easier to review. It's also better for people not to have to review tons of tiny PR's with one commit each instead of a complete "feature" or other change. Combining too much isn't good either because it makes it hard to understand when reviewing, a PR should if possible do one specific thing.

The only thing to remember when rebasing is that if you have already pushed that branch before rebasing, anyone else working on that branch will have to reset their branch and potentially have extra work adaping their changes. But, if only one person is working on a branch that is not a problem. The best is to wait with pushing until you've completed the work and finished any rebasing though.

**Comment by Sami32** [comment]
@Nadahar Maybe i should, but i don't plan to, i will stick to Github Web interface.
I read you resume, but i'm not sure what i need to do with that ?

**Comment by Nadahar** [comment]
@Sami32 I'm not sure I understand you. GitHub isn't meant to be a git tool, it's only an online git repository with "helper functions". If you choose to limit yourself to the GitHub web interface you miss out on most git capabilities.

You should install [TortoiseGit](https://tortoisegit.org/). It's basicly a git GUI for Windows that makes using and unserstanding git much easier. Some tasks are also much faster as you can "drill down" instead of handling a lot of reference values.

I don't know what you refer to as "my resume", so I don't know what to do with it either. I hope you didn't close this because of what I said, I just tried to help you make better PRs.

**Comment by Sami32** [comment]
This documentation should also be added, as it's used in Sony renderers:
> **AccurateDLNAOrgPN**
> Default: false

**Pull request closed without merging**
