### PR TITLE
fix update dialog hanging

### PR DESCRIPTION
**Pull request by tylovejoy**
Fix update dialog box hanging. 

Discussed here: https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4109#issuecomment-1876264311

Solves: #4315

### CODE REVIEW

**Review by SubJunk — CHANGES_REQUESTED** [review]
Thanks for the fast response. It still crashes when an update is available. You can see it by setting the version to an older one and running this

Unfortunately I think this bug will cause a lot of problems because everyone with automatic updating enabled will see UMS crash on startup. I should have tested it more.

I will make a change to disable automatic updating for the broken versions

**Comment by tylovejoy** [comment]
Strange- I tested that and it worked fine on my machine. My apologies for not catching this before submitting.

**Comment by SubJunk** [comment]
@tylovejoy interesting that it worked for you, maybe the code hadn't updated when you tested it? Here's a screenshot after I changed the version string to 13.7.1. Can you recheck?
image

Thanks for apologizing, I should have tested it more, plus the way the auto updating code is written it is very easy to introduce bugs. It is using a code pattern where it is heavily bound together so any small change often introduces a bug.

**Comment by SubJunk** [comment]
I think this will prevent those versions from ever finding an update while enabling future versions to find them https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4333

**Comment by SubJunk** [comment]
I think the problem is that the change event is fired twice, because of this observable method https://github.com/UniversalMediaServer/UniversalMediaServer/blob/a6586f671eaccde874bc6c446f0de1c200689976/src/main/java/net/pms/newgui/LooksFrame.java#L669
I noticed that observables are deprecated in Java now, in part because of thread safety problems.

**Comment by SubJunk** [comment]
I have narrowed down the problem to the line that removes the previous TrayIcon now, so I think I am close to a fix for that

**Comment by SubJunk** [comment]
This problem is fixed in https://github.com/UniversalMediaServer/UniversalMediaServer/pull/4333
Unfortunately it involves using a magic number (5000ms) but I had problems otherwise, and didn't want to refactor the entire updating code today 😆 
In testing I verified that it behaves on startup and when the button is clicked

Another thing I noticed is that the update icon is the Windows one, which looks strange on macOS because that has a different tray icon. Are you able to make a variation for macOS too @tylovejoy ?

**Pull request closed without merging**
