### PR TITLE
Fix InfoDb

### PR DESCRIPTION
**Pull request by SharkHunter**
As always this is a bit over designed. But then again why not :)

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/846)

### CODE REVIEW

**Comment by SubJunk** [comment]
The code looks great, will test later

**Comment by SubJunk** [comment]
@SharkHunter it seems to have fixed it, great job :) I have one stubborn file `[DmonHiro] Magi - 01st Night (v2) - Aladdin And Alibaba (BD, 720p) [D39B42F4].mkv` that keeps getting re-checked so I'll try to see why that is

**Comment by SubJunk** [comment]
@SharkHunter I tested some more and I'm happy to merge it. It still doesn't work for that one file, but this is a big improvement so let's merge.

@UniversalMediaServer/developers are you guys happy to merge?

**Comment by SubJunk** [comment]
Oh I figured out why it doesn't work for that file, it's just because we don't escape commas in filenames. I'll make that change

**Comment by SubJunk** [comment]
@SharkHunter this is working mostly great after more testing, but it seems to break our support for commas in filenames. The comma replacement still works for the OpenSubs information but just not the filenames.

**Comment by SharkHunter** [comment]
I'll have a look. I'm doing some more over engineering first

**Comment by SharkHunter** [comment]
Has that ever worked?
I didn't change that part (just moved that part around)

**Comment by SharkHunter** [comment]
Some extra overengieneering.

@SubJunk - can you send a snippet of the db file (with commas) in both filename and then in opensubs data..

**Comment by SubJunk** [comment]
@SharkHunter you're right that commas in filenames didn't work before. Here's a snippet from my infodb in master:

```D:\Cosmos.A.Spacetime.Odyssey.S01E06.1080p.BluRay.DD5.1.x264-DON.mkv,tt3120706,Deeper&comma; Deeper&comma; Deeper Still,Cosmos: A Spacetime Odyssey,1,6,2014
D:\[DmonHiro] Magi - 01st Night (v2) - Aladdin And Alibaba (BD, 720p) [D39B42F4].mkv,,,,,
```

Then this branch:

```
D:\Cosmos.A.Spacetime.Odyssey.S01E06.1080p.BluRay.DD5.1.x264-DON.mkv,tt3120706,Deeper&comma; Deeper&comma; Deeper Still,Cosmos: A Spacetime Odyssey,1,6,2014
D:\[DmonHiro] Magi - 01st Night (v2) - Aladdin And Alibaba (BD, 720p) [D39B42F4].mkv,@@@NULLOBJ@@@
```

and then if I restart UMS and load the folder again it truncates the filename at the comma like this:

```
D:\[DmonHiro] Magi - 01st Night (v2) - Aladdin And Alibaba (BD,@@@NULLOBJ@@@
```

**Comment by SubJunk** [comment]
It's using the encodedSeparator on filenames now

**Comment by SharkHunter** [comment]
@SubJunk - the culprit is found in FileDb.
Line 146 reads (this is in the null case): data = new StringBuilder(entry.getKey()); 
While in the non-null case (line 159) reads: data = new StringBuilder(Pattern.compile(separator, Pattern.LITERAL).matcher(entry.getKey()).replaceAll(Matcher.quoteReplacement(encodedSeparator)));

Simply replace copy line 159 to line 146 and it should work. This is something that never worked (there was no replacement of separators in the null case) . I'll do a proper fix tonight (no code at work :))

**Comment by SharkHunter** [comment]
@SubJunk - Damn you're faster than me (8 seconds).....

**Comment by SubJunk** [comment]
@SharkHunter haha cool :) Good to know we figured out the same fix at least that gives me confidence in it

**Comment by SubJunk** [comment]
@UniversalMediaServer/developers I want to merge this soon, any objections?

**Comment by SharkHunter** [comment]
I'm not grumpy :)
@SubJunk - if you could have test the retry feature that would be good (perhaps you need to lower the redo time from a week first). It's off by default so normally it will not do anything...

**Comment by SubJunk** [comment]
Sounds good to me, I'll test it tomorrow. I don't ever think of you as grumpy :)

**Comment by SubJunk** [comment]
@SharkHunter I tried the redo feature and get a bunch of:

```
11:33:20 INFO  Exception in thread "Thread-482" java.util.ConcurrentModificationException
11:33:20 INFO  	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
11:33:20 INFO  	at java.util.HashMap$KeyIterator.next(Unknown Source)
11:33:20 INFO  	at net.pms.util.InfoDb$2.run(InfoDb.java:141)
11:33:20 INFO  	at java.lang.Thread.run(Unknown Source)
```

if I browse within the time period. Also lots of duplicate lookups and it makes my computer unusable because UMS is taking up 100% CPU aggressively

**Comment by SharkHunter** [comment]
@SubJunk - yeah ok. Remove the calls to redoNulls before you merge and I'll fix that later.

**Comment by SubJunk** [comment]
@SharkHunter thanks for working on this more, I'll re-test it soon

**Comment by SubJunk** [comment]
@SharkHunter this seems to be working well for me now, do you think it's ready to merge?

**Comment by SharkHunter** [comment]
yeah merge on

**Comment by SubJunk** [comment]
Nice work!

**Pull request merged**
