### PR TITLE
Added prettifying test

### PR DESCRIPTION
**Pull request by SubJunk**

### CODE REVIEW

**Review by js-kyle — APPROVED** [review]

**Comment by valib** [comment]
@SubJunk what about the filename `Universal Media Server-1x23-Mysterious Wordplay.mkv` not the `Universal Media Server - 1x23 - Mysterious Wordplay.mkv`? This is not correctly prettified. The result is `Universal Media Server-1x23-Mysterious Wordplay`

**Review by valib — COMMENTED** [review]
It should be updated in the prettifying

**Comment by SubJunk** [comment]
@valib is that an actual format that people use?

**Comment by valib** [comment]
@SubJunk I have no idea but it should parse all possibilities, isn't it?

**Comment by SubJunk** [comment]
@valib ok, sure

**Comment by SubJunk** [comment]
@valib how's this?

**Review by valib — APPROVED** [review]

**Pull request merged**
