### PR TITLE
Addressing #640 Windows 10 compatibility 

### PR DESCRIPTION
**Pull request by Nadahar**
@UniversalMediaServer/developers @SubJunk 
As far as I can see, ```PmsConfiguration.isAdmin()``` is the only part of UMS directly incompatible with Windows 10 - if anyone knows of any other issues please let me know.

I've updated ```PmsConfiguration.isAdmin()``` to work for Windows 10, or actually to work for any Windows version from Windows XP and upwards. I've tested this on Windows XP, Windows 7 and Windows 10, so I assume it's correct also for Windows Vista and Windows 8. When looking at Windows version instead of matching a specific OS name, it will work for Windows servers as well a future Windows versions as long as the method work. The day it doesn't work anymore, the Windows version simply has to be limited upwards.

But, since I was already in that method, I wanted to complete it by adding support for Linux and OS X as well. This is done and tested (don't let me start on how much trouble it was getting a OS X VM to run and to get git and maven to work on OS X).

This has created problems with the "single instance" logic though, since ```isAdmin()``` has always returned ```true``` for Linux and OS X until now. I've tried to suggest fixes in #668, but the only feedback has been negative. Until that is solved I think it's better to leave this unmerged.

Any suggested resolutions are welcome.

### CODE REVIEW

**Comment by SubJunk** [comment]
This looks good. We could always comment out the Linux/OS X logic so it can merge now, and uncomment that when the single instance logic issues are fixed

**Comment by Optimusprimeums** [comment]
Great fix, i agree with @SubJunk

**Comment by valib** [comment]
Agree too.

**Comment by skeptical** [comment]
+1

**Comment by Nadahar** [comment]
Ok, I've disabled the check for Linux/OS X and will merge this, but then I really hope we can continue the discussion in #668 .

**Pull request merged**
