### PR TITLE
Update Panasonic-VieraE6.conf

### PR DESCRIPTION
**Pull request by Sami32**
Some format support adjustements

---
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/909)

### CODE REVIEW

**Comment by SubJunk** [comment]
@Sami32 thanks for the PR. Why 120x120?

**Comment by Sami32** [comment]
@subjunk https://github.com/UniversalMediaServer/UniversalMediaServer/files/267064/UPNP_Analyse.txt
Maybe not pertinent, but it is because i saw that in the UPnP analyse of my Renderer :
```
<icon>
				<mimetype>image/jpeg</mimetype>
				<width>48</width>
				<height>48</height>
				<depth>24</depth>
				<url>dlna_icon_48.jpg</url>
			</icon>
			<icon>
				<mimetype>image/jpeg</mimetype>
				<width>120</width>
				<height>120</height>
				<depth>24</depth>
				<url>dlna_icon_120.jpg</url>
			</icon>
```
So, if it's not correct, feel free to change it ;-)

**Comment by valib** [comment]
@Sami32 this analyse only shows what is TV sending to other devices. The only way how to find out the best size is to test it. You can start with the default size and compare it with smaler size if it looks similar on the screen or the picture quality is degraded.

**Comment by Sami32** [comment]
@valib Thanks for the tip :-)
I only saw that it's look like a square and that the quality don't drop, to me.
So, i will make more tests with lower size...

**Comment by SubJunk** [comment]
Typically it's best to leave it at the defaults, or at least leave 320 as the width and customize the height if you want a different aspect ratio.

**Comment by Sami32** [comment]
@SubJunk After testing and mesuring the size of my TV compared to it's definition, my TV will not make any displaying difference with thumbnails superior to 120x90.pixels.
I guess your default values are for UHD TV ?

**Comment by SubJunk** [comment]
@Sami32 the defaults are for PS3 which has huge thumbnails. In UMS we don't have different thumbnails for each renderer, so if you browse on your TV and that creates 120x90 thumbnails, then you use a PS3, the thumbnails will look bad on PS3

**Comment by Sami32** [comment]
@SubJunk Oh i see. Thank you very much for the explanation :+1: 
If one day i will have some PlayStation i need remember that ;-D

**Comment by SubJunk** [comment]
Hopefully in the future we will have different thumbnails per renderer. Thanks for the PR :)

**Pull request merged**
