### PR TITLE
update mantine v6.0.15

### PR DESCRIPTION
**Pull request by SurfaceS**

### CODE REVIEW

**Comment by SubJunk** [comment]
This looks good. Have you tested that notifications still work? I would have expected to need to add `<Notifications />` to enable it as described here https://github.com/mantinedev/mantine/releases/tag/6.0.0

**Review by SubJunk — COMMENTED** [review]
This looks good. Have you tested that notifications still work? I would have expected to need to add `<Notifications />` to enable it as described here https://github.com/mantinedev/mantine/releases/tag/6.0.0

**Comment by SurfaceS** [comment]
> This looks good. Have you tested that notifications still work? I would have expected to need to add `<Notifications />` to enable it as described here https://github.com/mantinedev/mantine/releases/tag/6.0.0

done

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
@SurfaceS approved but can't merge until conflicts are resolved

**Pull request merged**
