### PR TITLE
Remove buggy access control from v13

### PR DESCRIPTION
**Pull request by SubJunk**
This was supposed to be reverted before the 13.7.0 release but that did not fully happen. This also adds a migration back to the old config for now

### CODE REVIEW

**Comment by SubJunk** [comment]
This isn't ready yet because I will need to update the database files and related files because the versions got bumped. I am doing that now

**Comment by SurfaceS** [comment]
@SubJunk what is the goal of this PR ?

**Comment by SubJunk** [comment]
@SurfaceS to remove the access control feature from the v13 releases. It was supposed to be reverted and introduced in v14, but I made a mistake and only reverted half of it months ago

**Comment by SubJunk** [comment]
@SurfaceS I think this is ready now. I will upload it to the forum for testing

**Pull request merged**
