### PR TITLE
add renderer configuration file for Denon AVR-X4200W

### PR DESCRIPTION
**Pull request by sc3141**
Renderer configuration for Denon AVR-X4200W.  Emphasis upon audio support.  Caveat: I'm a video format novice.

With respect to configuration variables, I have endeavored to follow the ordering of DefaultRenderer.conf

I have found that addition of row boundary lines can improve readability of supported formats:

```
#--------------------------------------------------------------------------------------------------------------
Supported = f:mpa          n:2                              s:48000     b:320000     m:audio/mpeg
#--------------------------------------------------------------------------------------------------------------
Supported = f:wav                                           s:48000                  m:audio/wav
#--------------------------------------------------------------------------------------------------------------
Supported = f:wma          n:2                              s:48000     b:192000     m:audio/x-ms-wma
#--------------------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by sc3141** [comment]
Before review, looks like I should add this renderer to the test, [testKnownHeaders](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/92096cf99f3c512b44638f5248c6022f343d2ae9/src/test/java/net/pms/configuration/RendererConfigurationTest.java#L65)

**Comment by SubJunk** [comment]
@sc3141 is this ready?

**Comment by sc3141** [comment]
@SubJunk Yes.   Not much DLNA video support listed in manual.  Possible that I've missed some, but not a reason to delay availability IMHO.

**Comment by SubJunk** [comment]
Thanks!

**Pull request merged**
