### PR TITLE
Cleans up RequestHandlerV2

### PR DESCRIPTION
**Pull request by mfulgo**
I did a bunch of refactoring in the request handler. It should be a bit easier to understand what is going on now...

It may be easier to understand/review the individual commits rather than the whole pull request at once.

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/462)

### CODE REVIEW

**Comment by SubJunk** [comment]
I'm getting this in the current master after playing a file:

WARN  13:28:20.201 [nioEventLoopGroup-3-12] ChunkedInput.isEndOfInput() failed
java.io.IOException: Stream closed
	at java.io.PushbackInputStream.ensureOpen(Unknown Source) ~[na:1.8.0_31]
	at java.io.PushbackInputStream.read(Unknown Source) ~[na:1.8.0_31]
	at io.netty.handler.stream.ChunkedStream.isEndOfInput(ChunkedStream.java:82) ~[ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:177) [ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:203) [ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:147) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ums.jar:5.0.1]
	at io.netty.handler.codec.http.HttpObjectAggregator.channelInactive(HttpObjectAggregator.java:236) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247) [ums.jar:5.0.1]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:132) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576) [ums.jar:5.0.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [ums.jar:5.0.1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [ums.jar:5.0.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [ums.jar:5.0.1]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [ums.jar:5.0.1]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]

I hope this PR will fix it, just wanted to leave this here for future reference.

**Comment by mfulgo** [comment]
I'm pretty sure that's just from some of the extra logging I'd added in a previous commit.  It should be what happens when the client terminates the connection (e.g. hitting Stop on your TV).

**Comment by mfulgo** [comment]
Nevermind - I couldn't find any place where I changed the code to log a warning.  It's probably one of two possible causes though: 1) The client has closed the channel and the server is no longer able to write to it. 2) The server goes to see if the InputStream is still open, which results in the IOException.  I had run into something like that when I was investigating the delayed-writing issue; there are definitely some strange things going on with the `WaitBufferedInputStream` and the `BufferedOutputFileImpl`.

I'll try to reproduce/look into it.

**Comment by mfulgo** [comment]
Seems like my suspicions were wrong on both counts...  I don't think we need to close the InputStream in the ChannelFutureListener any more.  When the Channel goes inactive, that happens automatically for us.  I can submit a separate PR for master to address it, or I can just add it to this one if you'd rather.

**Comment by mfulgo** [comment]
I went ahead and put it in #469. Let me know if that resolves the issue for you... or just merge it if it does.

**Comment by SubJunk** [comment]
@mfulgo just tested and it doesn't fix it, darn

**Comment by mfulgo** [comment]
Okay.  I'll do some more digging/testing tomorrow.

**Comment by SubJunk** [comment]
@mfulgo thanks :) maybe we should create a 5.1.0 or 6.0.0 branch for the netty update, given that it seems less straightforward than it appeared. What do you think?

**Comment by mfulgo** [comment]
It's up to you. I usually favor working off of master and only branching if you must go back to fix a bug (that can't wait until the next point release from master).

**Comment by SubJunk** [comment]
@mfulgo I'm okay to keep going like we are, if we can fix that ChunkedInput.isEndOfInput() error soon. Does it exist with this branch? I haven't tested this yet

**Comment by mfulgo** [comment]
@SubJunk It's hard to tell -- I've only been able to cause the error once or twice, and those times were without extra logging.  As far as I can tell, something is closing the the `InputStream`, which results in the `ChunkedWriteHandler` to give that warning.  I don't think it's causing problems, but I'd like to get rid of it nonetheless.

Are you able to reliably reproduce it?  If so, try adding a `Thread.dumpStack()` to `WaitBufferedInputStream.close()` so we can see which event closes the stream.

**Comment by SubJunk** [comment]
Yeah it happens every time I play a file. Here's what that gave:

01-27 21:25:03  ChunkedInput.isEndOfInput() failed
java.io.IOException: Stream closed
	at java.io.PushbackInputStream.ensureOpen(Unknown Source) ~[na:1.8.0_31]
	at java.io.PushbackInputStream.read(Unknown Source) ~[na:1.8.0_31]
	at io.netty.handler.stream.ChunkedStream.isEndOfInput(ChunkedStream.java:82) ~[ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:177) [ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:203) [ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:147) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ums.jar:5.0.1]
	at io.netty.handler.codec.http.HttpObjectAggregator.channelInactive(HttpObjectAggregator.java:236) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247) [ums.jar:5.0.1]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:132) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576) [ums.jar:5.0.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [ums.jar:5.0.1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [ums.jar:5.0.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [ums.jar:5.0.1]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [ums.jar:5.0.1]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]

**Comment by mfulgo** [comment]
@SubJunk That seems to be the stack trace from the warning.  What's the stack trace for the call to `close`?

If you're not running it from the command line or a terminal, you should be able to make this your `WaitBufferedInputStream.close()` method instead:
```java
	private Logger logger = LoggerFactory.getLogger(getClass());
	@Override
	public void close() throws IOException {
		logger.debug(StringUtils.join(Thread.currentThread().getStackTrace(), '\n'));
		outputStream.removeInputStream(this);
		outputStream.detachInputStream();
	}
```

**Comment by SubJunk** [comment]
Woops you're right, I posted the wrong thing.

```
[nioEventLoopGroup-3-14] java.lang.Thread.getStackTrace(Unknown Source)
net.pms.io.WaitBufferedInputStream.close(WaitBufferedInputStream.java:78)
java.io.PushbackInputStream.close(Unknown Source)
io.netty.handler.stream.ChunkedStream.close(ChunkedStream.java:93)
io.netty.handler.stream.ChunkedWriteHandler.closeInput(ChunkedWriteHandler.java:325)
io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:282)
io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:278)
io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:645)
io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:290)
io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:589)
io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:568)
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:71)
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:157)
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
java.lang.Thread.run(Unknown Source)
```

**Comment by SubJunk** [comment]
Also if the whole debug log would be useful let me know

**Comment by mfulgo** [comment]
Yeah, if you could put up the full log in the forms, that might be helpful. I may have to submit an issue to netty.

**Comment by SubJunk** [comment]
@mfulgo yikes, hope it's not a bug with netty. Here's the log package: http://www.universalmediaserver.com/forum/download/file.php?id=1876

**Comment by valib** [comment]
@SubJunk @mfulgo it seems to me as a Netty bug which is reported by several users like http://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=2927 and I also have that error.

**Comment by SharkHunter** [comment]
This is why HTTPv1 is good to have :)

**Comment by ExSport** [comment]
This is why it is good to have working HTTPv1 so we know there muste be a bug in HTTPv2 (or anything connected to it) :)

**Comment by SubJunk** [comment]
If it is a netty bug that is already reported by users then it must not be caused by the upgrade, so I guess there is no point rolling back to netty 3.x..?

**Comment by mfulgo** [comment]
I didn't see other Netty users reporting the problem.  The logs in the post @valib linked to are from Netty 3.x. (You can tell from the package name org.jboss...)  And the `ClosedChannelException`s that are logged at the TRACE level are perfectly normal -- they're just getting logged as the cause for the future's completion.

@SubJunk: Thanks for the logs. I submitted an [issue](https://github.com/netty/netty/issues/3368) with Netty.  Hopefully, they'll address it.  I'd prefer we didn't roll back to Netty 3.x...

How about this: We open a local issue about fixing the warnings and take this discussion there, since it seems to be an issue with Netty4 and not with this pull request.

> though we should make it so those errors show up in trace mode...

We *could* make them show up in trace mode, but we'd have to copy/paste the entire ChunkedWriteHandler class from Netty, just to change the log level of that message... Entirely doable, but maybe overkill.  I propose we wait to see what the Netty folks say.  If you're looking to do a release before they've fixed it, we can copy the class. Otherwise, I don't think it hurts anything.

-----
@SharkHunter, @ExSport: I disagree; there are better ways to isolate problems -- well modularized code, unit tests, continuous integration, etc, but I'll leave it at that. The V1 code isn't getting in the way right now, so I'm fine leaving it there (until it does, then we can discuss further).  =)

**Comment by valib** [comment]
@mfulgo Sorrry I didn't look on it carefully and made a wrong link. Anyway as I wrote I have the same problem as @SubJunk sent. Thanks for your effort.

**Comment by mfulgo** [comment]
@valib No problem.  As for that PR in netty, I walked through the code, and I'm not sure it will actually fix the issue...

@SubJunk I hate to have to ask this, but since you're able to easily reproduce the problem, could you build a SNAPSHOT of Netty containing the change Libor mentioned, then see if that gets rid of the warning?  (They haven't actually merged the change yet, so you'd have to cherry-pick it or add the line manually...)

**Comment by SubJunk** [comment]
@mfulgo it was merged in https://github.com/netty/netty/commit/d43442a0e08a6117116b87974003bd1051a70782 but I don't see how it's the same thing as our issue either, it seems pretty different. But yeah I'll look into building it to be sure they haven't fixed it already in that or another commit.

**Comment by SubJunk** [comment]
@mfulgo there are snapshots at http://clinker.netty.io/nexus/content/repositories/snapshots/io/netty/netty-codec-http/4.0.26.Final-SNAPSHOT/ but I'm not sure how to load them. I've tried following a bunch of instructions like these http://charlie.cu.cc/2012/06/how-add-external-libraries-maven/ but I haven't been able to make them work.

**Comment by skeptical** [comment]
@SubJunk if all you want is to test the snapshot with ums put the netty jar first in the ums java command's classpath.

**Comment by mfulgo** [comment]
@SubJunk Clone the netty repo, cd into the directory and checkout the 4.0 branch.  Then, run `mvn install` to upload 4.0.26.Final-SNAPSHOT to your local maven cache.  Update the UMS pom to use version 4.0.26.Final-SNAPSHOT.  Build UMS.

**Comment by SubJunk** [comment]
@skeptical I just tried that and still got the same error when I played a file. However I should check that the new netty version was actually being used

@mfulgo mvn install gave me a bunch of errors that I kept fixing one by one but then found the online repo which includes that possible fix :)

**Comment by SubJunk** [comment]
Okay yeah, that fix didn't help this issue.

**Comment by SubJunk** [comment]
Can someone explain why using <artifactId>netty-codec-http</artifactId> works despite us relying on other netty packages like netty-buffer in our code? In order to get this snapshot to work I had to use netty-all instead of netty-codec-http.

**Comment by mfulgo** [comment]
They're transient dependencies of netty-codec-http. If you run `mvn
dependency:tree`, you'll see them listed. We should only have dependencies
listed in our pom for things on which we directly depend... So I could see
adding one or two explicitly, but netty-all would be overkill.

**Comment by SubJunk** [comment]
@mfulgo it always worked fine for us to include them all before, but sure, it doesn't make a big difference to me now that I know to change it when testing snapshots.

**Comment by SubJunk** [comment]
@mfulgo I'm looking to do the 5.0.1 release soon since we have fixed quite a few bugs since 5.0.0, so can we silence those errors until Netty fix the bug, or should we rollback to Netty 3 in the meantime?

**Comment by SubJunk** [comment]
@mfulgo I've rolled back Netty to 3.9 in master for now. I'll be happy to re-add it when that bug is sorted out, or even when it's just not logged.

**Comment by mfulgo** [comment]
@SubJunk That sounds fine. We should maybe make a branch.

**Comment by SubJunk** [comment]
@mfulgo good idea, I made the Netty4 branch now, PR at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/483. Feel free to submit this to that branch if you want them to be joined.

**Comment by SubJunk** [comment]
Looks like the fix won't make it in time for the next Netty release, they just moved the milestone to 2 releases away

**Comment by SubJunk** [comment]
Any interest in reviving this, or was it more about Netty 4?

**Comment by mfulgo** [comment]
I believe my primary motivation was to get the code to a point at which Netty 4 could easily replace Netty 3.  Nevertheless, there's probably still some good refactoring commits in there that could be cherry-picked or manually redone on a more focused PR.

**Comment by SubJunk** [comment]
Yeah that would be cool, looks like good stuff in here

**Comment by valib** [comment]
Changes included in  10f4d11. Thanks @mfulgo.

**Pull request closed without merging**
