### PR TITLE
Update vlc recognition 2

### PR DESCRIPTION
**Pull request by valib**
@SubJunk sorry but Regex is not my cup of cake. This should be the final version.

### CODE REVIEW

**Comment by SubJunk** [comment]
Maybe you could add some test cases for those 5 user-agent strings?

**Comment by valib** [comment]
@SubJunk I will try

**Comment by valib** [comment]
@SubJunk done

**Review by SubJunk — APPROVED** [review]

**Comment by valib** [comment]
@SubJunk I contributed to the VLC forum https://forum.videolan.org/viewtopic.php?f=18&t=155534 and hope they will change it.

**Pull request merged**
