### PR TITLE
Fix potential errors of video stream ffmpegvideo

### PR DESCRIPTION
**Pull request by onon765trb**
This PR fixes potential errors. Not used options can be a cause for errors. Extra options can result in decrease in quality or behavior users unexpect. Needs to consider ffmpeg often changes the behavior of options.

### CODE REVIEW

**Comment by SubJunk** [comment]
@onon765trb these changes look good but it is failing to find the `renderer` variable:

```
[ERROR] /home/travis/build/UniversalMediaServer/UniversalMediaServer/src/main/java/net/pms/encoders/FFMpegVideo.java:[436,46] cannot find symbol
  symbol:   variable renderer
  location: class net.pms.encoders.FFMpegVideo
```

**Comment by onon765trb** [comment]
@SubJunk The fixes are completed to merge the new master.

**Comment by onon765trb** [comment]
I close this PR, once.

**Comment by SubJunk** [comment]
Why?

**Comment by SubJunk** [comment]
Thanks for your contributions @onon765trb I wish you good luck at DMS

**Pull request closed without merging**
