### PR TITLE
Update the H.264 level checking

### PR DESCRIPTION
**Pull request by valib**
This is a quick fix for the issue #1417.

### CODE REVIEW

**Comment by Nadahar** [comment]
@valib Why make a "quick fix" for this when I made an implementation for supporting different levels a long time ago but left it since there was no response?

**Comment by valib** [comment]
@Nadahar maybe I missed something but in which PR you made this implementation?

**Comment by Nadahar** [comment]
@valib I don't remember now, I think it was one of @Sami32's PRs. I'll see if I can find it again.

**Comment by Nadahar** [comment]
@valib It was in #1242

**Comment by SubJunk** [comment]
I agree and have started to resurrect https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1242/files

**Pull request closed without merging**
