### PR TITLE
Extract subs for FFmpeg

### PR DESCRIPTION
**Pull request by SubJunk**
Closes https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2533
Fixes https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1123
Fixes https://github.com/UniversalMediaServer/UniversalMediaServer/issues/1721

### CODE REVIEW

**Comment by SubJunk** [comment]
I tested it last night and it seems to work - videos that timeout with internal subtitles burning via ffmpeg in master work in this branch.
One thing it still needs is to add the cleanup step so that subtitles for removed files get deleted

**Comment by SubJunk** [comment]
One note for testing is that FFmpeg caches the internal subtitles after the first run, so it can be annoying to reproduce - the bug this fixes only happens once per file. So if you do any testing on it you will likely need to find two similar files (I use two episodes of the same anime), verify the bug on one episode in master, then verify it is fixed on the other episode in this branch.

**Comment by SubJunk** [comment]
There also seems to be a memory leak in this branch, which I think likely exposes an existing memory leak. I'll look into it

**Comment by valib** [comment]
@SubJunk why we use linux-focal for testing? Linux is only 2,38% of the OS used by users. It seems that in the linux-focal they made some changes that destroyed the Java implementation.

**Comment by SubJunk** [comment]
I'm not sure why it's failing. It seems like some stuck cache problem like usual, because adding that logging cleared it in that branch. But then the problem came back.
Maybe it's not important to test two versions of Linux though.

**Comment by valib** [comment]
@SubJunk agree that testing Linux only in the most importand implementation could solve this problem.

**Comment by SubJunk** [comment]
An update on the memory leak is that I can't reproduce it but I think it is unrelated to this - there was a stuck transcoding process that was taking up memory, and then I was also transcoding another thing, and extracting subtitles. So the real bug is the stuck transcoding process which I have seen in other branches. We could also try increasing the maximum memory limit on supported Windows systems, given that it is at 1280 now while my web browser is using like 5GB+

**Comment by valib** [comment]
@SubJunk for me this implementation is not acceptable. Please try to delete the database, disable scanning folders and start browsing without starting scanning folders. For me it is extremly slow and works only in the web interface where there is no timeout like in renderers. In the web interface some media has no thumbnails because of timing.

**Comment by SubJunk** [comment]
Yeah I did the comparison and you're right, this is slower. I guess even when FFmpeg runs non-blocking, it still makes the CPU go slower for other things.

Maybe we can do some manual locking where this new extraction thread is not allowed to run while a browse request is running

**Comment by SubJunk** [comment]
I will try to make a lighter implementation of the extraction that only extracts the original format instead of converting to ASS, and will test again

**Comment by Nadahar** [comment]
I'm pretty sure that CPU isn't the bottleneck here - IO is. I recently tested extracting subtitles from a file that is on a network share via a WiFi (n) connection, and while I didn't measure the time, it was in the range of 20-30 minutes.

I don't know how FFmpeg does it internally, but I suspect that in many containers, the "subtitles chunks" are spread throughout the file (to supply them at an appropriate time for the decoder) so that the whole file actually has to be scanned. If the location of the subtitles chunks aren't "indexed" in some way, there's no way to jump to their location. Also, not all types of I/O allows "jumping"/skipping, so the file has to be read sequentially.

The file I did the test on was a 6.5GB MKV with embedded SRT. Doing it on a local disk or even better, SSD, would obviously make it much quicker, but it could still be enough to pretty much saturate I/O for a little while. This will make all other "competing" I/O very slow. It's not possible as far as I know to give I/O "lower priority" like you can with CPU time.

**Comment by SubJunk** [comment]
Yeah you're likely right. There could still be some manual locking solution I guess, where we make our known heavy IO methods use the lock. I'll try

**Comment by SubJunk** [comment]
I did that locking approach and it seems to work. Can you test @valib ?

One note for testing is that for me, hard drive (or something outside of UMS) caching seems to play a big role: if I let some subtitles get extracted between tests, then this branch is slower than master, even though the extraction is started after browsing has completed. However this test where we delete the database each time is only useful when we assume this is the user's first time browsing that folder, because the next times will be cached in our database on either branch, and those subsequent browse requests take 1 second on both branches for me no matter what.
So for testing, to rule out hard drive caching, it is important to close UMS as soon as the browse request completes; before the extraction process starts.
I hope that makes sense.

**Comment by SubJunk** [comment]
Also CI is failing because our SVN server is down, I'm working on it

**Comment by SubJunk** [comment]
SVN is fixed

**Comment by Nadahar** [comment]
@SubJunk If you want to test without the caching interfering, simply create a network share on another computer and put the media there. I don't think there is any caching on network drives.

**Comment by SubJunk** [comment]
@Nadahar that's a good idea. I have tested it anyway and I am satisfied that browsing is the same speed as it is in master. So now just waiting for @valib to comment

**Comment by SubJunk** [comment]
Actually I think there is another enhancement I'll do before this is ready - I will restore the previous functionality for when the subtitles are not extracted for a file that is being played yet. Because in that case, this branch will be worse for a user currently. I will comment here when that change is done

**Comment by SubJunk** [comment]
@valib this is ready for re-review
I recommend using the "Hide whitespace changes" functionality in GitHub because most of the line changes are just indentation

image

**Comment by valib** [comment]
@SubJunk I am now on holiday. I will test it when I return home.

**Comment by SubJunk** [comment]
@valib that's great, enjoy your holiday!

**Comment by valib** [comment]
Balaton. Hungary

**Comment by SubJunk** [comment]
@valib fixed this blocking the shutdown process

**Comment by valib** [comment]
@SubJunk can you check if I merged the master correctly? Than this PR could be merged.

**Comment by SubJunk** [comment]
This is a good idea but needed a better implementation, possibly a separate subtitle extraction process in the future. It was too flaky this way

**Pull request closed without merging**
