### PR TITLE
Fix master test

### PR DESCRIPTION
**Pull request by Nadahar**
Do **NOT** merge this PR, it's a test.

---
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/1257)

### CODE REVIEW

**Comment by Nadahar** [comment]
@UniversalMediaServer/developers If some of you're online, I need you to approve this PR.

**Comment by Nadahar** [comment]
@Sami32 Your "stage.diff" was merged into master with #1148

**Comment by Nadahar** [comment]
Ok, the attempt didn't work, only @SubJunk can fix it.

**Comment by Sami32** [comment]
I know that. While amending it for remowing a trainling space and changing the line ending as asked before merge.
This has been a "side effect"

**Comment by Nadahar** [comment]
@Sami32 You can't merge things with such "side effects" - but I guess you discovered it after the fact..?

In any case, it's easily resolved if @SubJunk does as I've written in #1148. In the meanwhile, nothing more must be merged.

**Comment by Sami32** [comment]
Of course i discovered that after.
I told you, and i added a correctif in an other PR, but i don't know if that can work that way.

I suspect that this empty file was added while amending, because i forgotten that i was in the middle of a rebase while amending.

**Comment by Nadahar** [comment]
@Sami32 I didn't understand that it was in master - I though you only had gotten this file inserted into a PR. But I understand now. I is possible to remove it again in another PR, a "reversal", but I prefer simply undoing errors like this so we don't have to have them in the history.

**Comment by Sami32** [comment]
As you want.

Can i delete this branch now ?

**Comment by Nadahar** [comment]
@Sami32 No, this has to stay until @SubJunk has done the reset/force push.

**Pull request closed without merging**
