### PR TITLE
Merge pull request #8 from UniversalMediaServer/master

### PR DESCRIPTION
**Pull request by ler0y**
Sync

### CODE REVIEW

**Comment by ler0y** [comment]
oeps

**Comment by Nadahar** [comment]
@ler0y Just a tip: You don't have to use pull requests to update your fork (I'm guessing that was what you were about to do). When I want to update my fork, or any branch in it, I make sure to check out to the correct repo/branch. Once that's done, make sure your git bash is in the root folder of the repo and write: ```git fetch UniversalMediaServer``` (given that that's your remote name, but I'm guessing it is as github does this). Once the fetch is done, write: ```git merge UniversalMediaServer/master``` (or another branch it that's what you want) and your fork is updated with the latest. Then you can just push that as normal your github fork, and they're in sync. If there are merge conflicts between your local changes and UniversalMediaServer/master, you will have to solve them and commit before pushing.

If you don't care about preserving the local changes, and effectively want a new "fresh" copy of UniversalMediaServer/master, you do the fetch like above but instead of the merge you do: ```git reset --hard UniversalMediaServer/master```. Then you get a fresh copy without any merge commits to get there. You probaly have to force push when pushing to your github fork in this case.

**Comment by ler0y** [comment]
@Nadahar Thanks for this info!

Next time l will try to use git bash again, wich is probably the best way to synchronize with newest UMS.
In past I tried to use git bash with mixed results. (Because of my poor knowledge of git)
I then found a stabile/easy way to do this with pull requests from UMS to my master brance.

Till i made this mistake:)

**Comment by Nadahar** [comment]
@ler0y If you're on Windows, I'd recommend TortoiseGit. It's simply a GUI frontend for the bash, so you don't have to remember all these commands. The great thing, since it's only a frontend actually running git bash commands for you, is that you can mix without problems. Things that's easier to do from the command line and you do often, you remember, and the rest you just use the GUI for :wink:

**Comment by ler0y** [comment]
@Nadal Any idea what goes wrong here if I try "git fetch UniversalMediaServer" in Git Bash?
niet kunnen fetchen

**Comment by Nadahar** [comment]
@ler0y I assume you meant me, Nadahar, not Nadal?

Assuming that you're placed in the right folder (the repository root, check with ```pwd```) that must mean that it's called something else (or doesn't exist at all) in your references. 

Use ```git show-ref``` to list your references.

**Comment by Nadahar** [comment]
If you're repo is missing the remote, write:
```bash
git remote add upstream https://github.com/UniversalMediaServer/UniversalMediaServer.git
```
and you will add the remote ```upstream```. You could also call it ```UniversalMediaServer``` like github did automaticly for me, but it's more writing every time you want to fetch or merge :wink: 

If you add "upstream", fetch is simply:
```bash
git fetch upstream
```
and merge is:
```bash
git merge upstream/master
```
and reset to upstream master is:
```bash
git reset --hard upstream/master
```

**Comment by ler0y** [comment]
@Nadahar Thanks for all this info!  And sorry about misnaming .oops..
I now see my typo "UniversalMediaserver" with the `git remote -v` command :)
mistake
Now I need to correct this i guess.

Should i now just write `git remote add upstream https://github.com/UniversalMediaServer/UniversalMediaServer.git`?

**Comment by Nadahar** [comment]
@ler0y I don't know if that will work, but you can just write:
```bash
git remote rm upstream
```
...and then add again.

**Comment by ler0y** [comment]
@Nadahar Hurray: https://github.com/ler0y/UniversalMediaServer/commit/69f3610f2ed09736f0ce44c2c64ccf1bc632a26d
Thanks alot :)

**Comment by Nadahar** [comment]
Nice :+1:

**Comment by SubJunk** [comment]
Yup, I use and love TortoiseGit!

**Comment by Nadahar** [comment]
Yes, it'd be a struggle without TortoiseGit - too much syntax formatting to remember.

**Pull request closed without merging**
