### PR TITLE
Update the subtitles test

### PR DESCRIPTION
**Pull request by valib**

### CODE REVIEW

**Comment by Sami32** [comment]
That's strange, when i approve a commit the whole PR get approved.
Is a more graduate reviewing possible with this Github interface as it's now ?

**Comment by Nadahar** [comment]
@Sami32 No, you can only approve the whole PR, and we can't approve anything before the PR in completed (or, you in fact "pre-approve" any future commits made to the PR).

Reviewable is so much better in that sense, you approve on a per-commit level (although, you can approve several commits at once). Any additional changes needs further approval. I wish we could just turn off GitHub's review functionality and go back to Reviewable.

**Comment by valib** [comment]
@Nadahar so is that PR mergeable?

**Comment by valib** [comment]
@Sami32 @Nadahar thanks.

**Pull request merged**
