### PR TITLE
Use network interface names instead of their hardware description

### PR DESCRIPTION
**Pull request by valib**
An attempt to make enhancement asked in the issue  #2074

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib do you want me to review this or is it still in progress?

**Comment by SubJunk** [comment]
The user has reported it is working for them, and I have verified it works for me when I switch between network interfaces.

However it would be nice if it could be backwards-compatible because if users already have a network interface selected, this clears that selection. Otherwise we may have some confused users

**Comment by valib** [comment]
@SubJunk done

**Comment by valib** [comment]
@SubJunk I think now it is ready to merge

**Comment by SubJunk** [comment]
Great, I have retested it with an old saved option and it retains that option, so I'll merge

**Pull request merged**
