### PR TITLE
Feature/api 3/library scan

### PR DESCRIPTION
**Pull request by ik666**
This PR scans the media library after startup and adds discovered resources.

This is checked for audio files:

If you start with an empty database. The virtual MediaLibrary - containing "video", "audio" and "photo" folders - is empty. Stepping into "Audio folder" you'll discover that all sub-folders ("genre", "artist", etc ...) are empty. Reason: Data is lazy initialized during the actual "browse request" of a control point. This means right now, you have to "click through" every physical library folder with your UPnP client, folder before all resources are being populated into "Audiotracks" table. 

This PR fills (at least) the Audiotrack table at startup (scan process). 

To bad, that I couldn't fiddle apart the changes with the other PR (musicbrainz support) ... Give me a hint, if I should create a clean branch from the current api-3 branch, just in case, you do not plan to merge the other PR.

### CODE REVIEW

**Comment by valib** [comment]
@ik666 the library scan is already implemented in the UMS. What is the benefit of this PR agains the current implementation?

**Comment by SubJunk** [comment]
I'm also confused about what is being added here - we already populate audio files into the database during the startup scan. What's different about this?

**Comment by valib** [comment]
@SubJunk also there is a problem with the MusicBrainz. Here is the respond of it `'00:43:12 ERROR Could not lookup audio cover for "I Need Your Love (www.freshmp3": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Get Lucky (Official Audio) ft. Pharrell Williams": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Do You Know (Ping Pong Song)": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Tired of Being Sorry": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Proper Education (Radio Edit)": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "What I Want [UK Radio Edit]": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Flashback": musicbrainz.org replied with status code 503
00:43:13 ERROR Could not lookup audio cover for "Call the Shots": musicbrainz.org replied with status code 503
00:43:13 ERROR Could not lookup audio cover for "The World Is Outside": musicbrainz.org replied with status code 503
00:43:13 ERROR Could not lookup audio cover for "Pitbull Feat Chris Brown - International Love": musicbrainz.org replied with status code 503
00:43:13 ERROR Could not lookup audio cover for "Impossible": musicbrainz.org replied with status code 503
00:43:13 ERROR Could not lookup audio cover for "Jason Derulo "The Other Side" Lyrics": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Acapella": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Nothing In My Way": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "With Every Heartbeat": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Love Is Wicked": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Dance With Somebody": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Rood": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Binnen": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Wake Up Call": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Didi": musicbrainz.org replied with status code 503
00:43:14 ERROR Could not lookup audio cover for "Living Darfur": musicbrainz.org replied with status code 503
00:43:15 ERROR Could not lookup audio cover for "Beautiful Monster": musicbrainz.org replied with status code 503
00:43:15 ERROR Could not lookup audio cover for "Truelove": musicbrainz.org replied with status code 503
00:43:15 ERROR Could not lookup audio cover for "Jai Ho": musicbrainz.org replied with status code 503
00:43:15 ERROR Could not lookup audio cover for "Don't Stop The Music [Album Version]": musicbrainz.org replied with status code 503
00:43:15 ERROR Could not lookup audio cover for "Umbrella": musicbrainz.org replied with status code 503
00:43:15 ERROR Could not lookup audio cover for "Fire with Fire (Digital Dog Radio Edit)": musicbrainz.org replied with status code 503
00:43:15 ERROR Could not lookup audio cover for "Amazing": musicbrainz.org replied with status code 503
00:43:16 ERROR Could not lookup audio cover for "She's Madonna": musicbrainz.org replied with status code 503
00:43:16 ERROR Could not lookup audio cover for "Entends-tu le Monde?": musicbrainz.org replied with status code 503
00:43:16 ERROR Could not lookup audio cover for "Eyes of a stranger": musicbrainz.org replied with status code 503
00:43:16 ERROR Could not lookup audio cover for "Automatic": musicbrainz.org replied with status code 503
00:43:16 ERROR Could not lookup audio cover for "Finish Line": musicbrainz.org replied with status code 503
00:43:16 ERROR Could not lookup audio cover for "Rise Up (Original Radio Edit)": musicbrainz.org replied with status code 503
`

**Comment by valib** [comment]
@SubJunk we have a problem with the MusicBrainz because the respond for requesting covers is `00:43:12 ERROR Could not lookup audio cover for "I Need Your Love (www.freshmp3": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Get Lucky (Official Audio) ft. Pharrell Williams": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Do You Know (Ping Pong Song)": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Tired of Being Sorry": musicbrainz.org replied with status code 503
00:43:12 ERROR Could not lookup audio cover for "Proper Education (Radio Edit)": musicbrainz.org replied with status code 503 t
`

It seems to me that we need to fix the implementation to avoid this.

**Comment by SubJunk** [comment]
Assuming that the HTTP status code is correct, 503 means the service is unavailable, maybe because their servers are under heavy load or maintenance. I would expect a different status code if it was something we could help, but maybe I'm wrong.
We could try sending a message to their support team or look at their docs?

**Comment by SubJunk** [comment]
If that error is happening frequently, one possible solution is to extend our API repository to cache MB requests like we do for OpenSubtitles, so any requests to MB go through our API. That way we only need each unique request to MB to succeed once.

**Comment by ik666** [comment]
On my system, the current UMS api-3 branch doesn't populate any music tracks into the "Audiotracks" table. After the scan finishes, the table is empty. The relevant changes are only those 3 files:

- MapFile
- RealFile
- ProcessWrapper

I'd like to share my thoughts with you, from what I've seen/debugged :

**Errors while scanning**

ProcessWrapper

- If the Process that is being started (around line 188) has any errors, the scan stops. In my case some libraries were not available (ffmpeg).

- If getResults (around line 360-375) is called without instantiated stdErrConsumer, the scan stops (probably results from the changes below).

** file not resolved **

I think, RealFile.resolve() has to be called for inserting entries into the Audiotracks table. In my case the scan() process finished without ever entering "resolve()" or alternatively hitting the "insert into audiotrack ..." SQL statement. 

From what I've analysed:

The MapFile class analyses children, but "resolve()" is never called for the child in case of a real file (music track).

Since the "resolve()" method is doing the actual insert into the Audiotracks table, I have 
- changed MapFile (around line 256) to call RealFile with the current file and parent folder as parameter for having all data available to resolve() the RealFile.
- added a new constructor to RealFile, which calls "resolve()". 

With this changes my "Audiotracks" table was populated, without clicking through the physical library structure.

**Comment by valib** [comment]
@SubJunk I think that the problem is that the UMS is reguesting more than is the limit. See https://musicbrainz.org/doc/MusicBrainz_API/Rate_Limiting
They allow through (on average) 50 requests per second and the rest is denied with a 503 Service Unavailable error.

**Comment by ik666** [comment]
ok, I see ... maybe the problem lies somewhere else and if everything is running as intended, the Audiotracks table would be filled after initial scan. 

However, I would propose to lookup coverart and other tags (musicbrainz trackid and releaseid) from inside the audio file if available, before requesting those data from musicbrainz. I believe most audio enthusiast have already (manually) tagged their library with (from a personal perspective correct) album and track information.

@SubJunk @valib : Actually, my original intention is to implement a UPnP CDS SearchHandler. I'd try to copy the behaviour of [Minimserver](https://minimserver.com/).  I've seen a search fork in another repo, but it never made it back into UMS. Do you think this would be of any interest for you if I'd give it a try (within the api-3 branch)?

**Comment by Nadahar** [comment]
> However, I would propose to lookup coverart and other tags (musicbrainz trackid and releaseid) from inside the audio file if available, before requesting those data from musicbrainz.

As far as I can remember, that's how I made it back in the days. I don't remember what fields where available in the tags (JAudioTagger is used to extract tag info, so it depends on what JAudioTagger supports), but lookups should only be done if this information couldn't be determined from the tag. It might be some room for refinement, as I didn't really have any viable sample files that would tell me how this is "usually done", but the basic functionality you're after should already be there.

**Comment by valib** [comment]
@Nadahar thanks for the comment I agree with you.

**Comment by SubJunk** [comment]
@ik666 I'm not really sure what `UPnP CDS SearchHandler` is but I welcome features and the server link you sent seems good. I'm very happy for you to implement new handlers into UMS. That can make us closer to "Universal" :)

**Pull request closed without merging**
