### PR TITLE
3004 web settings console

### PR DESCRIPTION
**Pull request by SurfaceS**
Home page for react GUI

Show found renderers as home page

remove restart server from menu (dangerous on mobile without confirm action)
added server activity on menu
added possibility to restart the server with confirm
added possibility to restart the app with confirm / permissions
added possibility to shutdown the app with confirm / permissions
added logs + debug packer page
quit moved away from swing gui (don't understand why it was there at first).
quit added to PMS, including old gui quit actions under the shutdown hook.

### CODE REVIEW

**Comment by SubJunk** [comment]
@SurfaceS you're a machine! 🥇

**Comment by SubJunk** [comment]
@SurfaceS is this ready for review?

**Comment by SurfaceS** [comment]
I think so

**Comment by SubJunk** [comment]
This looks great. It looks like renderer automatic images might not be working:

image

image

**Comment by SurfaceS** [comment]
should be fixed + added stuff

**Comment by SubJunk** [comment]
I like the changes. The renderer image still isn't working for me
image

**Pull request closed without merging**
