### PR TITLE
Added a back button to the web interface

### PR DESCRIPTION
**Pull request by SubJunk**
This is a pretty simple change so I'll merge it soon if there are no objections

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/825)

### CODE REVIEW

**Comment by Nadahar** [comment]
The missing back/up button has been my biggest annoyance using the web interface :+1: 

Is using browser history "safe" for this? Will this always bring you up one folder (that's what I assume the back button is for)?

Given that the above is no worry: :lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/resources/i18n/messages.properties, line 583 \[r1\]](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/825#-K9pdzfAruTvJMYi7IyY:-K9pdzfBn6KZdQLGLKc9:2011363119) ([raw file](https://github.com/universalmediaserver/universalmediaserver/blob/2cf9c7e65e71e2edb2ff93b5288345ff4c12b23e/src/main/resources/i18n/messages.properties#L583)):*
Remember to do a crowdin:push after this is merged since ```message.properties``` has been changed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/825#-:-K9pchE3UIr_UtvAxoGi:-1945340527)*

**Comment by valib** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/825)*

**Comment by valib** [comment]
:+1:

**Comment by SubJunk** [comment]
Yeah it'll always go to the previous folder unless the user has been manually typing in the URL

**Pull request merged**
