### PR TITLE
Improve raw image thumbnails

### PR DESCRIPTION
**Pull request by valib**
to fix problems reported in https://github.com/UniversalMediaServer/UniversalMediaServer/issues/554
The thumbnail size is the standard 320 x 180 pixels not the original image size.

### CODE REVIEW

**Comment by valib** [comment]
@ExSport can you test it ?

**Comment by ExSport** [comment]
Thx. Will try today :+1:

**Comment by ExSport** [comment]
@valib Thx for pull but it doesn't help. UMS still creates dcraw pipe which is never closed and UMS stops scanning. Force closing process unfreeze UMS scan by loading next file (if it is again cr2 it freezes again). Sample to test: https://copy.com/AQCIQ4S7A3MA96yH

**Comment by valib** [comment]
@ExSport I don't know what is wrong but your sample works fine for me.

**Comment by ExSport** [comment]
@Valib Maybe I posted wrong file or compiled pull wrongly? How have you tested it? You have to click on magnifying icon to scan shared folders. This way it stops scanning because dcraw.exe process will stay running on cr2 files. I have to test manually browsing the file if behavior will differ.

**Comment by valib** [comment]
@ExSport tested by manually browsing.

**Comment by ExSport** [comment]
@Valib So please test initial share scanning from UMS Gui. Thx

**Comment by valib** [comment]
@ExSport tested and there is no problem.

**Comment by valib** [comment]
@SubJunk I think that this commit should me merged after testing because it fix the the thumbnail generation of the RAW images.

**Comment by ExSport** [comment]
@Valib @SubJunk I must recompile it and retest because as logs show, on 64bit Windows it stops scanning files, scanning process freezes. So maybe 64bit specific problem or I am lost:-) Will also test on another PC, unfortunately I don't have any 32bit. Thx for this pull :+1

**Comment by ExSport** [comment]
@valib Sorry for wrong file. Check another one: https://copy.com/PpErMaLCSOGUGpWy
I retested all files separately and about 1/5 of cr2 file from tested folder reproduces bug, others not. IMG_1155.JPG is the one which stops scanning.

**Comment by valib** [comment]
@ExSport yes this sample image IMG_1155.JPG causes the same bug for me. The file must be corrupted but I can open it in Zoner Photo Studio without any problem.

**Comment by valib** [comment]
@ExSport to avoid to be UMS stacked we can start a timer and after some time e.g. 10 seconds kill the dcrawMS.exe process.

**Comment by ExSport** [comment]
@valib As I have more similar files but they are OK when displayed and also without artifacts, it doesn't seem files are corrupted. So timer will be excellent :+1: 
Thx!

**Comment by ExSport** [comment]
Also dcrawms.exe seems to work OK from command line with this file. Maybe only pipe get corrupt.

**Comment by valib** [comment]
@ExSport thanks for your comment. It makes me to think about the problem from the different point of view and I founded the problem. :+1:

**Pull request merged**
