### PR TITLE
Fix various macOS bugs

### PR DESCRIPTION
**Pull request by SubJunk**

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib please review this when you get a chance, we have quite a few users experiencing the file chooser bug

**Comment by SubJunk** [comment]
Fix confirmed on the forum https://www.universalmediaserver.com/forum/viewtopic.php?p=37227

**Comment by onon765trb** [comment]
@SubJunk I did some tests. Minimizing is hidden. Good!

But specifying share folders is not good on wizard. To specify share folders, a few times selecting folders is forced.
Further, home folder `/Users/x` is selected automatically. This is not good on security or the burden of PC.

If sellecting automatically, I think that `/Users/x/Movies`, `/Users/x/Music` or `/Users/x/Pictures` had better been done.

**Comment by SubJunk** [comment]
@onon765trb thanks for your review of this. I'm not sure what you mean by:

> But specifying share folders is not good on wizard. To specify share folders, a few times selecting folders is forced.

Can you please explain?

I agree that we should have better defaults too. Let's make another issue/PR for that

**Comment by onon765trb** [comment]
@SubJunk 

> I made an issue for that at #1572

Good issue!

> Can you please explain?

Select button does not became valid after selecting a folder at the first time.

**Comment by SubJunk** [comment]
Hmm it works for me. Which version of Java?

**Pull request merged**
