### PR TITLE
Remove duplicate information from prettified filenames in Media Library

### LINKED ISSUE #1582: Remove duplicate information from prettified filenames in Media Library
Currently it is like:

`Media Library > TV Shows > The Simpsons > Season 1 > The Simpsons - 101 - Episode Name`

It should be like:

`Media Library > TV Shows > The Simpsons > Season 1 > 1 - Episode Name`

It needs to do this only in that context though, not in the other folders

### PR DESCRIPTION
**Pull request by SubJunk**
Closes #1582

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib can you please review/merge this?

**Comment by valib** [comment]
@SubJunk there is a problem with Travis (see details)

**Comment by SubJunk** [comment]
It looks like the problem is that Travis only supports OpenJDK 9+ now

**Comment by SubJunk** [comment]
I'm working on a fix in another branch

**Comment by SubJunk** [comment]
Working on it at https://github.com/UniversalMediaServer/UniversalMediaServer/pull/1807

**Comment by SubJunk** [comment]
It's passing now @valib

**Pull request merged**
