### PR TITLE
Bravia EX cropping modifications

### PR DESCRIPTION
**Pull request by Sami32**
Following this UMS user guideline:
http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=9311

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 There's been an [update in the thread](http://www.universalmediaserver.com/forum/viewtopic.php?f=5&t=9311#p30342), so you should probably update the PR as well.

**Comment by Sami32** [comment]
That's nice to know that you're reading the forum ;)
Thanks.

**Comment by Nadahar** [comment]
@Sami32 I don't, but since I posted in that thread I got a notification.

**Comment by Nadahar** [comment]
This is something that I can't evaluate, I think @SubJunk will have to review this one.

**Comment by Sami32** [comment]
@SubJunk Thank you for your review and approval :+1:

**Pull request merged**
