### PR TITLE
Updates MusicBrainzIDs in AudioTracks table on initial scan.

### PR DESCRIPTION
**Pull request by ik666**
This is a follow up, to my last MusicBrainzID PR. 

Since I had some issues with "my" initial scan process (because of missing MediaInfo-Lib on my system) I've missed to code some update stuff.

The MBID_TRACK and MBID_RECORD columns of the AUDIOTRACKS table will now be filled after the initial scan has finished.

### CODE REVIEW

**Comment by ik666** [comment]
Ups ... looks like for linux-bionic the configuration is null ??!!

`java.lang.NullPointerException: Cannot invoke "net.pms.configuration.PmsConfiguration.isUseSymlinksTargetFile()" because "this.configuration" is null`

Is this something I can fix, or should it be fixed on the build pipeline ?!

**Comment by SubJunk** [comment]
@ik666 we have a fix pending for this, sorry for the trouble

**Comment by SubJunk** [comment]
It’s fixed now if you sync with master

**Comment by ik666** [comment]
Done.

**Review by SubJunk — APPROVED** [review]

**Comment by SubJunk** [comment]
@ik666 thanks!

**Comment by ik666** [comment]
You're welcome ...

**Pull request merged**
