### PR TITLE
Attempt to fix AIFF issue

### PR DESCRIPTION
**Pull request by Sami32**
Reported many times by MAC users on the forum.
Log of one of the user: http://www.universalmediaserver.com/forum/download/file.php?id=3616

**EDIT**: 
[test.aiff.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/716832/test.aiff.txt)

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 I've already made a PR with AIFF and several other formats a long time ago: #735.

**Comment by valib** [comment]
@Nadahar your PR #735 is worth to be merged but you personally stated that it is not ready to be merged and because you not managed it since that time that branch has conflicts that must be resolved.

**Comment by Nadahar** [comment]
@valib Yes I know, I had to many things going on, and I never got the answer to the question I had. There was a test that failed, and I wanted to understand why that test was as it was in the first place, not just change it.

Resolving the conflicts shouldn't be that much of a problem.

**Comment by Sami32** [comment]
@Nadahar **What that mean ?** Every time i push a PR with format upgrade you throw me that PR...

Do i need to stop any format upgrade until you finished your PR ? just to be clear one time for all on that...

As i already commented, i do not agree on non standard audio/3ga MIME type or audio/dsf...

**Comment by Nadahar** [comment]
@Sami32 I just don't think it's worth making the same things several times - perhaps it would be smarter to fix the problems in #735 than to make them all again?

**Comment by Sami32** [comment]
@Nadahar I tried with your pitch issue, but we didn't agree/understertood each other, so i solved mine and give up on your as i was not willing arguing or have word for that.

That's said i could have a deeper check on your PR on other point.

**Comment by Nadahar** [comment]
@Sami32 I think I have a pretty good idea what causes the pitch issue, and now I know that it's not really related to #735 so I think we can leave that unresolved for now. As I see it it's because of UMS' lack of DLNA compliance, specifically that the media format profiles is more or less completely ignored. Because of this, some renderers (like mine) will be confused a play back the binary as if had different properties, probably because it falls back to some defaults when no actual information is available.

**Comment by Sami32** [comment]
@nadahar As i already told, for me it's just because the channels are not specified while sendind the protocolInfo to the renderer. Meaning an incorrect DLNA implementation, IMO.

**Comment by Sami32** [comment]
@Nadahar Thank you very much, as i'm not yet able to do that...

Did you deleted aifc extension ? i don't see it anymore.

**Comment by Nadahar** [comment]
@Sami32 Can you merge it - so I can rebase #735 on top of it?

**Comment by Nadahar** [comment]
@Sami32 No, I didn't delete it - it wasn't there - but I can add that in #735.

**Comment by Sami32** [comment]
@Nadahar I just added it.

Strange because i remember did it...

**Comment by Nadahar** [comment]
@Sami32 :( That means I have to rebase again, and do the Travis builds again... which fails because of Imaging so that I have to restart them several times...

That's why I wanted to fix that in #735.

**Comment by Sami32** [comment]
@Nadahar You can merge it yourself, you will faster than me as i need the Github interface for now...
imageutil give issue many time so i'm stuck.

**Comment by Sami32** [comment]
Sorry about that but you first asked me to merge and after answer my
question about AIFC...

I'm only a newbie as you know...

2017-01-21 15:49 GMT+01:00 Nadar <notifications@github.com>:

**Comment by Nadahar** [comment]
@Sami32 We cross-posted. Your post showed up after I wrote mine, even though mine came in after yours...

**Pull request merged**
