### PR TITLE
Additional fourcc support for h263 codec

### PR DESCRIPTION
**Pull request by ler0y**
Additional fourcc support for h263 codec

### CODE REVIEW

**Comment by SubJunk** [comment]
@ler0y are these values all being given by the current version of MediaInfo?

**Comment by ler0y** [comment]
I am sure about h263, u263, and s263.
The additional 4cc's I have found here:
http://wiki.multimedia.cx/index.php?title=H.263

**Comment by SubJunk** [comment]
@ler0y I'd be interested to see a file that says u263 or s263, can you upload one? I don't think it's much good to add support for the other ones, since there's no indication that MediaInfo would identify them like that so far

**Comment by ler0y** [comment]
MediaInfo text output for these files posted here:
http://www.universalmediaserver.com/forum/viewtopic.php?f=14&t=1656&p=15466#p15466

**Comment by ler0y** [comment]
s263 samples can be downloaded here:
http://download.wavetlan.com/SVV/Media/HTTP/3GP/Media-Convert/

**Comment by SubJunk** [comment]
@ler0y cool. I'll merge if you can change the equals back to startsWith. There may be some reason it's like that

**Comment by SubJunk** [comment]
@ler0y I just confirmed that sometimes it's returned as "h264 (Profile)" so it needs to be startsWith

**Comment by ler0y** [comment]
@SubJunk Done :)

**Comment by SubJunk** [comment]
@ler0y thanks!

**Pull request merged**
