### PR TITLE
OpenSubtitles Hash to Cache feature

### PR DESCRIPTION
**Pull request by CodeLover254**
In this pull request, I submit the caching feature for OpenSubtitles hashes in order to minimize latency and resolve issue #2618. The caching feature leverages the use of H2 database.

### CODE REVIEW

**Comment by SubJunk** [comment]
@CodeLover254 great, thanks! You did a lot here and it looks good. I really like that you added tests for it! 🥇 

I wonder if it would be better to add it as a column to the existing FILES table, instead of making a new table. The hash is for the file so that makes sense I think. Then you can use the existing cache pattern where there is a getter/setter in `DLNAMediaInfo.java` and then the caching is handled by `MediaTableFiles:getData()` and `insertOrUpdateData()`

**Comment by CodeLover254** [comment]
@SubJunk , didn't think of it that way. Guess am still learning. Thanks for the feedback. I can refactor it so that it uses the FILES table instead.

**Comment by SubJunk** [comment]
I should have given those details in the issue to save you time. I'll try to make better issues

**Comment by SubJunk** [comment]
Closing this because of the hopefully incoming new one :)

**Comment by CodeLover254** [comment]
No problem. I will create a new one based on the discussions we had. :)

**Pull request closed without merging**
