### PR TITLE
Update Samsung-H6400.conf

### PR DESCRIPTION
**Pull request by WolfganP**
Added official FAQ URL on supported containers and codecs for future reference

[Review on Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/737)

### CODE REVIEW

**Comment by Nadahar** [comment]
@WolfganP Thank you. Have you tested them all?

**Comment by WolfganP** [comment]
I just added the FAQ article for future reference, no changes whatsoever to the supported formats yet (I need to get specific media files to test them before commit)

**Comment by Nadahar** [comment]
@WolfganP Can't you verify the formats as well, and then commit any needed changes to this PR?

Sample files can be found [here] (https://samples.ffmpeg.org/) or [here] (https://samples.mplayerhq.hu/).

**Comment by SubJunk** [comment]
@WolfganP if you can update this branch with master we can merge it

**Comment by Nadahar** [comment]
@SubJunk This PR is now synced.

**Comment by Nadahar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/universalmediaserver/universalmediaserver/737)*

**Comment by SubJunk** [comment]
Thanks :)

**Pull request merged**
