### PR TITLE
Samsung TV fixes

### PR DESCRIPTION
**Pull request by SubJunk**
Fixed MPEG-TS MIME type on Samsung UHD TVs, and improved detection of 2021 TVs

### CODE REVIEW

**Comment by SubJunk** [comment]
For some reason the code is not updating on GitHub CI so it is detecting lint even though that is fixed in this branch

**Comment by ahmedadan** [comment]
> 
> 
> For some reason the code is not updating on GitHub CI so it is detecting lint even though that is fixed in this branch

Also happening in #2621

**Review by valib — DISMISSED** [review]

**Comment by valib** [comment]
@SubJunk GitHub and also I have problem with the jaudiotagger repository `https://repository.mulesoft.org/nexus/content/repositories/public/`. That is why I downloaded the last version from `https://bitbucket.org/ijabz/jaudiotagger` and included it to UMS.

**Comment by SubJunk** [comment]
@valib the jaudiotagger has caused a big problem for me, that breaks all browsing and caching:

```
DEBUG 2021-09-20 19:52:12.922 [pool-5-thread-25] Error adding child: "video.mkv"
java.lang.NoClassDefFoundError: org/jaudiotagger/tag/KeyNotFoundException
	at net.pms.dlna.DLNAMediaDatabase.getData(DLNAMediaDatabase.java:566)
	at net.pms.dlna.RealFile.resolve(RealFile.java:217)
	at net.pms.dlna.DLNAResource.syncResolve(DLNAResource.java:1421)
	at net.pms.dlna.DLNAResource.run(DLNAResource.java:1220)
	at net.pms.dlna.RealFile.isValid(RealFile.java:93)
	at net.pms.dlna.DLNAResource.addChild(DLNAResource.java:535)
	at net.pms.dlna.MapFile.manageFile(MapFile.java:289)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:364)
	at net.pms.dlna.MapFile.analyzeChildren(MapFile.java:344)
	at net.pms.dlna.DLNAResource.discoverWithRenderer(DLNAResource.java:1177)
	at net.pms.dlna.DLNAResource.getDLNAResources(DLNAResource.java:1099)
	at net.pms.remote.RemoteBrowseHandler.mkBrowsePage(RemoteBrowseHandler.java:134)
	at net.pms.remote.RemoteBrowseHandler.handle(RemoteBrowseHandler.java:450)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:700)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:672)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.jaudiotagger.tag.KeyNotFoundException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 22 common frames omitted
```

**Comment by ik666** [comment]
@valib I've the same issue. The system scoped jaudiotagger library doesn't get repackaged into the big ums jar file ...

**Comment by valib** [comment]
@UniversalMediaServer/developers it seems that I made something wrong. For me it works because I manually add the audiotagger to the lib folder in my Eclipse. Can you help how to include this library to the project to be used for others?

**Comment by ik666** [comment]
Hmmm ... seems using `System` scoped library path is more tricky or should be avoided. One (very old) solution I found is described [here](https://stackoverflow.com/questions/2229757/maven-add-a-dependency-to-a-jar-by-relative-path/2230464#2230464)

**Pull request merged**
