### PR TITLE
Remove tags from srt subs reloaded

### PR DESCRIPTION
**Pull request by Nadahar**
This is just a continuation of #1013 since @Sami32 merged it prematurely.

@valib I've implemented some changes from my own comments except the temp file issue. That will require some more work, and I generally seem to be the only one that cares about multithreading issues here so it isn't worth it.

The commits should be pretty self-explanatory. Please review and retest.

---
This change is [Reviewable](https://reviewable.io/reviews/universalmediaserver/universalmediaserver/1018)

### CODE REVIEW

**Comment by Nadahar** [comment]
Merged? :open_mouth: 

Have you tested it?

**Comment by Nadahar** [comment]
@valib Did you force push? My commits are gone...

**Comment by valib** [comment]
@Nadahar of course I tested it and I use the [SubRip_capability_tester.srt.txt](https://github.com/UniversalMediaServer/UniversalMediaServer/files/490686/SubRip_capability_tester.srt.txt) for testing. Sorry I didn't checked if something was changed in this branch and I forced the push. The problem is that when @SubJunk disabled to push directly to the master branch there is still possibiliy to merge the other branches lke @Sami32 did with this branch without the permition. So for me to update and fix changes this way was the only choice.

**Comment by Nadahar** [comment]
@valib If you have to use force you should always check why. That generally means that the remote has commits that you don't. There should be no reason you'd have to force to continue working on this branch even if the pull request was merged..?

I still have my commits locally, so I can push them to this branch. My commits partly overlaps with yours though. I didn't know about the ```{ }``` tags though. Are they also supported by SubRip?

**Comment by valib** [comment]
@Nadahar It will be nice if you push your changes here. ```{ }``` tags you personally mentioned in your comment from [Wikipedia](https://en.wikipedia.org/wiki/SubRip#SubRip_text_file_format) and is also used in the SubRip capability tester I mentioned 10 hour ago.

**Pull request merged**
