### PR TITLE
Bump JRE to 16

### PR DESCRIPTION
**Pull request by SubJunk**

### CODE REVIEW

**Comment by SubJunk** [comment]
@valib it would be good to get this merged before I do the next release, if you are ok with that

**Comment by valib** [comment]
@SubJunk I tested JDK-16 and it doesn't work for me well. There are a lot of errors.

**Comment by SubJunk** [comment]
@valib I get those warnings from ProcessManager too, it would be good to create an issue for those. Not a big deal though

> The UMS is recognising my two renderers as one type with different IP addresses and renderers not send the ProtocolInfo

Are you able to investigate that? I am surprised that would be different with this new version

**Comment by valib** [comment]
@SubJunk I think that the implementation of the `ProcessManager` is the issue why the UMS doesn't work in the JRE-16. To solve it could fix other problems.

**Comment by SubJunk** [comment]
@valib ok, I will look into it

**Comment by SubJunk** [comment]
It makes me very happy that we are bundling JRE now. If we weren't we would suddenly have a lot of unhappy users when they updated JRE

**Comment by valib** [comment]
@SubJunk in the past developers mostly used general `Exception` in the code instead of exact exceptions raised by the class so the behaviour of the code is unexpected.

**Comment by Mik-S-UMS** [comment]
> UMS is recognising my two renderers as one type with different IP addresses and renderers not send the `ProtocolInfo`

@valib this sounds similar to the issue I had when I was using a different network for my internet #2338, no `GetProtocolInfo` was being sent while the wireless network was being used. Also it was causing UMS to not identify the correct conf for my TV. Might not be the same thing but may have a similar root cause.

**Comment by SubJunk** [comment]
@valib can you please test it now. I did a fix that requires Java 9+

**Comment by valib** [comment]
@Mik-S-UMS this is other case. For JRE-15 it works.

**Comment by valib** [comment]
@SubJunk it seems that the ProcessManager still has a problem and this may cause the problem with ProtocolInfo and also with transcoding.
[ums_dbg_2021-03-25-22-19.zip](https://github.com/UniversalMediaServer/UniversalMediaServer/files/6207945/ums_dbg_2021-03-25-22-19.zip)

**Comment by valib** [comment]
@SubJunk in the past developers used mostly general Exception in the classes not the relevant one for the class. So I am not surprised that exception raised e.g. in ProcessManager can cause problems in other threads. Those problems are still here.

**Comment by SubJunk** [comment]
@valib I don't see exceptions related to process manager in there. Can you please let me know where the problem is in the logs?

**Comment by valib** [comment]
@SubJunk there are not exceptions but it seems that `cling` is not working with JRE-16

**Comment by SubJunk** [comment]
@valib what makes you think it is Cling? We can always fork and fix it if it is that, as we have done with other dependencies

**Comment by valib** [comment]
@SubJunk because the UPNP service is not fully initialized see:

````Mar 27, 2021 12:47:55 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: >>> Starting UPnP service...
Mar 27, 2021 12:47:55 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: Using configuration: net.pms.network.UPNPControl$1
Mar 27, 2021 12:47:55 PM org.fourthline.cling.transport.RouterImpl <init>
INFO: Creating Router: org.fourthline.cling.transport.RouterImpl
Mar 27, 2021 12:47:55 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Mar 27, 2021 12:47:55 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: Intel(R) Dual Band Wireless-AC 3160
Mar 27, 2021 12:47:55 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /10.0.0.10:56105
Mar 27, 2021 12:47:55 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /10.0.0.10
Mar 27, 2021 12:47:55 PM org.fourthline.cling.transport.RouterImpl handleStartFailure
SEVERE: Unable to initialize network router: org.fourthline.cling.transport.spi.InitializationException: Failed to set modified URLStreamHandlerFactory in this environment. Can't use bundled default client based on HTTPURLConnection, see manual.
Mar 27, 2021 12:47:55 PM org.fourthline.cling.transport.RouterImpl handleStartFailure
SEVERE: Cause: org.fourthline.cling.transport.spi.InitializationException: Failed to set modified URLStreamHandlerFactory in this environment. Can't use bundled default client based on HTTPURLConnection, see manual.
Mar 27, 2021 12:47:55 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully

**Comment by valib** [comment]
For JRE-15 is

````Mar 27, 2021 1:07:47 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: >>> Starting UPnP service...
Mar 27, 2021 1:07:47 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: Using configuration: net.pms.network.UPNPControl$1
Mar 27, 2021 1:07:47 PM org.fourthline.cling.transport.RouterImpl <init>
INFO: Creating Router: org.fourthline.cling.transport.RouterImpl
Mar 27, 2021 1:07:48 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Creating wildcard socket (for receiving multicast datagrams) on port: 1900
Mar 27, 2021 1:07:48 PM org.fourthline.cling.transport.impl.MulticastReceiverImpl init
INFO: Joining multicast group: /239.255.255.250:1900 on network interface: Intel(R) Dual Band Wireless-AC 3160
Mar 27, 2021 1:07:48 PM org.fourthline.cling.transport.impl.StreamServerImpl init
INFO: Created server (for receiving TCP streams) on: /10.0.0.10:56206
Mar 27, 2021 1:07:48 PM org.fourthline.cling.transport.impl.DatagramIOImpl init
INFO: Creating bound socket (for datagram input/output) on: /10.0.0.10
Mar 27, 2021 1:07:48 PM org.fourthline.cling.UpnpServiceImpl <init>
INFO: <<< UPnP service started successfully

**Comment by SubJunk** [comment]
@valib thanks, I will try to look into it. I'm not familiar with Cling itself but Java 16 seems to have some good improvements so I am interested in getting onto it

**Comment by valib** [comment]
@SubJunk this issue lead me to mention about #2197 that this is a UPnP implementation  that the renderes doubles. This happenned also here for JRE-16 because of the Cling wrong initialization.

**Comment by SubJunk** [comment]
Yes and this is one of the most frequent issues with Cling, it is even in their FAQ in the manual. I will hopefully have time to look into it soon

**Comment by SubJunk** [comment]
I'm closing this for now as it depends on replacing Cling

**Pull request closed without merging**
