### PR TITLE
Encoding of xml predefined entities, Norwegian translation, new renderer profiles, audio formats ++

### PR DESCRIPTION
**Pull request by Nadahar**
**Notice**

This is not ready to merge, I just needed a place to discuss issues I have with this instead of posting comments and creating issues all around the place. 

**Preamble**

This is the first time I do a fork/pull request (I'm new to GitHub), and I've already realized that I've made some mistakes. The main problem is that this has grown to be a mixture of differnt things which makes is somewhat disorganized. In the future I will definitly create separate request for separate issues. That said, I do want to try to get this through as I've put quite a lot of effort into this.

It all started with me wanting to fix the xml predefined entities (xml encoding of "><&') for some renderers like my Onkyo TX-NR807. During that I found a couple other small things I thought needed improving. Then I figured I should re-do the Norwegian translation as it was so bad that it was hardly comprehensible, and so I retranslated everything, not only adding what was missing. As the existing renderer profile that was used on my Onkyo (Onkyo TX-NR717) didn't really work very well with my Onkyo (the only thing that would play was MP3), I wanted to add a better profile as well. Being slightly OCD, that led me to the conclution that I'd have to test every format Onkyo claimed to be compatible. That again led to a big overhaul of the audio formats as much was missing or interpreted wrong.

This is also the first time I'm coding Java, although I've used quite a few other languages before. Pascal is my primary language though, so there's a lot of unknowns here to me (Eclipse, dependencies, Maven, formatting +++).

Whether or not you wish to use my changes remains to be seen, but I hope atleast some of it is of interest. But, being new to the project, new to the language and new to the environment there's a lot of things that's unclear or unknown to me, so navigating this all has been somewhat difficult and I will just have to excuse if I've done some newbie mistakes. I certainly have tried my best to verify things, but sometimes I just can't seem to figure things out (as you've seen by my postings around here).

**Main**

These are the issues I have at the moment:

* While trying to build UMS, it fails a test: ``` org.junit.ComparisonFailure: "test.wma" is expected to match expected:<[M4]A> but was:<[WM]A> ```. I do understand why that fails, as I have reworked a lot of the audio formats and updated extensions. What I don't understand is why "test.wma" is supposed to be recognized as M4A when it clearly isn't. Is this some kind of special PS3 trick, and if so, shouldn't it be handled elsewhere (limited to the PS3, not globally)? I understand the importance of testing for backwards compability, but does that mean you want to keep something that is plain wrong, or should I just adjust the test to expect WMA?

Once I've worked out the issues I have with this code and tested to my ability, I will write a detailed explanation of the changes I've made before asking for merging.

### CODE REVIEW

**Comment by Nadahar** [comment]
Regarding the transcoding pitch error, I temporarily changed the PS3 tests and managed to build and install this build on the other computer. As far as I can tell, the problems are the same in 5.1.3. I then found a file that both Serviio and UMS transcodes, and did a Wireshark trace for comparison. Serviio does not have the pitch problem. 

UMS: 
```
GET /get/153/Owner-MonkeyHigh.ape HTTP/1.1
Host: 10.72.64.12:5001
Connection: close
User-Agent: foobar2000/1.3.8
Accept: */*
Icy-MetaData:1

HTTP/1.1 200 OK
Content-Type: audio/L16;rate=48000;channels=2
Accept-Ranges: bytes
Connection: keep-alive
Server: Windows_XP-x86-5.1, UPnP/1.0, UMS/5.1.3

.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
...................
...
.......................................................................................................................................................................................................................................................................................................................................................................................
...........
.......
...........
...
...
.........................................................................................................................................................................{...{...|...|...w...s...v...o...o...k...o...f...l...e...h...b...\...`..._...Y...P...Y...V...U...R...L...@...F...H...D...>...6...6...,.....z.)...1.y.).}.-...'...*.t.'.y.".w...|.2.s.&.n.#.i. .e...X...f...V...V...Z...V...W...Z...Q...N...S...H...T...F...C...A...*...0...7...(...,.../...#...,...%.
.#... ...(.......
```
Serviio:
```
GET /resource/5511/MEDIA_ITEM/LPCM16_44_STEREO-0/ORIGINAL HTTP/1.1
Host: 10.72.64.12:8895
Connection: close
User-Agent: foobar2000/1.3.8
Accept: */*
Icy-MetaData:1

HTTP/1.1 200 OK
Content-Type: audio/L16;rate=44100;channels=2
Cache-control: no-cache
Connection: close
Date: Fri, 03 Jul 2015 14:02:36 GMT
realTimeInfo.dlna.org: DLNA.ORG_TLAG=*
Server: Windows XP, UPnP/1.0 DLNADOC/1.50, Serviio/1.5.2
transferMode.dlna.org: Streaming
Transfer-Encoding: chunked

1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
1000
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
...................
...
.......................................................................................................................................................................................................................................................................................................................................................................................
...........
.......
...........
...
...
.........................................................................................................................................................................{...{...|...|...w...s...v...o...o...k...o...f...l...e...h...b...\...`..._...Y...P...Y...V...U...R...L...@...F...H...D...>...6...6...,.....z.)...1.y.).}.-...'...*.t.'.y.".w...|.2.s.&.n.#.i. .e...X...f...V...V...Z...V...W...Z...Q...N...S...H...T...F...C...A...*...0...7...(...,.../...#...,...%.
.#... ...(.......
```
As you can see, there are quite a few differences. First of all, the spesification in the headers differ with what information it gives. I don't really know what the headers do, but I notice for example that UMS doesn't specify DLNADOC/1.50. More interesting though is that UMS specifies the sample rate to 48000 while servio says 44100. That could be legit, but when I check the source file it is 44100. Automatic resampling is off, so I would think that FFmpeg wouldn't change the sampling rate when it's not given as a parameter. Why do UMS think the result is 48000? Is that correct?

**Comment by Nadahar** [comment]
@SubJunk @valib @skeptical @SharkHunter I don't mean to be impatient, and I see there are pull requests that's been waiting for months and even years, but I'd like a little hint if what I'm doing is at all interesting, or if I'm just wasting my time. I don't know the proper etiquette for this project or github in general, so please let me know if I'm doing things the wrong way and I'll comply.

It would also be nice to get some input on the PS3 compatibility case, I could try to make some special handling for the PS3, but some more knowledge of what is really the problem would be helpful to figure out the right approach. I don't have access to a PS3 for testing.

**Comment by SubJunk** [comment]
@Nadahar no problem, thanks for the note :) I think at the moment this pull request can be broken down into many pull requests for easier consumption, for example "Onkyo TX-NR807 support" and "Make sure FFmpeg doesn't try to encode embedded images into the stream", etc.

We don't really have rules about how to do things, it's all pretty unorganized, but I won't merge something if it's huge because it presents a lot more risk of breaking things. So it makes it a lot easier when pull requests are small and we can have a quick look at the code and see how safe it's going to be, and test it in specific ways that don't take up all our time :)

**Comment by Nadahar** [comment]
@SubJunk I'll try to brake it up as much as possible, the problem is that many of the changes depends on the other things. Most of the changes I've made is to the handling of audio files that has been as a direct result of the testing I've done when trying to make the Onkyo-NR807 support. While there are no specific quirks done to support the Onkyo, many general things have been done that the Onkyo-NR807 configuration relies on. That means that submitting the renderer configuration separatly simply won't work as intended. 

As a general note, I have the impression that audio support haven't been a priority in UMS, I guess most of you are first and foremost interested in video streaming, and this explains why so many things are lacking in the audio department.

**Comment by ler0y** [comment]
Sorry for late response on this..
This PR includes some great changes.
I already thought it was not the best solution to just add new supported audio formats just to the OGG.java.
When these formats are separated, we can give best default MIME type for each new format :)

**Comment by Nadahar** [comment]
@ler0y Thanks, yes, I think these changes will be a real "lift" to the audio support. I've not only added the formats, I've downloaded multiple sample files for each format and tested and adjusted recognition as well. I've already made separate PR's for most of the small things in the PR, and once the logging PR is merged, I think I will start on an audio support PR. 

This PR (#589) will never be merged, I'm just keeping it here as a reference to what's still to come while I separate the individual parts from this one, and improve them further if that's required before I make a request. 

There is an issue with the audio formats though, as UMS today classifies WMA files as M4A files. The audio format "rework" corrects this, but then one of the UMS tests actually fail so it seems that it was intentional to misrepresent WMA files as M4A for the PS3 probably. I'd have to figure out what to do about that, it's hard to come up with a correct solution as long as I'm not sure what the underlying reason for this is. I don't have any PS3 to test with, but to me it's obvious that doing this will create problems on a lot of other renderers, not to mention that it undermines the "supported" configuration in the renderer. I could make some kind of renderer exception to handle this for the PS3, but I'd really like to know the underlying reasoning before I do something like that.

**Comment by ler0y** [comment]
I never noticed there is an issue with the audio formats,
where UMS classifies WMA files as M4A files.
What I know is that all wma audio codecs are parsed as wma,
including Windows Media Audio Professional/ Lossless and Voice,
wich are not all supported on all renderers.

So I guess it will be great, if we can distinguish these different wma codecs.

where I found that:
wma has Codec ID 161,
wma pro has Codec ID 162,
wma lossless has Codec ID 163, and
wma voice has Codec ID id A

I collected almost all available media test files out there to test on my renderers the last couple off years.
If you need some specific format/codec to test, don't hassle, just ask for the download location for missing files. You know how to contact me :)

**Comment by Nadahar** [comment]
@ler0y I though about separating the different WMA flavors as well, but that's not done in this PM. That's not covered in the "formats" but must be handled by audio codec, since the format in UMS is actuall tied to extension even if the interal format differs. Two formats can't per definition "share" an extension. Separating them on audio codec would probably be possible though, but if you look at ```LibMediaInfoParser.getFormat()``` that is one big mess where the codec information is not sent in parallell so you can take them all into account, but sequentially. That makes it a bit dangerous to mach simply on Codec ID, but there's probably a relatively safe way to do it. Today WMA is simply matched to ```161```, so "pro", "lossless" and "voice" won't even be picked up as WMA on the audio codec level (although it will be "wma" as format, since that depends on the extension).


Regarding the sample files, that's great, I have gathered a lot of sample files as well. I currently have 6,7 GB consisting of 377 files downloaded just as samples for testing UMS formats, but I don't think I have all the wma flavours.

**Pull request closed without merging**
