### PR TITLE
feat: Github Actions for CI

### PR DESCRIPTION
**Pull request by js-kyle**
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2152

Ubuntu 18.04 is failing on the same test mentioned here, https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2177, however that doesn't run on Travis at the moment anyway

### CODE REVIEW

**Comment by valib** [comment]
@js-kyle travis is still waiting for the status to be reported.

**Comment by js-kyle** [comment]
@valib The intention is to replace Travis, so the job won't run there

**Comment by valib** [comment]
@js-kyle so what will be the next step?

**Comment by js-kyle** [comment]
@valib I think the next steps for this would be

- general agreement that we want to switch CI platforms
- agree on the actual changes I have made (e.g. do we want to add more build combinations?)
- disable Travis as a required repository check

Then we could merge

**Comment by SubJunk** [comment]
I think it makes sense to switch to this from Travis.

> Ubuntu 18.04 is failing on the same test mentioned here, #2177, however that doesn't run on Travis at the moment anyway
If we want to use that version instead of 16 here, changing MediaInfo to 18.12 should fix that test

Also we probably don't need to support Javas 9-13 IMO; 8 and 14 are the currently supported ones. So I would do 8 on Linux just as a canary for us breaking compatibility, and then 14 on Windows and macOS

One improvement would be to use AdoptOpenJDK instead of whatever these Java distributions are. Eventually I want to use the actual JRE we supply via pom.xml but that could be its own story

**Comment by js-kyle** [comment]
I've made some tweaks based on the above comment

**Pull request merged**
