### PR TITLE
3004 web player

### PR DESCRIPTION
**Pull request by SurfaceS**
A testing web player under react.
It need more work on it, but let's have a try.

### CODE REVIEW

**Comment by js-kyle** [comment]
This is looking great

**Comment by SubJunk** [comment]
Exciting to see this!

**Comment by SubJunk** [comment]
There's a bug I just saw on this branch, but I think it is also in the main web settings branch. After creating the initial user, it logged me in and took me to the settings. Then I clicked "Player" in the menu, then it showed me the login page again. I think I had that happen on the 3004 branch when I clicked "Accounts" too

**Comment by SubJunk** [comment]
After that I logged in successfully and I am amazed at how much is here already. In some ways it is already better than what is in `main`

**Comment by SurfaceS** [comment]
> There's a bug I just saw on this branch, but I think it is also in the main web settings branch. After creating the initial user, it logged me in and took me to the settings. Then I clicked "Player" in the menu, then it showed me the login page again. I think I had that happen on the 3004 branch when I clicked "Accounts" too

Can't reproduce this. I use `UMS`, not `yarn`. Maybe that's the cause.

**Comment by SubJunk** [comment]
Do you mean `NPM`?

**Comment by SurfaceS** [comment]
No, I mean I built UMS (that do a yarn build) and run it from UMS.

**Comment by SubJunk** [comment]
@SurfaceS ah I see, yeah that's what I did too. I'll try to get full reproduction steps

**Comment by SurfaceS** [comment]
I was looking on metadata...
What a mess on the db.
I think it will need a big review on this side.

**Comment by SurfaceS** [comment]
Added TV Series Metadata

**Pull request merged**
