### PR TITLE
Disable "Web interface" button until the web interface is browsable

### PR DESCRIPTION
**Pull request by js-kyle**
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/2331

### CODE REVIEW

**Comment by SubJunk** [comment]
@js-kyle it looks good but it seems to not quite have the timing right - if I click the button as soon as UMS opens, it takes me to `http://null:9001/`

**Comment by js-kyle** [comment]
Okay cool I'll look into it

**Comment by valib** [comment]
@js-kyle nice work. I updated your PR to not make the button invisible but only disable it until the PMS is fully initialized.

**Comment by js-kyle** [comment]
@valib thanks - that makes sense

**Review by valib — APPROVED** [review]

**Pull request merged**
