### PR TITLE
Fix the subs recognition bugs - Rebased

### PR DESCRIPTION
**Pull request by valib**
Reverts UniversalMediaServer/UniversalMediaServer#1098
Sorry but it not works as expecting.

### CODE REVIEW

**Comment by Nadahar** [comment]
@valib Why did you close this - wasn't the reversal needed?

**Comment by valib** [comment]
@Nadahar I made a wrong assumption. I wanted to reset master branch to https://github.com/UniversalMediaServer/UniversalMediaServer/commit/5453878a34d88c91ebfdc0e4d851d50d6b393329 by force push which is not allowed for the master. I didn't know that. 😞

**Comment by Nadahar** [comment]
@SubJunk If you could do ```git reset --hard 5453878a34d88c91ebfdc0e4d851d50d6b393329``` and then force push that on master it would be great.

**Comment by SubJunk** [comment]
Sure I can do that. Will do it later today

**Comment by SubJunk** [comment]
That's done now

**Comment by Nadahar** [comment]
@valib You have to make a new PR from that branch now..? What was the problem that made you reverse it?

**Pull request closed without merging**
