### PR TITLE
Revert "ChromeCast update and fix"

### PR DESCRIPTION
**Pull request by Sami32**
Reverts UniversalMediaServer/UniversalMediaServer#1066

### CODE REVIEW

**Comment by SubJunk** [comment]
Why?

**Comment by Sami32** [comment]
@SubJunk For now it doesn't improve issue while using the latest Chromecast firmware but only give a NPE add...so i'm afraid that it could affect all the others Chromecast  users as well.

They are working on though...so maybe better to wait next version.
Users having this kind of issue can just revert they firmware update until it get solved.

**Comment by Nadahar** [comment]
You guys are too trigger happy - test first, THEN merge :wink:

**Comment by vitalidze** [comment]
Wait, I don't consider that NPE an issue in library. Please read this: https://github.com/vitalidze/chromecast-java-api-v2/issues/51#issuecomment-256838206 for an explanation about what happened. The thing is that there are no running application at the moment of sending that request. So most probably the fix in next version will be to throw a more descriptive error than NPE. This will not fix the root cause in UMS. 

I don't know how the code is being used right now in UMS, haven't got a time to read it. But I think it should check for a running application before sending request to play some media on ChromeCast.

**Comment by Nadahar** [comment]
@vitalidze That sounds reasonable, thank you for informing. I just understood @Sami32's description of the issue like it was a library issue.

I don't think we will be able to get this up and running as there seems to be no developer that owns a Chromecast.

**Comment by SubJunk** [comment]
I own a Chromecast and am happy to do testing. I've used it before with UMS and it worked well but I haven't done heaps

**Comment by Sami32** [comment]
That's a great new :-)

**Comment by Sami32** [comment]
The NPE has been already fixed in 0.9.4 SNAPSHOT:
https://github.com/vitalidze/chromecast-java-api-v2/commit/99250880bb0ba0246abb18248fc11df52cc51ba9

**Comment by Nadahar** [comment]
@Sami32 UMS code will still have to be changed, an exception will still be thrown - we will just get a ```ChromeCastException``` instead of a ```NullPointerException```. The result will be the same, UMS will have to keep track of whether an "app" (whatever that might be) is running or not before making the call.

**Comment by Sami32** [comment]
@Nadahar It's why in my first post, i asked to wait this [PR](https://github.com/vitalidze/chromecast-java-api-v2/pull/40) to be realized.

**Pull request closed without merging**
