### PR TITLE
Information complémentaire

### PR DESCRIPTION
**Pull request by Sami32**

### CODE REVIEW

**Comment by Nadahar** [comment]
@Sami32 Why won't it work with subtitles? Renderer supported subtitles should play fine..? Anything not supported by the renderer obviously won't play...

**Comment by Sami32** [comment]
@Nadahar Did you tried it ?

**Comment by Nadahar** [comment]
@Sami32 No, I haven't. I just don't understand why subtitles would make a difference as long as the renderer understand the subtitles. If it doesn't, it will need to be transcoded and since that is turned off it will obviously fail, but that's logical and the only way it can be.

**Comment by Sami32** [comment]
https://github.com/UniversalMediaServer/UniversalMediaServer/issues/565

**Comment by Nadahar** [comment]
@Sami32 If that's what you mean, it's not accurate to say simply ```Will not work with files having subtitle(s).```. Subtitles that can be streamed will be streamed, the problem is when there's a subtitle that can't be streamed. While one could argue that UMS should then instead stream the file without the external subtitle or stream it with an internal subtitle the renderer doesn't understand, that's not the choice that's been made. I think this logic should be looked at, but I don't think adding this line of text will solve any problems - especially since it's not entirely truthful.

**Comment by Sami32** [comment]
> Problem: even setting disable_transcode_for_extensions to "*" will sometimes result in UMS transcoding a file!

Waiting that it's solve itself, or commenting or modify the logic...that's the question.

**Pull request closed without merging**
